### ISSUE TITLE
Loot Pet effects stack with multiple Loot Pets

### ISSUE THREAD

**Issue by capnkirok** [capnkirok/Inventory-Pets#10]
Will add as an option to config file, but should default to no stacking effects.

**Comment by capnkirok** [comment]
And sometimes create ghost items

**Comment by hagfelsh** [comment]
Hello @capnkirok !  Loot pet stacking is highly desireable in the world we're making.  I'm using inventorypets-1.12-2.0.15 and I see no stacking option in inventorypets.cfg.  Was this implementation removed?  Is there anything I can add to the cfg to change it?
