### ISSUE TITLE
Chest Pet deletes items

### ISSUE THREAD

**Issue by Recour** [capnkirok/Inventory-Pets#100]
Apologies if this bug has already been reported.
My Double Chest Pet seems to delete all items stored in its storage that were placed in it after trying to put the same Double Chest Pet in it (so after I tried storing it in itself basically).
What I did exactly;
-Opened Double Chest Pet 1,
-Put an item (for ease, I'll say I stored an Egg in it),
-Tried putting Double Chest Pet 1 in it's own storage (because hey, why not),
-Realized it didn't let me store it in itself because that'd be pretty stupid,
-Stored some other items in Double Chest Pet 1 (a Cake, Cow Pet, and String),
-Closed Double Chest Pet 1,
-Reopened Double Chest Pet 1 and realized the Cake, Cow Pet and String had been deleted (they were not in the storage anymore).

I haven't done any other testing with this so, so far this is all I can give.

Kind regards,
Viktor

**Comment by capnkirok** [comment]
Ooh, that's nasty. I will take a look. 

EDIT: Hey @zZzViktor , I am not able to replicate the issue. What version of Minecraft, and Inventory Pets are you using? There was an 'item disappearing' issue about 6 months ago (on version 1.3.6), but it was closed, make sure you are on the latest.

**Comment by capnkirok** [comment]
I'm going to close this issue after 30 days open and no response, so just let me know.

**Comment by capnkirok** [comment]
Closing as I cannot replicate, and is likely an old issue from an early build.
