### ISSUE TITLE
[1.10] Grave Pet not working in modpack 

### ISSUE THREAD

**Issue by NathanWolfu** [capnkirok/Inventory-Pets#104]
Grave pet is not working. Have had multiple people on my modpack server die and lose their items.

Inventory Pet Version: InventoryPets-1,10-1.4.8

Forge Version: 1.10 - 12.18.0.2000

Mod List: http://prnt.sc/by0v72 and http://prntscr.com/by0vah

**Comment by capnkirok** [comment]
Really sorry to hear this. This sucks. Thanks for posting your modlist, it will help.

It's a tricky pet. 
- First, it stores all your items in Player NBT Data
- Then it deletes all of the items that would have been dropped
- Then when you reload your character, it grabs the saved items in Player NBT Data

Sometimes a conflicting mod prevents what happens in the first step, or prioritises one of its events over Inventory Pets. I will take a look and see if there's something I can do.

**Comment by capnkirok** [comment]
Just to make sure, I tested the mod again to ensure the Grave Pet was working alone on client and server and it is. I'll start the process of downloading all of the mods so I can isolate the problem.

**Comment by NathanWolfu** [comment]
An easier way to do it, is download my public modpack on Curse. Just search Reawakening. It has all the mods listed in the screenshot I sent you. It would also save you some time.

**Comment by capnkirok** [comment]
Cheers. Will look at this over the weekend.

**Comment by NathanWolfu** [comment]
Cheers!

**Comment by capnkirok** [comment]
In single player all items are returned EXCEPT Baubles in Baubles Item Slots seem to disappear. Will continue testing.

**Comment by capnkirok** [comment]
Ok, figured out why Baubles wasn't working: Azanor never made a 1.10 API, and the 1.9.4 version does not work in 1.10. So I updated it, and now it restores Baubles.

But I have a feeling you are talking about the entire inventory not being restored, correct? Not just Baubles items?

**Comment by capnkirok** [comment]
Sorry to say I am not able to replicate the issue. Only difference in my setup is that I used all the mods you provided in a forge client/server (not Curse), plus I used the latest version of Botania Unofficial (314). 

Recommend you give this version a test (still not officially published yet): https://dl.dropboxusercontent.com/u/127642501/inventorypets-1.10-1.4.8.jar

You can easily test by using the /kill command with a Grave Pet + Bones in hotbar. It should now work with Baubles. Let me know if your problem still exists.

If you continue to have problems, would recommend you disable the Grave Pet in the config until a better solution presents itself.

**Comment by capnkirok** [comment]
Hey @NathanWolfu I'm going to push this build tonight. Let me know if this fixed your issue.

**Comment by capnkirok** [comment]
Closing issue. Tested in dev environment and baubles are now returned.
