### ISSUE TITLE
Tough as Nails interaction with Anvil pet

### ISSUE THREAD

**Issue by unlightednetting** [capnkirok/Inventory-Pets#105]
When using the mod Tough As Nails and having a full water canteen full of clean water,

the repair goes off, and it does repair items, but it also resets the water to zero in the canteen.

Forge 1.10.2 - 12.18.1.2011, --- Inventory pets 1.4.8 ----  Tough as Nails 1.9.4-1.0.10

**Comment by capnkirok** [comment]
Cheers. The canteen must use damage to determine water level. I should be able to make an exception.

**Comment by capnkirok** [comment]
I should have made the joke: "Now that's hardcore!"

**Comment by capnkirok** [comment]
Can confirm this is an issue. I have added a workaround in Inventory Pets, and also posted on Glitchfiend's github, since using damage to determine water level will cause more problems down the road for him.
https://github.com/Glitchfiend/ToughAsNails/issues/91
