### ISSUE TITLE
Extremely random bug with a banana and a dummy

### ISSUE THREAD

**Issue by Mach12** [capnkirok/Inventory-Pets#108]
- Take a banana pet.
- Take [MmmMmmMmmMmm](https://mods.curse.com/mc-mods/minecraft/225738-mmmmmmmmmmmm)'s dummy.
- Slap da dummy with da banan
- Crash

I am amazed at how random it is. Tossing a banana at any other entity is fine, tossing your apple projectiles (any of em) is fine... Just tossing a banana at the dummy crashes your game.
Also the crash has other very random properties. It happens less often if you put yourself further away, seems guaranteed if the dummy is on a single solitary block, but impossible to do if it's on a flatland or in the ground...

(Yes it might be from MmmMmmMmmMmm, but the stacktrace gives both mods so I don't know. If you don't find a thing I'll cross-post this to MmmMmmMmmMmm.)

[Of course I have a crash log.](https://github.com/capnkirok/Inventory-Pets/files/413448/crash-2016-08-11_16.32.46-client.txt)

**Comment by capnkirok** [comment]
Thanks for the detail. I'll look into it and let you know what I find.

**Comment by capnkirok** [comment]
Sorry for late reply. This will be fixed in 1.4.8.2. Due to a null error when returning GetThrower().
