### ISSUE TITLE
[1.7.10-1.3.91] dupe bug 

### ISSUE THREAD

**Issue by johnfg2610** [capnkirok/Inventory-Pets#109]
Steps to replicate
1. Get a double chest pet
2. get block you want to dupe
3. use a 1 block morph although i feel normal suffocation would work
4. place piece of sand above you
5. hold the materials you want to dupe in the double chest pet
6. die
7. your items will appear in your grave/world and the inv pet

i have had another person check and this worked for both of us.

crash logs:
Client: http://pastebin.com/QXu6m50L
Server(intergrated server): http://pastebin.com/6yJ3dQre

**Comment by capnkirok** [comment]
Yeah, this was a problem with the old container code. You could actually dupe in much easier ways, but your method is definitely unique! The classes mentioned in the crash report don't even exist anymore, as the code has been completely replaced from scratch. 

Recommend you update to 1.4.8+ version. New pets, no duping, etc. etc. 

Thanks for the report though and the detail  👍
