### ISSUE TITLE
[Suggestion-ish] Blacklist a mod for Illuminati Pet

### ISSUE THREAD

**Issue by Mach12** [capnkirok/Inventory-Pets#110]
Well well... The Illuminati is a fun pet.

Unless you have mods like Building Bricks.

Send help, I summoned it like 25 times, and in all of this, I got 7 trowels in 10 items, and the rest are sliced blocks.
I am literally building a monument of random slabs and stairs as I write this, halp pls.

**Comment by capnkirok** [comment]
Black list the entire mod? Or just specific items. Blacklisting a mod would be fairly straightforward.

**Comment by Mach12** [comment]
I mean, ooc it sounds more like a good idea to make it per-item, but when the problem is that a mod has gazillions of items it could make far too lengthy config entry...

So I guess both per item and whole-mod exclusion would be great, but if both is too tedious to make, I do believe it is more important to block out the mods that block the fun side of this pet.

((Holy macaroni I got 12 trowels in one hour))

**Comment by Mach12** [comment]
I mean, ooc it sounds more like a good idea to make it per-item, but when the problem is that a mod has gazillions of items it could make far too lengthy config entry...

So I guess both per item and whole-mod exclusion would be great, but if both is too tedious to make, I do believe it is more important to block out the mods that block the fun side of this pet.

((Holy macaroni I got 12 trowels in one hour))

**Comment by Mach12** [comment]
However if you think you can have an alternative solution, try installing your mod and BBricks, and spamming the Illuminati in creative mode to investigate. Maybe some pattern could be used to procedurally recognize spammed items and nerf their likelihood, but I'm just speculating.

**Comment by capnkirok** [comment]
Hmmm... Ok I just figured out how to create and update JSON files. Could potentially have two different lists. Blacklist for mods (based on mod name) and a blacklist for items (based on unlocalized name). Would be for future, but can definitely do.

**Comment by capnkirok** [comment]
Quick fix, in 1.4.8.2 I am excluding Trowels, Fancy Lamps and Lanterns. I will add blacklist later.

**Comment by MrAmericanMike** [comment]
Is the Blacklist Option coming on some update? I could give that good use.

Thanks a lot.

**Comment by capnkirok** [comment]
Hey MrAmericanMike!

Yeah, update coming late Feb.

PC

**Comment by MrAmericanMike** [comment]
Thanks you so much <3

**Comment by capnkirok** [comment]
Oh, and here, have a Fancy Lamp... have a few extra...

**Comment by capnkirok** [comment]
Ok, this feature is in 1.4.9.3 and currently live in the 1.11.2 version. Will move it to the other versions and close it out. I guess this took longer than February... 

Solution:

JSON file, accessible in the Inventory Pets config directory
add the registry name of the item you want blacklisted (e.g., "minecraft:command_block")
add the mod name (e.g., "bibliocraft:")

**Comment by capnkirok** [comment]
Closing this one, and leaving it to: #129
