### ISSUE TITLE
Glitch on server with double chest pets

### ISSUE THREAD

**Issue by Muffinity** [capnkirok/Inventory-Pets#111]
My boyfriend and I were playing on a private crazycraft 3.0 server that we created. It has no plugins in it whatsoever. Well i'm not sure how this happened but I think we opened the double chest pet at the same time and I managed to get his items from my double chest pet. Which basically duplicated all the items in his chest. I'm sorry I dont have an error for this but I thought I would report it. c:

Sincerely,
-Muffinity

**Comment by capnkirok** [comment]
Thanks muffinity. Yeah this is an old bug that has been closed for some time. Recommend you download the latest version (1.4.8.1) of Inventory Pets and replace it in your CrazyCraft 3.0 directory. Thx and good luck :)

**Comment by Muffinity** [comment]
Alright thank you! c:
