### ISSUE TITLE
[ 1.10 ] cheetah pet

### ISSUE THREAD

**Issue by andrelec1** [capnkirok/Inventory-Pets#113]
Hello,
I play on 1.10.2 with forge 12.18.1.2073 and inventory pets 1.10-1.4.8.1
In the description cheetah pet eat "Raw meat" ...
So put some food in my inventory :

Raw beef and Raw Porkchop work fine, but the pet can't eat Raw Rabbit and Raw Mutton !!

The pet is a cat so i try with fish ... and pet eat all fish 
( Raw Fish, Raw Salmon, Clownfish, Pufferfish)

**Comment by capnkirok** [comment]
Good catch. Forgot about Mutton and Rabbit in the latest versions.
