### ISSUE TITLE
bannana food dupe glitch

### ISSUE THREAD

**Issue by explodingdigg** [capnkirok/Inventory-Pets#114]
i found a stupid bug/glitch where when you set bannana as your left handed item and put a food item in your hotbar ie. raw chicken and right click with food in your right hand the food will turn into a bannana with almost full durability

**Comment by capnkirok** [comment]
Very strange. Will check it out.

**Comment by capnkirok** [comment]
Can't seem to replicate in 1.10.2. Any more info on this one? It stays 'raw chicken'. Am using the latest recommended version of forge.

**Comment by explodingdigg** [comment]
Im not sure why it works for me but it does and I tried it with other pets
but it only works on the banana

**Comment by capnkirok** [comment]
Are you on Forge 1.10.2? Can you tell me which version?

**Comment by capnkirok** [comment]
Ahhh! I got it. I know what this is...

**Comment by capnkirok** [comment]
Ok, the solution to make it work in the offhand is more complicated and is something I'll roll into a future update. For now, I am simply going to turn off using it in the offhand, which prevents duping.

**Comment by explodingdigg** [comment]
Ok good idea. Your welcome

**Comment by capnkirok** [comment]
Thank you !
