### ISSUE TITLE
Loot Pet Not working on my server 

### ISSUE THREAD

**Issue by Goldstone16** [capnkirok/Inventory-Pets#117]
it was recently working until i made a tool with silk touch and now the loot pet will not auto smelt or work at that please help.. i am on Crundee Craft.

**Comment by capnkirok** [comment]
Loot Pet does not work with an item that has silk touch on it, so working as intended.

**Comment by Goldstone16** [comment]
I know but it's now disabled some how

Get Outlook for Androidhttps://aka.ms/ghei36

On Fri, Oct 7, 2016 at 3:41 PM -0300, "Purplicious_Cow" <notifications@github.com<mailto:notifications@github.com>> wrote:

Loot Pet does not work with an item that has silk touch on it, so working as intended.

##

**Comment by capnkirok** [comment]
Ah yes, you have an older version of Inventory Pets (you are on Crundee Craft). Would recommend you update to the latest version (1.4.8.1). Until then, you will have to reboot your server. Apologies for the inconvenience.

**Comment by Goldstone16** [comment]
Ah well thank you  very mucj

Get Outlook for Androidhttps://aka.ms/ghei36

On Sat, Oct 8, 2016 at 3:23 AM -0300, "Purplicious_Cow" <notifications@github.com<mailto:notifications@github.com>> wrote:

Ah yes, you have an older version of Inventory Pets (you are on Crundee Craft). Would recommend you update to the latest version. Until then, you will have to reboot your server. Apologies for the inconvenience.

##
