### ISSUE TITLE
1.10.2 Quiver Pet is awesome but..

### ISSUE THREAD

**Issue by LordHellscream** [capnkirok/Inventory-Pets#119]
But it's doing double damage in addition to the cool bonus. I love it, is it oversight or intended?

Regular bow does 3-4 damage (vs the Dummy), and it is doing 8-10 damage with quiver pet.
Fully enchanted dark bow (from ender IO) does about 13-17 damage vs the Dummy and with the quiver it does up to 35 damage a pop. 

Btw, you music of insta-shot mode is AWESOME :)

**Comment by LordHellscream** [comment]
Oh one other bug, if you the bow already have infinity enchantment, you will get free arrows from quiver pet from every shot, this is clearly a bug. 
(edit) actually, when you activate the insta-shoot mode, you will get free arrows even with a regular bow.

**Comment by capnkirok** [comment]
Thanks LordHellscream. I should do some Dummy testing I think, damage should not be that high. And good point on infinity, that is an easy one.

**Comment by capnkirok** [comment]
Actually, I totally forgot. Quiver provides free arrows, regardless if it is activated or not. So, that part is not a bug. It's one of the attributes. I will nerf the damage, tho.

**Comment by capnkirok** [comment]
Yes, it is exactly double damage. I've changed it to 1.5x instead.
