### ISSUE TITLE
1.10.2 Utility pet (repair) - repaired items reverted back to damaged state when moved

### ISSUE THREAD

**Issue by LordHellscream** [capnkirok/Inventory-Pets#121]
V= 1.4.8.1

Repro:
1.Have a damaged piece of armor on you (i was using a slightly damage diamond chest piece)
2. wait until the pet repair the armor
3. before the next item is repaired, moved the armor (equip/unequip)
4. Armor reverted back to the durability before repair.

This repair would not actually "commit" until next item is repaired.

**Comment by LordHellscream** [comment]
oh (I am not sure about this one), but i think the pet also tried to repair RF-powered items from mod that have full durability (mekanism jetpack, dark weapons from ender io)

**Comment by capnkirok** [comment]
Sounds like a client/server issue. Thanks again for the details.

**Comment by capnkirok** [comment]
Hmm.... not able to replicate this in Single Player. Checking server.

EDIT: Ok, now I see it, but only with Armor. Working on fix.

**Comment by capnkirok** [comment]
Fixed in Dev. Weird. The armor repair code is the same as the rest. Must be something different about how Minecraft treats the armor slots. To solve it, I made a copy of the original item, repair the copy, fully remove the original item, then replace the empty stack it with the copy.

**Comment by LordHellscream** [comment]
> I made a copy of the original item, repair the copy, fully remove the original item, then replace the empty stack it with the copy.

Is this safe? for modded armors with potential complex NBT data and such?

**Comment by capnkirok** [comment]
Yes, it makes a complete clone of the ItemStack, which would include anything stored on the item (like NBT data)
