### ISSUE TITLE
[1.10.2] Missing Textures

### ISSUE THREAD

**Issue by Akiishii** [capnkirok/Inventory-Pets#122]
All of the Inventory Pets are missing textures in 1.10.2

**Comment by DaFuJosh** [comment]
Hi i having same issue please fix the Pink/black textures 

using Version 1.10.2

![2016-10-13_16 39 06](https://cloud.githubusercontent.com/assets/22819922/19355999/30b934ae-9164-11e6-8d0c-40014afd91b1.png)

**Comment by capnkirok** [comment]
This is not the mod. Textures are fine. Would recommend you re-install the mod from scratch/re-boot Minecraft. Nearly 40,000 downloads of this version of the mod and no complaints about the textures, so something else is going on on your side.

**Comment by capnkirok** [comment]
Could be that CurseForge had a problem. Also might want to try re-downloading the file. I tried the current version on Forge and it is is fine.

**Comment by DaFuJosh** [comment]
i will try

**Comment by DaFuJosh** [comment]
if i send u the mod pack i made can u test it for me?

**Comment by DaFuJosh** [comment]
got over 186 mods for 1.10.2

**Comment by DaFuJosh** [comment]
Please test and find my issue https://www.dropbox.com/sh/6hmirj4vqi27vy2/AADyX9ngC0DoB8oehNiyf_6Ya?dl=0

**Comment by thetaCriterion** [comment]
I'm also running the 1.10.2 version, and I'm having an identical issue to this currently. Maybe I can add some information that might help?

Most items from this mod appear untextured, and don't show up in JEI searches-- including items like the iron/diamond/ender nuggets. The only exceptions are the Anvil Pet, the Solstice Sword, and the Cloud/Stone/Sand blocks and Spawner blocks.

Reinstalling the mod and updating forge hasn't fixed the issue, but creating a new instance and installing ONLY this mod does fix it. So it's probably a mod conflict. I've taken a look at the mod list posted by the person above, compared it to mine, and [put together a list](http://pastebin.com/JXaB2wb5) of the mods we're both running-- in case that helps. I'll try to do some more testing of my own when I have time.

**Comment by RyanP1991** [comment]
So I am running in to the same issue as stated above, this is using Forge 12.18.2.2105 and the latest version of this mod. This includes a reinstall of the mod.

List of other mods used: - https://minecraft.curseforge.com/projects/the-ryrypatpatpackpack-1-10-2

**Comment by capnkirok** [comment]
Hey guys 

There is a problem with the latest version of Chisel (.51) which is causing this problem. Recommend you downgrade back to .50.

Issue reported here on Chisel: https://github.com/Chisel-Team/Chisel/issues/257

**Comment by capnkirok** [comment]
Follow up: Drullkus is right, there is something strange in Inventory Pets json file formatting, which is causing a conflict with Chisel. I have already tested a fix and will update today. 

EDIT: There's an extra close bracket on the JSONs in question :/

**Comment by capnkirok** [comment]
@thetaCriterion this comment helped tremendously, thank you. Turns out it had something to do with the file formatting. Once I re-saved the JSON file of the items that had issues (no other changes) it worked. Can only theorize that that Chisel is reading the raw JSON of other mods and had trouble with something in the formatting.

Thank you!
