### ISSUE TITLE
1.10.2 Armor pieces still reverted to damage state after repair (1.4.8.2)

### ISSUE THREAD

**Issue by LordHellscream** [capnkirok/Inventory-Pets#124]
Just updated to the latest version, and surprising this still occur.
My equipments:
1. slightly damaged (90% or so) diamond helmet (un-enchanted)
2. badly damaged gold armor (30%)  (projectile protection II) -- a random loot.
3. slightly damaged diamond leggings (un-enchanted)
4. slime boots (from tinker construct) - no durability (it cannot be damaged).

After a few repairs, the gold armor is back to full HP, i took it off, and surprisingly, it reverted back to 50% HP, and the diamond helmet and leggings reverted back to their HP before repair (90% or so).

I waited for several more repairs, and after like 4-5 more repairs then they are finally stayed fixed.

**Comment by capnkirok** [comment]
Ok, will check again. I must have jumped the gun. Thanks for re-testing.

**Comment by capnkirok** [comment]
Well, 6 months later, I think I've figured out the problem. It appears the repairs weren't being processed on the server side, seems obvious now. Well, better late than never.
