### ISSUE TITLE
Bananarama

### ISSUE THREAD

**Issue by Medusalem** [capnkirok/Inventory-Pets#125]
We found out, that if the bannana is used and a item replaced it's place in hotbar the Item gets overwritten if Bannana comes Bag! 

This is kind of a problem while Playing with Magnet!
Also it is a Problem, in case of Dieng, we had the case that the Banana Pet was thrown away to kill a mob, Player was killed before banana pet came back, when Player was walking to his Gravestone he had a Angel Ring on the same Hotbar Slot that was taken by the Banana before. The Banana, even if the Inventory completly is empty has a change to erase Items...

**Comment by capnkirok** [comment]
Ah yes. You are right. I didn't imagine this situation. Will work on it for an update.

**Comment by capnkirok** [comment]
Ok, this is fixed in dev. Will update with 1.4.9
