### ISSUE TITLE
Banana Suicide [1.10.2]

### ISSUE THREAD

**Issue by Flexico** [capnkirok/Inventory-Pets#126]
If I'm standing too close to a mob when I throw my Banana Pet at it, somehow it kills me too, with the death message "Flexico was slain by Flexico." After my inventory spills to the ground, the pet returns, and is deleted upon respawn. http://i.imgur.com/iO6hrYo.png

**Comment by capnkirok** [comment]
Thanks for the posting. Yeah, I think the easiest way to solve this is that it doesn't damage the thrower....

**Comment by capnkirok** [comment]
Fixed in Dev. Now does only 2 damage to thrower.
