### ISSUE TITLE
[1.7.10] Whitelist for Illuminati Pet

### ISSUE THREAD

**Issue by capnkirok** [capnkirok/Inventory-Pets#129]
Add an option to choose from Vanilla only items (in config) for Illuminati. Credit: Flexico

**Comment by Flexico** [comment]
Would it be possible to add a whitelist/blacklist for different mods also? There's an item in the Adventure Backpacks mod, for example, that has no crafting recipe, so it would be cool to have a chance to get it via Illuminati.

Also might want to blacklist anything with the word "creative" in the name, as I got a "Creative Machinist's Workbench" (from Thermal Expansion), which can be used to perform crafting recipes for free.

**Comment by capnkirok** [comment]
Yes, I can explore a few ways of exclusion/inclusion. Are there any mods you know of that do this well? Otherwise I will just work it out on my own :D

**Comment by Flexico** [comment]
Nothing springs readily to mind. I know there's an addon to Bibliocraft that lets you make furniture out of new woods added by mods, but I don't think it has a way of disabling certain mods.

**Comment by capnkirok** [comment]
Ok, this feature is in 1.4.9.3 and currently live in the 1.11.2 version. Will move it to the other versions and close it out.

Solution:
- JSON file, accessible in the Inventory Pets config directory
- add the registry name of the item you want blacklisted (e.g., "minecraft:command_block")
- add the mod name (e.g., "bibliocraft:")

#110

**Comment by capnkirok** [comment]
- Added 1.10.2 version

Leaving open to fix in 1.7.10 at a later date

**Comment by capnkirok** [comment]
OK, 1.7.10 will have the blacklist in the next update.

**Comment by capnkirok** [comment]
Added to 1.4.9.6
