### ISSUE TITLE
Lines in console for Illuminati Pet/Blacklist ItemID's config option (1.7.10)

### ISSUE THREAD

**Issue by mew2keegan** [capnkirok/Inventory-Pets#132]
I've been having an issue on my modpack server with the Illuminati pet. I've got the config enabled to make the pet spawn any item, regardless whether it's craftable or not, but there's some item that it tries to spawn that simply crashes the player, sending them out of the server if multiplayer, or out of client if SP. I have no way of knowing which item it is, as checking the console and player logs shows me nothing. 

If it is possible, can a feature be added to the mod (For 1.7.10 and all versions, not just the 1.10/11), to add in a line to the console showing what the Illuminati Pet is spawning, and who used it? It would be greatly appreciated...

And then, to another extent, add in a config option to blacklist certain ItemID's?

**Comment by capnkirok** [comment]
Hey mew2keegan. Yeah, been having a similar issue with Voxels... there are some items in some mods that are missing key information, causing a crash. How they get registered with bad info I don't understand... but still I need to put better error trapping in. 

I can add this line in as well (it's actually already there, just commented out when I make a build).

And a blacklist has already been requested. Am working on this. Thanks for all the good suggestions.

PC

**Comment by capnkirok** [comment]
Closing this one.... lines in console now added. Whitelist/Blacklist covered in #110
