### ISSUE TITLE
[1.10] Dupe bug with Chest Pet

### ISSUE THREAD

**Issue by Eufranio** [capnkirok/Inventory-Pets#133]
**Steps to reproduce:**

1. Right click with a Chest Pet and put items there
2. Close the GUI
3. Right click with it again. Take the items, then move the mouse to the slot of the pet, and type Q (for drop the item)
4. Take items from this GUI, close, take the pet from the ground and get your duplicated items

**Comment by capnkirok** [comment]
Ooh, that one sounds very bad. What version of MC and also of InvPets are you using?

**Comment by capnkirok** [comment]
Ah, ok, got it. Good catch. I need to close the GUI after tossing the item (or something).

**Comment by capnkirok** [comment]
Ok fixed in Dev in 1.4.9. You can no longer 'Throw' the chest when the GUI is open. Great catch, major thanks!

**Comment by capnkirok** [comment]
Only on version 1.10+.
