### ISSUE TITLE
Banana Pet dupe bug

### ISSUE THREAD

**Issue by ShikuroAi** [capnkirok/Inventory-Pets#137]
If you spam click banana pet in atleast 5 blocks distance against a wall it creates multiple banana pets. It fills up my inventory and starts annoying me. Also I can throw infinite amount of banana pet without giving him glowstone by switching the original one to the least destroyed durability one and create more copies.

**Comment by capnkirok** [comment]
Ahhhh.... thanks. Not good. What version of MC are you on?

**Comment by ShikuroAi** [comment]
I'm on minecraft 1.7.10 and the version of the mod is 1.4.9
