### ISSUE TITLE
Cloud Pet Flight Not Working

### ISSUE THREAD

**Issue by tlsctf2** [capnkirok/Inventory-Pets#141]
Whenever I try to fly w/ the Cloud Pet, I stay on the ground and take (usually) one-time **insane** fall damage when landing on any other y-axis value, _even if the difference is only one block._ Please send help.

**Comment by capnkirok** [comment]
Definitely a compat issue, or I would have been hearing it from the community by now. Can you share your modlist? Typically, this problem in the past is caused by another mod's implementation of flight.

**Comment by tlsctf2** [comment]
I'm not sure which of my other mods does that, I'll look into it.

**Comment by tlsctf2** [comment]
Figured it out, ArmorPlus was causing the issue. The Ender Dragon Helmet I was wearing was keeping me from flying, you can fly if you wear that full set. Cloud Pet works fine w/o any of that armor.

**Comment by MysteryQuestMan** [comment]
I'm in an SMP with your mod and armor plus in 1.8.9, and even though no one has gotten into the armor plus mod we have found cloud pets. none of them work, we just get a weird double jump effect and fall to the floor. nothing else happens and we don't know how to fix it.

**Comment by capnkirok** [comment]
If you remove ArmorPlus mod (as a test only), does flying work?

**Comment by capnkirok** [comment]
Guys, I'm not supporting 1.8.9 anymore. It sounds like a compat issue, but I'm sure with what. Let me know if you see it on the supported versions list: 1.7.10, 1.10.2, 1.11.2
