### ISSUE TITLE
purpliciotion cow pet heal not working 

### ISSUE THREAD

**Issue by herz19** [capnkirok/Inventory-Pets#143]
when I play crainercraft purpkiciotion cow pet heal not working help plzzzz

**Comment by capnkirok** [comment]
It has an automated heal now, and no longer uses the potion effect. Can you check again? I think you will see it is healing you... (just slower than before)

**Comment by herz19** [comment]
U mean if I get heat the pet will heal me


On Feb 1, 2017 8:33 PM, "Purplicious_Cow" <notifications@github.com> wrote:

It has an automated heal now, and no longer uses the potion effect. Can you
check again? I think you will see it is healing you... (just slower than
before)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/capnkirok/Inventory-Pets/issues/143#issuecomment-276724344>,
or mute the thread

**Comment by herz19** [comment]
Yaa it's working thx for help

**Comment by capnkirok** [comment]
Great, thanks for following up!
