### ISSUE TITLE
Pingot Not finding Some moded ores

### ISSUE THREAD

**Issue by tyler489** [capnkirok/Inventory-Pets#144]
how does pingot recognise ores as it seems certain mods in 1.10 do not have there ores found... for example i was standing ontop of Gregtech coal ore and near Railcrafts poor iron ore and it wouldnt find either

**Comment by capnkirok** [comment]
Yes, it currently doesn't catch everything. It uses a combination of unlocalized name and meta data. I'm wondering if there's a way to do this with OreDictionary... will check.

**Comment by capnkirok** [comment]
Ok, i've improved the search. Should cover a lot more modded ores. Tested with IC2 and GregTech.
