### ISSUE TITLE
(Suggestion) Pingot Pet Ore Blacklist/Whitelist

### ISSUE THREAD

**Issue by tlsctf2** [capnkirok/Inventory-Pets#146]
I would like a blacklist and/or whitelist to be added for the Pingot. I used the Pingot once and was somewhat annoyed that it would mainly tell me about coal and iron while occasionally giving me a notification for diamond or emerald. Could this be added to avoid issues like this?

**Comment by capnkirok** [comment]
Hmmmm... there is a Pingot Harvest level in the config. By default it is set to 0 (coal). You can set it to 3 (diamond, emerald).

Remember, it will only locate ores that are within a certain radius of the player. Try it out and let me know.

**Comment by capnkirok** [comment]
Going to close this one.
