### ISSUE TITLE
[1.10.2] Bed Pet resets world back to day 0

### ISSUE THREAD

**Issue by ghost** [capnkirok/Inventory-Pets#149]
I have put Inventory Pets in one of my modpacks and one of my testers noticed that whenever the bed pet is used it resets the world back to day 0, rather than the morning of the next day.

Short recording here: https://dl.dropboxusercontent.com/u/29361581/ShareX/2017-03-03_18-58-38.mp4

**Comment by capnkirok** [comment]
Thanks for the feedback. Finally figured out how to fix this, and it will be updated in next week. Already working in 1.11.2
