### ISSUE TITLE
Mooshroom Pet randomly deleted when Pets Must Eat=false

### ISSUE THREAD

**Issue by RWBYKing** [capnkirok/Inventory-Pets#150]
I also have Improving Minecraft (which modifies how bonemeal works) installed on the modpack where I am experiencing this, so that mod may (also) be at fault.

**Comment by RWBYKing** [comment]
Nevermind, the way that Improving Minecraft handles the bonemeal mechanic is playing havoc with the Mooshroom Pet. Will cross-post this to pifou92000's git.

**Comment by capnkirok** [comment]
Cheers
