### ISSUE TITLE
[1.10.2] Opening Chest Pets from off-hand crashes game in build 1.4.9.2

### ISSUE THREAD

**Issue by RWBYKing** [capnkirok/Inventory-Pets#151]
What the title says. I have tested with all chest-type pets.

**Comment by capnkirok** [comment]
Thanks... did this not happen in previous versions? I think it must have...

**Comment by RWBYKing** [comment]
IIRC it also happened in 1.7.10, but i marked it as 1.10.2 because I haven't formally tested it in other versions

**Comment by RWBYKing** [comment]
wait wtf am i talking abt, we didnt have off-hand in 1.7.10. anyway, i don't use the intervening MC versions so idk

**Comment by capnkirok** [comment]
Ok, this is fixed in 1.10 and 1.11 for Chest Pet, Double Chest Pet, and Feed Bag. Will be released with 1.4.9.4.
