### ISSUE TITLE
Is there any way to disable the version checker? It claims 1.4.9.1 is up but it is older than what im using

### ISSUE THREAD

**Issue by Lothrazar** [capnkirok/Inventory-Pets#152]
I am using inventorypets-1.11.2-1.4.9.3

And the version checker yells at me in chat saying "HEY UPGRADE TO 1.4.9.1". but umm thats a downgrade,  so its confusing.

I checked the config file and there is no disable flag that i could see.

FYI there is a non invasive update checker built into forge where you give the @mod tak an updateJSON remote url as in here https://github.com/PrinceOfAmber/Cyclic/blob/94d0de9aa638532544b9c3480e4e3ed73904206a/src/main/java/com/lothrazar/cyclicmagic/ModCyclic.java#L25

**Comment by capnkirok** [comment]
Yeah, super annoying. Two things. 
1) I forgot to update my service that shows the latest version (so that's fixed)
2) Yes, you can turn off the flag. It's called "Show Update Message".

Thx!
