### ISSUE TITLE
Update check and notification.

### ISSUE THREAD

**Issue by Senophoe** [capnkirok/Inventory-Pets#153]
Can we have a update checker and notification configuration on the config files? It's important for us modpackers because we prefer to disable the notifications and update checker from mods when using them on modpacks, but leave it enabled for our own games. That way we receive the notification about a new update, but not our modpack users. They get the update on the next modpack update.

**Comment by capnkirok** [comment]
It's in there.... under Game Rules: Show Update Notification

PC

**Comment by Senophoe** [comment]
Oh, I kinda skipped that line on the configs while reading them, I guess.
Thank you!

**Comment by capnkirok** [comment]
No problem!
