### ISSUE TITLE
[1.11.2 - 1.4.9.3] Illuminati [sneak+rt click] & Black Hole Pets [sneak] abilities crashes player on server

### ISSUE THREAD

**Issue by VallenFrostweaver** [capnkirok/Inventory-Pets#155]
Server is unaffected and upon trying to relog the request is denied and player data needs to be reset before relog is allowed. No crash report is created. :/

Does NOT reproduce in single player strangely.

**Comment by capnkirok** [comment]
Ditto, didn't test this on server. Probably others that use 'sneak' have an issue too.

**Comment by capnkirok** [comment]
This is also due to using Java 1.6 on server. Math Helper does not have the fastfloor function in 1.6. Changed to a backwards compatible function. Rolled out at next release.
