### ISSUE TITLE
[1.11.2 - 1.4.9.3] Grave Pet not working at all

### ISSUE THREAD

**Issue by VallenFrostweaver** [capnkirok/Inventory-Pets#156]
I do have the mod Tomb Many Graves installed so I'm not sure if this is conflicting or not.

**Comment by capnkirok** [comment]
Might be a conflict, might be server. Will check.

**Comment by capnkirok** [comment]
Yes, this is a conflict with Tomb Many Graves. If you want to use that mod, would recommend you disable the Grave Pet (via the config). I've contacted the author as well.
