### ISSUE TITLE
[1.11.2 - 1.4.9.3] Enderman Pet only works reactively

### ISSUE THREAD

**Issue by VallenFrostweaver** [capnkirok/Inventory-Pets#157]
If about to die from an attack/damage you will teleport fine but if you attempt to teleport with it normally it does not work. This is only in a server/multiplayer and cannot be reproduced in single player.

**Comment by capnkirok** [comment]
Cheers. I didn't test all the functions on servers, obviously.

**Comment by capnkirok** [comment]
Ok, turns out this has to do with using Java 1.6 instead of 1.8. There is a new MathHelper function (fastfloor), which doesn't work with 1.6. I've changed it to a backwards compatible function.

**Comment by VallenFrostweaver** [comment]
Are you saying the player was using Java 1.6 or that the mod was trying to?

**Comment by capnkirok** [comment]
Well, neither. The mod is built to support Java 1.6 (still, but this will change at the next version of Minecraft Forge). However my code references a function which seems to appear only after Java 1.6 called FastFloor that seems to not work on Forge servers, only on clients. I've reverted back to the previous function (just Floor), which solves the problem. But in the server log, the error states that the function is simply not available. I'm probably not grasping the full extent of the problem.
