### ISSUE TITLE
Ocelot and Servers 1.11.2

### ISSUE THREAD

**Issue by Ravin890** [capnkirok/Inventory-Pets#158]
So when in the server the client will kick players if an ocelot pet is on the ground (there was also an incident where a player had issue when it was in his bag)

Since there is no actual crash report (and not know how I can force crash game to get one) here is a log to possibly help: https://pastebin.com/HuwwiZgd

**Comment by capnkirok** [comment]
Thanks. Definitely a bug.

**Comment by Ravin890** [comment]
Turns out the ocelot pet was actually in my inventory, and it was causing a ticking error so it was crashing player. I did a test on a local server and saw that in log (which i provided)

**Comment by capnkirok** [comment]
This is also due to the MathHelper fastfloor function not working on servers running 1.6 Java

**Comment by capnkirok** [comment]
I've updated to a backwards compatible math function. Fixed in dev, available in next release.
