### ISSUE TITLE
1.11.2: disabling an item in config causes NullPointerException in IPTextures.registerTextures

### ISSUE THREAD

**Issue by Lothrazar** [capnkirok/Inventory-Pets#159]
I set    B:"Exclude April Fool"=true

and then this is the crash log
https://pastebin.com/G0T2J8ZV

**Comment by capnkirok** [comment]
Thanks, will update. There is another method to disable April Fools in the config (which I am pretty sure works).

**Comment by capnkirok** [comment]
Ok, this is just a bug with disabling the April Fool pet, and it was on both 1.10 and 1.11.  I've made both Disable the Pet and Disable April Fool's to be equivalent. This is now fixed in Dev.
