### ISSUE TITLE
Cloud Block and Cloud Spawner have see through sides on non-cloud blocks

### ISSUE THREAD

**Issue by MichaelTon** [capnkirok/Inventory-Pets#16]
First of all I'm new to this mod so I'm not 100% on what things are supposed to be like and what things aren't, but I shall do my best.

When you place cloud blocks/spawners on non-cloud blocks the texture where ever the non-cloud blocks are becomes see through and you are able to see caves with it. Not sure if this is known, but like I said, I am trying my best to help out. :)

![2015-08-21_02 01 03](https://cloud.githubusercontent.com/assets/13895696/9399251/8e95dcb8-47a9-11e5-909f-ae63ab33662a.png)

**Comment by capnkirok** [comment]
This is intentional behavior. But, these blocks are currently not harvestable in 1.7.10 regardless. Instead of disabling x-ray altogether, we'll provide a config option to turn it off, and we'll make them harvestable only with Silk Touch (as intended). Thanks for reporting :)

**Comment by capnkirok** [comment]
Ok, these blocks will be only harvestable with a Diamond Pickaxe or higher with Silk Touch in the 1.3.3 update.
