### ISSUE TITLE
Bug: Illuminati Pet Does Not Respect Config File Setting

### ISSUE THREAD

**Issue by Jo-Mamma75** [capnkirok/Inventory-Pets#160]
Attempted to change Illuminati Cooldown Period via Config File for FoolCraft 1.2.2 to 5 Minutes via:
I:"Illuminati Cooldown (0-5) minutes"=5

Resulting behavior is that Illuminati Pet is perpetually stuck at 2:30.  Only viable solution at this time is to reduce the cool-down period to less than 2.5 minutes.  Issue posted on FoolCraft Github as Issue [#205](https://github.com/scalda/FoolCraft/issues/205).

Is this something that can be addressed and resolved in a future update?
Thanks in advance,
Jo_Mamma75
Iskall85 Community Administrator
FoolCraft Dev Team

**Comment by capnkirok** [comment]
Yes, will fix in next update. Thx!

**Comment by Jo-Mamma75** [comment]
@capnkirok 
Thank you for looking into it for us.
Would it be possible to extend the timer range from 0-5 minutes to like 0-10 minutes in that update?

**Comment by capnkirok** [comment]
As for second request, yes, I can expand it to 10 minutes. The label in the config will stay the same, but you will be able to set it to 10 regardless.

**Comment by capnkirok** [comment]
Also on 1.10.2 it appears. And 1.7.10.
