### ISSUE TITLE
Pet chests do not show up in alternate terrain generation biomes.

### ISSUE THREAD

**Issue by malwilson** [capnkirok/Inventory-Pets#169]
specificaly biomes o plenty, they will show up in vanilla biomes but will not show up in modded biomes not sure if thats something you guys are looking to fix but it would be nice.

i closed a issue i made about this a while ago because i found them in a vanilla biome with biomes o plenty on but it seems that they only spawn in vanilla biomes so i guess i am re doing this. probably fixable by ordering of when they are generated and biomes o plenty or something

**Comment by capnkirok** [comment]
Yep. Hardcoded biome names. I can biomedictionary this.... stay tuned.

**Comment by capnkirok** [comment]
Ok, updated to use BiomeDictionary. One note... Cloud Dungeons never check biomes, so they should always have appeared regardless of terrain gen.

**Comment by capnkirok** [comment]
Also... had difficulty testing Biomes of Plenty... that mod appears to be crashing due to its own problems with CascadingWorldGenCrash #170
