### ISSUE TITLE
[1.11.2] Dupe Bug Double Chest

### ISSUE THREAD

**Issue by capnkirok** [capnkirok/Inventory-Pets#171]
from: Flint

I found a "bug" with the 1.11.2 version I got a double chest pet and got some iron and separated the iron inside it then took out and it Doubles THE Iron. I did it with some other items and it worked as well

**Comment by capnkirok** [comment]
I see a problem if I shift-right-click on something back into the chest, after splitting.. to me it looks like it gives a full stack instead of adding to the total.

Also see it on Chest (and likely Feed Bag too).

**Comment by Flint17** [comment]
Here is video proof of this bug [)](https://youtu.be/WAdnObbYO74) the duping begins at 2:26.

**Comment by capnkirok** [comment]
Yeah, this is a stacking issue.

**Comment by capnkirok** [comment]
Ok fixed in dev for Chest, DoubleChest, and Feed Bag. Will be in next release.

Which is coming tonight.
