### ISSUE TITLE
Enchanting a book

### ISSUE THREAD

**Issue by ChaoticLogic** [capnkirok/Inventory-Pets#172]
When trying to enchant a book with the enchantment table pet, the XP is spent and the enchantments available cycle, but nothing happens to the book.

Using version 1.4.9.5 for 1.11.2

**Comment by capnkirok** [comment]
I have never tried enchanting a book. I'll bet you this part of the code is still from 1.7.10 :)

**Comment by ChaoticLogic** [comment]
I am happy to report that enchanting a book works in version 1.61 for Minecraft 1.10.2. Hopefully that helps narrow your search.

**Comment by capnkirok** [comment]
Yes, that helps! Means something changed very recently. Cheers :)

**Comment by capnkirok** [comment]
See also #177
