### ISSUE TITLE
PacMan Pet Config Options PLEASE

### ISSUE THREAD

**Issue by Boolyman** [capnkirok/Inventory-Pets#173]
The PacMan pet offers a very reasonable auto feed feature, which I would love for my players to use.  But then for some reason you can click it for a ridciulously overpowered boosted ability to nearly two shot any boss in the game.  Why is there no config to turn that part of the pet off?  The two abilities seem completely unrelated.  Can't it do something like conjure a few smoothies or something...

**Comment by Boolyman** [comment]
Hello?

**Comment by capnkirok** [comment]
Thanks Boolyman. I haven't looked at this pet in a while. Thanks for the feedback, and yes, can add to config.

**Comment by capnkirok** [comment]
Ok, going to do two things: 1) reduce the damage, and 2) make the damage option configurable.

**Comment by capnkirok** [comment]
Ok, this is fixed in dev. Damage was 10x. Now it is 2x, and the factor is configurable.
