### ISSUE TITLE
Config Option to reduce Pet Chests

### ISSUE THREAD

**Issue by Lost-Ninja** [capnkirok/Inventory-Pets#175]
Not really an issue with trees, clouds or dungeons but the sea cave chests are far too common. All sandy beaches have at least one but more often I'm finding 10 -15, frequently finding several in the same location.

I love getting the pets but it does feel a bit cheap to find them this easily.

**Comment by capnkirok** [comment]
You can configure the frequency of the beaches already in the config. Why don't you see if that helps?

And let me know if you find a level that makes sense... I can change the default to that.

**Comment by Lost-Ninja** [comment]
Wow, looked through the config several times and must be going blind in my old age... :/

Sorry for adding this issue. :(
