### ISSUE TITLE
Too Many Creepers

### ISSUE THREAD

**Issue by Frobuzmumber** [capnkirok/Inventory-Pets#176]
In every version I have found that creepers flock to me. They stack up to where there is about 30 or 40 of them. They start running away and then just as they get out of range, they come back. I am currently using the latest 1.10.2 version (1.4.9.5) 

I made a short video: https://youtu.be/z0wNywQXByA

![2017-05-13_10 34 02](https://cloud.githubusercontent.com/assets/9470663/26026402/27d5a498-37c8-11e7-9532-cae4b81a67db.png)

Its good for leveling up my tinkers weapons, but a pain when trying to build.

**Comment by capnkirok** [comment]
Yeah, that's because of the Ocelot. Right now, if there are any creepers even remotely in the vicinity, they will all run to the same spot. I know how to make it random... just haven't done it yet. Also listed as bug #91

**Comment by capnkirok** [comment]
Yeah, this will be closed in 1.4.9.6. Closing this as it is a dupe.
