### ISSUE TITLE
Enchanting Table Pet issues...

### ISSUE THREAD

**Issue by Lost-Ninja** [capnkirok/Inventory-Pets#177]
Using the enchanting table pet I have the following issues:

1. If you enchant an item with the maximum tier of enchant while the enchant works the stated levels are not removed from your XP bar.
2. You cannot enchant books.
3. When enchanting books while the pet appears to function correctly (the book has an enchant listed) the actual enchant doesn't stick to the book and regardless of which level you enchanted with some random number of XP levels are removed.

**Comment by capnkirok** [comment]
Will be fixed in next release. In two years of this mod being in existence... I had never tested books.
