### ISSUE TITLE
Crash on death with Tomb Many Graves 2

### ISSUE THREAD

**Issue by Chromogen** [capnkirok/Inventory-Pets#179]
some random NullPointerException with TombManyGraves2 and something gravepet-ish?

Version:
inventorypets-1.11.2-1.4.9.5
TombManyGraves-1.11.2-3.0.7

report:
https://pastebin.com/Yq8pM8Yj

**Comment by capnkirok** [comment]
Yup. Looks like it. I can disable in next release.

**Comment by Chromogen** [comment]
also: TMG2 + inventory pet will prevent tmg to create a block for some reasons eventhough tmb is way down in the death event priority list


-> all items are deleted on death


maybe add option to disable gravepet plus deathhandler connected to this option?

**Comment by capnkirok** [comment]
Another way to look at it is that TombManyGraves interferes with the GravePet trying to save your inventory....

**Comment by Chromogen** [comment]
true :)

might post report to m4thg33k too.
compat is a B...uddy   :D 


anyway, an option to safely disable the handler with the pet might be a not so bad idea.
thinking, i can recall some serveradmins dismissing mods for interfering with their most beloved gravemods eventough the problem was the gravemod itself :/

**Comment by capnkirok** [comment]
Hey, spoke to Tomb Many Graves moddev... he is going to issue a release.  I will also put in another update.

**Comment by Chromogen** [comment]
yeah, he mentioned :)
thx alot!

**Comment by capnkirok** [comment]
Technically, it was my fault. I refactored the code and didn't give him the new path...
