### ISSUE TITLE
Illuminati Pet - Make more configurable please!

### ISSUE THREAD

**Issue by Aliveagain** [capnkirok/Inventory-Pets#181]
I run a pretty popular Craft of the Titans server and the Illuminati pet kinda breaks the progression.   I just had a guy get over 50 million gunpowder, 500k Gold Blocks, over 2 million diamonds/draconium etc etc.  It;s pretty cool, but I need to be able to tone down how much they get of the items.  Any way you can accommodate that? Quickly?

**Comment by capnkirok** [comment]
Hey @Aliveagain , not sure what version of minecraft you are running, but the Illuminati pet is the most configurable pet in the game. Check out the config file, you'll see several levers in there.

If you are on 1.10 / 1.11 you can even set up a blacklist. Why don't you check it out and let me know.

**Comment by capnkirok** [comment]
Following up one more time before I close this one. Let me know.

**Comment by capnkirok** [comment]
Ok, closing this one. If it has to do with 1.7.10, then it is covered under #129
