### ISSUE TITLE
Anvil Pet appearing to cause Chisels & Bits chisels to break/vanish.

### ISSUE THREAD

**Issue by xevira** [capnkirok/Inventory-Pets#182]
Several times today while working with Chisels & Bits, I had the diamond chisel utterly vanish after an Anvil Pet repair despite having an almost full durability.  I'm currently using Inventory Pets 1.11.2 / 1.4.9.5 with Chisels & Bits 1.11.2 / 13.10.  It has been suggested that it's due to the chisel's massive durability (over 700k).

**Comment by capnkirok** [comment]
Thanks.

**Comment by capnkirok** [comment]
Doesn't look like it's the massive durability. It doesn't seem to be making any difference at all in my testing. I might make it skip this item just to be safe. Will look at the Chisel & Bits code first.

**Comment by capnkirok** [comment]
Yes, it uses it's own custom damage. But it leverages Minecraft Item class... which means that repairing the Minecraft damage could cause problems....  I'm going to have the Anvil Pet manually skip this item.

![image](https://user-images.githubusercontent.com/9628379/27254409-bac3f7de-5387-11e7-8147-a3c3cd1a8857.png)

**Comment by capnkirok** [comment]
Interestingly, if you use the living Anvil, it works fine.

**Comment by capnkirok** [comment]
Anyway, this is now fixed in Dev.
