### ISSUE TITLE
Cloud Pet Flight Bug

### ISSUE THREAD

**Issue by zzApotheosis** [capnkirok/Inventory-Pets#183]
Minecraft 1.7.10
Inventory Pets 1.4.9.5

It seems that the player maintains flight ability even after losing the Cloud Pet. I put my Cloud Pet in storage for a bit but noticed that I was still able to fly, albeit having no Cloud Pet.

Also, great mod!

**Comment by capnkirok** [comment]
Hey @zzApotheosis ! Long time.

Thanks. Sometimes this happens when there is a conflict with another mod. I've also seen this happen randomly. I'll do some more testing!

**Comment by zzApotheosis** [comment]
Alright, so I'd like to report that I'm not getting this bug anymore... That was so strange the day I was getting it. It **might** have been conflicting with Draconic Evolution's Draconic Armor because I do recall using that around the same time as my Cloud Pet.

Feel free to close this issue, since now the problem seems to be gone... for now, haha.

**Comment by capnkirok** [comment]
Ok, great, thanks! Let me know if it happens again.
