### ISSUE TITLE
1.11 pet dupe playerfile corruption and server issues

### ISSUE THREAD

**Issue by tyler489** [capnkirok/Inventory-Pets#184]
I do not know why but when a player uses a storage pet such as a chestpet and logs off with stuff in it when they attept to join the server the server crashes. Upon investigating there playerfile they had 4 doublechest pets with the exact same inventory. When i removed all 4 they were able to join again and play.

Playing the new frontier curse modpack on a spongeforge server.

**Comment by capnkirok** [comment]
Weird. Containers are the bane of my existence.

Which version of Inventory Pets are you using? There was an issue with the first 1.11 version.

**Comment by tyler489** [comment]
1.11.2-1.4.9.5

**Comment by tyler489** [comment]
If you wish to test it out the modpack is https://minecraft.curseforge.com/projects/the-new-frontier v 24. Our server is top of the list

**Comment by capnkirok** [comment]
ah great, thx

**Comment by johnfg2610** [comment]
Hey i work backend on the server if you need anything(player data/crash logs etc) just ask :)

**Comment by capnkirok** [comment]
Hey @johnfg10 , yes, can you send the crash logs? Or just put them in a pastebin and link them? Thx.

**Comment by tyler489** [comment]
Forgot this was still open. Wooops. We figured out  it was a bug in another mod causing crashes and inventory dupes.

**Comment by capnkirok** [comment]
Great :)

Was unable to repro, so glad there is a solution.
