### ISSUE TITLE
A few bugs I found

### ISSUE THREAD

**Issue by FKFHNIS** [capnkirok/Inventory-Pets#185]
1. Banana pet will disappear forever if you right click it then instantly pick up an item before it auto returns to you. If that item goes into your hotbar where the Banana would return to then the pet is gone.

2. Pets with a passive like Ocelot getting fish for you when near water will work forever if you have 2 or more of the same ones on your hotbar at once.  For example if I have 9x Ocelot pets on my hotbar only the first one will get hungry and the other 8 will keep working forever and never get hungry. Tested with Ocelot and Mickerson.

I would love a response as this mod easily became my favorite mod the day I downloaded it.

EDIT: Using 1.7.10 latest version.

**Comment by capnkirok** [comment]
Thanks for sharing the version number!

**Comment by capnkirok** [comment]
1. For Banana, you are correct. Also on 1.10+ versions, the pet actually replaces whatever was in the original slot
2. Oooh, that's nasty. Surprised no one has caught this before.

**Comment by capnkirok** [comment]
OK 1) is fixed in Dev, working on 2)

**Comment by FKFHNIS** [comment]
Thankyou so much for the update!

**Comment by capnkirok** [comment]
ok 2) will be fixed in next update (it's fixed in the development environment). I'm really surprised no one found this one.
