### ISSUE TITLE
Night Vision Potion Effect application

### ISSUE THREAD

**Issue by Shinoow** [capnkirok/Inventory-Pets#186]
I've received issues where the user has described that the Potion Effects applied from my armor sets (specifically Night Vision, but there's also status effect HUD flickering) in AbyssalCraft causes constant flickers, all cases in a modpack environment. A recent reply from another user in a issue (https://github.com/Shinoow/AbyssalCraft/issues/212#issuecomment-306668207) revealed that this is triggered by Inventory Pets. The picture below shows where it happens (decompiled copy of 1.10.2-1.4.9.5):
![](https://puu.sh/wdkRH/7fc6de911e.png)
What happens is your code removes the Night Vision Potion Effect whenever it's duration is less than 20.5 seconds (410 ticks), which effectively removes it if anything applies that Potion Effect with a shorter duration than that (in my case I set it to 260 ticks).
A fix for this would be if you added an additional check along with the duration to check whether or not the current amplifier is 5 (as you set that whenever you apply the effect), thus only removing it if the amplifier is at that particular number (doing a little search on GitHub revealed that none of the projects I encountered there set any amplifier on this particular effect, so it should be safe to assume that 5 will be from your application of the effect).
Alternatively, you could limit it to only checking the amplifier, but that has the potential of leading towards issues in the event that someone else would apply the effect with that particular amplifier on it (small chance, but not completely impossible).

**Comment by capnkirok** [comment]
Thanks for the suggestion. Definitely will try out both options.

BTW, what did you use to decompile this? It's super clean.

**Comment by Shinoow** [comment]
I used BON (Bearded Octo Nemesis) to deobfuscate the mod, then JD GUI to view the source code (that technically isn't decompilation, other than what the program does in order for me to view the contents of the .class files).

**Comment by capnkirok** [comment]
The Amplifier check does the trick. This will solve problems for a few mods. Thanks for the great tip.

Fixed in next release.
