### ISSUE TITLE
Ender Nuggets issue 1.7.10

### ISSUE THREAD

**Issue by hoogledesigns** [capnkirok/Inventory-Pets#187]
never ran a modpack that has custom pets and inventory pets. But recently on my server people have complained that you can not craft ender nuggets that inventory pets feed off as it automatically comes up as a customs pet ender nugget so inventory pets does not see it as their food.
even if you mix with Dirt you still get custom pets version. 
just ender pearl in crafting slot also gives you custom pet version
all though I can spawn in inventory pet nuggets for them but crafting is not possible. Ore dictionary they are the same item but have different ID numbers,

**Comment by capnkirok** [comment]
Thanks, will take a look. House Pet is super useful now, so understand the need. Could be compat issue, but I doubt it based on what you've written.

**Comment by capnkirok** [comment]
Hey I just tested this and am seeing no issues.

- House Pet eats both Custom Pets and Inventory Pets nuggets
- Both recipes work

I did fix something like this a while back. Are you on the latest version? 1.4.9.5?

**Comment by capnkirok** [comment]
I did close a couple of issues associated with Ender Nuggets in 1.4.7 and 1.4.8, and after thorough testing with no issues, I can only assume you are using an earlier version.
