### ISSUE TITLE
Inventory Pets Have No Texture 1.10.2

### ISSUE THREAD

**Issue by 4Benj** [capnkirok/Inventory-Pets#189]
Every Inventory Pet Except The Anvil Pet Has No Texture And I Have Downloaded 2 Versions, I'm On 1.10.2

**Comment by capnkirok** [comment]
Two questions:
Are you using Chisel? 
Which version of Inventory Pets?

**Comment by 4Benj** [comment]
The Jar File Name 
Minecraft Version: 1.10
Inventory Pets Version: 1.4.8.1

And I'm Not Using Chisel

**Comment by 4Benj** [comment]
Also, I Looked In The Jar File, All The Assets Are There, Just To Let You Know

**Comment by capnkirok** [comment]
There was a problem with earlier versions of the item model JSON files. Any mod that tries to read them like Chisel (instead of letting forge/mc handle it) would create this problem. This was fixed in 1.4.9+. Would recommend you download the latest version of Inventory Pets (1.4.9.5) and test.

**Comment by 4Benj** [comment]
Ok I'll Try That Version

**Comment by 4Benj** [comment]
My Game Can No Longer Initialize
[crash-2017-06-19_19.54.24-client.txt](https://github.com/capnkirok/Inventory-Pets/files/1084786/crash-2017-06-19_19.54.24-client.txt)

**Comment by capnkirok** [comment]
Strange. This is an MC error. At work right now, so can't test. In the meantime:

Ok, see if 1.4.8.2 works. That is the exact version where the json fix was made.

**Comment by 4Benj** [comment]
That Has Worked

**Comment by capnkirok** [comment]
Great, thanks for the update!
