### ISSUE TITLE
[1.11.2] First 11 slots in doublechest pet are bugged.

### ISSUE THREAD

**Issue by CatShot112** [capnkirok/Inventory-Pets#190]
MC Version: 1.11.2
Forge Version: 13.20.0.2315
Mod Version: 1.11.2-1.4.9.5

When i open doublechest pet and put some items in it, when i open pet again items are in slots 12+. First 11 slots are empty. When pet is full (all slots except first 11) and try to insert item to one of them, then close it and open inventory, when you click at slot where that item was it goes back to inventory.

**Comment by capnkirok** [comment]
Thanks, will check it out.

**Comment by capnkirok** [comment]
I am not seeing the issue.... are you working with any inventory type mods?

**Comment by CatShot112** [comment]
Here is my full mod list that i use at this time. Sorry but i can't check which mod causes problems because i have big renovation in house and I can't use computer. Names are from mods folder.

Backpacks 1.11.2 - 3.1.9
buildcraft-7.99.4
CodeChickenLib-1.11.2-universal
CXLibrary-1.11.2
Damage-Indicator-1.11.2
industrialcraft-2-2.7.33-ex111
InventoryTweaks-1.62
jei_1.11.2-4.3.5.277
Mekanism-1.11.2-9.3.2.307
More-Furnaces-Mod-1.11.2
Multi-Page_chest-Mod-1.11.2
NotEnoughItems-1.11.2-2.2.0.216-universal
OpenComputers-MC1.11.2-1.7.0.24
TreeChopper-1.11.2-1.1.2
Xaeros_Minimap_1.13.1_Forge_1.11

I also noticed that NEI causes some random crashes so maybe that is problem. And in InvTweaks no buttons are displayed to sort etc. (only with inventorypets)

**Comment by capnkirok** [comment]
I was not able to replicate this. I'm going to assume this was as you say. I'm going to stop supporting 1.11 updates anyway. Let me know if you see the issue in 1.12
