### ISSUE TITLE
No pet hunger in autonomous activator (TE-COFH mod compat)

### ISSUE THREAD

**Issue by maldiablo** [capnkirok/Inventory-Pets#192]
Some of my server users found out that the pets don't get hungry when used in machines like the autonomous activator in thermal expansion.

In one case, I've got a user who put the mooshroom cow in an activator pet and is endlessly mass-growing crops at an insane rate.  The pet never gets hungry because it's not in a player inventory.

My server is a 1.7.10 forge server if that makes a difference.  

If tracking pet hunger when not in a player inventory is too much of a programming issue, I'd be just as happy with a storage blacklist option.  Basically, I'd love to list types of storage pets refuse to 'live' in.  When a player tries to put a pet in blacklisted storage, they can simply be greeted with '%PETNAME% refuses to live in those conditions' and it goes back to the player inventory or just plops out to the ground.

**Comment by capnkirok** [comment]
Thanks for the suggestion. Yeah, they only get hungry when they are in your hotbar. I'll have to look at this one see what to do.

**Comment by capnkirok** [comment]
Unfortunately, I can't seem to find a way to modify the item when it's held by a 'Fake Player'. However, I can disable the abilities. I've added this to the config as an option: DisableRightClickMachines... just set that to true in the next release.
