### ISSUE TITLE
Hardcore Heart Pet won't eat

### ISSUE THREAD

**Issue by capnkirok** [capnkirok/Inventory-Pets#196]
When mod set to hardcore mode, Heart Pet doesn't eat Brewing Stands.

Credit: Wulfie03

**Comment by capnkirok** [comment]
Ok, this is fixed in next release

**Comment by Th3l0stSpart4n** [comment]
This still affects the latest version for 1.10.2, any chance of a update?

**Comment by capnkirok** [comment]
I might make a hotfix this weekend... as there are a few bugs on 1.12 that need remedy.

**Comment by Th3l0stSpart4n** [comment]
This also affects the Illuminati pet, on hardcore mode it will not eat nether stars.

**Comment by capnkirok** [comment]
Yeah, I just looked at the code. It's still set to eat whole Emeralds. This will be updated to Nether Stars.
