### ISSUE TITLE
inventorypet + worldBorder issue

### ISSUE THREAD

**Issue by runescapejon** [capnkirok/Inventory-Pets#197]
hello i ran into an issue and it can effect performance wise if a server owner set a world border to and it to prevent players from loading up new chunk to cause lag on the server
in is how you can get outside the world border you can get a enderman pet or silverfish pet then you right click right next the world border and then you should be outside you can get few slimepets to not die outside the border 
i have tried with version: `1.10-1.4.9.6` Mc 1.10.2
and it works fine 
the world border that i had tried using with it's regular Minecraft mechanics using cmd `/worldborder set`
and i had tried using Nucleus from Spongepowered and it still work you can get outside of the border

**Comment by capnkirok** [comment]
Hey runescapejon!

Yeah, I could see how that could happen. Is there a way for a mod to know where the worldborder is? I can put in a check if so...

PC

**Comment by runescapejon** [comment]
im not sure if there are a mod for worldborder because in 1.8++ mojang made there own worldborder

**Comment by capnkirok** [comment]
Ok, with the changes to WorldGen I made, this will no longer be an issue.

**Comment by runescapejon** [comment]
hm sorry but it seem it's not fixed in 1.12.2
i am using 
inventorypets-1.12-1.4.9.9a

**Comment by capnkirok** [comment]
That's just sad. Do you have a crash report / log for me ?

**Comment by runescapejon** [comment]
where what i did
i went to singleplayer and type
`/worldborder set 20`
then `/worldborder center <X> <Z>`
the X and Z i put in my cords so i can center the worldborder where i am standing so i can bypass it
then i grab an enderman pet and right click it near the border and bypass it you will die if you outside of the border but thanks to slimepet you wont die or you can just use sliverfish pet
LOG: https://pastebin.com/3KrPWRfA

EDIT: and also you can use Sliverfish right click it near world border to bypass it

**Comment by capnkirok** [comment]
Ok, finally figured out how to fix this. Can only do so on 1.10, 1.11, and 1.12
