### ISSUE TITLE
[1.12] Inventory Pets Iron Nuggets Recipe causing conflicts

### ISSUE THREAD

**Issue by capnkirok** [capnkirok/Inventory-Pets#198]
Need to remove the IP recipe and change all recipes to use the default Vanilla.

Credit: cakeymat

**Comment by capnkirok** [comment]
Ok, this is ready and will be in the next release. Will wait a few more days and see if any finds anything else.

**Comment by winsrp** [comment]
waiting for the release!! had high hopes of crafting a pet but, those dang nuggets!!! lol.

**Comment by capnkirok** [comment]
I am amazed there have been no other bugs reported.... looks like i'll just update this one fix
