### ISSUE TITLE
[1.12] Crash when I click RMB on a live bed pet

### ISSUE THREAD

**Issue by Usered238** [capnkirok/Inventory-Pets#199]
In creative mode, I picked up the bed-pet, and, holding Shift, hit the right mouse button. Appeared live bed. I clicked RMB on it, and Minecraft hangs for a few seconds, then closed. In the folder "crash-reports" I found this file: [crash-2017-08-06_11.32.26-client.txt](https://github.com/capnkirok/Inventory-Pets/files/1202847/crash-2017-08-06_11.32.26-client.txt).
I think it will help in solving the problem.
PS.: There was a day.

**Comment by capnkirok** [comment]
Thanks for the report! Probaby affecting the Anvil too, I will check both.

**Comment by capnkirok** [comment]
Ok, this is fixed. It was only the bed :). Will be in the next update.
