### ISSUE TITLE
Idea: 3D Pets

### ISSUE THREAD

**Issue by zzApotheosis** [capnkirok/Inventory-Pets#20]
This just randomly came to me, but I think it would be cool if you could add a way to render the actual pets around the player. Not as actual entities, but simply as a render that stays near the player. Depending on the pet, it could be floating behind the player, sitting on the player's shoulder, walking next to the player, etc.

I know that kind of defeats the purpose of having "inventory pets" but it's just a random idea that came to me. Feel free to dismiss this idea if it strays too far from the mod's theme!

**Comment by capnkirok** [comment]
Feels close to the familiars mod, but it's a fun idea :).  Maybe we could add a pet, or a special recipe that helps bring a pet to life. Thanks for the suggestion.

**Comment by Shahelion** [comment]
Perhaps have it similar to iChun's Guilt Trip mod, where a tiny version floats around the player when active?

**Comment by capnkirok** [comment]
After many discussions, we will probably not do this, so I am closing the idea. It really is a fun idea, though, just no time :)

**Comment by capnkirok** [comment]
By the way, this is now going in with the help of RazzleberryFox :D

**Comment by capnkirok** [comment]
Closing... we'll be adding these over time :)
