### ISSUE TITLE
[1.10.2][1.4.9.6] Update Notification in Chat

### ISSUE THREAD

**Issue by Spazmunki13** [capnkirok/Inventory-Pets#200]
Hello!

Thank you for making this neat mod. :)

I just wanted to let you know that, despite having updated to the latest version 1.4.9.6, I still get a message in chat to update to... 1.4.9.5? Haha.

Not sure why that is.

Thanks!

**Comment by capnkirok** [comment]
Thanks, I forgot to update something :). You can turn this message off in the config (ShowUpdateMessage = false)... or you can wait for the next update :)
