### ISSUE TITLE
[1.12] Coal Nuggets aren't fuel?  They conflict with Mini Coal

### ISSUE THREAD

**Issue by MokahTGS** [capnkirok/Inventory-Pets#201]
In 1.12 coal nuggets which have a conflicting recipe with Mini Coal from Quark are not useable as fuel.  Can this be changed?

**Comment by capnkirok** [comment]
Hmmm... they used to be fuel. Must be a difference between 1.11.2 and 1.12. Thanks for the report.

**Comment by capnkirok** [comment]
Had to do with OreDictionary. Will be fixed in next update.
