### ISSUE TITLE
1.12: Cascading worldgen logs

### ISSUE THREAD

**Issue by Darkmega18** [capnkirok/Inventory-Pets#202]
Hi, I'm getting a decent handful of forge cascading world gen pop-ups every time I generate a world, and they're chain reacting with a handful of other mods and just going off to buggery sometimes if I get bad luck. Would you be able to look into making it not occur? How should I deal with this for now, however? Just turn down the spawn rates of the inventory pets structures so they have less chance to gen more chunks and chain react?

[B#349]  INFO: LifeStreamLake is generated at (14800, 4, 10548)
[B#349]  Aug 21, 2017 7:06:07 PM ak.enchantchanger.eventhandler.GenerateHandler populateLifeStreamLake
[B#349]  INFO: LifeStreamLake is generated at (14884, 13, 10247)
[B#349]  Aug 21, 2017 7:06:10 PM ak.enchantchanger.eventhandler.GenerateHandler populateLifeStreamLake
[B#349]  INFO: LifeStreamLake is generated at (15119, 11, 10768)
[B#349]  [19:06:11] [Server thread/WARN] [FML]: Inventory Pets loaded a new chunk (946, 654  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[B#349]  Aug 21, 2017 7:06:11 PM ak.enchantchanger.eventhandler.GenerateHandler populateLifeStreamLake
[B#349]  INFO: LifeStreamLake is generated at (15294, 14, 10718)
[B#349]  Aug 21, 2017 7:06:11 PM ak.enchantchanger.eventhandler.GenerateHandler populateLifeStreamLake
[B#349]  INFO: LifeStreamLake is generated at (14944, 3, 10315)
[B#349]  Aug 21, 2017 7:06:14 PM ak.enchantchanger.eventhandler.GenerateHandler populateLifeStreamLake
[B#349]  INFO: LifeStreamLake is generated at (14901, 13, 10148)
[B#349]  [19:06:14] [Server thread/WARN] [FML]: Inventory Pets loaded a new chunk (912, 615  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[B#349]  Aug 21, 2017 7:06:17 PM ak.enchantchanger.eventhandler.GenerateHandler populateLifeStreamLake
[B#349]  INFO: LifeStreamLake is generated at (13903, 2, 9328)
[B#349]  [19:06:18] [Server thread/WARN] [FML]: GottschCore loaded a new chunk (932, 655  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[B#349]  Aug 21, 2017 7:06:19 PM ak.enchantchanger.eventhandler.GenerateHandler populateLifeStreamLake
[B#349]  INFO: LifeStreamLake is generated at (15371, 0, 10890)
[B#349]  Aug 21, 2017 7:06:27 PM ak.enchantchanger.eventhandler.GenerateHandler populateLifeStreamLake
[B#349]  INFO: LifeStreamLake is generated at (15069, 13, 10601)
[B#349]  [19:06:28] [Server thread/WARN] [FML]: Inventory Pets loaded a new chunk (934, 683  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[B#349]  [19:06:30] [Server thread/WARN] [FML]: GottschCore loaded a new chunk (958, 685  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[B#349]  Aug 21, 2017 7:06:30 PM ak.enchantchanger.eventhandler.GenerateHandler populateLifeStreamLake
[B#349]  INFO: LifeStreamLake is generated at (15441, 1, 10968)
[B#349]  Aug 21, 2017 7:06:30 PM ak.enchantchanger.eventhandler.GenerateHandler populateLifeStreamLake
[B#349]  INFO: LifeStreamLake is generated at (15440, 9, 11168)
[B#349]  Aug 21, 2017 7:06:30 PM ak.enchantchanger.eventhandler.GenerateHandler populateLifeStreamLake
[B#349]  INFO: LifeStreamLake is generated at (15337, 2, 10944)
[B#349]  Aug 21, 2017 7:06:31 PM ak.enchantchanger.eventhandler.GenerateHandler populateLifeStreamLake
[B#349]  INFO: LifeStreamLake is generated at (15226, 1, 10924)
[B#349]  [19:06:31] [Server thread/WARN] [FML]: Roots 2 loaded a new chunk (967, 694  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[B#349]  Aug 21, 2017 7:06:32 PM ak.enchantchanger.eventhandler.GenerateHandler populateLifeStreamLake
[B#349]  INFO: LifeStreamLake is generated at (15566, 7, 10978)
[B#349]  Aug 21, 2017 7:06:33 PM ak.enchantchanger.eventhandler.GenerateHandler populateLifeStreamLake
[B#349]  INFO: LifeStreamLake is generated at (15572, 15, 11006)
[B#349]  [19:06:33] [Server thread/WARN] [FML]: Inventory Pets loaded a new chunk (973, 693  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[B#349]  [19:06:34] [Server thread/WARN] [FML]: Roots 2 loaded a new chunk (949, 685  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[B#349]  Aug 21, 2017 7:06:34 PM ak.enchantchanger.eventhandler.GenerateHandler populateLifeStreamLake
[B#349]  INFO: LifeStreamLake is generated at (16153, 10, 11517)
[B#349]  Aug 21, 2017 7:06:35 PM ak.enchantchanger.eventhandler.GenerateHandler populateLifeStreamLake
[B#349]  INFO: LifeStreamLake is generated at (16119, 11, 11437)
[B#349]  [19:06:37] [Server thread/WARN] [FML]: Inventory Pets loaded a new chunk (1002, 726  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[B#349]  [19:06:37] [Server thread/WARN] [FML]: ToroQuest loaded a new chunk (1009, 740  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[B#349]  [19:06:39] [Server thread/INFO] [STDOUT]: [net.torocraft.toroquest.generation.WorldGenPlacer:genBastionsLair:68]: ToroQuest Gen Placer: Bastion's Lair BlockPos{x=16183, y=256, z=11912}
[B#349]  Aug 21, 2017 7:06:41 PM ak.enchantchanger.eventhandler.GenerateHandler populateLifeStreamLake
[B#349]  INFO: LifeStreamLake is generated at (15725, 7, 11278)
[B#349]  Aug 21, 2017 7:06:46 PM ak.enchantchanger.eventhandler.GenerateHandler populateLifeStreamLake
[B#349]  INFO: LifeStreamLake is generated at (15775, 14, 11725)
[B#349]  [19:06:48] [Server thread/WARN] [FML]: ToroQuest loaded a new chunk (979, 716  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[B#349]  Aug 21, 2017 7:06:48 PM ak.enchantchanger.eventhandler.GenerateHandler populateLifeStreamLake
[B#349]  INFO: LifeStreamLake is generated at (15689, 9, 11480)
[B#349]  [19:06:49] [Server thread/INFO] [STDOUT]: [net.torocraft.toroquest.generation.WorldGenPlacer:genThroneRoom:89]: ToroQuest Gen Placer: Throne Room BlockPos{x=15670, y=11, z=11405}
[B#349]  [19:06:49] [Server thread/WARN] [FML]: Inventory Pets loaded a new chunk (1006, 733  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[B#349]  [19:06:54] [Server thread/WARN] [FML]: Inventory Pets loaded a new chunk (998, 723  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[B#349]  Aug 21, 2017 7:06:55 PM ak.enchantchanger.eventhandler.GenerateHandler populateLifeStreamLake
[B#349]  INFO: LifeStreamLake is generated at (15680, 5, 11316)

and so on and so forth. :V

**Comment by capnkirok** [comment]
Thanks, will take a closer look. I've updated the code to follow best practices for WorldGen, but it appears there are still some issues. Any idea which 'dungeon' is causing the issue (my guess is the Sea Cave), that will help me narrow it down.

**Comment by Darkmega18** [comment]
Sorry. completely clueless as to which. D: since the mod doesn't say what is spawning. but I know your clouds and tree tops should fit within a chunk. but your underground dungeons might not, since they have two rooms to them. Also, never come across a sea cave, so depending on their size, possibly that too. 

since if I understand it correctly the cascades are caused when a mod spawns a structure that takes up more than one chunk in the wrong way and it procs the world gen to spawn more chunks where even more world gen occurs and then with enough bad luck and structures that are too large being spawned it chain reacts and freezes the game eternally. (like it did for me). I've since turned down the spawn levels anyway by half and that seems to have cut down the issue.

the lifestream lakes are from enchantment changer mod, however they're not cascading, they've just got some debug message attached to them it seems.

**Comment by capnkirok** [comment]
Thanks for the follow up, Darkmega. I will do some bug fixing this weekend.

**Comment by Darkmega18** [comment]
Roger. Good luck. :)

**Comment by capnkirok** [comment]
This is proving harder than I thought, but still working on it. Keep the faith :)

**Comment by Darkmega18** [comment]
Still just got it set lower, and most pets are craftable or toggleable to be craftable in some form. so haven't had a massive freeze into lag to death since I turned it down and removed some other cascading mods. So really the only massive gen-lag bursts i get now are from a roguelike dungeon or dungeons2! dungeon being generated.

You'll find it. You can dooo it!

**Comment by capnkirok** [comment]
Ok, I think I've got it. Will try to get an update out in the next two days.

**Comment by capnkirok** [comment]
Yup, looks good. Gonna throw in a few more fixes before I release.

**Comment by Darkmega18** [comment]
oh balls. 1.12.2. D: I can't get it cause my pack is 1.12.1 and I'm waiting on everything to carry over. :V

**Comment by capnkirok** [comment]
This is my bad, I can make it back-compatible, just forgot. Gimmee a week.

**Comment by Darkmega18** [comment]
thank you. :)
