### ISSUE TITLE
[1.12.1] Bed pet doesn't need food on multiplayer server with more than 1 people

### ISSUE THREAD

**Issue by winsrp** [capnkirok/Inventory-Pets#203]
Bed pet doesn't need food on multiplayer server with more than 1 people

If the server has 2 or more people on connected using the bed pet requires no wool. If you are alone in the server it does requires wool, I think it should always require wool.

**Comment by capnkirok** [comment]
Yes, it should require wool. Thanks for the report.

**Comment by capnkirok** [comment]
I meant to post this awhile back. I can't replicate this error. Finally getting around to closing it.
