### ISSUE TITLE
[1.12]Legendary pet bug

### ISSUE THREAD

**Issue by iTaeyeonKim** [capnkirok/Inventory-Pets#204]
i don't know what happening, but when i     B:"Disable Cloud Recipe"=true set to false i don't get crafting recipe, i mean i still can't craft the cloud one, didn't tried with others but I also checked the .jar file (assets/inventorypets/recipes) and i don't see cloud_pet,json file there or anything that have cloud in, also tried with my own crafting recipe and still nothing

Also i see that you need language helpers, if you need Slovak ( SK ) and Serbian ( RS ) i can be one if you want

thanks

**Comment by capnkirok** [comment]
Ah, yes. The recipes don't exist in 1.12 because of the new recipe system. Good catch. It's not you :)

**Comment by capnkirok** [comment]
Ok this is fixed in 1.4.9.9
