### ISSUE TITLE
feature request config

### ISSUE THREAD

**Issue by IchigoGames** [capnkirok/Inventory-Pets#205]
hay sorry if this is not the right format but i normally only do bug reports.
some one ask me if the chests from the Inventory-Pets mod could be disabled in a config and i got me thinking you should be able to do that hopefully you can add a config option so that if some one only wants to craft Inventory-Pets and not get extra stuff you get in chests all the chests and clouds can be disabled. it would  also help with a issue i had where i disabled bed pets but you could still find and use them.

**Comment by capnkirok** [comment]
All of this is in the config already :)

- You can turn off all the dungeons
- You can turn on crafting recipes for the legendary pets (since by default they can only be found)
- You can disable individual pets as well
