### ISSUE TITLE
[1.12] Enchanting table pet does not work 

### ISSUE THREAD

**Issue by Chaosx3** [capnkirok/Inventory-Pets#206]
Minecraft version 1.10.2
InventoryPets 1.10-1.4.9.6
forge 12.18.3.2422

After placing a weapon, armor, or book in the slot and clicking on any of the enchant buttons nothing happens. Also seems to cause some strange delay when trying to eat afterwords.

**Comment by capnkirok** [comment]
Weird that no-one has not reported this! Yes, this appears to be broken in 1.10. Thanks for the heads up.

**Comment by capnkirok** [comment]
Ok, this is fixed. Will be in next release.

**Comment by capnkirok** [comment]
Issue found again with 1.12 when in Survival Mode

**Comment by capnkirok** [comment]
Ok, fixed in next release
