### ISSUE TITLE
Sheep Pet only works in single player, multiplayer it only works on one person at a time.

### ISSUE THREAD

**Issue by ghost** [capnkirok/Inventory-Pets#207]
Minecraft version 1.10.2
InventoryPets 1.10-1.4.9.6
forge 12.18.3.2477

When one person on a server uses the Sheep Inventory Pet, they take no damage from falls. When multiple people have it in their hotbar, it doesn't work for anyone. We have tried this with both people using it, then one removing and trying, then the other trying it. It always works when only one person is using it and it never works when both are using it. It worked in version 1.10-1.4.9.5, it broke in 1.10-1.4.9.6.

Edit: We can't get it to work properly in the older version now either. We tried new config files and everything. We did, however, find an interesting work around. If you and anyone else on the server has the sheep pet both on your hotbar AND in your inventories, it works (2 sheep per person). It only works that way, not if any of them are in backpacks or other spaces.

**Comment by capnkirok** [comment]
Wow, that is bizarre. Have never tested this scenario before, so thanks for the detail.

**Comment by capnkirok** [comment]
Ok, this will be fixed at next update. On 1.12, this fix goes into 1.4.9.9a.
