### ISSUE TITLE
Glitched Biome

### ISSUE THREAD

**Issue by DamadmanGD** [capnkirok/Inventory-Pets#208]
every single oak tree in the taiga biome has a chest in it

**Comment by capnkirok** [comment]
What version of Minecraft are you running?

**Comment by capnkirok** [comment]
Hey @DamadmanGD I'm closing this as I just completely redid worldgen, and things tested fine. If you think the WorldGen is too high (which it is), you can always turn the frequency down in the config. Default is 5 (out of 10). Might recommend 2 if you have the same issue going forward.

**Comment by capnkirok** [comment]
#202
