### ISSUE TITLE
[1.7.10] Sky Clouds Crash

### ISSUE THREAD

**Issue by ZEROOblivious** [capnkirok/Inventory-Pets#209]
I'm not sure if you're still caring about the 1.7 version of the mod, but I've been having a Ticking Crash with the clouds.

I think its just them consonantly ticking and waiting to spawn in blazes it just crashes the server, could be because of low RAM on the server but, thought id point it out. 

Here is the crash report on Pastebin!

https://pastebin.com/bCJAJiEK

**Comment by capnkirok** [comment]
Yes, still I still care :) Actually this is a ticking sand spawn block (so underwater dungeon). Are you playing on a server with limited size?

**Comment by ZEROOblivious** [comment]
Limited Size of RAM or players? If players yes it can only support about 70 people? Atleast that's what the Host Company says lol, But however I only have a max of at least 20 people. Its a private server just for a few friends.
RAM size is currently 3.5GB, However I do have it Restart every 6 hours.

**Comment by capnkirok** [comment]
No, I meant world border... are you limited to a certain number of blocks/chunks? (this is an important detail).

**Comment by ZEROOblivious** [comment]
No its Unlimited - However I keep the players KINDA close to eachother but still out exploring is non stop.

**Comment by capnkirok** [comment]
Thank you for the follow up! Going to see what I can do.
