### ISSUE TITLE
Warp speed bug (w/ Astral Sorcery)

### ISSUE THREAD

**Issue by DeiusShrab** [capnkirok/Inventory-Pets#211]
While using the squid pet underwater, a player that has received the Vicio Attunement (speed buff + swim speed buff) from Astral Sorcery will begin accelerating infinitely to the point that the map loading cannot keep up and they move through terrain before it has loaded.

**Comment by DeiusShrab** [comment]
[Crossposted to the Astral Sorcery issue tracker](https://github.com/HellFirePvP/AstralSorcery/issues/300)

**Comment by capnkirok** [comment]
Ha ha. I see he put down wontfix on this one. Ok, well, what I recommend you do is to enable disableSquidSpeed in the InventoryPets config. Sorry I didn't reply earlier.
