### ISSUE TITLE
[1.12.2] Cannot get recipe for feed bag from JEI

### ISSUE THREAD

**Issue by Knito58** [capnkirok/Inventory-Pets#214]
MC 1.12.2, Forge 14.23.0.2515, Inventory-Pets 1.4.9.9a, JEI 4.8.0.11

Using JEI to get the recipes for everything. The recipe for the the feed bag is not shown when clicking on the bag in the JEI's list.

**Comment by Mythrrinthael** [comment]
The problem I'm having is that JEI doesn't show the recipe because _it can't find one_. The recipe for the feed bag is simply absent from the game. Using the crafting recipe mentioned on the wiki/the forum post produces no results. @capnkirok

**Comment by capnkirok** [comment]
Yeah, the recipe is just missing guys. We'll get it in the update.

**Comment by capnkirok** [comment]
This is fixed in the next update. If you want it right away, however, you can just switch the config for 'Disable Feed Bag Recipe' to true. It looks like I implemented the config backwards. Just remember to switch the config back after the update comes out.

**Comment by Knito58** [comment]
Thanks - it works now for me.

**Comment by capnkirok** [comment]
Yay!
