### ISSUE TITLE
The pet won't work sometimes...

### ISSUE THREAD

**Issue by Jaycraft03** [capnkirok/Inventory-Pets#215]
So I was making a few pets I had one down and it worked but when I crafted the next the 2nd one didn't work and I know I had food for it but it for some reason just desided not to work. If someone could fix this it would be great because I can't play my modpack without this being done.(the reason for that is because it is apart of my acheivement book to get certain ones and battle something with their ability)

**Comment by capnkirok** [comment]
Hey @Jaycraft03 which pet is not working? What version of Minecraft are you using? Also, sounds like you are using a modpack... which one?

**Comment by capnkirok** [comment]
Hey @Jaycraft03 I'm going to close this one since it's you haven't responded. Hopefully you figured it out.
