### ISSUE TITLE
Sea Caves Spawning in Open Water

### ISSUE THREAD

**Issue by Faedelity** [capnkirok/Inventory-Pets#216]
Using Inventory Pets in 1.7.10 with quite a few other mods- will run comparison checks for mod interaction probably Sunday. Pretty much what it says on the tin- IP sea caves are spawning every hundred blocks or so in the Deep Ocean biome when using Biomes O' Plenty. World seed I encountered the bug in first is 199998776. Please let me know what other information would be helpful.

**Comment by capnkirok** [comment]
Yeah, I moved the caves to open water, but now they seem more frequent. As a temporary fix until I can get an update out, you can lower the frequency in the config to something like 1 or 2 and see if that is better during WorldGen.

**Comment by capnkirok** [comment]
Ok in the next release, I've reduced the spawning of Sea caves substantially (literally 85% reduction).
