### ISSUE TITLE
Disable recipes config not working properly in 1.12-1.4.9.9a

### ISSUE THREAD

**Issue by virmodoetiae** [capnkirok/Inventory-Pets#218]
I wanted to make the mod a little less OP and add a bit more incentive to explore the world by disabling all pet recipes, so that they would be obtainable only via loot from treetops, dungeons, etc.. However, for some reason, the Spider, Pac-man and Pingot pet recipes are still available (and thus these pets are still craftable) even after setting all the recipes for all pets to false (i.e. "disable recipe [...]" set to "true" in the config file). Can this be easly fixed? The version I am using is 1.12-1.4.9.9a, the latest. Thanks! Great mod by the way!

**Comment by capnkirok** [comment]
Must be a bug. Will take a look, thanks!

**Comment by capnkirok** [comment]
Yeah, typos. Super dumb. Ok fixed in dev will be in next release (1.4.9.9b)
