### ISSUE TITLE
Spawn Egg from Petmas is a blank! (1.12.2, 1.11.2, and maybe other versions.)

### ISSUE THREAD

**Issue by GlitchReaper** [capnkirok/Inventory-Pets#219]
The Spawn Iron Golem received from December 19th (6th day of Petmas) event is a blank Spawn item instead on these versions. I believe this is because of the Forge overhaul on how Spawn Eggs are handled. (I know it was supposed to be an Iron Golem because it works fine on 1.7.10.)

**Comment by capnkirok** [comment]
Yes, you are correct. Totally forgot about this one. Thanks for flagging.

**Comment by GlitchReaper** [comment]
I was doing part of a mod review for Inventory Pets when it happened. It's one of the reasons I had to bounce between profiles for my "Twelve Days of Petmas" segment. The Easter Egg that spawns CEOs still works fine though. Maybe it just doesn't like assigning an Iron Golem to a Spawn Egg?

**Comment by capnkirok** [comment]
I'm going to swap this out with another 'gift', looks like Iron Golem spawn egg is no longer available.

**Comment by capnkirok** [comment]
Yeah, also affected 1.10 and 1.11! Thanks for catching this one!
