### ISSUE TITLE
Cloud Pet Not Able To fly

### ISSUE THREAD

**Issue by Crystalsama12** [capnkirok/Inventory-Pets#220]
So when I started playing my world I went searching for the cloud pet and when I got it I wasn’t able to fly even though it was in my hot bar and it wouldn’t work for me I’m running a 1.7.10 world

**Comment by capnkirok** [comment]
Is it possible you have another mod that provides flight? It's possible that is is interfering. What version of IP are you using?

**Comment by capnkirok** [comment]
Closing since I haven't heard back. Likely a compat issue. Please report back if you find out.
