### ISSUE TITLE
Cloud Pet Flight Not Allowing Me To Shift

### ISSUE THREAD

**Issue by JamesSkullBlood** [capnkirok/Inventory-Pets#221]
I gotten the cloud pet and it is not allowing me to shift while on the ground, and it still gives me the speed boost as if I was flying, but I am not. I am using the inventory pet version 1.4.9.9a (1.4.9.9a) the 1.12.2 version. I remember back when the mod was 1.7.10 the cloud pet allowed shifting while on the ground.
Example:
I was mining to get Obsidian and I was shifting and I died in lava that was under the obsidian that I've mined.

**Comment by capnkirok** [comment]
A loyal player I see :)

Let me see if I can repro based on your example.

**Comment by JamesSkullBlood** [comment]
Thanks for responding, I hoping it get fixed soon and I really hope I've explained it good enough since I am not a very good explainer, so good luck! I think it is staying me in perm flight mode even while on the ground, which means, I shouldn't be flying.

**Comment by JamesSkullBlood** [comment]
How's the investigating coming along? I would really want to start playing again soon as possible. I've stopped playing until this gotten fixed.

**Comment by JamesSkullBlood** [comment]
Anything new? I know it takes time to fix this, but may you please give an update so I will approximately know when it will be fixed?

**Comment by capnkirok** [comment]
Hey @JamesSkullBlood ... i'm not seeing an issue, so it looks like a conflict of some sort. Can you share with me your version of Forge and also other mods you are using?

**Comment by JamesSkullBlood** [comment]
I tried it with ONLY the inventory pet mod and I still was getting perm flight even when I was on the ground meaning whenever i shift, I am not actually shifting. I did get the pet from creative mode, but it isn't me getting it from creative mode, as when I tested it out in 1.7.10 it was working fine. Meaning I was actually shifting and not going down a block when I shouldn't be able to.
Try to do this example:
I was flying around with the cloud pet, I then go down on the ground, I should be walking at normal speed, but I was still getting the fly speed boost. I know I am not flying as when I go over a 3by3 area where the middle of it is all broken I will fall right into it like normal, but when I hold shift to NOT fall into the hole, I still fall into the hole no matter what.
Example ended.

Okay this is my version of Forge:
1.12.2-forge1.12.2-14.23.1.2587

I know it is NOT any of my other mods as I have tested it out with only the inventory pet mod but here I will give a screenshot of the mods.
![screenshot_61](https://user-images.githubusercontent.com/35322531/35195774-f0369730-fe8d-11e7-80e6-7fb317c92c44.png)

**Comment by capnkirok** [comment]
Thanks for the steps, forge version, and modlist. Let see if we can figure this out! I have to get an Animania update out first, so be patient for a few more days, thanks!

**Comment by JamesSkullBlood** [comment]
Thank you for giving an estimate of when the issue will (hopefully) be fixed. I hope the new steps will come with improved results. To make it more visual here is an imagine of what to see it as to make it better to look at.
Here it is, I hope this is a better visual imagine. Sorry it doesn't look as neat, but it is a good visual imagine.
![screenshot_62](https://user-images.githubusercontent.com/35322531/35197820-0f7a592a-feab-11e7-92dc-8ad0570e13af.png)

**Comment by capnkirok** [comment]
Verified! Yes, this is not working properly. Thank you for the visual!

**Comment by JamesSkullBlood** [comment]
Aye, Glad to be of help, cannot wait for this to get fixed so I can start playing my modded survival again! 👍

**Comment by capnkirok** [comment]
Ok, I've fixed this in my dev environment. Will be in next release. Going to try to throw a couple more bug fixes in before I release. But soon!
