### ISSUE TITLE
ocelot pet scares creepers world wide

### ISSUE THREAD

**Issue by payonel** [capnkirok/Inventory-Pets#222]
multi-player issue where one player is using an ocelot pet, and other players 800m away see creepers running towards them

**Comment by payonel** [comment]
inventorypets-1.12-1.4.9.9a.jar

**Comment by capnkirok** [comment]
Interesting. It should have a limited range, as you suspect. Thanks.

**Comment by payonel** [comment]
@capnkirok btw, seriously LOVE the mod! did not expect to enjoy it this much :)
and seeing the wave of creepers running at me over the horizon was awesomely terrifying

**Comment by capnkirok** [comment]
Finally figured this out out, was exactly as you said. Any creeper in active chunks stays in a constant state of panic. Just because one player (somewhere) has the Ocelot pet in their hotbar. Now that's OP.

Fixed in the next release.
