### ISSUE TITLE
Is this supposed to happen?

### ISSUE THREAD

**Issue by 1nfern00** [capnkirok/Inventory-Pets#223]
My cloud pet broke while I was underwater mining. Are there any mods that could cause this?

**Comment by 1nfern00** [comment]
inventorypets-1.12-1.4.9.9a.jar

**Comment by JamesSkullBlood** [comment]
I am not the one who can help you, but I think you should explain what it is doing when since it broke.

**Comment by 1nfern00** [comment]
I was mining straight down with a fast modded pickaxe, when suddenly I hear a break noise and my cloud pet is gone. Was in a deep ocean biome.

**Comment by capnkirok** [comment]
Thanks for the context. Pets are not supposed to disappear, no. Sounds like a bug or a conflict.

Any idea what the durability on the Cloud was? Was it hungry, for instance?

**Comment by 1nfern00** [comment]
Yes, it had just got hungry again when it broke. I had accidentally ran out of nether quartz when it happened.

**Comment by capnkirok** [comment]
I can't replicate this unfortunately. I did various tests, all using your scenario outlined above. It sounds like the Cloud Pet somehow got damaged twice. The first one due to hunger, but then it somehow got damaged again. If somehow it gets damaged, it will indeed disappear. This could be a conflict. But it seems like a freak occurrence. Can you share your modlist?

**Comment by 1nfern00** [comment]
Sorry I took so long. Here:
 ae2stuff-0.7.0.4-mc1.12.2
  AppleSkin-mc1.12-1.0.9
  appliedenergistics2-rv5-stable-6
  base-1.12.2-3.5.0
  bdlib-1.14.3.12-mc1.12.2
  Bedrock Ores-MC1.12-1.2.5.38
  BiomesOPlenty-1.12.2-7.0.1.2312-universal
  Bookshelf-1.12.2-2.3.523
  BrandonsCore-1.12-2.3.7.140-universal
  ChestTransporter-1.12-2.8.7
  ChickenChunks-1.12.2-2.4.1.71-universal
  Clumps-3.0.0
  CodeChickenLib-1.12.2-3.1.5.331-universal
  CoFHCore-1.12.2-4.3.10.4-universal
  CoFHWorld-1.12.2-1.1.1.12-universal
  DarkUtils-1.12.2-1.8.193
  Draconic-Evolution-1.12-2.3.8.279-universal
  ElevatorMod-1.12.2-1.4.0
  EnderStorage-1.12.2-2.4.2.126-universal
  energyconverters_1.12.1-1.0.1.2
  ExtremeReactors-1.12.2-0.4.5.46
  forestry_1.12.2-5.7.0.238
  gravestone-1.10.0
  Hwyla-1.8.23-B38_1.12
  inventorypets-1.12-1.4.9.9a
  InventoryTweaks-1.64-dev
  ironchest-1.12.2-7.0.34.820
  jei_1.12.2-4.8.5.144
  journeymap-1.12.2-5.6.0b1
  MagicBees-1.12.2-3.1.9
  Mantle-1.12-1.3.1.21
  Morpheus-1.12-3.3.2
  NaturesCompass-1.12.2-1.5.1
  Neat 1.4-15
  NotEnoughItems-1.12.2-2.4.1.233-universal
  OpenComputers-MC1.12.1-1.7.1.54
  OpenGlider-1.12.1-1.1.0
  RedstoneFlux-1.12-2.0.1.2-universal
  Scannable-MC1.12-1.6.2.13
  stg-1.12.2-1.2.3
  TConstruct-1.12.2-2.9.0.55
  ThermalDynamics-1.12.2-2.3.10.4-universal
  ThermalExpansion-1.12.2-5.3.10.12-universal
  ThermalFoundation-1.12.2-2.3.10.6-universal
  torchmaster_1.12.2-1.6.1.53
  VeinMiner-1.12-0.38.1.639+134fb1e
  Waystones_1.12.2-4.0.20
  zerocore-1.12-0.1.1.0

**Comment by capnkirok** [comment]
Thanks @1nfern00 won't get to this one in the release that's coming out today... let me know if it happens again... I will keep this one open.

**Comment by capnkirok** [comment]
I tried again to replicate this with the other mods, but can't. Going to close this one now. I assume it hasn't happened again and I've had no other reports.
