### ISSUE TITLE
Support for Tinkers Construct Tools

### ISSUE THREAD

**Issue by Nitrama** [capnkirok/Inventory-Pets#225]
Add Support for Tinkers Contruct Tools

**Comment by capnkirok** [comment]
This one is a tough one, as the tools follow their own rules outside of Minecraft. But maybe you can add more detail? What tool? What purpose?

**Comment by capnkirok** [comment]
I'm going to close this one. There's very little I can do right now. However, with 1.13 Tinkers will be forced to not use Metadata anymore to store their tool types/values. We'll take a look again then.
