### ISSUE TITLE
Suggestion: Poo Bag

### ISSUE THREAD

**Issue by Knito58** [capnkirok/Inventory-Pets#226]
Just to have more space in the inventory:

The feed bag is one thing to clean the inv up and the pet which holds other pets is already suggested.

What about a bag which would catch all the items which are otherwise spit into your inventory from active pets?

**Comment by capnkirok** [comment]
You can turn the 'give' items off in the config if you want. Disable Pets Give Items. Does that help?

**Comment by Knito58** [comment]
Hmmm.... I want that items in early game. It is an idea and would not clutter the inventory but still the items are needed.

**Comment by capnkirok** [comment]
Ok, thanks for response. I'll leave it up as an enhancement. I'll probably give it a different name though 😄

**Comment by Knito58** [comment]
Pheeew.

**Comment by capnkirok** [comment]
Ok, I've implemented an enhancement in the 2.0 release. Basically, you can toggle on/off the 'giving' of items on a pet by pet basis, with a simple sneak-right-click.

**Comment by Knito58** [comment]
So this would be In-Game? w/o leaving the game to get into mod-config-mode? Not quite what I suggested but very helpful.

**Comment by capnkirok** [comment]
Yup, in game.
