### ISSUE TITLE
Loot Pet bugs

### ISSUE THREAD

**Issue by Foxgreat** [capnkirok/Inventory-Pets#227]
Here some bugs what i found if i have loot pet active.

If i dig any ore frome Immersive engineering it wont drop any of ore. 
Same with Marble from Ore Core.

If i dig a redstone ore with silk touch - drops dust, not ore. Same with glowstone and modded tile ore drops.

**Comment by capnkirok** [comment]
Thanks. Will look into it.

**Comment by capnkirok** [comment]
Hey sorry for late reply. The loot pet auto-smelts everything. This is to prevent duping of items that have the chance to drop more than one item (e.g., place, break, get 2, do it again).
