### ISSUE TITLE
Player Inventory Check Error

### ISSUE THREAD

**Issue by nickick7x3** [capnkirok/Inventory-Pets#229]
Minecraft Version

1.12.2

Forge Version

1.12.2-14.23.2.2611

Mod Version

Latest

Describe your problem, including steps to reproduce it

Install pneumaticcraft and IP.

Created a drone with pneumaticcraft
Programmed drone to dig
Server crashes when a player loads the chunk the drone is in
Ticking Entity exception caused by inventory pets checking the drone's inventory and checking out of the array size

First 5 lines of the error report should show the error, I have attached the pastebin below.
"Description: Ticking entity

java.lang.RuntimeException: Slot 1 not in valid range - [0,1)
at net.minecraftforge.items.ItemStackHandler.validateSlotIndex(ItemStackHandler.java:210)
at net.minecraftforge.items.ItemStackHandler.getStackInSlot(ItemStackHandler.java:75)
at me.desht.pneumaticcraft.common.entity.living.EntityDrone$InventoryFakePlayer.func_70301_a(EntityDrone.java:1319)
at com.inventorypets.events.HarvestHandler.onPlayerBreaking(HarvestHandler.java:109)"

Any other comments?

Initially checked with Pneumaticcraft author, he discovered the issue is with Inventory Pets. https://github.com/TeamPneumatic/pnc-repressurized/issues/128

"Inventory Pets needs to check the size of the inventory it's iterating over (using getSizeInventory()) and not assume the number of slots. This will break for any mod which uses a FakePlayer (whose inventory is less than 9 slots) to break blocks."

For now it can be dealt with by disabling Inventory Pets, however this is not ideal.
Pastebin:
https://pastebin.com/02rXLZvM

**Comment by capnkirok** [comment]
Thanks @nickick7x3 yes, the Pneumaticraft author is correct. In most locations I do check size first.

**Comment by capnkirok** [comment]
Ok, this is fixed in Dev and will be in next release.
