### ISSUE TITLE
[Suggestion] Turning off the Cloud Pet's Thunder sound being heard server-wide

### ISSUE THREAD

**Issue by KelleyEngineering** [capnkirok/Inventory-Pets#230]
Name is in the title, request an option be put in to remove the thunder-sound being heard server-wide when the cloud pet's secondary ability is used.

**Comment by capnkirok** [comment]
Ah yes, this can probably be quite annoying.

**Comment by tyler489** [comment]
The mod "Bad Wither No Cookie" solves the thunder sound as a work around

**Comment by capnkirok** [comment]
Ok added a config option to turn this off. Will be in next release.
