### ISSUE TITLE
 bug between anvil pet entity and pokecube mods

### ISSUE THREAD

**Issue by joelkingg** [capnkirok/Inventory-Pets#231]
Steps to reproduce
1. summon the anvil entity out
2. have your poke attack the anvil entiy
3. crashes the game and loops, stops only when removing pokecube but continutes still with removal of inventory pets.

**Comment by joelkingg** [comment]
https://paste.ubuntu.com/p/TNFcRvyPNB/

**Comment by capnkirok** [comment]
Sorry for late reply. Have you reported this to Pokecube author? 

The error is here: 
`java.lang.ClassCastException: pokecube.core.entity.pokemobs.GenericPokemob_gardevoir cannot be cast to net.minecraft.entity.player.EntityPlayer`

**Comment by capnkirok** [comment]
Directly related to #376
