### ISSUE TITLE
CLOUD PET PROBLEMS/BUG

### ISSUE THREAD

**Issue by ghost** [capnkirok/Inventory-Pets#232]
When cloud pet is equipped, it makes us double jump!
i dont know if this is meant to happen but it happens! also the speed is crazy! is there anyway of turning it down a bit?

**Comment by JamesSkullBlood** [comment]
I am not someone who can help you with this sadly, but does this also happen to you https://github.com/capnkirok/Inventory-Pets/issues/224 (Click the #244) that is my issue I made about 3-4 months ago and he hasn't commented on it in a while. I don't know what is going on with Capnkirok.

**Comment by ghost** [comment]
Yes, it also happens to me. When I press shift i suddenly get pulled down to the ground. It's like my inner demon is telling me to come back home im so confused

**Comment by capnkirok** [comment]
Hey guys. Yeah, I started a new job, and have been very busy. This is a conflict with another mod and is due to a fix I recently made. I may have to roll back the fix if I can't identify the problem.

**Comment by capnkirok** [comment]
Actually, this is not a compat issue. It's just a bug. This is directly related to the fix I made @JamesSkullBlood . Shift to float down works in Creative mode, but not in Survival. Will be fixed in next release.

**Comment by capnkirok** [comment]
Fixed in Dev for 1.7.10. Was able to make it work without rolling back.

Also added support for preventing walking of edge while using Cloud Pet on 1.10, 1.11, 1.12
