### ISSUE TITLE
Additional cost for spawn Anvil Pet?

### ISSUE THREAD

**Issue by nathanjfealko** [capnkirok/Inventory-Pets#235]
Hi, I've noticed that I can severely abuse the spawn-Anvil-Pet ability in conjunction with a few of my other mods...such as mass spawning it for ingot drops or blood (ala EvilCraft).

For a personal sense of balance, is there a way I can add an activation cost to spawning an Anvil Pet? Say, 2 or 3 nuggets or something?

**Comment by capnkirok** [comment]
I will limit it so you can only Spawn 1, using the same method from the Wolf Pet. Thanks for the post.

**Comment by nathanjfealko** [comment]
Thanks, that solution will be perfect.

**Comment by capnkirok** [comment]
Ok, this will be fixed in update.
