### ISSUE TITLE
Apple pet bug

### ISSUE THREAD

**Issue by mxnmnm** [capnkirok/Inventory-Pets#237]
Whenever I use an apple pet it hits me with the apple (it still shoots a projectile) this includes the golden apple aka I get stuck in the ground whenever I use it.  Using mod version 1.12-1.4.9.9b

**Comment by capnkirok** [comment]
I'm not able to replicate your error. 

Can you send me screenshot? Also version of Forge you are using. And are you just in Single Player?

**Comment by mxnmnm** [comment]
https://imgur.com/a/TN0o2Ac

forge 1.12.2-14.23.4.27055

Yes this is single player

**Comment by capnkirok** [comment]
Ahhh... thanks for the video. It doesn't look like it's doing damage, but I see the particle effects as if it is landing on the player when it is initially thrown.

**Comment by capnkirok** [comment]
Ok, this will be fixed in next release (1.5).
