### ISSUE TITLE
Mooshroom pet incompatibility with pam's harvestcraft

### ISSUE THREAD

**Issue by mxnmnm** [capnkirok/Inventory-Pets#238]
When I try to use the bonemeal feature on a pam's harvestcraft crop, the pet disappears.

**Comment by capnkirok** [comment]
What version of mc, forge, HC and IP are you running?

**Comment by capnkirok** [comment]
I can't replicate this problem. Using latest version Pam's HarvestCraft 1.12.2u.jar and latest IP.

**Comment by capnkirok** [comment]
I'm going to close this one. Please comment again if you can provide more details, but since it's working fine with the latest versions, nothing I can do.

**Comment by mxnmnm** [comment]
Pam's HarvestCraft 1.12.2u, inventorypets-1.12-1.4.9.9b and forge 1.12.2-14.23.4.27055

With further testing it seems to also happen with vanilla crops and I've disabled the pet's eating feature

Here's a vid of what's happening https://imgur.com/a/ShzMzOL

**Comment by capnkirok** [comment]
Ok, let me test this again, based on your video (thanks again for the visual and the details).

**Comment by capnkirok** [comment]
Yeah, I have no problems. I matched your specs. My guess is another mod is interfering, which makes sense, since no one else has reported this. 

Also, the mooshroom pet doesn't take damage when you use right click. It eats based on a timer. Meaning some other mod is damaging the Mooshroom.

Can you post your modlist?

**Comment by mxnmnm** [comment]
Would it be ok if I directly sent you the mods?  Mainly because I have a lot of mods and I haven't updated most of the mods in a few months (planning on updating soonish) but mostly because I'm lazy lol

**Comment by capnkirok** [comment]
That's even better and will save me time. You can load them up into a dropbox (or whatever) and send me the link.

**Comment by mxnmnm** [comment]
https://drive.google.com/open?id=1QiEuK_3Xt4kxNTLRRjRRedKgZLwP9paQ

**Comment by capnkirok** [comment]
I didn't figure out what mod it was, but it is fixed in the next release. I had added a hook into Forge, which opened it up for other mods to play with. Anyway, working now.
