### ISSUE TITLE
Anvil pet rollback the repair

### ISSUE THREAD

**Issue by sahilewaya** [capnkirok/Inventory-Pets#239]
When using the pet anvil, sometimes the repair goes back when moving the repaired items inside the inventory. It is not always what happens, but every 5 repairs, at least 1 back.

**Comment by capnkirok** [comment]
Are you in MP or SP

**Comment by sahilewaya** [comment]
SP, im playing with another mods, and the anvil pet works with all the armors and tools from other mods.

**Comment by capnkirok** [comment]
This sounds like a client/server desync. Let me see if I can replicate/pinpoint.

(even SP has a server, in case you are wondering, it's just integrated)

**Comment by capnkirok** [comment]
Yep. It was repairing on the client side occasionally, which never gets stored on the server, hence the rollback. Can't believe this wasn't found before! Fixed in the dev environment. Will be in the 1.5 update.

**Comment by sahilewaya** [comment]
WOW! You're fast xD
Thanks for answering /o/
