### ISSUE TITLE
[1.12.2] Player bounces across the water with no pet and dies from fall damage

### ISSUE THREAD

**Issue by RyanP1991** [capnkirok/Inventory-Pets#243]
When playing when with just Forge 14.23.4.2708 and Inventory Pet version 1.5 for version 1.12 the player will bounce across the surface and will build momentum and dies when hitting solid ground.

Video evidence - https://www.youtube.com/watch?v=GtpMTx5pXUc&feature=youtu.be

**Comment by capnkirok** [comment]
Oh crap. I know what happened here.

**Comment by capnkirok** [comment]
Hey @RyanP1991  Well, thank god this looks like a compat issue (conflict with another mod). It's working fine standalone. Still need to feed though. Can you post your modlist asap?

**Comment by RyanP1991** [comment]
Hello, thank you for the fast reply. 

Here is the pack with the list of mods added:

https://minecraft.curseforge.com/projects/the-ryrypatpatpackpack

I shall double check soon if your fix has helped.

**Comment by JamesSkullBlood** [comment]
I also have this problem and I just tested it without any other mods and it still does it.

**Comment by capnkirok** [comment]
Ah yes, I see it now. You can jump on water without the Sponge Pet if you time it right. Thanks both.

**Comment by capnkirok** [comment]
Ok, this is fixed. Same issue also with Magma Cube pet, which is also fixed. Will be in 1.5.1 release.
