### ISSUE TITLE
Flying is perm

### ISSUE THREAD

**Issue by JamesSkullBlood** [capnkirok/Inventory-Pets#244]
I was using the cloud pet and was mid air when i took it out of my inventory and I was still flying even with it not in my inventory, no other mods is added. I also have another thing is, Walk speed and Fly speed seem to have change with the cloud pet, instead of getting faster flight I will get faster walking/running. I would also like to have a config for the flying speed. If needed I can make them 2 last things into separate things, and this is in 1.12.2

**Comment by capnkirok** [comment]
1.7.10?

**Comment by JamesSkullBlood** [comment]
Read the post again, was editing it.

**Comment by capnkirok** [comment]
Actually all versions it looks like. Exactly as you say. Once you remove the cloud flying becomes permanent. Requires you to have it first though. Thanks!

**Comment by JamesSkullBlood** [comment]
Alright, do you want me to make a separate thing about them last 2 things i said? With the flying speed config and the fast flight changed to faster walk speed?

**Comment by capnkirok** [comment]
Yeah, you can put those two into one suggestion. Thanks!

**Comment by JamesSkullBlood** [comment]
So, a bit confused, the second thing the "fast flight is changed to faster walk speed" that is a bug as far as I'm aware of since I am not getting fast flight with cloud pet. The one with the flying speed config is the suggestion.

**Comment by JamesSkullBlood** [comment]
Eh I will make 2 posts

**Comment by capnkirok** [comment]
Ok this one is fixed in next release, version 1.5.1, will go out later today.
