### ISSUE TITLE
Apple pet- Golden apples

### ISSUE THREAD

**Issue by mxnmnm** [capnkirok/Inventory-Pets#245]
Regular apples are fixed but golden apples still hit the player.  You don't sink into the ground but if you're flying it brings you down.  And it always blanks out the screen for a second which is annoying.  Again this is only with the golden apples.

https://imgur.com/a/9xnztSp

forge 1.12.2-14.23.4.27055

single player

inventory pets 1.5

**Comment by JamesSkullBlood** [comment]
Can confirm this as well to be in 1.12.2

**Comment by capnkirok** [comment]
Man, I didn't even look at the Golden Apples.

**Comment by capnkirok** [comment]
Ok, this is fixed. Made a better implementation as well so the Apple doesn't pass before your eyes when you toss it. Will be in 1.5.1
