### ISSUE TITLE
Flying Speed Config

### ISSUE THREAD

**Issue by JamesSkullBlood** [capnkirok/Inventory-Pets#247]
The title explains it.
I think there should be a fly speed config for those who wants to change the flying speed.
Maybe somewhere from 1-3 with 3 being the faster flying and 1 being a normal flying speed you would normally get with creative mode. Maybe the default could be set to 2? I don't know how hard that could be to code. If needed you can change the numbers up.

**Comment by capnkirok** [comment]
This is added in 1.5.1
