### ISSUE TITLE
Shifting Off Edges Again

### ISSUE THREAD

**Issue by JamesSkullBlood** [capnkirok/Inventory-Pets#249]
Hey, well remember that bug you fixed before about my issue with the cloud pet and how you can shift off edges? Well it is back. I am not gonna go into many details as you already fixed this bug before.
Mod Version: 1.5.1
Minecraft Version: 1.12.2

**Comment by JamesSkullBlood** [comment]
Also, once you get the cloud pet, you won't take fall damage even if it is out of your inventory until you re-log back into the world you are playing with the mod.
Mod Version: 1.5.1
Minecraft Version: 1.12.2

**Comment by JamesSkullBlood** [comment]
And the final thing for me to say is this.
![screenshot_40](https://user-images.githubusercontent.com/35322531/41813282-65c4ce6c-76f8-11e8-9ab0-6c9d2449165e.png)

It is saying that when it is in version 1.5.1
Mod Version: 1.5.1
Minecraft Version: 1.12.2

**Comment by capnkirok** [comment]
1) Disappointing. I think it works if you are over lava. 
2) That's not good
3) I haven't updated the versioning server yet

**Comment by JamesSkullBlood** [comment]
The shifting doesn't work when I am over lava :(

**Comment by capnkirok** [comment]
Ok, I got it working again, and with everything else. Sheesh. This is all tied together... Sponge on Water, Compats for other flying mods, config speeds, and peeking.

For the record, Draconic Evolution doesn't work with peeking. Once you put that armor on, peeking won't work until you remove armor and then re-start (nothing to do with Inventory Pets).

**Comment by capnkirok** [comment]
The fall damage bug after cloud removal has been in code since the beginning (I just spent the last 3 hours testing). I'm going to make a note of it for 2.0 release, but won't fix for now. 

The same happens by the way for Draconic Armor.
