### ISSUE TITLE
Apple pet doesn't do damage

### ISSUE THREAD

**Issue by mxnmnm** [capnkirok/Inventory-Pets#250]
The apples and golden apples hit the mobs but they don't do any damage or sink them into the ground.

forge 1.12.2-14.23.4.27055

inventory pets 1.5.1

vid-https://imgur.com/a/Yyq1tyd

**Comment by mxnmnm** [comment]
Golden apples occasionally sink mobs in the ground but it's rather rare and unreliable and it still doesn't do any damage.  They also pop right back up out of the ground.

**Comment by capnkirok** [comment]
Thx. Sigh.

**Comment by capnkirok** [comment]
Ok, this one definitely fixed now. My mechanism from preventing player damage was preventing all damage.... I made a completely different implementation.
