### ISSUE TITLE
Inventory Pets 1.5.1 prevents flight from other mods

### ISSUE THREAD

**Issue by UntoldForce** [capnkirok/Inventory-Pets#251]
I upgraded my mod pack with a single change-Inventory Pets went from 1.5 to 1.5.1. Now I cannot fly while using Draconic Armor. I believe this may be a result of the following change

Players will no longer be able to permanently fly after removing the Cloud Pet from hotbar (credit: JamesSkullBlood)

I have not regenerated my config file yet, but I'm doing that right now to test to see if there's a config option that is causing this unintended effect.

**Comment by UntoldForce** [comment]
The config file has no options to correct this behavior. 

The current version of Inventory Pets blocks all methods of pseudo-creative flight.

**Comment by capnkirok** [comment]
Damn. Looks like we'll need another hotfix.

**Comment by Darkmega18** [comment]
I can confirm. on my server I've had a flugel tiara from botania for quite some time now (actually thanks to the illuminati pet, true story). Even the non permanent flight of the tiara cannot work anymore unless I get out a cloud pet. I can still glide like normal though and flying with the cloud pet consumes my flight bar. I have a feeling your flight "fix" inadvertently broke everything else. I'm tempted to roll back till you hot fix it. but I've got other ways of burst movement thankfully. (heightened jumping, hang gliders, throwing myself with pearls, player launchers of every shape and size etc etc)

**Comment by capnkirok** [comment]
Working on it :)

**Comment by capnkirok** [comment]
Ok, got it. Going to see if I can fix the 'peeking' issue now as well.

**Comment by capnkirok** [comment]
For the record, it was the change I made to add configurable speeds...

**Comment by Darkmega18** [comment]
bingo, and light it up. and onto the server and a pack update that goes. good turn over right there. :D
