### ISSUE TITLE
Player don't take fall damage after Cloud Pet used then removed

### ISSUE THREAD

**Issue by capnkirok** [capnkirok/Inventory-Pets#252]
credit: JamesSkullBlood

Requires restart, or creative/survival switch. Looks like a client/server desync. Once flight is allowed, then you try to switch back in code, only the client side is processed. Probably needs a Server Tick Handler, but also must be aware of other mods that have flight capabilities.

Present in other flight mods as well (Draconic Evolution).

**Comment by capnkirok** [comment]
~~Ok, this one is fixed. Actually, quite simple in 1.12, just need to both stop flying and disallow flying if the Cloud Pet no longer in hotbar.~~

Still not working, even with a packet send (borrowed from Elytra). Seems to work in Dev environment only.

**Comment by Neubenutzer** [comment]
also I saw that you could still fly sometimes. I thought this was maybe related.

**Comment by capnkirok** [comment]
I've finally fixed this, but it's on 1.16.5 and higher versions.
