### ISSUE TITLE
Grounded Dragons

### ISSUE THREAD

**Issue by kittyemi** [capnkirok/Inventory-Pets#253]
hello, i want to inform of a problem i have,
there is a mod i have called "ice and fire" and in the mod there are dragons,
when i installed ur mod "inventory pets mod" im having a bug where the dragons
arent able to go in the sky aka fly and if i remove the mod and keep "ice and fire"
everything works properly here is what i mean:
https://www.youtube.com/watch?v=aWa-vdhecyI
im trying to spam the space bar but nothing is happening

**Comment by kittyemi** [comment]
another problem i have with the nether portal pet,the first time time i used it teleported me to lava, i couldve died but luckly i had my magma pet in my hotbar,it said it would teleport me somewhere safe but it teleported me in lava i wouldve really finded a big deal but others might alot if that wouldve happened to them

**Comment by capnkirok** [comment]
There was a bug in the 1.5.1 version that prevented flight from other mods. Are you on 1.5.1 or 1.5.2?

PC

**Comment by kittyemi** [comment]
im in version 1.5.2

**Comment by capnkirok** [comment]
Damn. If it's easy for you can you see if the 1.4.9.9b version (of inventory pets) does the same thing?

**Comment by capnkirok** [comment]
Ok, I know what this. It's not the fix I recently made to Cloud recently, it has to do with a new pet I am working on (and the new code is interfering with Riding).

**Comment by kittyemi** [comment]
Thats great news! but i want to know will the new version or coding would give the dragons the ability to fly again?

**Comment by capnkirok** [comment]
New version of Inventory Pets is required. You could roll back to a previous version until I can release if you want (would go back to 1.4.8).

**Comment by capnkirok** [comment]
Fixed, should be up on Curse shortly. Thanks again!
