### ISSUE TITLE
Nether Portal Pet Unsafe Bug

### ISSUE THREAD

**Issue by kittyemi** [capnkirok/Inventory-Pets#254]
I have a problem with the nether portal pet, the first time i used it, teleported me to lava, i could've died but luckly i had my magma pet in my hotbar, it said it would teleport me somewhere safe but it teleported me in lava i wouldnt really had found it a big deal but others might, if that wouldve happened to them,they might've had died.

**Comment by capnkirok** [comment]
Sounds like you were unlucky. I loops through 20 possible landing places before it gives up. Regardless, the Nether Portal gives you 3 minutes of Fire Resistance anyway, so you would have been safe without the Magma Pet.

Also, it remembers the last coordinates you teleported from, so once you find 'dry land' and teleport back you will never go through the pain again.

Recommend you try again and see.

**Comment by kittyemi** [comment]
I'll give more discription of what happened for the first i used it:
once it teleport me i spawned in the middle of the lava sea and 3 mins would not be enough to get back on land safely since we swim slowly.
I tryed again to use it, but it seems like it teleported me back to the lava sea i tested the 3 mins fire resistance but i still died, and first time wanted to reteleport back home to the overworld i was in 'dry land'.

**Comment by capnkirok** [comment]
In 1.15 and 1.16 versions, I've made some small changes that find safe locations easier and also give players additional fire resistance time every time they enter the Nether from their Nether Portal pet. Additionally, the Nether Portal pet now remembers the exact location you teleported from, so once you get to a safe location, you won't have to deal with the occasional lava lake anymore.
