### ISSUE TITLE
Lava acting like water with magma pet

### ISSUE THREAD

**Issue by Craftdo** [capnkirok/Inventory-Pets#255]
if I try to mine while using the magma pet to stand on the lava, my mining speed is reduced as if I'm underwater.

is that intentional?

**Comment by capnkirok** [comment]
Well, yes. The vanilla mining mechanism detects if a player is not on the ground or in liquid and slows down mining speed. I can bypass this with the same method I use for the Cloud pet. Thanks for the suggestion.

**Comment by capnkirok** [comment]
Ok, I've updated this so you can mine at normal speed if you are in Lava with a Magma Cube pet. Will be in next update.
