### ISSUE TITLE
A suggestion for the apple pet

### ISSUE THREAD

**Issue by mxnmnm** [capnkirok/Inventory-Pets#257]
The apple pet's apples should bounce off of surfaces (it should at least be a config option)

**Comment by capnkirok** [comment]
Well, then then they would get unlimited apples, which would be a problem.

**Comment by capnkirok** [comment]
I agree it would be cool (and it could actually be done), but due to the above, I'm going to skip it.

**Comment by mxnmnm** [comment]
How would they get unlimited apples if that happened?  It should probably bounce a few times and disappear.  Maybe we're picturing it happening in different ways?
