### ISSUE TITLE
we would love to shift click items to+from the chest pets!

### ISSUE THREAD

**Issue by payonel** [capnkirok/Inventory-Pets#259]
ItemStacks cannot be shift clicked into and out of the chest pets and we would love to see this feature added.
Thank you so much!

**Comment by capnkirok** [comment]
Yeah, this was bugged before and I couldn't figure out the source, so I just turned it off.

**Comment by PenguinMan98** [comment]
Huge +1 on this from me. Amazing mod. Super fun! This is my only gripe with it.

**Comment by capnkirok** [comment]
You will see this in the next release! (2.0.4) coming soon to a forge near you...

**Comment by PenguinMan98** [comment]
*Happy squeals!*

------ Original Message ------
Received: 04:31 PM MDT, 03/20/2020
