### ISSUE TITLE
Crash, seems to be related to mo' creatures

### ISSUE THREAD

**Issue by BugmanBugman** [capnkirok/Inventory-Pets#260]
Time: 2018-07-03 21:00:59 CDT
Description: Ticking entity

java.lang.ClassCastException: net.minecraft.entity.item.EntityItem cannot be cast to net.minecraft.entity.EntityLivingBase
    at com.inventorypets.events.ItemEntityEvents.travel(ItemEntityEvents.java:103)
    at com.inventorypets.events.ItemEntityEvents.handleLivingUpdateEvent(ItemEntityEvents.java:90)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1947_ItemEntityEvents_handleLivingUpdateEvent_LivingUpdateEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:567)
    at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2086)
    at net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:377)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1990)
    at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
    at net.minecraft.world.World.updateEntity(World.java:1952)
    at net.minecraft.world.World.redirect$updateEntity$zbj000(World.java:4114)
    at net.minecraft.world.World.updateEntities(World.java:1756)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:252)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being ticked --
  Entity Type: mocreatures:ant (drzhark.mocreatures.entity.ambient.MoCEntityAnt)
  Entity ID: 1249
  Entity Name: Ant
  Entity's Exact location: 256.50, 74.00, 215.74
  Entity's Block location: World: (256,74,215), Chunk: (at 0,4,7 in 16,13; contains blocks 256,0,208 to 271,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Entity's Momentum: 0.00, 0.00, 0.00
  Entity's Passengers: [EntityItem['item.item.seeds'/6738, l='New World', x=256.50, y=74.15, z=215.74]]
  Entity's Vehicle: ~~ERROR~~ NullPointerException: null
  Entity NBT: {HurtByTimestamp:3607,ForgeData:{mocreatures:{Edad:45,Adult:0b,TypeInt:1,Name:""}},Attributes:[{Base:4.0d,Name:"generic.maxHealth"},{Base:0.0d,Name:"generic.knockbackResistance"},{Base:0.28d,Name:"generic.movementSpeed"},{Base:0.0d,Name:"generic.armor"},{Base:0.0d,Name:"generic.armorToughness"},{Base:16.0d,Modifiers:[{UUIDMost:-3640947566137815661L,UUIDLeast:-7792700519162033696L,Amount:0.015301792219690906d,Operation:1,Name:"Random spawn bonus"}],Name:"generic.followRange"}],Invulnerable:0b,FallFlying:0b,ForcedAge:0,PortalCooldown:0,AbsorptionAmount:0.0f,FallDistance:0.0f,InLove:0,DeathTime:0s,ForgeCaps:{"thebetweenlands:entity_gems":{gems:[]},"techguns:deathtype":{},"voidcraft:voidicinfusioncapabilityhandler":{infusion:0,maxInfusion:6000,xiaDefeats:0.0f},"thebetweenlands:custom_step_sound":{},"llibrary:extendedentitydatacapability":{"mm:living":{frozenYaw:0.0f,freezeProgress:0.0f,frozenPitch:0.0f,frozenYawHead:0.0f,frozenEntityID:-1,frozenLimbSwingAmount:0.0f,frozenRenderYawOffset:0.0f,frozenSwingProgress:0.0f},"Ice And Fire - Chicken Property Tracker":{TimeUntilNextEgg:0},"Ice And Fire - Siren Property Tracker":{CharmedBySiren:0b},"Ice And Fire - Frozen Property Tracker":{TicksUntilUnfrozen:0,IsFrozen:0b},"Ice And Fire - Stone Property Tracker":{StoneBreakLvl:0,TurnedToStone:0b}},"thebetweenlands:puppet":{ticks:0},"thebetweenlands:equipment":{amuletSlots:1},"cavern:portal_cache":{LastPos:[],LastDim:[]},"lycanitesmobs:iextendedentity":{}},HandDropChances:[0.085f,0.085f],PersistenceRequired:0b,Age:0,Motion:[0.0d,0.0d,0.0d],Leashed:0b,UUIDLeast:-4981616486833058679L,Health:3.0f,LeftHanded:0b,Air:300s,OnGround:1b,Dimension:0,Rotation:[0.07426453f,0.0f],UpdateBlocked:0b,HandItems:[{},{}],ArmorDropChances:[0.085f,0.085f,0.085f,0.085f],UUIDMost:-9179424299256951109L,Passengers:[{Motion:[0.0d,-0.03919999988675116d,0.0d],ForgeData:{},UUIDLeast:-7993150256764927536L,Health:5s,Invulnerable:0b,Air:300s,OnGround:0b,Dimension:0,PortalCooldown:0,Rotation:[51.218346f,0.0f],UpdateBlocked:0b,FallDistance:0.04f,Item:{id:"minecraft:wheat_seeds",Count:1b,Damage:0s},UUIDMost:-5450157830215875620L,Pos:[256.5010486185188d,74.15000000223517d,215.74191815331378d],PickupDelay:0s,Fire:-1s,ForgeCaps:{"llibrary:extendedentitydatacapability":{},"cavern:portal_cache":{LastPos:[],LastDim:[]}},id:"minecraft:item",Lifespan:6000,Age:2s}],Pos:[256.5010486185188d,74.0d,215.74191815331378d],Fire:-1s,ArmorItems:[{},{},{},{}],CanPickUpLoot:0b,HurtTime:0s}

-- Affected level --
  Level name: New World
  All players: 1 total; [GCEntityPlayerMP['Velocihater'/1491, l='New World', x=259.56, y=76.85, z=197.75]]
  Chunk stats: ServerChunkCache: 391 Drop: 0
  Level seed: 1061820781346745234
  Level generator: ID 02 - largeBiomes, ver 0. Features enabled: true
  Level generator options: 
  Level spawn location: World: (108,64,256), Chunk: (at 12,4,0 in 6,16; contains blocks 96,0,256 to 111,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Level time: 64552 game time, 71686 day time
  Level dimension: 0
  Level storage version: 0x04ABD - Anvil
  Level weather: Rain time: 78082 (now: false), thunder time: 79778 (now: false)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true

**Comment by capnkirok** [comment]
Ok, this is a very strange bug. This code is not being used by Inventory Pets yet, it's for the upcoming Saddle Pet, which lets you ride any creature. So... it should never be called.

Second... looks like mo' creatures let's an Item ride an Entity? At any rate, I've prevented that from happening.

**Comment by BugmanBugman** [comment]
Mo creatures ants are able to hold dropped items so maybe that could be why
