### ISSUE TITLE
Cloud pet OP?

### ISSUE THREAD

**Issue by Zunlite** [capnkirok/Inventory-Pets#261]
Its pretty easy to get the pet, all you would really need to do is place water under one of the clouds in the overworld, build a tower to the cloud, destroy the chest, and bam you would have the pet, the blazes are not even that dangerous as you could either spam em with snowballs or ditch and fall into the water (or fly away bc you have the pet now)

Not only that, but keeping it fed is easy af, nether quartz is one of the easiest things to find in the nether bc they are as common as iron or coal. Just that for the power of flight and summoning lightning? Really OP!

Im not saying the pet is bad, its very fun to use! But getting it is way too easy in my opinion.

**Comment by capnkirok** [comment]
The Cloud Pet is only found in about 1% of Sky Chests. It doesn't sound like you've found one yet in Survival? Or maybe you got lucky? You can also turn down the frequency of dungeons.

They eat nether quartz twice in a mc day, so you'll go through that pretty quick. If you think that's easy, just change it to hardcore mode where they eat an entire block.

**Comment by capnkirok** [comment]
At some point I will add the ability to select your own food for each pet... and then you can choose what you want (Diamond Block if you want).
