### ISSUE TITLE
Horses are extremely fast

### ISSUE THREAD

**Issue by TheRealDadbeard** [capnkirok/Inventory-Pets#264]
I just tried it with only the mod on newest available forge and minecraft. Was going crazy what was making my horses go crazy fast on my server

**Comment by capnkirok** [comment]
Thanks, for the post. I think I know what this is.

**Comment by capnkirok** [comment]
Yeah, this code was not supposed to be running in the last version, was test code for the new Saddle Pet. It will be removed in a hotfix.
