### ISSUE TITLE
Inventory Pets disables the flight of Ice and Fire dragons and Aether II Moas

### ISSUE THREAD

**Issue by AlexModGuy** [capnkirok/Inventory-Pets#265]
https://github.com/Alex-the-666/Ice_and_Fire/issues/921

Inventory pets must be overwriting Minecraft's spacebar in some manner every tick that blocks other mods from taking advantage of it.

**Comment by AlexModGuy** [comment]
also effects flying aether mobs

**Comment by capnkirok** [comment]
Hey Alex. Yeah I saw this and I know exactly what is causing it. Will fix this weekend.

PC

**Comment by Eranderil** [comment]
Out of curiosity, is there an update on this?

**Comment by Glitchster9000** [comment]
finally found this thread...  Please tell me what I need to do to allow dragons to fly with inventory pets on.  Ice and Fire need their own keybinding section, but I don't think that will fix the problem.

**Comment by capnkirok** [comment]
If you need it immediately, you can roll back to a previous version of Inventory Pets. Recommend InventoryPets-1.12-1.4.9.9b.

Should have an update out this upcoming weekend regardless.

**Comment by Eranderil** [comment]
Awesome reply. Your professionalism and timeliness are appreciated. If I may ask, what is lost if one should roll back?

**Comment by capnkirok** [comment]
Mostly some small new features and bug fixes. You can read the release notes here:
https://minecraft.curseforge.com/projects/inventory-pets/files/2573761
https://minecraft.curseforge.com/projects/inventory-pets/files/2575780
https://minecraft.curseforge.com/projects/inventory-pets/files/2576157

**Comment by Eranderil** [comment]
Hm. No update over the weekend. I'm gonna assume that A: Dev was busy with RL issues or, B:the issue was more complicated than it initially appeared and the Dev wasn't yet able to fix it. (or C: all of the above to some degree.) Gonna roll back to suggested version for server until a new version releases, unless Dev replies to wait. Good luck! Looking forward to fix!

**Comment by capnkirok** [comment]
Yeah, there was a big animania update this weekend, that took Sunday as well. BUT I think this bug is fixed in my dev environment now, but need to test. Hoping to get it it out today or tomorrow. Thanks for patience.

**Comment by capnkirok** [comment]
Ok, tested and it is fixed. Let me see if there's anything else I can throw into this update...

**Comment by Eranderil** [comment]
Just woke up, updating now! Will leave feedback as needed! I would, at this point, rate you as the best thing since indoor plumbing though!
