### ISSUE TITLE
Illuminati Pet causes FPS drop with Applied Energistics

### ISSUE THREAD

**Issue by UntoldForce** [capnkirok/Inventory-Pets#267]
Hey, first off thanks for fixing the cloud pet problems with the hotfix a while back. I found another weird issue:

If you have multiple Illuminati Pets in your inventory, FPS will drop to 1 eventually if you interact with a Pattern Terminal from Applied Energistics 2. I'm using the last rv5-stable build of AE2, and the latest version of Inventory Pets (1.5.2) on Minecraft 1.12.2.

I'm also using Optifine, so it could be related to that. If you'd like me to do more testing to see if it is just AE2 + Inventory Pets then I could disable Optifine. If you need more information about the mods and Forge version, just let me know.

This only happens with multiple illuminati pets. I've tested it with 1 and my FPS is fine.

**Comment by UntoldForce** [comment]
![2018-07-16_01 26 52](https://user-images.githubusercontent.com/17446062/42744074-9cb102be-8897-11e8-82ce-e00a8b6f6f56.png)

**Comment by capnkirok** [comment]
Weird. Thanks.

**Comment by chatsonf** [comment]
Not sure if related, but having 5 illuminati pets plus some number of other items in your inventory (tested with multiple cobblestone stacks) causes all mobs to lag/freeze. 

Able to still attack mobs and interact with world, no FPS drop.
If GUI (like a chest, not the regular inventory) is opened up then mobs move fine. 

This is in a modpack, Awakening Sky of Diamonds. 
Latest version of Inventory Pets (2.0.6) on Minecraft 1.12.2. Modpack also includes Optifine.

**Comment by capnkirok** [comment]
Well that is bizarre. I look forward to testing this out once I have 1.15.x released. It could have something to do with some AI modification I am doing when you turn invisible (just a hunch).

**Comment by capnkirok** [comment]
Long overdue, but wanted to say I think the latest update should fix this problem (2.0.10). From my testing, it appears to be the way I was using the cooldown timer. I was storing the updated world time at every tick on the Item NBT (e.g., 20 times/second), which resets the animation timer and caused additional render processing. I don't think there's anything special about 5 illuminati pets (now if it was 3 pets... ha ha)
