### ISSUE TITLE
[V1.5.2] Angel Rings from EU2

### ISSUE THREAD

**Issue by AnyaDinky** [capnkirok/Inventory-Pets#268]
Angel Ring(s) from Extra Utilities 2 Mod equipped in Baubles inventory or just laying in your inventory causes you to not be able to fly when cloud pet is in your hotbar.

Mod Versions ~

- Pet Inventory = [1.5.2]
- Extra Utilities 2 = [1.7.6]

I have tested when the ring has power and when it doesn't, but when it doesn't have power it's glitchy and it seems to act similarly to when you're trying to fly a dragon in the **_Ice and Fire mod_**. And when you have power for the rings it acts normal.

**Comment by capnkirok** [comment]
Yes, seeing the same thing. This may have to go to RWTema, let me investigate further if there's something I can do.

**Comment by capnkirok** [comment]
So, this is the code from EU2. Looks like if you are holding an Angel Ring and it's not powered, it won't let you fly. I'll have to poke RWTema.

```
@Override
public void powerChanged(boolean powered) {
	if (invalid) return;
		EntityPlayerMP entityPlayerMP = getPlayerMP();
		if (entityPlayerMP.isDead || entityPlayerMP.isSpectator()) return;
		if (entityPlayerMP.capabilities.isCreativeMode) powered = true;
		if (entityPlayerMP.capabilities.allowFlying != powered) {
			entityPlayerMP.capabilities.allowFlying = powered;
			if (!powered) entityPlayerMP.capabilities.isFlying = false;
			entityPlayerMP.sendPlayerAbilities();
	}
}
```

**Comment by capnkirok** [comment]
So, there's no solution for this on IP side. You must remove the unpowered ring from your inventory if you want to fly with the Cloud Pet.
