### ISSUE TITLE
Bed Pet doesn't sleep on servers

### ISSUE THREAD

**Issue by Shahelion** [capnkirok/Inventory-Pets#27]
The Bed pet makes you sleep just fine in singleplayer, but on servers, it instantly makes it day, regardless of whoever else is online.

**Comment by capnkirok** [comment]
That's actually what it does in single player, too. We like the way it works now on servers, but could understand how it could be abused. We could a config option to check other players are in bed on servers, though.

**Comment by capnkirok** [comment]
See #38

**Comment by capnkirok** [comment]
Submitted long ago, but not forgotten. This will be updated in the 1.4.0 release. Default will remain the same. But you can change it in the config so that it checks to see if all players are in beds.
