### ISSUE TITLE
Chest pet not showing item names

### ISSUE THREAD

**Issue by mxnmnm** [capnkirok/Inventory-Pets#270]
https://imgur.com/a/pqWZ5sN
the title and pic say it all

forge 1.12.2-14.23.4.2705
inventory pets 1.5.2

If you want more info let me know

**Comment by capnkirok** [comment]
This looks like a mod conflict. Are you using any kind of inventory/chest mod on top of this?

**Comment by mxnmnm** [comment]
Hmmmm I have a lot of mods in the pack so probably, the question is which mod...

**Comment by mxnmnm** [comment]
Ok I tried disabling some mods to find the mod causing the issue and it seems it happens with no other mods installed, so it looks like it's something related to inventory pets

**Comment by capnkirok** [comment]
Man, sorry to send you on a wild goose chase. You are right. This is a bug.

**Comment by capnkirok** [comment]
This one will be fixed in the 2.0 update
