### ISSUE TITLE
Chest pet using off hand

### ISSUE THREAD

**Issue by mxnmnm** [capnkirok/Inventory-Pets#271]
Whenever I use my chest pet it places whatever is in my off hand which I find rather annoying
forge 1.12.2-14.23.4.2705
inventory pets 1.5.2

**Comment by capnkirok** [comment]
Sorry for very late reply, finally getting through this list. Not sure what you mean, can you elaborate?

**Comment by mxnmnm** [comment]
Let's say that I have torches in my off hand and I'm opening the chest pet.  It ends up placing the torches while opening the chest pet.  It gets really annoying really fast ;-;

**Comment by capnkirok** [comment]
Ah got it. Thx.

**Comment by capnkirok** [comment]
1 year later... I've finally implemented this. Basically, if you have something 'actionable' in your offhand, but you are holding a pet in your main hand, it will ignore the offhand action. This will allow you to keep items like torches, blocks, or tools in your offhand and still be able to access your chest or use other pets as necessary.

**Comment by capnkirok** [comment]
Available in 2.0.4 coming soon
