### ISSUE TITLE
an Error with Advanced Hook Launchers mod

### ISSUE THREAD

**Issue by tunaeskanaytac** [capnkirok/Inventory-Pets#272]
I've got a crash with Advanced Hook Launchers mod I wrote the issue and the author of that mod told me "it is because of Inventory Pets mod please report this to its author" so here's my crash report
[https://pastebin.com/raw/WP9zndSX](url)

**Comment by capnkirok** [comment]
That link gives me a 404, can you repost?

**Comment by tunaeskanaytac** [comment]
I'll try to attach a file
[crash-2018-07-30_03.22.47-server.txt](https://github.com/capnkirok/Inventory-Pets/files/2240620/crash-2018-07-30_03.22.47-server.txt)
Or I'll drop a link again
https://pastebin.com/WP9zndSX
Try copy and paste if link give you 404

**Comment by capnkirok** [comment]
Thanks, see #273

**Comment by capnkirok** [comment]
Closing, as this is duplicate
