### ISSUE TITLE
An Error With Advanced Hook Launchers Mod

### ISSUE THREAD

**Issue by tunaeskanaytac** [capnkirok/Inventory-Pets#273]
I've got a crash with Advanced Hook Launchers mod I wrote the issue and the author of that mod told me "it is because of Inventory Pets mod please report this to its author" so here's my crash report
https://pastebin.com/raw/WP9zndSX
if link gives 404 try to copy and paste link

I'll attach the file here just in case
[crash-2018-07-30_03.22.47-server.txt](https://github.com/capnkirok/Inventory-Pets/files/2240710/crash-2018-07-30_03.22.47-server.txt)

**Comment by capnkirok** [comment]
Ah yes. This is a known issue and is fixed in the next release.

**Comment by capnkirok** [comment]
#272 and #260

**Comment by tunaeskanaytac** [comment]
Um... But this is the latest version that I use

**Comment by capnkirok** [comment]
Next release means it's not out yet :)

**Comment by tunaeskanaytac** [comment]
Oh I see. Do you have any ideas when will it release ?
