### ISSUE TITLE
Log Spam

### ISSUE THREAD

**Issue by LocalBoomer** [capnkirok/Inventory-Pets#274]
`[22:14:34] [main/INFO] [STDOUT]: [com.inventorypets.events.PlayerTickHandler:onLivingUpdateEvent:339]: yeah
`

This keeps spamming in my log every tick. Is this supposed to happen and how do I stop it?

**Comment by capnkirok** [comment]
No. Ha ha. Sorry. Will fix.

**Comment by capnkirok** [comment]
That should only occur if you have EU2 installed.

**Comment by LocalBoomer** [comment]
Yeah I do. Not sure which version but should be the newest as of yesterday (not at my pc so can't check right now) Should I report this there as well?

**Comment by capnkirok** [comment]
No, it's my problem for sure. There are a couple of other errors to fix as well, so I will do a hotfix. Thanks for the report!

**Comment by LocalBoomer** [comment]
thanks for the awesome mod!

**Comment by capnkirok** [comment]
Fixed in the upcoming 1.5.3.1 release

**Comment by LocalBoomer** [comment]
Awesome thanks!
