### ISSUE TITLE
Illuminati pet invisibility

### ISSUE THREAD

**Issue by LemADEC** [capnkirok/Inventory-Pets#276]
As of 1.12-1.5.3, enabling illuminati pet causes GLState bleeding, making inventory invisible to that player and other players nearby:
- before enabling invisibility
![image](https://user-images.githubusercontent.com/4776032/43805632-ce9cda4e-9aa0-11e8-9d7e-380d2fbd7884.png)

- after enabling invisibility
![image](https://user-images.githubusercontent.com/4776032/43805640-d692c8a8-9aa0-11e8-85ea-836131e4c9bd.png)

**Comment by capnkirok** [comment]
Wow, no one has ever mentioned this. Will have to see if possible to fix.

**Comment by capnkirok** [comment]
This looks like a compat issue, but I'm not sure of the conflicting mod. I don't see the issue in a straight up installation. Any chance you can share your modlist? Anything with a GUI could be the culprit.

**Comment by LemADEC** [comment]
GLState bleeding is when you're directly calling OpenGL instead of going through the proper Vanilla library.

**Comment by capnkirok** [comment]
None of my code around the Illuminati Pet calls OpenGL directly. There is some code used in the GUIs but that is the same code being used by Vanilla MC, e.g.:

```
@Override
	protected void drawGuiContainerBackgroundLayer(float p_146976_1_, int p_146976_2_, int p_146976_3_)
	{
		mc.renderEngine.bindTexture(new ResourceLocation("textures/gui/container/generic_54.png"));
		GL11.glColor4f(1.0F, 1.0F, 1.0F, 1.0F);
		int k = (this.width - this.xSize) / 2;
		int l = (this.height - this.ySize) / 2;
		this.drawTexturedModalRect(k, l, 0, 0, this.xSize, 3 * 18 + 17);
		this.drawTexturedModalRect(k, l + 3 * 18 + 17, 0, 126, this.xSize, 96);
	}
```

**Comment by LemADEC** [comment]
It was reproduced initially while working on this modpack: https://www.technicpack.net/modpack/fsg-spectracraft.1282933/mods , but I don't have the exact set of mods involved at that time.

The Illuminati tooltip says it's doing more than an 'simple' invisibility potion, how is it done?

**Comment by capnkirok** [comment]
Sorry for late reply. It simply cancels the render event.
