### ISSUE TITLE
Quiver Pet fills inventory with Arrows

### ISSUE THREAD

**Issue by mxnmnm** [capnkirok/Inventory-Pets#277]
When using a tinkers bow with the quiver pet, it automatically fills your inventory with arrows which can be rather annoying.  If you spam right click the bow without actually shooting, it gives you arrows but if you actually shoot an arrow it renders that it added an arrow but when you update your inventory (move an item or something) it reverts back to the original number of arrows.  If you need screenshots/vids let me know.

forge-14.23.4.2739
inventory pets-1.5.3
tinkers construct-2.10.1.87
mantle-1.3.2.24

**Comment by capnkirok** [comment]
Doesn't matter what the bow is. Looks like something changed with Arrows in a recent version.

**Comment by capnkirok** [comment]
Going to change your titles, since these aren't helpful to others trying to find stuff.

**Comment by capnkirok** [comment]
Well, it wasn't Forge. I have a feeling I never fixed this properly for 1.12. Anyway, fixed now in 1.5.3.1.
