### ISSUE TITLE
Quiver pet Instashot not working

### ISSUE THREAD

**Issue by mxnmnm** [capnkirok/Inventory-Pets#278]
The instashot on the quiver pet doesn't seem to work, I might be doing it wrong so a double check on how it's supposed to work would be nice otherwise it might need fixing.  If you need screenshots/vids let me know.

forge-14.23.4.2739
inventory pets-1.5.3

**Comment by capnkirok** [comment]
Yeah, something has definitely changed in on of the recent forge versions, will have to see what's up. Still works on 1.10 and 1.7.10
