### ISSUE TITLE
Quiver Pet features don't work when COFH installed

### ISSUE THREAD

**Issue by mxnmnm** [capnkirok/Inventory-Pets#279]
Perhaps the biggest issue is that the quiver pet doesn't supply infinite arrows when installed with cofh core.  If you need screenshots/vids let me know.

forge-14.23.4.2739
inventory pets-1.5.3
cofh core-4.5.3.20

**Comment by capnkirok** [comment]
This one I'm not sure I can do anything about, may have to post on COFH.

**Comment by mxnmnm** [comment]
here's what king lemming said https://github.com/CoFH/Feedback/issues/1252#issuecomment-412230901

**Comment by capnkirok** [comment]
Yeah, I can't do anything about this, unfortunately.
