### ISSUE TITLE
Quiver pet instashot with vanilla bows and tinker arrow dupes

### ISSUE THREAD

**Issue by mxnmnm** [capnkirok/Inventory-Pets#280]
The latest update hasn't fixed the issues :/

**Comment by capnkirok** [comment]
Well, that's not fair. The Quiver Pet is working fine now. 
[![Video Link](https://gyazo.com/88b5a72b761a5ee7d2425182d06ff357/raw)](https://gyazo.com/88b5a72b761a5ee7d2425182d06ff357)

It really isn't my fault that the other mod devs have hijacked the Arrow Loose event from vanilla. My code only borrows the event when the quiver is enabled, not all the time. This is a compat issue, not a problem with Inventory Pets.

I can 'try' for a workaround. But super annoying.

**Comment by mxnmnm** [comment]
Alright after more testing the quiver pet works just fine on tinkers bows (instashot and infinite arrows) (even with cofh installed) except for it putting more arrows in your inventory which is annoying but I'll live lol.  So that's all I really care about but I'll leave this issue open in case peps don't have tinkers or something.

**Comment by capnkirok** [comment]
I *might* be able to do something if these two are installed (like disable infinite arrows)

**Comment by capnkirok** [comment]
Ok, the last piece of this equation... the double adding of arrows to the inventory is finally fixed in next release.
