### ISSUE TITLE
Problem with Player inventory size

### ISSUE THREAD

**Issue by gamelnderGamler** [capnkirok/Inventory-Pets#281]
Minecraft Version: 1.12.2.

Mod Version: inventorypets-1.12-1.5.2

Hello,

I had a server crash with the following crash report after using drones from Pneumaticcraft:
[crash-2018-08-12_17.31.01-server.txt](https://github.com/capnkirok/Inventory-Pets/files/2281142/crash-2018-08-12_17.31.01-server.txt)

After reporting the crash, the developer of Pneumatticcraft said: 

"This is a bug in Inventory Pets, not PneumaticCraft.

That mod's HarvestHandler class is making incorrect assumptions about the size of the player's inventory (assuming it has at least 9 slots), which is not necessarily true for a drone's fake player (only 1 slot by default). They should be checking the player's inventory size before iterating over it."

So iam here to let you know about the bug.
Thank you for your help :-).

**Comment by capnkirok** [comment]
Thx. Fixed in next release.
