### ISSUE TITLE
Squid breaks everything (way too fast)

### ISSUE THREAD

**Issue by RubberEyes** [capnkirok/Inventory-Pets#284]
It basically allowed me to break obsidian at the same speed as I would break a cobblestone, both with a common Diamond Pickaxe, under and over water.
Note: I was playing with Botania and Ender IO, but I hadn't anythin fancy with me; Removing the squid made me work at normal speed again

**Comment by capnkirok** [comment]
Nice catch. The bug actually extends to Cloud and Magma Cube as well. If you had any of these in your inventory, you got fast breaking on super hard blocks. Fixed in next release.
