### ISSUE TITLE
EnderIO Boots Interaction?

### ISSUE THREAD

**Issue by znxster** [capnkirok/Inventory-Pets#285]
I am running a modpack, so these are the versions and this is single player.

FoolCraft v1.5.4
Forge v14.23.4.2760
MineCraft v1.12.2
EnderIO v1.12.2-5.0.33
Inventory Pets v1.12-1.5.3.1

There seems to be an interaction issue, as such I am unsure if its EnderIO or Inventory Pets which is causing the broken interaction.

When using the "Squid Pet" and wearing "Dark Boots" of EnderIO. The Dark Boots have an upgrade installed called "Flippers".

If I walk into water with the boots on, it works as expected. If I remove the boots and only use the Squid, again it works as expected. So on their own the items are fine.

However if I wear the Boots and use the Squid, I start to move forward (without pressing forward), this rapidly increases to the point at which my world cannot keep up! The motion doesn't allow for me to move left/right or slow down until I bump into some land.

I have tested with a set of Dark Boots that lacks the "Flippers" feature and it's OK, no bad interaction.

Thanks!

**Comment by capnkirok** [comment]
Hmm.. let me see if I can make an exception if there are 'flippers' in the hotbar.

**Comment by capnkirok** [comment]
Ok, this will be in next release
