### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by agentwolf88** [capnkirok/Inventory-Pets#286]
https://paste.dimdev.org/yidohawofu.mccrash

**Comment by agentwolf88** [comment]
https://paste.dimdev.org/mebuxopone.mccrash

**Comment by capnkirok** [comment]
~~Very strange. I know what's causing this, but the event should not even be firing. At any rate, will be fixed in the next update.~~

**Comment by capnkirok** [comment]
Actually you just need to update to the latest version 1.5.3.1
