### ISSUE TITLE
Double Chest pet not eating when "Pets Eat Whole Items" option enabled

### ISSUE THREAD

**Issue by wafflesword** [capnkirok/Inventory-Pets#287]
Enviroment: 
Minecraft: 1.12.2
Forge: 14.23.5.2768
Mods: Inventory Pets 1.5.3.1

Replication: Enable "Pets Eat Whole Items (hardcore Pets)" and the double chest pet does not eat. After turning the option off the pet instantly eats logs

**Comment by capnkirok** [comment]
Yeah, that's a mistake in the tooltip. It should say it eats golden nuggets when it's in Pets Eat Whole Items mode. Will fix... but you should be able to feed it that.
