### ISSUE TITLE
CLOUD PET BUG

### ISSUE THREAD

**Issue by ghost** [capnkirok/Inventory-Pets#288]
• double jumps
• weird shifting action : when you shift, the player suddenly gets pulled down

**Comment by capnkirok** [comment]
Let me ask a couple of questions:

1. What version of Inventory Pets and Minecraft are you on?
2. What do you mean by Double Jumps? Not seeing that.
3. What do you mean by 'pulled down'. Shift should definitely help you 'float' down, but you shouldn't fall.
4. Any other mods you are using with Inv Pets that have 'flying' items ?

**Comment by capnkirok** [comment]
I haven't heard back in a while. Planning to close this one unless I hear back.
