### ISSUE TITLE
Crash - IPExtender Module Broken By this Mod 

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [capnkirok/Inventory-Pets#29]
Server Log

https://gist.github.com/DPxKnightxZero/2bc4a147b2a8fff4a013

**Comment by capnkirok** [comment]
Hmmm.... it's failing to find the NBT Data files for the player. We can put some error checking in here, but you may have a problem with your player files too.

**Comment by P3rf3ctXZer0** [comment]
I understand Thank you!

**Comment by capnkirok** [comment]
Finally coming back on this issue. This is just a warning, not the cause of a crash. It only happens the first time you run the mod.
