### ISSUE TITLE
Can't hear music when using Jukebox pet

### ISSUE THREAD

**Issue by voidb** [capnkirok/Inventory-Pets#291]
Yesterday, I found and started to use the Jukebox Pet. Today, when I got back on, it wouldn't make a noise. It says it's playing the disc, but no sound comes out. I am using Forge in 1.12.2.

**Comment by capnkirok** [comment]
Hmm.. haven't heard of this one. Questions:

1) Is it fed? Sometimes it's hard to tell (I assume so)
2) Are you standing in the same location or near where you originally played the disc? (Discs are location-based in Minecraft)
3) Have you tried re-playing the disc or a different disc?
4) If you grab a Jukebox in a new world does that one work?

**Comment by capnkirok** [comment]
Closing this one since I didn't hear back
