### ISSUE TITLE
Can't seem to use the Quiver pet

### ISSUE THREAD

**Issue by MrBread009** [capnkirok/Inventory-Pets#292]
I am not able to use the quiver pet. It is in my hotbar, i tried shooting with 1 arrow in my inventory and with none, i tried right clicking it, but it won't give me infinite arrows. I have feathers in my hotbar as well. It took a long time to find the diamond to make this, so I hope I'm just using it wrong. Would someone please help me!? It's been a week and there are no comments. :(

**Comment by capnkirok** [comment]
Are you on 1.12?

**Comment by capnkirok** [comment]
[![Quiver Pet Demo](https://gyazo.com/bca220aa87431f1c44ad1fe5c53bc7b4/raw)](https://gyazo.com/bca220aa87431f1c44ad1fe5c53bc7b4)

**Comment by capnkirok** [comment]
Going to close this one unless I hear back
