### ISSUE TITLE
Night Vision conflict with Adventure Backpack Mod

### ISSUE THREAD

**Issue by sourdusk** [capnkirok/Inventory-Pets#297]
Whenever this mod (v 1.7.10-1.5.2) is installed alongisde Adventure Backpack 2 (https://minecraft.curseforge.com/projects/adventure-backpack v 1.7.10-0.9-h10) the night vision effect for the bat adventure backpack doesn't work. Changing mod load order to load adventure backpack after Inventory Pets has no effect, as does disabling the ocelot pet and recipe in the config file.

Possibly related to #186 or number #140 ?

**Comment by capnkirok** [comment]
Can no longer update 1.7.10
