### ISSUE TITLE
Enchant Table pet

### ISSUE THREAD

**Issue by jthunter00** [capnkirok/Inventory-Pets#301]
The enchant table pet shows the old enchanting levels and requires you to have the levels to even use it but it only takes the new amount of levels for enchanting

**Comment by capnkirok** [comment]
Can you clarify and explain why this is a problem?

**Comment by jthunter00** [comment]
when you want to use the enchant table pet you are required to have 30 levels for the highest enchant even though it doesn't take that amount, its more of a hassle for people to get to 30 than it is to get to the 3 levels it costs

**Comment by capnkirok** [comment]
It actually works the same as the vanilla enchanting table (minus the Lapis). You need to have 30 levels in order to use a level 30 enchant, even though it only costs 3 levels to use.

I recommend you try it out in Creative mode to see.
