### ISSUE TITLE
Can't disable annoying April fools message!

### ISSUE THREAD

**Issue by knoxhack** [capnkirok/Inventory-Pets#302]
I could not find in the config a way to disable this message, Its annoying because I have disable all holidays pets in my modpack.
https://imgur.com/a/ZFFSxYm

**Comment by capnkirok** [comment]
Ok, in the future update if you switch 'showUpdateMessage' to false, it will hide any of the holiday messages, too.

**Comment by capnkirok** [comment]
Of course, now it's May, but hey.

**Comment by capnkirok** [comment]
Actually made a separate config for this: Show Holiday Messages. Just turn it to  false.
