### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by runescapejon** [capnkirok/Inventory-Pets#303]
Hello on my server i am having performance issues from inventorypets
![82263afeb2ec078c8408f5cc69db9733](https://user-images.githubusercontent.com/10858509/56098688-cb634580-5ed0-11e9-97f8-7e2c826b244d.png)
mind fixing this please? thanks

EDIT: i forgot to include the versions i was using i am using
- InventoryPets: -1.12-2.0.1
- Forge: - 14.23.5.2814

**Comment by capnkirok** [comment]
Weird, as this code hasn't been updated in some time, so this is the only report I've seen. This is the 'make Creepers run away' code. My guess is that it's bumping up against your world border.

You could temporarily 'disable' the Ocelot Pet in the config until this is fixed. In the version you have, this just removes the capabilities, but keeps the pet in game.

**Comment by capnkirok** [comment]
Ok, I've done two things that should prevent this in the future:
- Limiting the search radius for creepers to 1 chunk
- Checking for world border

Updated in 2.0.2 (to be released soon)

**Comment by capnkirok** [comment]
Also did this to the Siamese Pet (which uses the same code to scare Zombies).
