### ISSUE TITLE
Lead pet crashes game

### ISSUE THREAD

**Issue by sugary-stardust** [capnkirok/Inventory-Pets#304]
Attempting to put the lead pet in an item frame crashes the game, whether right-clicking or shift-right-clicking - presumably because the pet can only be "used" on living entities (that's basically what the crash log said, anyway).

**Comment by capnkirok** [comment]
Item Frames... gah. Yeah, I'll ned to put something in there. Minecraft thinks they are living entities, so need to add some error trapping.

Interestingly, I made sure the Saddle Pet worked with Item Frames, but not Leads...

Thx!

**Comment by capnkirok** [comment]
Ok, this is fixed in the next release

**Comment by capnkirok** [comment]
#317
