### ISSUE TITLE
keybind issue

### ISSUE THREAD

**Issue by ThsHaunted124** [capnkirok/Inventory-Pets#306]
so with the flying saddle pet i cant descend because of my keybinds being shift for sprint and crouch to sneak, so if i press either of these keys i get off my mount instead of descending. it would be nice if there was an option to change the descend keybind in de controls so i can keep my crouch sprint controls.

**Comment by capnkirok** [comment]
~~Yeah, I can do that~~

Actually, putting in a true keybind causes a conflict with the main keyboard as LCTRL is the default for Sprint. Any other ideas?

**Comment by capnkirok** [comment]
Going to close this one.
