### ISSUE TITLE
Issue with avatar mod

### ISSUE THREAD

**Issue by GoldenSoul624** [capnkirok/Inventory-Pets#311]
There was a crash when I attempted to use a bending capability from Avatar: Out of the Iceberg 2 on a creature with this mod installed.

[crash-2019-07-02_09.24.34-client.txt](https://github.com/capnkirok/Inventory-Pets/files/3350346/crash-2019-07-02_09.24.34-client.txt)

**Comment by capnkirok** [comment]
If you got an error here, it would only occur if a player was trying to attach a lead to an EntityWaterBubble, using the Lead Pet.

I've added error trapping for this in 2.0.2
