### ISSUE TITLE
Torch Pet Not Placing Fire

### ISSUE THREAD

**Issue by mxnmnm** [capnkirok/Inventory-Pets#313]
I can't place fire using the torch pet by sneak + right clicking like the description says I can (do note that I have disabled food for pets in case that breaks anything)

**Comment by mxnmnm** [comment]
Inventory Pets: 1.12-2.0.1
Forge: 14.23.5.2838

**Comment by capnkirok** [comment]
Thanks! You are correct, this is a bug.

**Comment by capnkirok** [comment]
Alright, this is fixed in dev. Will be updated in version 2.0.2
