### ISSUE TITLE
player cannot summon hostiles while holding sun pet

### ISSUE THREAD

**Issue by ranshaa05** [capnkirok/Inventory-Pets#314]
The player cannot summon hostile mobs while holding the sun pet. not even by using /summon.

**Comment by ranshaa05** [comment]
mod version: 1.12-2.0.1
forge: 1.12 - 14.21.1.2387

**Comment by capnkirok** [comment]
Ah yes. That's a good one. Will affect nearby players as well.

**Comment by capnkirok** [comment]
Alright, I've added a proximity detector if the player is within 3 blocks of the mob spawn. Fixed in next version (2.0.2)
