### ISSUE TITLE
Question: Chests blowing up

### ISSUE THREAD

**Issue by DoesntCare** [capnkirok/Inventory-Pets#315]
About half of the pet chests in trees are blowing up when opened when they never have before.  Why?  Something in my inventory?  Some event that occurred in-game?  The date (7-17)?  The time (early morning)? Opening them from the top instead of the bottom?  Some other mod making chests explode?  Any ideas?

**Comment by capnkirok** [comment]
Oh, that's on purpose. There are no 'guards' for these chests, so this is an alternate defense. You'll have to figure out how to disarm :)
