### ISSUE TITLE
[Mod Compatibility?] Tinkers SlimeSling +Squid pet

### ISSUE THREAD

**Issue by Pulz-TCP** [capnkirok/Inventory-Pets#316]
**inventorypets 1.12.2-0.1**
A streamer playing my modpack (The Classic Pack) reported this to me:

While having the squid inv pet active and in my hotbar, I fired myself from land into water using the slimesling. Game seems to constantly add forward momentum with no upper limit. Only way to stop it is to get out of the water. Put [another streamer]'s server under a ton of load 3 times the other night while streaming because I kept forgetting about it 

User also provided a clip from his stream of the issue:
https://www.twitch.tv/heretic121/clip/HeartlessSwissTortoiseTTours

**Comment by capnkirok** [comment]
Seems like an interaction between the sling and the squid. I've disabled the Squid speed boost if the user has the sling in the inventory (in the next version, 2.0.2)
