### ISSUE TITLE
Game crashing when going to a floating island in 1.12.2

### ISSUE THREAD

**Issue by Gamerlifestylee** [capnkirok/Inventory-Pets#317]
I just recently tried out the inventory pets mod in 1.12.2 and discovered while going to the floating islands that spawn witches, some of them will crash my game and put me in a infinite loop of crashing
[Crash Report](https://pastebin.com/dpTD1HNN)

**Comment by capnkirok** [comment]
This is also Damage Indicators Mod

![image](https://user-images.githubusercontent.com/9628379/63228372-cc2e2000-c1bf-11e9-953f-425fdc5cf075.png)
