### ISSUE TITLE
Squid pet crashing game after playerdata position change in 1.12.2

### ISSUE THREAD

**Issue by Gamerlifestylee** [capnkirok/Inventory-Pets#318]
I recently changed my playerdata position in my world to fix a problem I had and discovered that I would crash if I was in the water with a squid pet
[Crash Report](https://pastebin.com/qp6Qe5r4)
  Not sure if this is linked to my [previous problem](https://github.com/capnkirok/Inventory-Pets/issues/317) or not.

**Comment by capnkirok** [comment]
This is a problem for Damage Indicators mod. You should bring this to the attention of that author

![image](https://user-images.githubusercontent.com/9628379/63228360-8ec99280-c1bf-11e9-9b53-7e015be20081.png)
