### ISSUE TITLE
[Mod Compatibilty] Pixelmon reforged + Latest version of Inventory Pets

### ISSUE THREAD

**Issue by MrFufferman** [capnkirok/Inventory-Pets#319]
I was trying to start a forge pixelmon server, and I added journeymap and pixelmon and everything worked fine. Once I added inventory pets, it seemed like it completely disabled the pixelmon mod. The item ID's are close to the same range for both mods, so that could be it.

**Comment by capnkirok** [comment]
Finally responding...

I just tested with the latest version of Pixelmon and Inventory Pets and there were no problems. They must have fixed this on the Pixelmon side.

Also, all Item IDs are dynamic, so that couldn't be the issue.
