### ISSUE TITLE
Crash during world gen after update.

### ISSUE THREAD

**Issue by ddd800** [capnkirok/Inventory-Pets#320]
Just /rtp'ed after updating inventory pets and server lost its mind and crashed. I looked at the crash logs and only your mod popped up but I cannot figure out why.

[crash-2019-08-19_00.28.53-server.txt](https://github.com/capnkirok/Inventory-Pets/files/3514194/crash-2019-08-19_00.28.53-server.txt)

Update: After starting the server back up it keeps kicking me before I can join and if I rejoin too many times it crashes again. This is what it says before that happens.

`19.08 04:43:14 [Server] Server thread/ERROR [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$PlayerTickEvent@f86de64:
19.08 04:43:14 [Server] INFO java.lang.NoSuchMethodError: net.minecraft.world.biome.Biome.func_185359_l()Ljava/lang/String;
19.08 04:43:14 [Server] INFO at com.inventorypets.worldgen.WorldGenTreeTop.func_180709_b(WorldGenTreeTop.java:57) ~[WorldGenTreeTop.class:?]
19.08 04:43:14 [Server] INFO at com.inventorypets.worldgen.WorldGenInventoryPets.generateOverworldDungeons(WorldGenInventoryPets.java:72) ~[WorldGenInventoryPets.class:?]
19.08 04:43:14 [Server] INFO at com.inventorypets.worldgen.WorldGenInventoryPets.generate(WorldGenInventoryPets.java:21) ~[WorldGenInventoryPets.class:?]
19.08 04:43:14 [Server] INFO at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167) ~[GameRegistry.class:?]
19.08 04:43:14 [Server] INFO at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1020) ~[axw.class:?]
19.08 04:43:14 [Server] INFO at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:999) ~[axw.class:?]
19.08 04:43:14 [Server] INFO at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:110) ~[ChunkIOProvider.class:?]
19.08 04:43:14 [Server] INFO at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) ~[ChunkIOExecutor.class:?]
19.08 04:43:14 [Server] INFO at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118) ~[on.class:?]
19.08 04:43:14 [Server] INFO at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89) ~[on.class:?]
19.08 04:43:14 [Server] INFO at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135) ~[on.class:?]
19.08 04:43:14 [Server] INFO at net.minecraft.world.World.func_72964_e(World.java:310) ~[amu.class:?]
19.08 04:43:14 [Server] INFO at net.minecraft.world.World.func_175726_f(World.java:305) ~[amu.class:?]
19.08 04:43:14 [Server] INFO at com.zeitheron.hammercore.world.WorldGenHelper.playerTick(WorldGenHelper.java:282) ~[WorldGenHelper.class:?]
19.08 04:43:14 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1098_WorldGenHelper_playerTick_PlayerTickEvent.invoke(.dynamic) ~[?:?]
19.08 04:43:14 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
19.08 04:43:14 [Server] INFO at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
19.08 04:43:14 [Server] INFO at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:370) [FMLCommonHandler.class:?]
19.08 04:43:14 [Server] INFO at net.minecraft.entity.player.EntityPlayer.func_184808_cD(EntityPlayer.java:378) [aed.class:?]
19.08 04:43:14 [Server] INFO at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288) [aed.class:?]
19.08 04:43:14 [Server] INFO at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) [oq.class:?]
19.08 04:43:14 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) [pa.class:?]
19.08 04:43:14 [Server] INFO at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) [NetworkDispatcher$1.class:?]
19.08 04:43:14 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) [gw.class:?]
19.08 04:43:14 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
19.08 04:43:14 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
19.08 04:43:14 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
19.08 04:43:14 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
19.08 04:43:14 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
19.08 04:43:14 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]`

**Comment by capnkirok** [comment]
Gah. Yep. One of the methods I used was client-side only. Putting out a fix now.

**Comment by ddd800** [comment]
Yep that fixed it thanks!
