### ISSUE TITLE
Chest pet improvement suggestion and problem with its food

### ISSUE THREAD

**Issue by Lictor000** [capnkirok/Inventory-Pets#322]
Hello,
I was trying this mod for the first time, and it's great and cute!
But I noticed that the chest pets may be improved. It would be nice, if possible, to be able to shift-click the items from your inventory to the one of the pet as for the normal chests.

Also I noticed that it seems that the double chest pet doesn't eat dark oak and acacia wood. I had a stack of both in my inventory but the pet went hungry anyway.

**Comment by Lictor000** [comment]
I add that the spider pet doesn't seem to be eating raw mutton.

**Comment by capnkirok** [comment]
Thanks for the feedback. I'll take these one at a time.

1) Spider will now eat raw mutton in the next release

**Comment by capnkirok** [comment]
2. Chest pet uses OreDictionary... so it eats all wooden planks (just tested and it works Dark Oak and Acacia). I think this might be a bug from an older version you are using. If so, please update.

**Comment by capnkirok** [comment]
3. Ok, after several days of messing around, I finally got Shift-Click to work with stacks with all the chest pets. Next release (2.0.4) coming soon!

**Comment by capnkirok** [comment]
And the feed bag!
