### ISSUE TITLE
Pam's Harvest Craft causes feeding issues with some pets in 1.12.2

### ISSUE THREAD

**Issue by Claycubed50** [capnkirok/Inventory-Pets#325]
Pam's Harvest Craft changes many of the details of certain foods, like making the wheat edible. for some reason, the small changes to these foods make them unfindable to the inventory pets that eat them. including the sheep, cow, ocelot, and cheeta. there still might be more issues that I was unable to find as well.

**Comment by capnkirok** [comment]
Yes, it looks like she modifies the item and makes a new one, whereas the pets are looking for the original. But she did list the new version in OreDictionary.

Two options:
1) Turn that feature off in HarvestCraft via the config
2) Have my pets look for the OreDictionary version

Recommend you do 1) until 2) can be implemented.

Who eats wheat?

**Comment by capnkirok** [comment]
Ok, I went through the list at Harvestcraft (https://github.com/MatrexsVigil/harvestcraft/blob/master/src/main/java/com/pam/harvestcraft/item/GeneralOreRegistry.java)

I've updated the following pets to be compatible with Harvestcraft's OreDictionary recipes.
Cow
Chicken
Sheep
Spider
Cheetah
