### ISSUE TITLE
Inventory Spider Pet

### ISSUE THREAD

**Issue by PiordaNautor** [capnkirok/Inventory-Pets#327]
I am unsure if this is the correct mod but currently I have yet to identify another mod that alters fall damage.
Sometime after removing my spider pet from my hotbar as it was on 0 durability, my screen now shakes up and down as if I were standing still on a bed or slime block. My default movement acts as if affected by Slowness I and Jump Boost I

**Comment by capnkirok** [comment]
Has it happened more than once? There's a weird bug in Minecraft where it sometimes doesn't update the hotbar properly. Happens very rarely.

**Comment by PiordaNautor** [comment]
Not that I have seen, yet. But it just seemed like it had similar effects to what the Spider Pet had, and the bug occurred shortly after I removed it from my hotbar/the Spider Pet got hungry. This was fixed by logging in and out again.

**Comment by capnkirok** [comment]
Really strange one. I have noticed that sometimes when you remove a pet from the hotbar, it somehow doesn't properly register. Happens very rarely though. I'm going to close this one, but will keep an eye out if anyone else reports. Thank you!
