### ISSUE TITLE
Quiver pet problem

### ISSUE THREAD

**Issue by DoesntCare** [capnkirok/Inventory-Pets#332]
Minecraft 12.2, pets 2.0.1, I had the quiver pet on the hot bar, feathers in my inventory and four arrows.  After four shots all the arrows were gone.  Looks like the infinite arrows isn't working.

**Comment by capnkirok** [comment]
Do you have any other mods installed? I know that there is a compat issue with COFH (meaning infinite arrows won't work with COFH installed)

**Comment by DoesntCare** [comment]
I have a lot of mods installed and, yes, CoFHCore is one of them.  Oh well.

**Comment by capnkirok** [comment]
Sorry about that one.
