### ISSUE TITLE
Mini dungeon invisible Wither Skeletons

### ISSUE THREAD

**Issue by Pulz-TCP** [capnkirok/Inventory-Pets#333]
The wither skeletons that spawn in the Inventory Pets mini dungeon are completely invisible for  [my modpack ](https://www.technicpack.net/modpack/tc-redux)players and reportedly won't stop spawning.

- Inventory Pets: 2.0.3
- Minecraft: 1.12.2
- SpongeAPI: 7.1.0-fb496dbf0
- Sponge: 1.12.2-7.1.6
- SpongeForge: 1.12.2-2825-7.1.6
- Minecraft Forge: 14.23.5.2838

Disabling the nether dungeons via the config fixes the issue on new worlds.

**Comment by capnkirok** [comment]
Yes, this is intentional. And yes, they don't stop spawning if you are nearby unless you destroy the spawner block(s). They are supposed to be challenging.

**Comment by Pulz-TCP** [comment]
Okay, thanks for letting me know.
