### ISSUE TITLE
Is there any way to sets Illuminati Cooldown for more than 5 min?

### ISSUE THREAD

**Issue by SlavikW** [capnkirok/Inventory-Pets#334]
i‘m using this mod for single player，i like these surprises but 5 min is just too short for me. I want the game be more challenging,

**Comment by capnkirok** [comment]
You can actually put up to 10 minutes in for the illuminati (even though it says 5).

**Comment by capnkirok** [comment]
This was updated in 1.15.x and 1.16.x to up to 10 minutes.
