### ISSUE TITLE
Small duplication bug regarding of looting pet

### ISSUE THREAD

**Issue by runescapejon** [capnkirok/Inventory-Pets#335]
So, here are the mods you'll need InventoryPet - 1.12-2.0.3 with [thaumic gadgets -1.12.2_0.1.5.1_tb.26 ](https://www.curseforge.com/minecraft/mc-mods/thaumic-gadgets)Then once you have them installed the mod. Get any type of pickaxe even diamond pickage works and an loot pet _(from inventory pet)_. Mine a ore called "Light Ore" or "Shade Ore" _(these ores are from thaumic gadgets)_ Also, be sure that you are in survival while mining. Finally you'll see an double the ore from mining just one of them.

**Comment by capnkirok** [comment]
Thanks @runescapejon. Will have to add these to a blacklist.

**Comment by capnkirok** [comment]
Ok, this is fixed and will be in the 2.0.4 update.
