### ISSUE TITLE
Quantum Crystal Monster crashes game if used?Can't log into world again?

### ISSUE THREAD

**Issue by NMihnea** [capnkirok/Inventory-Pets#337]
So I'm using the crazycraft 3 modpack,and I crafted the Quantum Crystal Monster pet and used it and it crashed the game.After this,I looked on the wiki and on the twitch page,and haven't found any error or glitch submissions about this.Then I logged onto the world again,and it crashed.Any help please?I really want to play with this mod,so yeah.PS:Sorry if I sound weird,first time posting.

**Comment by capnkirok** [comment]
Do you have the crash log?

**Comment by NMihnea** [comment]
uh,not anymore,i don't think so,i'll search for it

    Pe duminică, 8 martie 2020, 21:44:00 EET, Purplicious_Cow <notifications@github.com> a scris:  
 
 
Do you have the crash log?

**Comment by capnkirok** [comment]
Unfortunately, I can't updated 1.7.10 anymore as it is no longer supported by Forge. Try seeing if you can put the latest version of 1.7.10 into the modpack and if that fixes the issue.
