### ISSUE TITLE
1.7.10 Incompat. with Morphing Mod- Sort of...

### ISSUE THREAD

**Issue by CirceSays** [capnkirok/Inventory-Pets#338]
So my friend and I are running a, uh, "modpacked" server that includes inventory pets and the morphing mod- but for some reason, we can't fly as a bat due to some incompatibility. Advice or tips??? We removed inventory pets temporarily to test if it was the problem, and it was the only mod causing the issue.

**Comment by capnkirok** [comment]
I can no longer update 1.7.10 as it's not supported by Forge. It could in fact that the morph mod and inventory pets have a conflict with flying.
