### ISSUE TITLE
Any possibility to change the availability of items?

### ISSUE THREAD

**Issue by MYFlywolf** [capnkirok/Inventory-Pets#339]
Hi,

because i want to use this Mod for a Mod-Project, i want to change the availability of some items, because some are too strong or OP. Exists a config file for that?
Because only change  the recipes isn't the solution for that because of Itemdrops from chests.

It would be great if you respond to my Question and i hope for a fast answer ^^

Yours Faithfully

MyFlywolf

**Comment by capnkirok** [comment]
Hey @MYFlywolf yes, you can disable any pet in the config. This turns off their abilities.

Another option is to make them 'hardcore' feeding, which makes them harder to maintain.
