### ISSUE TITLE
Night vision potion effect not working.

### ISSUE THREAD

**Issue by luffykick** [capnkirok/Inventory-Pets#34]
Inventory pets seems to disable night vision effect from potions, or mods that use that potion effect. I noticed this happening when I installed ProjectE with Inventory Pets, that the Gem armors night vision would not work. Removing Inventory Pets solves the issue.

**Comment by capnkirok** [comment]
Yes, I can confirm this is a bug. Of course, ProjectE's talisman needs to stop repairing Inventory Pets. I may suggest a trade of sorts with that mod creator :)

**Comment by capnkirok** [comment]
Ok, just sent a note to sinkillerj. Hopefully we can fix two compatibility issues @ once.

**Comment by capnkirok** [comment]
Rolling out a fix in 1.3.7, workaround on the Inv Pets side.

**Comment by capnkirok** [comment]
Fixed in 1.7.10, now on to 1.8

**Comment by capnkirok** [comment]
Fixed in 1.3.8 for 1.8
