### ISSUE TITLE
Riding a tamable mob with the saddle pet will make it passive and unable to move on its own even after dismounting

### ISSUE THREAD

**Issue by MetroNight** [capnkirok/Inventory-Pets#340]
This applies to both modded mobs and vanilla wolves. Even though they would not move I could still get modded mobs to teleport to me. Wolves would not teleport to me regardless of how far I moved away from them. 

It took a lot of testing before I learned that the saddle pet was the cause of these issues.

I am using version 2.0.1

**Comment by capnkirok** [comment]
Cheers. Will take a look.

**Comment by capnkirok** [comment]
Yes, I was able to replicate. This only occurs if the mob is already tamed.

**Comment by capnkirok** [comment]
Ok, this is fixed in next release (2.0.4).
