### ISSUE TITLE
Snow Golem pet causes server to become unresponsive

### ISSUE THREAD

**Issue by Izabellum** [capnkirok/Inventory-Pets#341]
In the mc.eternal, latest version, putting the snow golem pet in a players inventory (sometimes the achievement triggers, sometimes it doesn't) causes a server to completely freeze. The client can still walk around without issue but no blocks drop, entities cannot be interacted with and etc. The server is completely unresponsive both by sending commands to it through a player client and by trying to write commands directly in the server terminal. The server produces no error messages or any information about whats going on. If it's relevant to the issue, the snow golem was removed from an actually additions small storage crate. 
To clarify, the issue happens when the snow golem is picked up into the players inventory and not when you try to remove it. But trying to pick it up from the storage crate did make it drop to the ground instantly. Other items in the crate did not share this trait.
Issue does not appear with mooshroom pets from the same inventory, but other pets have not been tested,

**Comment by capnkirok** [comment]
Sounds like the server side is crashing. Have you tried 'disabling' the pet in the Config? That may give you a temporary solution until I can address.

Any other mods installed? And assume you are on 1.12?

**Comment by capnkirok** [comment]
I just tried to replicate in both client and server environments and had no issues. Please let me know what other mods you have installed and what version you are using.

**Comment by capnkirok** [comment]
I'm closing this, since I haven't heard back
