### ISSUE TITLE
Inventory Pets(ver2.0.3) Language File Simplified Chinese

### ISSUE THREAD

**Issue by 1048139283** [capnkirok/Inventory-Pets#342]
Hi guys, I translator it into Simplified Chinese.
`
# Inventory Pets Language File Simplified Chinese (zh-CN)
# Inventory Pets Chinese Language File Translator: 'JIE'
item.inventorypets_ghast_pet.name=[宠物]恶魂
item.inventorypets_wither_pet.name=[宠物]凋灵
item.inventorypets_creeper_pet.name=[宠物]爬行者
item.inventorypets_enderman_pet.name=[宠物]末影人
item.inventorypets_iron_golem_pet.name=[宠物]铁傀儡
item.inventorypets_snow_golem_pet.name=[宠物]雪傀儡
item.inventorypets_spider_pet.name=[宠物]蜘蛛
item.inventorypets_magma_cube_pet.name=[宠物]岩浆怪
item.inventorypets_sheep_pet.name=[宠物]羊
item.inventorypets_cow_pet.name=[宠物]牛
item.inventorypets_chicken_pet.name=[宠物]鸡
item.inventorypets_pig_pet.name=[宠物]猪
item.inventorypets_squid_pet.name=[宠物]鱿鱼
item.inventorypets_ocelot_pet.name=[宠物]豹猫
item.inventorypets_furnace_pet.name=[宠物]熔炉
item.inventorypets_enchanting_table_pet.name=[宠物]附魔台
item.inventorypets_crafting_table_pet.name=[宠物]工作台
item.inventorypets_chest_pet.name=[宠物]箱子
item.inventorypets_double_chest_pet.name=[宠物]大箱子
item.inventorypets_bed_pet.name=[宠物]床
item.inventorypets_jukebox_pet.name=[宠物]唱片机
item.inventorypets_anvil_pet.name=[宠物]铁砧
item.inventorypets_brewing_stand_pet.name=[宠物]酿造台
item.inventorypets_nether_portal_pet.name=[宠物]下界传送门
item.inventorypets_pingot_pet.name=[宠物]声呐
item.inventorypets_mickerson_pet.name=[宠物]Mickerson
item.inventorypets_purplicious_cow_pet.name=[宠物]紫斑牛
item.inventorypets_qcm_pet.name=[宠物]量子晶体怪物
item.inventorypets_cloud_pet.name=[宠物]云
item.inventorypets_black_hole_pet.name=[宠物]黑洞
item.inventorypets_pufferfish_pet.name=[宠物]河豚
item.inventorypets_slime_pet.name=[宠物]史莱姆
item.inventorypets_shield_pet.name=[宠物]盾 
item.inventorypets_moon_pet.name=[宠物]月亮
item.inventorypets_heart_pet.name=[宠物]心
item.inventorypets_dubstep_pet.name=[宠物]重音回响
item.inventorypets_sponge_pet.name=[宠物]海绵
item.inventorypets_banana_pet.name=[宠物]香蕉
item.inventorypets_blaze_pet.name=[宠物]烈焰人
item.inventorypets_ender_chest_pet.name=[宠物]末影箱
item.inventorypets_mooshroom_pet.name=[宠物]哞菇
item.inventorypets_loot_pet.name=[宠物]战利品
item.inventorypets_juggernaut_pet.name=[宠物]红坦克
item.inventorypets_grave_pet.name=[宠物]墓碑
item.inventorypets_illuminati_pet.name=[宠物]光明会
item.inventorypets_custom_pet.name=[宠物]自定义
item.inventorypets_pacman_pet.name=[宠物]吃豆人
item.inventorypets_quiver_pet.name=[宠物]箭筒
item.inventorypets_april_fool_pet.name=[宠物]愚人节
item.inventorypets_cheetah_pet.name=[宠物]猎豹
item.inventorypets_house_pet.name=[宠物]家
item.inventorypets_silverfish_pet.name=[宠物]蠹虫
item.inventorypets_wolf_pet.name=[宠物]狼
item.inventorypets_apple_pet.name=[宠物]苹果
item.inventorypets_sun_pet.name=[宠物]太阳
item.inventorypets_torch_pet.name=[宠物]火把
item.inventorypets_siamese_pet.name=[宠物]暹罗猫
item.inventorypets_biome_pet.name=[宠物]生物群系
item.inventorypets_lead_pet.name=[宠物]栓绳
item.inventorypets_saddle_pet.name=[宠物]鞍
item.inventorypets_flying_saddle_pet.name=[宠物]飞鞍
item.inventorypets_pixie_pet.name=[宠物]像素
item.inventorypets_dirt_pet.name=[宠物]泥土
item.inventorypets_cobblestone_pet.name=[宠物]圆石
item.inventorypets_meta_pet.name=[宠物]元
item.inventorypets_meta_pet.0.name=[宠物]元
item.inventorypets_meta_pet.10.name=[宠物]元
item.inventorypets_meta_pet.20.name=[宠物]元
item.inventorypets_meta_pet.30.name=[宠物]元
item.inventorypets_meta_pet.40.name=[宠物]元
item.inventorypets_meta_pet.50.name=[宠物]元
item.inventorypets_meta_pet.60.name=[宠物]元
item.inventorypets_meta_pet.70.name=[宠物]元
item.inventorypets_meta_pet.100.name=[宠物]元
item.inventorypets_meta_pet.101.name=[宠物]元
item.inventorypets_meta_pet.102.name=[宠物]元
item.inventorypets_meta_pet.103.name=[宠物]元

item.inventorypets_xerox_parc_gui.name=Xerox PARC GUI
item.inventorypets_windows_31.name=Windoes 3.1
item.inventorypets_blue_screen_of_death.name=蓝屏
item.inventorypets_windows_me.name=Windoes ME
item.inventorypets_windows_xp.name=Windoes XP
item.inventorypets_windows_mojave.name=Windoes Mojave
item.inventorypets_windows_7.name=Windoes 7
item.inventorypets_windows_8.name=Windoes 8
item.inventorypets_start_button.name=开始
item.inventorypets_easter_egg.name=复活节彩蛋
item.inventorypets_rock_candy.name=硬糖

item.inventorypets_candy_cane.name=拐杖糖
item.inventorypets_mug_egg_nog.name=蛋奶酒
item.inventorypets_holiday_cookie.name=节日曲奇
item.inventorypets_item_gift.name=礼物
item.inventorypets_solstice_helmet.name=冬至头盔
item.inventorypets_solstice_chestplate.name=冬至胸甲
item.inventorypets_solstice_leggings.name=冬至护腿
item.inventorypets_solstice_boots.name=冬至靴子
item.inventorypets_solstice_sword.name=冬至剑
inventorypets.solstice.recipes=["持续十二天的Petmas节到了! 欢乐从12月14日开始 . 想要参加只需要创建一个节日宠物: [",{"text":"Recipes Here","color":"aqua","hoverEvent":{"action":"show_text","value":{"text":"Click to see the Holiday Pet recipes","color":"dark_aqua"}},"clickEvent":{"action":"open_url","value":"http://www.creeptech.net/images/ip/recipes/holiday_rec.png"}},"]"]
item.inventorypets_pet_christmas_tree.name=[宠物]圣诞树
item.inventorypets_pet_menorah.name=[宠物]九灯烛台
item.inventorypets_pet_mishumaa_saba.name=[宠物]七灯烛台
item.inventorypets_pet_politically_correct.name=[宠物]节日快乐
item.gift.notholiday=节日宠物只在十二月十四日到二十五日有效
item.gift.taken=你今天已经拿到礼物了
item.gift.dates=礼物只能在十二月十四日到二十五日使用
pet.holiday.dates=请在十二月十四日到二十五日尝试

item.inventorypets_nugget_diamond.name=钻石粒
item.inventorypets_nugget_obsidian.name=黑曜石粒
item.inventorypets_nugget_coal.name=煤粒
item.inventorypets_nugget_emerald.name=绿宝石粒
item.inventorypets_nugget_iron.name=铁粒
item.inventorypets_nugget_ender.name=末影粒
item.inventorypets_nugget_lapis.name=青金石粒
item.inventorypets_feed_bag.name=饲料袋
item.inventorypets_siamese_gift.name=礼物
item.inventorypets_item_petrifier.name=驯化器

item.inventorypets_patreon_head.name=Purplicious Cow Head
item.inventorypets_patreon_shirt.name=Cool T-Shirt

tile.inventorypets_cloud.name=云
tile.inventorypets_cloud_spawn.name=生成云
tile.inventorypets_sand.name=沙
tile.inventorypets_sand_spawn.name=生成沙
tile.inventorypets_stone.name=石
tile.inventorypets_stone_spawn.name=生成石
tile.inventorypets_space_spawn.name=宇宙刷怪笼
tile.inventorypets_nether_spawn.name=下届刷怪笼

tile.bed.notHere=你不能在这里睡
tile.bed.allPlayersNotSleeping=所有玩家都必须在床上

entity.inventorypets.MiniQuantumBlaze.name=迷你量子烈焰人
entity.inventorypets.MiniQuantumEnderman.name=迷你量子末影人
entity.inventorypets.BillGates.name=Bill Gates
entity.inventorypets.SteveBallmer.name=Steve Ballmer
entity.inventorypets.SatyaNadella.name=Satya Nadella
entity.inventorypets.EntityAnvilPet.name=铁砧
entity.inventorypets.EntityBedPet.name=床
entity.inventorypets.Banana.name=香蕉

entity.MiniQuantumBlaze.name=迷你量子烈焰人
entity.MiniQuantumEnderman.name=迷你量子末影人
entity.BillGates.name=Bill Gates
entity.SteveBallmer.name=Steve Ballmer
entity.SatyaNadella.name=Satya Nadella
entity.EntityAnvilPet.name=[宠物]铁砧
entity.EntityBedPet.name=[宠物]床
entity.Banana.name=[宠物]香蕉

item.wolf.false=警报关
item.wolf.true=警报开
item.loot.noenchants=[宠物]战利品 无法与时运、精准采集、抢夺效果叠加
item.petHouse.spawnpoint=[宠物]家已将出生点设置于
item.blackhole.on=[宠物]黑洞在吸收物品
item.blackhole.off=[宠物]黑洞不在吸收物品
item.pig.on=[宠物]猪将给予你物品
item.pig.off=[宠物]猪将不在予你物品
item.chicken.on=[宠物]鸡将给予你物品
item.chicken.off=[宠物]鸡将不在予你物品
item.irongolem.on=[宠物]铁傀儡将给予你物品
item.irongolem.off=[宠物]铁傀儡将不在予你物品
item.snowgolem.on=[宠物]雪傀儡将给予你物品
item.snowgolem.off=[宠物]雪傀儡将不在予你物品
item.slime.on=[宠物]史莱姆将给予你物品
item.slime.off=[宠物]史莱姆将不在予你物品
item.spider.on=[宠物]蜘蛛将给予你物品
item.spider.off=[宠物]蜘蛛将不在予你物品
item.sheep.on=[宠物]羊将给予你物品
item.sheep.off=[宠物]羊将不在予你物品

inventorypets.aprilfool.info=["四月，愚人节! 此时此刻, 享受愚人节宠物, 但请注意，他有点小顽皮! [",{"text":"Recipe Here","color":"aqua","hoverEvent":{"action":"show_text","value":{"text":"Click to see April Fool Pet recipe","color":"dark_aqua"}},"clickEvent":{"action":"open_url","value":"http://www.creeptech.net/images/ip/recipes/aprilfool_rec.png"}},"]"]
pet.fool.dates=请在愚人节尝试
pet.fool.disabled=愚人节结束了

container.petnamer=宠物名称
gui.accept=接受
gui.inventorypets.find=寻找
gui.inventorypets.teleport=传送
gui.biometofind=选择生物群系
gui.nameyourpet=为你的宠物取名
pop.inventorypets.biomein=你已经在这了

key.inventorypets.category=背包宠物
key.categories.naming=宠物名称

item.netherportal.noreturn=找不到返回的位置，自动回到最后一个出生点
item.netherportal.patience=请耐心等待，正在寻找安全地点
inventorypets.update.download=["Click to: [",{"text":"Download","color":"gold","hoverEvent":{"action":"show_text","value":{"text":"Click to see the latest files for 1.11.2 available for download","color":"gold"}},"clickEvent":{"action":"open_url","value":"http://minecraft.curseforge.com/projects/inventory-pets/files"}},"]"]

achievement.ip.petachieve1=第一步
achievement.ip.petachieve1.desc=获得你的第一只宠物！
achievement.ip.petachieve5=宠物学初学者
achievement.ip.petachieve5.desc=获得五只宠物
achievement.ip.petachieve10=宠物学研究者
achievement.ip.petachieve10.desc=获得十只宠物
achievement.ip.petachieve20=宠物学收藏家
achievement.ip.petachieve20.desc=获得二十只宠物
advancement.ip.petachieve30=宠物学科学家
advancement.ip.petachieve30.desc=获得三十只宠物
advancement.ip.petachieve40=宠物学专家
advancement.ip.petachieve40.desc=获得四十只宠物
advancement.ip.petachieve50=宠物学教授
advancement.ip.petachieve50.desc=获得五十只宠物
advancement.ip.petachieve60=宠物学行家
advancement.ip.petachieve60.desc=获得六十只宠物
achievement.ip.petachieveAll=宠物学权威
achievement.ip.petachieveAll.desc=获取MOD中的所有宠物！
achievement.ip.petachieveGeneralist=全能高手！
achievement.ip.petachieveGeneralist.desc=获得一种系列宠物
achievement.ip.petachievePacifist=和平主义者
achievement.ip.petachievePacifist.desc=获得所有和平系列的宠物
achievement.ip.petachieveMobster=“怪”人
achievement.ip.petachieveMobster.desc=获取所有的怪物系列的宠物
achievement.ip.petachieveUtilitarian=实用主义者
achievement.ip.petachieveUtilitarian.desc=获得所有实用系列的宠物
achievement.ip.petachieveSpecialist=特别的你
achievement.ip.petachieveSpecialist.desc=获得所有特殊系列的宠物
achievement.ip.petachieveFan=铁粉
achievement.ip.petachieveFan.desc=获得所有玩家建议系列的宠物
achievement.ip.petachieveAOE=有生力量
achievement.ip.petachieveAOE.desc=获得所有系列的宠物
achievement.ip.petachieveLegend=传奇
achievement.ip.petachieveLegend.desc=获得所有传说系列的宠物
advancement.ip.petachieveYouTuber=订阅者
advancement.ip.petachieveYouTuber.desc=获得所有Youtuber系列的宠物
advancement.ip.petachieveHoliday=圆满度过
advancement.ip.petachieveHoliday.desc=获得所有节日系列的宠物
advancement.ip.petachieveCat=猫奴
advancement.ip.petachieveCat.desc=获得所有猫系列的宠物
achievement.ip.petachieveIlluminati=光明会确认！！
achievement.ip.petachieveIlluminati.desc=来自光明会宠物的光照宠物！
achievement.ip.petachieveHolidaysOne=Petmas！
achievement.ip.petachieveHolidaysOne.desc=打开礼物
achievement.ip.petachieveHolidaysAll=给予
achievement.ip.petachieveHolidaysAll.desc=获得所有节日宠物
advancement.ip.petachieveRoot=背包宠物
advancement.ip.petachieveRoot.desc=获取MOD中的所有宠物！

advancement.ip.petachieveUseMeta=So Meta
advancement.ip.petachieveUseMeta.desc=使用[宠物]元
advancement.ip.petachieveMetaMeta=So Very Meta
advancement.ip.petachieveMetaMeta.desc=使用[宠物]元获得[宠物]元
advancement.ip.petachieveScavenger=Mr. Softy
advancement.ip.petachieveScavenger.desc=完成寻宝游戏
advancement.ip.petachieveSolstice=凛冬已至
advancement.ip.petachieveSolstice.desc=获得冬至套装
advancement.ip.petachievePetrifier=Wingardium Petiosa
advancement.ip.petachievePetrifier.desc=使用驯化器
advancement.ip.petachievePetrifyGhast=口袋恶魂
advancement.ip.petachievePetfifyGhast.desc=训化一只恶魂
advancement.ip.petachievePetrifyWither=口袋凋灵
advancement.ip.petachievePetfifyWither.desc=训化一只凋灵
advancement.ip.petachievekill_dirt=圆石就是生命！
advancement.ip.petachievekill_dirt.desc=杀死Crainer的粉丝
advancement.ip.petachievekill_cobble=泥土就是生命！
advancement.ip.petachievekill_cobble.desc=杀死Ssundee的粉丝

tooltip.ip.peaceful=和平
tooltip.ip.mob=怪物
tooltip.ip.special=特殊
tooltip.ip.youtuber=YouTuber
tooltip.ip.legendary=传奇的
tooltip.ip.utility=功能
tooltip.ip.holiday节日
tooltip.ip.fan=粉丝建议
tooltip.ip.aoe=影响范围
tooltip.ip.favoritefood=最爱的食物:
tooltip.ip.rawmeat=生肉
tooltip.ip.rightclick=右击
tooltip.ip.sneak=潜行
tooltip.ip.sneakrightclick=潜行+右击
tooltip.ip.control=左控制 
tooltip.ip.jump=跳跃
tooltip.ip.suggestedby=建议 by
tooltip.ip.designedby=设计 by
tooltip.ip.approvedby=批准 by
tooltip.ip.random=随机
tooltip.ip.on=开
tooltip.ip.off=关
tooltip.ip.togglegiveitems=切换物品给予模式
tooltip.ip.found=创建:
tooltip.ip.disabled=无效

tooltip.ip.petanvil1=缓慢自动修理
tooltip.ip.petanvil2=有损坏的物品
tooltip.ip.petanvil3=生成/移除一个活的铁砧（60s）
tooltip.ip.petapple1=丢苹果
tooltip.ip.petapple2=重击
tooltip.ip.petaprilfool1=生成Foolishness
tooltip.ip.petbanana1=丢
tooltip.ip.petbanana2=自动收会
tooltip.ip.petbed1=睡
tooltip.ip.petbed2=生成/移除一个活的床（60s）
tooltip.ip.petblackhole1=减慢时间
tooltip.ip.petblackhole2=吸引物品
tooltip.ip.petblackhole3=切换吸引物品模式
tooltip.ip.petbiome1=选择和寻找
tooltip.ip.petbiome2=再次寻找
tooltip.ip.petblaze1=伤害提升
tooltip.ip.petblaze2=火焰附加
tooltip.ip.petbrewingstand1=酿造随机药水
tooltip.ip.petcheetah1=急迫
tooltip.ip.petcheetah2=超级速度提升
tooltip.ip.petchestopen=开
tooltip.ip.petchicken1=速度提升
tooltip.ip.petchicken2=给予鸡蛋
tooltip.ip.petmas1=给予礼物
tooltip.ip.petcloud1=快速飞行
tooltip.ip.petcloud3=雷击
tooltip.ip.petcloud2=飘落
tooltip.ip.petcow1=去除负面效果
tooltip.ip.petcow2=用牛奶填满空桶
tooltip.ip.petcraftingtable1=合成
tooltip.ip.petcreeper1=爆炸
tooltip.ip.petcreeper2=免疫爆炸
tooltip.ip.petdubstep1=声爆
tooltip.ip.petenchantingtable1=附魔
tooltip.ip.petenderman1=传送
tooltip.ip.petenderman2=当血量不足时自动传送
tooltip.ip.petfurnace1=冶炼快捷栏内第一个可以被冶炼的物品
tooltip.ip.petfurnace2=放置在快捷栏内
tooltip.ip.petghast1=射击火球
tooltip.ip.petgrave1=死亡不掉落
tooltip.ip.petheart1=生命恢复
tooltip.ip.pethouse1=传送家
tooltip.ip.pethouse2=设置家
tooltip.ip.petilluminati1=生成随机物品
tooltip.ip.petilluminati2=隐形
tooltip.ip.petminute=分钟
tooltip.ip.petminutes=分钟
tooltip.ip.petminutecooldown=冷却时间
tooltip.ip.petirongolem1=伤害吸收
tooltip.ip.petirongolem2=给予虞美人
tooltip.ip.petjuggernaut1=无敌
tooltip.ip.petjuggernaut2=虚弱
tooltip.ip.petjukebox1=播放光盘
tooltip.ip.petjukebox2=停止播放
tooltip.ip.petjukebox3=播放下一光盘
tooltip.ip.petloot1=怪物的掉落物
tooltip.ip.petloot2=和挖矿
tooltip.ip.petmagmacube1=火焰抗性
tooltip.ip.petmagmacube2=岩浆行走
tooltip.ip.petmagmacube3=岩浆游动
tooltip.ip.petmickerson1=抗性
tooltip.ip.petmickerson2=生命的奥秘
tooltip.ip.petmoon1=逆转重力
tooltip.ip.petmooshroom1=骨粉
tooltip.ip.petmooshroom2=将物品栏中的空碗变成蘑菇煲
tooltip.ip.petnetherportal1=传送至下界
tooltip.ip.petnetherportal2=(回来)
tooltip.ip.petocelot1=夜视 
tooltip.ip.petocelot2=驱除苦力怕
tooltip.ip.petocelot3=钓鱼
tooltip.ip.petpacman1=饥饿时自动进食
tooltip.ip.petpacman2=超级伤害提升
tooltip.ip.petpig1=额外的食物饱和度
tooltip.ip.petpig2=可以吃有毒食物
tooltip.ip.petpig3=给予猪排
tooltip.ip.petpingot1=矿物追踪
tooltip.ip.petpingot2=自动挖取附近矿物
tooltip.ip.petpufferfish1=淬毒
tooltip.ip.petpufferfish2=毒液爆炸
tooltip.ip.petpurpliciouscow1=生命恢复
tooltip.ip.petpurpliciouscow2=用熔岩填满空桶
tooltip.ip.petqcm1=召唤奴仆
tooltip.ip.petquiver1=无限箭
tooltip.ip.petquiver2=射击（30s）
tooltip.ip.petsheep1=减速降落
tooltip.ip.petsheep2=给予羊毛
tooltip.ip.petshield1=抗性提升
tooltip.ip.petsilverfish1=免疫窒息
tooltip.ip.petsilverfish2=穿墙
tooltip.ip.petslime1=使你免于某种死亡
tooltip.ip.petslime2=给予粘液球
tooltip.ip.petsnowgolem1=击退
tooltip.ip.petsnowgolem2=给予雪球
tooltip.ip.petspider1=跳跃提升
tooltip.ip.petspider2=爬墙
tooltip.ip.petspider3=悬挂于墙上
tooltip.ip.petspider4=给予蛛丝
tooltip.ip.petsponge1=放置水
tooltip.ip.petsponge2=吸收水
tooltip.ip.petsponge3=水上行走
tooltip.ip.petsponge4=潜水
tooltip.ip.petsquid1=水下呼吸
tooltip.ip.petsquid2=水下视线
tooltip.ip.petsquid3=深海探索者
tooltip.ip.petsquid4=下沉
tooltip.ip.petwither1=25%吸血
tooltip.ip.petwither2=免疫凋零
tooltip.ip.petwither3=多发凋零骷髅头
tooltip.ip.petwither4=发射凋零骷髅头
tooltip.ip.petwolf1=生成/移除一只狼
tooltip.ip.petwolf2=切换警报
tooltip.ip.petwolf1=Summon/Dismiss Wolf
tooltip.ip.petwolf2=切换警报模式
tooltip.ip.petwolf3=驱除骷髅
tooltip.ip.petcobblestone1=将泥土转化成圆石
tooltip.ip.petcobblestone2=随机攻击
tooltip.ip.petcobblestone3=在圆石上获得加成
tooltip.ip.petdirt1=将圆石转化成泥土
tooltip.ip.petdirt2=随机攻击
tooltip.ip.petdirt3=在泥土上获得加成

tooltip.ip.petmasopen=立即打开！
tooltip.ip.petmasvalid=Note: 只在PETMAS期间有效，12月14日至25日
tooltip.ip.eat=吃
tooltip.ip.drink=喝
tooltip.ip.candycane1=速度提升2（5min）
tooltip.ip.candycane2=急迫2 (5min)
tooltip.ip.solsticesword1=增加9点伤害 (叠加)
tooltip.ip.solsticesword2=不活动三秒冷却结束
tooltip.ip.easteregg=生成一个友好的CEO
tooltip.ip.holidaycookie1=力量2(5min)
tooltip.ip.eggnog1=瞬间恢复所有生命值
tooltip.ip.foolishnesscooldown=Foolishness在冷却。剩余时间： 
tooltip.ip.homespawnpoint=设置出生点
tooltip.ip.illuminaticooldown=在冷却 剩余时间： 
tooltip.ip.pingotfound=声呐发现
tooltip.ip.wolfsays1=据说有个
tooltip.ip.wolfsays2=在附近
tooltip.ip.xeroxparcgui=可能没用
info.ip.livingbedinteract=喂我最喜欢的食物来睡觉
info.ip.livinganvilinteract=喂我最喜欢的食物来修理你的物品
tooltip.ip.patreonitem=Patreons限定

advancement.ip.petach_april_fool=开个玩笑
advancement.ip.petach_april_fool.desc=获得愚人节宠物
advancement.ip.petach_anvil=小心！
advancement.ip.petach_anvil.desc=获得[宠物]铁砧
advancement.ip.petach_apple=烂透了
advancement.ip.petach_apple.desc=获得[宠物]苹果
advancement.ip.petach_banana=劈啪
advancement.ip.petach_banana.desc=获得[宠物]香蕉
advancement.ip.petach_bed=小睡片刻
advancement.ip.petach_bed.desc=获得[宠物]床
advancement.ip.petach_biome=环境保护
advancement.ip.petach_biome.desc=获得[宠物]生物群系
advancement.ip.petach_black_hole=没问题
advancement.ip.petach_black_hole.desc=获得[宠物]黑洞
advancement.ip.petach_blaze=友善的火焰
advancement.ip.petach_blaze.desc=获得[宠物]烈焰人
advancement.ip.petach_brewing_stand=酿造学
advancement.ip.petach_brewing_stand.desc=获得[宠物]酿造台
advancement.ip.petach_cheetah=他们从未成功
advancement.ip.petach_cheetah.desc=获得[宠物]猎豹
advancement.ip.petach_chest=箱子
advancement.ip.petach_chest.desc=获得[宠物]箱子
advancement.ip.petach_chicken=便携式家禽
advancement.ip.petach_chicken.desc=获得[宠物]鸡
advancement.ip.petach_christmas_tree=圣诞节愉快!
advancement.ip.petach_christmas_tree.desc=获得[宠物]圣诞树
advancement.ip.petach_cloud=叫我宙斯！
advancement.ip.petach_cloud.desc=获得[宠物]云
advancement.ip.petach_cobblestone=Team Ssundee
advancement.ip.petach_cobblestone.desc=获得[宠物]圆石
advancement.ip.petach_cow=银河
advancement.ip.petach_cow.desc=获得[宠物]牛
advancement.ip.petach_crafting_table=创造性
advancement.ip.petach_crafting_table.desc=获得[宠物]工作台
advancement.ip.petach_creeper=火药溢出
advancement.ip.petach_creeper.desc=获得[宠物]苦力怕
advancement.ip.petach_dirt=Team Crainer
advancement.ip.petach_dirt.desc=获得[宠物]泥土
advancement.ip.petach_double_chest=更多的箱子
advancement.ip.petach_double_chest.desc=获得[宠物]大箱子
advancement.ip.petach_dubstep=Beat Down！
advancement.ip.petach_dubstep.desc=获得[宠物]重音回响
advancement.ip.petach_enchanting_table=Enchanted to Meet You
advancement.ip.petach_enchanting_table.desc=获得[宠物]附魔台
advancement.ip.petach_ender_chest=ChickenBones万岁
advancement.ip.petach_ender_chest.desc=获得[宠物]末影箱
advancement.ip.petach_enderman=Vwoop!
advancement.ip.petach_enderman.desc=获得[宠物]末影人
advancement.ip.petach_flying_saddle=高空骑乘
advancement.ip.petach_flying_saddle.desc=获得[宠物]飞鞍
advancement.ip.petach_furnace=Cooking with Nuggets
advancement.ip.petach_furnace.desc=获得[宠物]熔炉
advancement.ip.petach_ghast=目瞪口呆
advancement.ip.petach_ghast.desc=获得[宠物]恶魂
advancement.ip.petach_grave=Ain`t it a Shame?
advancement.ip.petach_grave.desc=获得[宠物]墓碑
advancement.ip.petach_heart=❤ ❤ ❤ ❤
advancement.ip.petach_heart.desc=获得[宠物]心
advancement.ip.petach_house=Jiggity-Jig
advancement.ip.petach_house.desc=获得[宠物]家
advancement.ip.petach_illuminati=我们在监视
advancement.ip.petach_illuminati.desc=获得[宠物]光明会
advancement.ip.petach_iron_golem=Is is Not Ironical?
advancement.ip.petach_iron_golem.desc=获得[宠物]铁傀儡
advancement.ip.petach_juggernaut=太多了
advancement.ip.petach_juggernaut.desc=获得[宠物]红坦克
advancement.ip.petach_jukebox=扣人心弦
advancement.ip.petach_jukebox.desc=获得[宠物]唱片机
advancement.ip.petach_lead=激发潜能
advancement.ip.petach_lead.desc=获得[宠物]栓绳
advancement.ip.petach_loot=寻宝人
advancement.ip.petach_loot.desc=获得[宠物]战利品
advancement.ip.petach_meta=遇见[宠物]元
advancement.ip.petach_meta.desc=创造[宠物]元
advancement.ip.petach_magma_cube=烫！
advancement.ip.petach_magma_cube.desc=获得[宠物]岩浆怪
advancement.ip.petach_menorah=Chag Sameach!
advancement.ip.petach_menorah.desc=获得[宠物]光明会
advancement.ip.petach_mickerson=42
advancement.ip.petach_mickerson.desc=获得[宠物]Mickerson
advancement.ip.petach_mishumaa_saba=Umoja!
advancement.ip.petach_mishumaa_saba.desc=获得[宠物]Kwanzaa Pet!
advancement.ip.petach_moon=So Cheesy
advancement.ip.petach_moon.desc=获得[宠物]月
advancement.ip.petach_mooshroom=真菌感染
advancement.ip.petach_mooshroom.desc=获得[宠物]哞菇
advancement.ip.petach_nether_portal=Nether Say Nether
advancement.ip.petach_nether_portal.desc=获得[宠物]下界传送门
advancement.ip.petach_ocelot=野猫
advancement.ip.petach_ocelot.desc=获得[宠物]豹猫
advancement.ip.petach_pacman=哇咔咔哇咔咔！
advancement.ip.petach_pacman.desc=获得[宠物]吃豆人
advancement.ip.petach_pig=Squealer
advancement.ip.petach_pig.desc=获得[宠物]猪
advancement.ip.petach_pingot=把它挖出来!
advancement.ip.petach_pingot.desc=获得[宠物]声呐
advancement.ip.petach_pixie=No Dust on You
advancement.ip.petach_pixie.desc=获得[宠物]像素
advancement.ip.petach_politically_correct=节日快乐!
advancement.ip.petach_politically_correct.desc=获得[宠物]节日快乐
advancement.ip.petach_pufferfish=河豚目
advancement.ip.petach_pufferfish.desc=获得[宠物]河豚
advancement.ip.petach_purplicious_cow=Vainglorious!
advancement.ip.petach_purplicious_cow.desc=获得[宠物]Purplicious Cow
advancement.ip.petach_qcm=快救救我!
advancement.ip.petach_qcm.desc=获得[宠物]量子晶体怪物
advancement.ip.petach_quiver=侠盗罗宾汉
advancement.ip.petach_quiver.desc=获得[宠物]箭筒
advancement.ip.petach_saddle=骑乘
advancement.ip.petach_saddle.desc=获得[宠物]鞍
advancement.ip.petach_sheep=喷泉之友 
advancement.ip.petach_sheep.desc=获得[宠物]羊
advancement.ip.petach_shield=Off Hand Joker
advancement.ip.petach_shield.desc=获得[宠物]盾
advancement.ip.petach_siamese=Stacy Approves!
advancement.ip.petach_siamese.desc=获得[宠物]暹罗猫
advancement.ip.petach_silverfish=离水之鱼
advancement.ip.petach_silverfish.desc=获得[宠物]蠹虫
advancement.ip.petach_slime=Jerry不朽 
advancement.ip.petach_slime.desc=获得[宠物]史莱姆
advancement.ip.petach_snow_golem=南瓜恶灵!
advancement.ip.petach_snow_golem.desc=获得[宠物]雪傀儡
advancement.ip.petach_spider=Aragog Lives
advancement.ip.petach_spider.desc=获得[宠物]蜘蛛
advancement.ip.petach_sponge=Suck it Up
advancement.ip.petach_sponge.desc=获得[宠物]海绵
advancement.ip.petach_squid=Slippery When Wet
advancement.ip.petach_squid.desc=获得[宠物]鱿鱼
advancement.ip.petach_sun=Gone Fusion
advancement.ip.petach_sun.desc=获得[宠物]日
advancement.ip.petach_torch=Sick Burn
advancement.ip.petach_torch.desc=获得[宠物]火把
advancement.ip.petach_wither=你会凋灵的 
advancement.ip.petach_wither.desc=获得[宠物]凋灵
advancement.ip.petach_wolf=Big and Bad
advancement.ip.petach_wolf.desc=获得[宠物]狼

tooltip.ip.petsun1=阻止周围生成怪物
tooltip.ip.petsun2=将怪物暴露在烈日下
tooltip.ip.pettorch1=复制火把
tooltip.ip.pettorch2=放置火
tooltip.ip.petlead1=束缚并驯服怪物
tooltip.ip.petsaddle1=骑乘怪物
tooltip.ip.petflyingsaddle1骑乘怪物
tooltip.ip.petflyingsaddle2=飞行（骑乘时）
tooltip.ip.petflyingsaddle3=下降
tooltip.ip.petsiamese1=给予你随机的礼物
tooltip.ip.petsiamese2=驱除周围的僵尸
tooltip.ip.petsiamese3=生成/移除宠物
tooltip.ip.petsiamese4= 已经给予你了一个特别的礼物
tooltip.ip.petpixie1=双倍经验
tooltip.ip.petmeta1=变形
tooltip.ip.petmeta2=元评分:
tooltip.ip.petrifier1=驯服方块或者怪物
tooltip.ip.petrifier2=使用时消耗钻石
tooltip.ip.petrifier3=使用时消耗钻石块
`

**Comment by capnkirok** [comment]
Thank you!
