### ISSUE TITLE
Config to change favourite pet food

### ISSUE THREAD

**Issue by firyy** [capnkirok/Inventory-Pets#344]
As the title says, it would be very useful, even more if one disables the new nuggets for example :)

**Comment by capnkirok** [comment]
Yeah, I hear you. This is on my list, but it's going to require a complete rewrite, so not so easy. Leaving it up here as a reminder.

**Comment by Neubenutzer** [comment]
how soon do you think, that you can implement this?

**Comment by capnkirok** [comment]
closing this one as #363 is on the list
