### ISSUE TITLE
Anvil pet stopped working

### ISSUE THREAD

**Issue by Shat4f** [capnkirok/Inventory-Pets#346]
I don't know what happened but my anvil pet has stopped working even tho it was fine a few hours ago and this has been goin on for a couple days. IT WAS WORKING BEFORE NOT DISABLED. all the other pets are just fine

**Comment by capnkirok** [comment]
- Which version of Inventory Pets are you running?
- Assuming you have iron nuggets in your inventory? 
- Any other mods for a potential conflict?

**Comment by capnkirok** [comment]
(I just tested and it's working fine for me)

**Comment by postal291** [comment]
I'm experiencing the same issue in the MC Eternal pack (Inventory Pets 2.0.4).

Anvil pet just stopped working, tried reloading, and it worked once after reloading then stopped again.

Nothing produced in logs regarding this.

Feeding via the feed bag in inventory.  Anvil pet is in slot 8.
Tried iron nuggets in slot 7 as well, nothing.

Note: My armor is tinkers' armory armor, perhaps it doesn't repair that type?

**Comment by capnkirok** [comment]
Ah! Yes... it won't repair Tinkers' armor. Tinkers uses a completely different system. Sorry about that.
