### ISSUE TITLE
Mooshroom and Torch pet right click capability not working

### ISSUE THREAD

**Issue by amberan** [capnkirok/Inventory-Pets#347]
In last version (1.12-2.0.4) the bone meal right click capability of mooshroom pet does not work. It worked in previous version.

**Comment by capnkirok** [comment]
Looks like it only works in off hand. Same with Torch Pet.

**Comment by capnkirok** [comment]
Ok, this is fixed in dev. Look for the 2.0.5 release in the next few days. Thanks for the report!
