### ISSUE TITLE
Wither Pet does not grant immunity to wither effect

### ISSUE THREAD

**Issue by tlitookilakin** [capnkirok/Inventory-Pets#349]
Running v2.0.4 on forge 14.23.5.2847. (MC Eternal)
Pet is fully fed and left in hotbar, still afflicted by wither. Also tested with holding pet in main hand, with no change. Tested wither effect sources: lingering potions, gaia guardian. Other effects of wither pet work correctly.

**Comment by capnkirok** [comment]
Thanks. Will look into it.

**Comment by capnkirok** [comment]
Ok, just checked and it's working for me. Are you sure it's fed? With the Wither pet, it's hard to tell if it's fed because of the color. 

Also, can you send me a link to the pack version you are using? 

PC

**Comment by tlitookilakin** [comment]
Hmmmm, can't seem to replicate it now. Must have been a one-off thing. Sorry about that. I'll reopen this if I ever figure out what happened.
