### ISSUE TITLE
Illuminati Pet Confirms Non-Craftable Items [cross-mods]

### ISSUE THREAD

**Issue by OracleofWuffing** [capnkirok/Inventory-Pets#35]
I have been receiving items that can't be crafted from a recipe from the Illuminati pet.  Don't get me wrong, it's incredibly fun to spam the slot machines, but I don't think some of these items were intended.  I initially had this experience on InventoryPets version 1.3.6 for minecraft 1.7.10.  I did not see anything in the changelog indicating that the Illuminati Pet was changed in the newest version, so I also tried this on 1.3.7, and still had items that don't have a recipe to craft.

What I saw from my 1.3.6 trial was:
Creative Speedy Hopper from Gany's End (http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291092-ganys-end-miscellaneous-ender-themed-additions)
End Portal Frame from Vanilla Minecraft
Lemurite Oreberry Bush from AOBD: Berry Bushes (http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2472300-aobd-berry-bushes-dynamically-generated-bushes)
Creative Charge pad from EnderTech (https://github.com/carrotengineer/EnderTech)
Reactor Creative Coolant Port from BigReactors (http://www.big-reactors.com/#/)

What I saw in my 1.3.7 trial was:
Platinum Oreberry Bush from AOBD: Berry Bushes
tile.block.LightNode.name from EnderIO (http://enderio.com/)
Apple from Growthcraft (http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2505072-growthcraft-community-edition-proper-1-7-10) - To clarify, this isn't an actual item, but a block that grows, you punch it and get the vanilla apple item.
Small Fire from GardenCore (http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2163513-garden-stuff-v-1-7-0-updated-dec-06-15)
Rice Paddy from GrowthCraft (not a big offender, just this isn't something you craft)
Forcefield from Malisis' Doors (http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2076338-malisisdoors-1-8-2-2-0-1-7-10-1-13-0-30-11-2015)
Creative Infinite Fluid Source from Gany's End

I know mods made by Ganymedes appears there a lot, so I'm uncertain if this is an Inventory Pets issue, or actually something on his end.  Some things, like the Oreberry Bushes, can be used in Gany's Volcanic Furnace to "craft" lava, or Gany's Organic Matter Compressor to "craft" coal blocks.  I thought "All Craftable Items from mods" meant "All items that you can craft," if it actually works by "all items you can craft, and all items that can be used to craft items," well, I'm sorry for being a derp and apologize for the waste of time on some of those entries.  There's the same sort of situation with Thermal Dynamics, where items like the End Portal Frame can be used to make an item, but the End Portal Frame itself isn't craftable.

Regardless of those items, items like the Creative Speedy Hopper, Creative Charge Pad, Forcefield, and Creative Infinite Fluid Source do not have a crafting recipe to make, and are not used in a crafting recipe... At least as far as NEI tells me.  I know I can "fix" this by turning off the Illuminati Pet's ability to confirm items, but that's taking a lot of fun out of the pet.

I'm sorry for not offering a solution to this, but the actual mod writing isn't my bag, so as far as I know it could just be that everyone else is doing something wrong.  I figure if you're good enough to make the pet as fun as it is, any suggestion I'd throw would've either been thought or brought up to you by someone else at this point.

**Comment by capnkirok** [comment]
Thanks for the detail. Illuminati was originally supposed to spawn any item (not just craftable ones). I changed it in 1.3.6 (I believe) to enable all items. Kudos to you for reading the release notes ;)

The solution that has been suggested is to make an 'exclusion list' available. Probably a JSON or some kind of text file. But haven't taken that anywhere yet.

Right now, we're a bit torn about how to handle. We like the random items that can't really be used (just for fun), and that you have a chance to get any item from the game. If we went back to craftable only, it would fix some of the issues, but you'd miss out on getting the top level items that might be hidden. Need to think on this one some more.

**Comment by capnkirok** [comment]
Ok, just an update on this. The exclusion list will be quite time consuming. In the short term, we're going to add some config options in the next update:

1) Only craftable vanilla items
2) Only craftable items from all mods
3) All items from all mods in game

Default option will be #2

**Comment by capnkirok** [comment]
Illuminati now by default only gives craftable items. You can change it in the config to give any item in the game, if so desired.
