### ISSUE TITLE
Config disable on server not being enforced on clients

### ISSUE THREAD

**Issue by EnderMelody** [capnkirok/Inventory-Pets#353]
I have a server with others, and I have the cloud pet disabled. My friend went into their clients config and enabled the cloud pet, and is now able to use it despite it being disabled on the server.
Not sure if this works for other pets.

MC - 1.12.2
Inventory pet - inventorypets-1.12-2.0.4.jar

**Comment by capnkirok** [comment]
Will add this in a future release

**Comment by capnkirok** [comment]
Took me so long to identify the issue. It's actually not a config issue, but some poor coding the Cloud Pet flying. I'll make an update soon.
