### ISSUE TITLE
Dirt Pet and Cobblestone Pet

### ISSUE THREAD

**Issue by GladBody22** [capnkirok/Inventory-Pets#354]
Me and my friends started the Almost Vanilla modpack and I'm currently working on getting Inventory pets. I found a few already, but everytime i equip certain ones, like the dirt or cobblestone pet, they give me Weakness, Slowness, Mining Fatigue and Poison indefinitely. I've looked around and can't find anything about that online. What is happening? Is this a bug? They also sometimes give like super effects, like Haste, Regeneration and Speed.

**Comment by capnkirok** [comment]
The Dirt Pet and Cobblestone Pet are mortal enemies and are basically PVP pets. If you have one in your hotbar and your friend has the other... you play a random attack on right click, and can convert Dirt to Stone and vice versa.

If you have Dirt in your hotbar and walk on Stone... you get negative effects...
If you have Stone in your hotbar and walk on Dirt... same

And you get positive effects if you have Dirt in your hotbar and walk on Dirt and same if you have Stone in your inventory and walk on Stone.

Try it out...

**Comment by capnkirok** [comment]
Closing....
