### ISSUE TITLE
House Pet doesn't work if home is in other dimension

### ISSUE THREAD

**Issue by anbecker** [capnkirok/Inventory-Pets#361]
**Version where encountered:** 
v. 2.0.4 (in context of the 'Roguelike Adventures and Dungeons' modpack)

**Issue:**

When warping to a home in another dimension, the player can (or _will_, in my experience) fall into the void before the world loads (or else fall into the ground and begin to suffocate).

Additionally, the x,z location within said dimension also does not always seem to match the one to which it was set.

**Repro steps:**
Create House Pet
Set home in one dimension (issue encountered so far in the Aether, the vanilla overworld, and home tent dimensions from Nomadic Tents mod)
Travel to another dimension
Use pet to warp to set home

**Comment by capnkirok** [comment]
Thanks for the detailed examples. Checking it out.

**Comment by capnkirok** [comment]
~~No issues with Aether & Inventory Pets alone on SP. Will check MP.~~

**Comment by capnkirok** [comment]
Ok, got it. Looks like if you set your spawn in a custom dimension it is not saving that location correctly. Works fine if you set spawn in vanilla overworld.

**Comment by capnkirok** [comment]
Ok, this is fixed in dev. Look for the 2.0.6 update relatively soon.

**Comment by anbecker** [comment]
Thanks for the quick attention!
