### ISSUE TITLE
Unlimited Meta pet usage

### ISSUE THREAD

**Issue by Xnosis** [capnkirok/Inventory-Pets#362]
If you put meta pet in off hand and use it, you get a new pet, but it doesn't consume the meta pet.

Replicated with only JEI and Inventory Pets 1.12-2.0.5

**Comment by capnkirok** [comment]
Ohhhh boy. That's a bad one.

*shakes off-hand fist*

**Comment by capnkirok** [comment]
Alright, I've disabled Meta Pet in offhand. Will be in the 2.0.6 release. Thank you!
