### ISSUE TITLE
Cloud Pet disabled flight via double tap space

### ISSUE THREAD

**Issue by Wakizashimaster** [capnkirok/Inventory-Pets#365]
Minecraft Version: 1.12.2
Mod: FTB Sky Odyssey 1.2.0
Issues: Cloud Pet disables flight via double tap space bar (jet packs are fine)

1) Whilst wearing Supremium armor full set you are granted something akin to creative flight by double tapping space bar.  Holding the cloud pet in inventory disables this.

2) Whilst wearing Angel Ring powered via Grid Power it too is disabled when holding the cloud pet in inventory. It is also enabled via double tap spacebar.

Removing the pet restores flight

**Comment by capnkirok** [comment]
I've found a way to fix this permanently, but it's on 1.16 versions and up.
