### ISSUE TITLE
Saddle Pet dose not work with some mobs

### ISSUE THREAD

**Issue by oi12004253** [capnkirok/Inventory-Pets#366]
When i use the saddle pet for a creeper, it works! But when i get off of the creeper it suddenly explodes. the same thing for the wither boss. the wither starts attacking me when i'm riding and when i get off.

**Comment by capnkirok** [comment]
That is intended behavior. It's dangerous to ride these things!

I recommend putting the Ocelot or Creeper in your hotbar to prevent Creeper from killing you.

I can't do anything about the Wither Pet. You could load yourself up with the Wither Pet, Creeper Pet, Pcow Etc, Mickerson, etc. and see how long you can go.
