### ISSUE TITLE
Issue with Mutli Hotbar mod 1.12.2

### ISSUE THREAD

**Issue by Code-phant0m** [capnkirok/Inventory-Pets#367]
Trying to use a pet that gives effect on the secondary hotbar will result as ingame crash

**Comment by capnkirok** [comment]
Can you post your crash log? Maybe put in pastebin.com and put the link here.

**Comment by DieselpunkCyborg** [comment]
I got this crash too. I hope that this is the right log, I have no idea what I'm doing. If its not let me know and I'll try to get the right one

https://paste.ee/p/jj8Nk

**Comment by capnkirok** [comment]
This crash has nothing to do with Inventory Pets @DieselpunkCyborg . Looks like JEI didn't like something from another mod. Might want to reach out to Mezz (creator of JEI).

**Comment by capnkirok** [comment]
Multi-hotbar appears to be working fine with all pets in latest release (2.0.10). If you do get issues please post your crash log. I can't do anything without it.
