### ISSUE TITLE
Client side wont boot up, But my server is till running with the exact same version

### ISSUE THREAD

**Issue by Forevera7x02** [capnkirok/Inventory-Pets#368]
[crash-2020-11-21_13.08.43-client.txt](https://github.com/capnkirok/Inventory-Pets/files/5578153/crash-2020-11-21_13.08.43-client.txt)

**Comment by Forevera7x02** [comment]
It was working perfectly fine yesterday, just randomly stopped working today

**Comment by Forevera7x02** [comment]
For some reason my Inventorypet.cfg file was in a folder and technic launcher wouldnt read it

**Comment by capnkirok** [comment]
Glad it worked out!
