### ISSUE TITLE
Redundant texture list for particle inventorypets:quantum_particle (1.15.2)

### ISSUE THREAD

**Issue by leyxcx** [capnkirok/Inventory-Pets#369]
I have no other mods installed, and the game almost launches but then crashes. I don't know if this is an error on my part, but I can't find any solution. [crash-2020-12-15_15.07.28-client.txt](https://github.com/capnkirok/Inventory-Pets/files/5692797/crash-2020-12-15_15.07.28-client.txt)

**Comment by capnkirok** [comment]
I don't think it's you. I've never had an issue in my testing, but I see this has been an issue for others:
https://github.com/itsmeow/whisperwoods/issues/1

I'll see if I can make a similar change and put in an update. You may get lucky and be able to launch as it appears to be related to the registry order of Particles (which should not cause a crash). I also notice you are using an Alpha (and bugged) version of Forge (31.2.47). I've tested on the Recommended version (31.2.0), which seems to work fine.

You may want to test this^^ while I work on a potential fix. Thanks for the report!

**Comment by capnkirok** [comment]
Ok, I've fixed this on my side, will release 2.0.7 tomorrow.

**Comment by capnkirok** [comment]
https://www.curseforge.com/minecraft/mc-mods/inventory-pets/files/3139154

Grab the latest!

**Comment by leyxcx** [comment]
> https://www.curseforge.com/minecraft/mc-mods/inventory-pets/files/3139154
> 
> 
> 
> Grab the latest!

thank you!
