### ISSUE TITLE
[1.15.2] Illuminati Pet cooldown notif seems broken

### ISSUE THREAD

**Issue by tlsctf2** [capnkirok/Inventory-Pets#371]
small thing here, but the message you get when you try to use an Illuminati Pet on cooldown doesn't seem to work. even when the time is still set to its default time, and I try using it right after I use an item spawn, it always says "Less than a minute remaining." even if it has over a minute remaining
(sorry for no labels, I don't know how to add them. been a while since I used GitHub)

**Comment by capnkirok** [comment]
I'll check it out. Thx.
