### ISSUE TITLE
Feature Request: Pet bag

### ISSUE THREAD

**Issue by Miqhtiedev** [capnkirok/Inventory-Pets#373]
An inventory item that you can put pets in similar to a backpack but only pets.
Pets in this "backpack" will still be activated regardless of if the bag is in the hot bar or somewhere else in the inventory.

**Comment by capnkirok** [comment]
Mmmmmm... well, the point is that players have to choose which pets are active in their hotbar.

**Comment by capnkirok** [comment]
But thanks for the suggestion!
