### ISSUE TITLE
Client Side Crash from server

### ISSUE THREAD

**Issue by Deathstar175** [capnkirok/Inventory-Pets#375]
On 1.16.4 when using the enchanting pet, and the food bag on a server, if the pet tries to eat from food bag the client will crash to server list and will be unable to connect until bag has been removed from inventory by server op.

[Crash info from server.txt](https://github.com/capnkirok/Inventory-Pets/files/5758465/Crash.info.from.server.txt)

Possibly Client side only code trying to run on server?

**Comment by capnkirok** [comment]
Oh, that's a bad one. It should not be running that code on the server, you are correct. Let me jump on this one.

**Comment by capnkirok** [comment]
Yes, it's a bug in all 'Right-Click'' triggered pets. Should have it fixed shortly.

**Comment by capnkirok** [comment]
Ok, update is up. Should fix this permanently, and player can recover after installation without involving Server Op deletion.
