### ISSUE TITLE
Banana Pet Server Crash

### ISSUE THREAD

**Issue by WenXin20** [capnkirok/Inventory-Pets#376]
`Inventory Pets v2.0.9`
[`Pokecube AIO v3.5.1`](https://www.curseforge.com/minecraft/mc-mods/pokecube-aoi)
`Minecraft v1.16.4`
`Forge v35.1.28`

If another entity picks up the Banana Pet, the server crashes. The crash happens if pokecube is installed and the config setting `vanilla_pokemobs` in `pokecube_common.toml` is set to `true`. In my case, the crash occured when a piglin picked up the banana pet that I had tagged with `minecraft:piglin_loved`
[Crash Report](https://gist.github.com/WenXin20/0f39795447e4909ebd840aa1cf12c889)

**Comment by Thutmose** [comment]
The specifics of what is occurring in that crash:

Item has a method `public void inventoryTick(ItemStack stack, World worldIn, Entity entityIn, int itemSlot, boolean isSelected)`, this method in vanilla minecraft is only called from `PlayerInventory`, so the `entityIn` is a player. Where it is used in vanilla however (the map item mostly, the other use case doesn't care about the `entityIn`), does checks to see if the `entityIn` is an instanceof `PlayerEntity`, before further processing, this indicates that `entityIn` can be other types of entities if needed.

It seems that `petBanana` is doing an un-checked cast to `PlayerEntity`, and this is causing the crash.

**Comment by capnkirok** [comment]
Thank you for the detailed report. You are exactly correct. This has been in the Inventory Pets code since 2015, and applies to all pets (not just the Banana). Didn't occur to me then that a non-player would try to use a Pet item, and never looked at it before.

Straightforward fix. I'll try to flip it around today.

**Comment by WenXin20** [comment]
Alright, thanks!
