### ISSUE TITLE
Iron Ingot recipe is redundant

### ISSUE THREAD

**Issue by ModernGamingWorld** [capnkirok/Inventory-Pets#377]
![2021-01-02_23 38 29](https://user-images.githubusercontent.com/75923060/103472474-a3c2a980-4d53-11eb-83ca-23bfae7d518c.png)

Example try and disabled your Iron Nugget recipe in a datapack as its not even needed to begin with and it wont disable

**Comment by capnkirok** [comment]
Which version of MC and Inventory Pets are you using? Are there any other recipes that can't be disabled? I can certainly remove the recipe from 1.15 and 1.16 altogether, but want to know if there are others that are causing problems.

**Comment by capnkirok** [comment]
I've removed the redundant Iron Ingot recipe from 1.12, 1.15, and 1.16. Please report back if you find any other recipes with this issue. I did a quick sweep and didn't see any others that would cause issues.

**Comment by ModernGamingWorld** [comment]
I'll let ya know shortly if I found more
