### ISSUE TITLE
Loot pet stopped working!

### ISSUE THREAD

**Issue by NinjaStealth21** [capnkirok/Inventory-Pets#38]
I was exploring a castle in crundee craft and at some point i got blown up and after this happened the loot pet from inventory pets stopped working for me and my friend but my friend did not die.

**Comment by capnkirok** [comment]
I assume the pet is not just hungry? I have made that mistake, so I have to ask. I will test based on the info your provided and see what I find. Thanks for the report!

**Comment by capnkirok** [comment]
I don't see any issues with the Loot Pet. Can you let me know if you are still having an issue?

**Comment by capnkirok** [comment]
Found the issue(s) and rewrote all Loot Pet code for drops and mining. Should be fixed in 1.4.0, working with all mods.
