### ISSUE TITLE
Baubles-related Crash 1.16.4

### ISSUE THREAD

**Issue by agentwolf88** [capnkirok/Inventory-Pets#380]
https://paste.ee/p/5C7Ir

**Comment by capnkirok** [comment]
Disable the Grave Pet in the config. It's currently not compatible with Baubles as their API has changed.

Same as #379

**Comment by agentwolf88** [comment]
Oh, thx!

**Comment by ItSammyboi** [comment]
How do I go about getting into the config?

**Comment by capnkirok** [comment]
Go to your Minecraft folder, open the config folder. Find the file inventorypets-common.toml and open with a text editor like Notepad.

**Comment by capnkirok** [comment]
Ok, a fix for this is added to 2.0.11. Grave Pet now works with baubles, so you can re-enable Grave Pet.
