### ISSUE TITLE
Quiver pet not working

### ISSUE THREAD

**Issue by queso619** [capnkirok/Inventory-Pets#381]
The quiver pet doesn't seem to be making infinite arrows or insta-shotting when I right click. It's well fed and the music plays but it doesn't seem to work.

**Comment by capnkirok** [comment]
Which version of MC are you using? And I assume you are right clicking with your bow, right?

**Comment by queso619** [comment]
I'm using 1.16.4 and yea I'm right clicking the bow.

**Comment by capnkirok** [comment]
Confirmed. Only works in Creative. Working on fix.

**Comment by capnkirok** [comment]
Actually, this is working as intended. You must have arrows in your inventory. Since Mojang changed it so that all 'shot' arrows can be picked up, there's no longer a need for infinite arrows. I might explore an alternate solution, however.

**Comment by capnkirok** [comment]
Ok, I'm adding in some new functionality that will replace your arrows if you run out. It's on a slight delay, but still gives a significant advantage without overloading your inventory with tons of extra arrows, which is what used to happen.

**Comment by P-rox-y** [comment]
Was this fix added in 2.0.12? 
Quiver pet still doesn't seem to be giving extra arrows on survival so wasn't sure if the fix was meant for .12 or .13
