### ISSUE TITLE
Conflict with vanilla Lapis Recipe

### ISSUE THREAD

**Issue by ModernGamingWorld** [capnkirok/Inventory-Pets#383]
I try to remove the Lapis and Emerald Recipes through a datapack and they dont disable at all

**Comment by capnkirok** [comment]
There's nothing special about the recipes, so not being able to remove/overwrite them is something on your end. However, there is a conflict with the vanilla Lapis -> Blue Dye, which I'll fix.

**Comment by capnkirok** [comment]
Did a quick bit of research. Datapacks don't work reliably on modded recipes. Recommend you try Crafttweaker mod.

**Comment by capnkirok** [comment]
I've removed the Lapis nugget recipe and left in the Lapis alt recipe... which Lapis + Dirt -> 9 Lapis nuggets.

**Comment by ModernGamingWorld** [comment]
@capnkirok I have had not issues with removing other mods recipes using datapacks, yours just seems to not remove

**Comment by capnkirok** [comment]
Here's the Emerald -> Emerald Nugget recipe. There is no other code in the mod affecting this. If there's something you think I can do, let me know, but I am at loss.

`
{
  "result": {
    "item": "inventorypets:nugget_emerald",
    "count": 9
  },
  "ingredients": [
    {
      "item": "minecraft:emerald"
    }
  ],
  "type": "minecraft:crafting_shapeless"
}
`
