### ISSUE TITLE
Juggernaut Pet bug

### ISSUE THREAD

**Issue by jiansheng010** [capnkirok/Inventory-Pets#386]
The cool down is broken. I have "invisibility" forever.

**Comment by capnkirok** [comment]
Juggernaut provides invulnerability. Did you mean Illuminati? 

Also, what version of MC and Inventory Pets are you using?

**Comment by jiansheng010** [comment]
Invulnerability I mean. I was using it and I always had invulnerability. I couldn't die. Not sure if that was intended or not so I looked up the cool down time and it says 1minute cool down. But there was no cool down, i had invulnerability forever and couldn't die. I'm on 1.16.4 and 2.0.10.

**Comment by capnkirok** [comment]
Thanks for the detail. Will look at it now.

**Comment by jiansheng010** [comment]
No problem! Let me know if there's anything else I can provide.

**Comment by capnkirok** [comment]
Got it! Will be fixed in next release... coming tonight! Thanks for the report :)

**Comment by jiansheng010** [comment]
That's awesome! Thank you so much! I have a server with the mod and everyone says it's the best mod they've played with.
