### ISSUE TITLE
Sky Dungeon conflict with Alps from Biomes You'll Go

### ISSUE THREAD

**Issue by WenXin20** [capnkirok/Inventory-Pets#387]
`Minecraft v1.16.4`
`Forge v35.1.36`
`Inventory Pets v2.0.10`

The cloud blocks, cloud spawner, and space spawner provide xray when placed next to other blocks. The cloud dungeon also can generate inside terrain, in this picture is the Alps from Biomes You'll Go.

![2021-01-10_00 15 55](https://user-images.githubusercontent.com/12000593/104115842-45f50b00-52d9-11eb-95aa-49dc37c260b2.png)

**Comment by capnkirok** [comment]
Thanks for the report. I'll some space checking for the Sky dungeon, which will fix the overlap. 

The cloud blocks are supposed to provide X-ray. They are harvest level 3 (Diamond), and require Silk Touch, so not easy to mine. The original intention was to help players further along in their quest find underground dungeons, as they are very difficult to find.

**Comment by WenXin20** [comment]
Alright, thanks

**Comment by capnkirok** [comment]
Will be in next release
