### ISSUE TITLE
Some pet sounds are not localized.

### ISSUE THREAD

**Issue by Futi63** [capnkirok/Inventory-Pets#389]
Currently, the Dubstep pet and the Pacman pet sounds on use are not localized, meaning the whole server regardless of location can hear these pets.

**Comment by capnkirok** [comment]
Thanks for the examples. Super-annoying I am sure. Easy fix, will do a sweep of all sounds and add in next release.

**Comment by capnkirok** [comment]
Ok, this is fixed in next release. I had 7 sounds set as AMBIENT type (including Dubstep, PacMan, Shield, Heart). Examples made it easy to find and fix, so thanks!

**Comment by jiansheng010** [comment]
The cloud pet too, I could hear someone use the cloud pet from miles away.
