### ISSUE TITLE
Loot pet combined with fortune III

### ISSUE THREAD

**Issue by Haiglis** [capnkirok/Inventory-Pets#39]
I find this fairly overpowered since I received 39 stacks of iron ingots from one stack of iron ore. This has the same effect on every type of ore.

Don't know if this is a known 'issue'
Crundee Craft version 1.0.19

**Comment by capnkirok** [comment]
Hmmm.... it shouldn't stack with fortune. Thanks for the version number. Will look into this one too.

**Comment by Haiglis** [comment]
Maybe it could be a legendary pet? Or perhaps just more expensive to create :+1:

**Comment by capnkirok** [comment]
This will be fixed in 1.3.9

**Comment by capnkirok** [comment]
This was fixed in 1.3.9+
