### ISSUE TITLE
2.0.10 update prompt

### ISSUE THREAD

**Issue by Pulz-TCP** [capnkirok/Inventory-Pets#390]
Essentially a dupe of #331
Displaying new version prompt with the specified version in use- and also mentions 1.11.2 instead of 1.12.2

![](https://www.pulz.site/x/sZeTMQjWAk8q.png)

**Comment by capnkirok** [comment]
Gah. Looks like I forgot to update the 'version' setting in the build. Well, I've fixed the 'text' for now so it doesn't show the MC version. 

If you find this super-annoying, you can turn the message off using the config... just set showUpdateMessage to false. Or I have an update planned in the next 2 weeks where this will be included. Thanks for the report!
