### ISSUE TITLE
[1.16.4] When respawning with an active grave pet, retained, stackable items will not stack.

### ISSUE THREAD

**Issue by oliblue100** [capnkirok/Inventory-Pets#391]
When I die with an active grave pet, any stackable item that I have acts as if its own item.

e.g.

I have 32 cobblestone, 32 torches, and 32 coal. I die with an active grave pet, and retain those items after respawning. However, any new cobblestone I gather, does not stack with the 32 I retained, but starts its own, new stack. This is the same with the torches, and coal.

There is a sort of, half solution. If I throw the two separate stacks on the floor, they will combine. However, the new combined stack will not combine with any new items either.

**Comment by capnkirok** [comment]
Will take a look. Thank you for the report and details.

**Comment by capnkirok** [comment]
It has to do with the way I've copied the NBT data. I'll need to redo this.

**Comment by capnkirok** [comment]
Ok, this one boiled down to an empty NBT Data tag. A null tag is not the same as a tag with null contents. Once you create a tag, even if it has 'null' contents, there's no way to remove. To fix this, don't create a tag at all.

Fixed in next release
