### ISSUE TITLE
1.12.2 illuminati pet random gets a cool down of thousands of minutes

### ISSUE THREAD

**Issue by JT122406** [capnkirok/Inventory-Pets#395]
randomly the illuminati pet will gain a huge cool down and the only way to fix it is to get rid of it and spawn a new one in creative

**Comment by capnkirok** [comment]
The Illuminati timer uses real world time. So, if you manipulate world time, it will reflect in time. I had a post about that one, so just checking to see if that could be the case here.

Thousands of minutes sounds suspicious as it's only using the 24-hour Minecraft scale, so the max would be 15 minutes. Some questions, while I take a look:
What version of Inventory Pets are you using? (assuming 2.0.10)?
Are there any other mods installed that might affect time? 
Were you changing dimensions or manipulating time in any way?

**Comment by JT122406** [comment]
I’m on Minecraft version 1.12.2 and inventory pets version: 2.0.10
We are changing dimensions but even when we don’t it can still happen and sometimes it happens just from putting it in a chest.  Other mods are installed but I do not think any of them affect the time

**Comment by capnkirok** [comment]
Alright, I figured the issue out. I'm only looking at 'daytime' so if there's a night cycle it will mess up the timing. I'm going to add a month/day/year check as well which should fix the issue (as long as you don't go backwards in time).

**Comment by JT122406** [comment]
Sounds good, lmk when you push out an update, please.

**Comment by capnkirok** [comment]
Fixed in dev. Going to try to get one more bug fixed, then release later today.

**Comment by JT122406** [comment]
sounds good, thank you for fixing this bug
