### ISSUE TITLE
1.16 incompatibility with Ice and Fire

### ISSUE THREAD

**Issue by Jacboy567** [capnkirok/Inventory-Pets#396]
I have a small modpack that includes inventory pets and Ice and Fire. When it comes to Ice and Fire it will not allow you to use lightening (either when hatching a dragon or using the sword) as it kills the dragon or yourself instantly. We found out it was something wrong between these two mods. Would like to know if there is a work around or if this is something we should wait on.

**Comment by capnkirok** [comment]
Hey Jacboy567. Yes, there's a lightning boost in InventoryPets. It should be checking to see if you are using the Cloud Pet feature, but it looks like I removed this accidentally in the update. I will put out a fix. Thanks!

There's no real workaround as it's not mod-dependent, so requires an update.

**Comment by Jacboy567** [comment]
Do you have a rough time estimate of when this update could be? No rush, just wanted to see if there’s something I could tell everyone else. Thank you!

**Comment by capnkirok** [comment]
This is fixed and will be in the next release coming very soon (next day or 2).

**Comment by Jacboy567** [comment]
Ok! Can’t wait!
