### ISSUE TITLE
1.16.4 - Quark issue and feed bag

### ISSUE THREAD

**Issue by mnsnownutt** [capnkirok/Inventory-Pets#397]
Version 2.0.11 of inventory pets mod.  When Quark is used and the Quark mod is set to use Quark chests in world gen and for player created chests, it is not possible to craft a feed bag, because the recipe does not recognize the Quark chest.  The only fix is to change the settings in Quark, craft a chest to make the bag and then go back into Quark and change it back.

**Comment by capnkirok** [comment]
Thanks Goldy93 for the details. I think you are saying there's a recipe conflict. I can add an alternate non-conflicting recipe for the Feed Bag that should work.

**Comment by capnkirok** [comment]
~~In the meantime, I believe you can use CraftTweaker to modify the recipe.~~

Never mind, just re-read the description. There might be a way to do this with tags. Checking...

**Comment by capnkirok** [comment]
Yep. Using the forge tag worked. This will be fixed in the next update, coming soon.

**Comment by mnsnownutt** [comment]
Glad to hear you figured it out.
