### ISSUE TITLE
1.16.4 FTB Ultimine compatibility

### ISSUE THREAD

**Issue by mnsnownutt** [capnkirok/Inventory-Pets#398]
When using the Loot pet, the FTB ultimine does not work.  The blocks are highlighted, but only one block will break.

https://user-images.githubusercontent.com/31514693/105411616-3a6ae380-5bf9-11eb-85e0-5594522ae151.mp4

**Comment by capnkirok** [comment]
Sounds like an event conflict. I've never used FTB ultimine, so will need to test.

**Comment by capnkirok** [comment]
FTBUltimine and Inventory Pets are using the same event. The only way I can make Ultimine work is to disable the Loot Pet mining when Ultimine is installed. I have no way of telling when the Ultimine key trigger is being pressed, unfortunately, unless I create specific keybind packets for Ultimine. Perhaps Latvian Modder can open up an API, or provide a further clue?

**Comment by capnkirok** [comment]
I will add the above to Inventory Pets ^^ for now.
