### ISSUE TITLE
1.16.4 Loot Pet, no XP

### ISSUE THREAD

**Issue by mnsnownutt** [capnkirok/Inventory-Pets#399]
When using the loot pet, XP is not generated from ores that should generate xp, such as coal, redstone, etc.

https://user-images.githubusercontent.com/31514693/105411847-89187d80-5bf9-11eb-8767-fb11aa7886d2.mp4

**Comment by capnkirok** [comment]
Thanks Goldy93. I'll look into this.

**Comment by capnkirok** [comment]
Confirmed this is indeed a bug, and has to do with how I'm firing the harvest drops event. Nice catch.

**Comment by capnkirok** [comment]
Ok, found the issue. This will be fixed in next release.

**Comment by mnsnownutt** [comment]
Excellent.  Great job and great mod.  Keep it up!!
