### ISSUE TITLE
1.12.2 Mooshroom+Petrifier=Cow Pet

### ISSUE THREAD

**Issue by skwii69** [capnkirok/Inventory-Pets#406]
If you use a Mooshroom Petrifier, you will get a Cow Pet instead of a Mooshroom Pet.

https://gyazo.com/2e013f611dbf04dd5854600892cb773b (gif)

version
InventoryPets 1.12 2.0.10

**Comment by capnkirok** [comment]
Thank you! Should be an easy fix. Stay tuned.

**Comment by capnkirok** [comment]
Ok, this will be fixed in the next release.
