### ISSUE TITLE
Can't make a world

### ISSUE THREAD

**Issue by TheOtherworldly** [capnkirok/Inventory-Pets#409]
every time I load up a world it takes forever or crashes when I finally get in.
If I take inventory pets out of my modpack, it lets me get into a world just fine. Because I am closing the game manually, I have no crash report. When I say it crashes, I mean the world crashes not the game

**Comment by capnkirok** [comment]
Hey ArcticFox921! Do you have a link to your modpack? Clearly, this is a conflict with another mod, so I need to know what mods you are using.

Also, you should have a log still even if not a crash log. It will let me know what point in the load process is failing. Check out your logs folder in Minecraft folder and see if you have a 'debug' (preferred) or 'latest' log file. You can copy/paste it into pastebin.com and share the link to it here.

**Comment by capnkirok** [comment]
Hey ArcticFox, going to close this one since I was not able to replicate.
