### ISSUE TITLE
Double Chest Pet- disappearing inventory

### ISSUE THREAD

**Issue by WheresMyMtnDew** [capnkirok/Inventory-Pets#41]
Using this mod on our private lan game and my friend and I both had double chest pets and everything was fine until I opened mine and the entire inventory was gone and was replaced by his chest pets inventory..... WTH? Not sure what happened but it was working fine for over an hour of play and then this.

**Comment by capnkirok** [comment]
Sorry about this, and thanks for the report. Yeah, there is a problem with DoubleChest, just reported a few days ago. Can you tell me which version of the mod you are using?

**Comment by WheresMyMtnDew** [comment]
Yeah we are using the 1.8 version, love this mod by the way. Do you need a list of the mods we are using? If that will help let me know.

**Comment by capnkirok** [comment]
That would be great. I'll try to get an update out as soon as possible. Would avoid the Double Chest in the meantime.

**Comment by WheresMyMtnDew** [comment]
Mods are as following:
code chicken Lib
autoswitch
enchant view
bspkrscore
treecapitator
wood converter
advanced inventory
alchemycraft
aromacore
base metals
better HUD
better chests
better foliage
better villages
butterflymania
chameleon
chest transporter
code chicken core
custom npcs
cyanos lootable bodies, wonderful wands
decoration mega pack
electric advantage
exotic birds
fairy lights
gems plus
inventory pets
journeymap
lattice mod
level up
loot++
Minecraft comes alive
minerology
more furnaces
mr crayfish furn.
multipage chest
no more rec. conflict
NEI
plants mega pack
power advantage
radix core
redstone paste
simple refinement
smelt cycle
steam advantage
storage drawers
the agricultural revolution
the luttle things
utility worlds
wild caves
world edit and
zombie steak...

yeah its a lot but the kids are really having a great time with it. Hope you can fix the double chest pet. Thanks.

**Comment by capnkirok** [comment]
Thank so much! Hopefully will have it solved soon.

**Comment by capnkirok** [comment]
This has been fixed in 1.3.9+ on all versions
