### ISSUE TITLE
1.16.4 Furnace Pet

### ISSUE THREAD

**Issue by PCRGaming** [capnkirok/Inventory-Pets#411]
On rightclick it turns iron axe to an iron nugget (smelting) why is that a thing

**Comment by capnkirok** [comment]
It's actually a recipe in Minecraft. Iron tools are smeltable into iron nuggets (and Gold tools into gold nuggets). I could make an exception for tools to prevent unwanted behavior.

**Comment by capnkirok** [comment]
Ok, I have added the above change in the next release, coming soon.

**Comment by PCRGaming** [comment]
ok thanks
