### ISSUE TITLE
Conflict with Ultimine Mod

### ISSUE THREAD

**Issue by HueyKablooey** [capnkirok/Inventory-Pets#412]
I get a message that says that Loot Pet bonus is disabled to avoid conflict with Ultimine every time I mine a block and a few other times that involve interacting with blocks.

**Comment by HueyKablooey** [comment]
This occurs with the latest 1.16.5 release of Inventory Pets.

**Comment by capnkirok** [comment]
That's what it's supposed to do (that's a message from Inventory Pets). Loot Pet is not compatible with FTB Ultimine. Is there a different behavior you would expect?

**Comment by HueyKablooey** [comment]
Why is there a conflict? Ultimine requires a key to be held down to activate and this error is getting thrown when just doing regular mining and whatnot. Ultimine doesn't give extra of anything so they do two separate things.

**Comment by capnkirok** [comment]
InventoryPets and FTB Ultimine are using the same event in Minecraft (BreakBlock). InventoryPets waits for the block to break and the duplicates the drops from the BlockEvent.BreakEvent. FTB Ultimine waits for the first block to break and then and then finds all connected blocks and then creates a new drops list and drops that. Inventory Pets has no access to FTB's drop list. If I didn't disable InventoryPets Loot Pet when it was in the hotbar, FTB Ultimine would break all the blocks but then only drop one block, which is why I put this warning in. I also don't know when FTB Ultimine key press is down. Technically, I could use packets and send a note to the server side to know when the key is being pressed, but that is an awful lot of work for a compat for a mod.

**Comment by capnkirok** [comment]
The FTB Ultimine event code is here, in case you are interested:
https://github.com/FTBTeam/FTB-Ultimine/blob/afa7cc222353cc13c8150cf3aaf53e347244117f/common/src/main/java/com/feed_the_beast/mods/ftbultimine/FTBUltimine.java

**Comment by HueyKablooey** [comment]
Ok. Thanks for the explanation. Could you leave Loot Pet's ability enabled and put a disclaimer that players need to remove the Loot Pet from their hotbars when actually using Ultimine? There won't be a conflict unless the player is holding down the Ultimine key.

**Comment by capnkirok** [comment]
This message feature was put in as a request of another modpack maker, so I'm not going to change the default behavior. However, I will put in a config option and you can turn the message off if you desire. 

Side note: I don't know why I'm the one making exceptions for FTB Ultimine. Did you actually reach out to LatvianModder about this? Or rather, can you?

**Comment by HueyKablooey** [comment]
I'm not sure if you're understanding my request. The in game message is important for how the mod is right now. I want to be able to use the Loot Pet when I'm not Ultimining (holding down the Ultimine key). Is it possible to reenable the Loot Pet with Ultimine installed and just put a disclaimer on the mod page that using Ultimine with the Loot Pet in the hotbar will cause a problem? Right now the only solution is to uninstall the Ultimine mod. If I need to clear out a lot of stone, I'd like to use Ultimine. If I'm mining diamond or attacking mobs, the Loot Pet would be pretty handy. Make sense? If it isn't possible than so be it but it seems like they won't conflict unless they're being used together (as in holding down the ultimine key and mining while the Loot Pet is in the hotbar). For a modpack where players don't always pay attention to all the mods installed, your current way makes sense. For those of us that add a few extra mods to modpacks, some control over this issue would be nice.

**Comment by capnkirok** [comment]
Ah, I get it. Thanks for the clarification. Here's what I can do. I'll add a config that re-enables the Loot Pet and disables the message. It will default to the current configuration, but easy for you to change.

Also, I would recommend you reach out to LatvianModder. You can use that link above, and just go to the issues page and log one there. I would really like these things to work together, perhaps he can open up an API to FTBUltimine so I could access the result set and we solve all problems for everyone.

**Comment by HueyKablooey** [comment]
Perfect thank you.

I posted on the Ultimine Github so we'll see if he responds or reaches out to you.
