### ISSUE TITLE
Conflict with Fire and Ice Mod

### ISSUE THREAD

**Issue by BusinessRex** [capnkirok/Inventory-Pets#415]
When lightning strikes the lightning dragon egg, bonus magical damage is done and the dragon inside the egg is killed.

**Comment by capnkirok** [comment]
Which version of Inventory Pets and Minecraft are you using?

**Comment by capnkirok** [comment]
I'm closing this, as this bug was fixed in a previous release (2.0.11). Additional lightning damage is only applied when manually using the Cloud Pet. All other instances uses default Vanilla behavior.
