### ISSUE TITLE
Pac-Man Pet does not work

### ISSUE THREAD

**Issue by Kooramah** [capnkirok/Inventory-Pets#421]
Currently using Inventory Pets 1.16-2.0.12

Mods:
![image](https://user-images.githubusercontent.com/5595669/110266418-98b61080-7f72-11eb-9161-e6507b529b6d.png)

I made this MineColonies Modpack for myself and a few friends. It has InventoryPets and didn't modify the configs at all. After a few weeks, I've gotten my hands on the PacMan Pet. The PacMan pet does not feed me at all, I started with full hunger points and saturation. I went from full to no hunger points and the Pacman Pet didn't feed me.

I tried all Vanilla Food and it doesn't work. No errors were found on the console.

![image](https://user-images.githubusercontent.com/5595669/110266743-52ad7c80-7f73-11eb-9744-0beb1082bbc8.png)

Let me know if you need more info

**Comment by capnkirok** [comment]
Thanks for sharing your mods. I'll take a look and see what's going on.

**Comment by capnkirok** [comment]
Confirmed this is a bug in the 1.15.x and 1.16.x versions.

**Comment by capnkirok** [comment]
Ok, this will be fixed in next release.

**Comment by Kooramah** [comment]
> Ok, this will be fixed in next release.

Sweet, thank you for checking it out
