### ISSUE TITLE
Cloud pet can break any block

### ISSUE THREAD

**Issue by TheDeadEnder** [capnkirok/Inventory-Pets#422]
I found a bug. I don't know if anyone has reported this yet but if you right click a block and another block is above the block will be replaced with fire and deleted completely including indestructible blocks like bedrock (this is in 1.16.4)

**Comment by capnkirok** [comment]
Can confirm that this is a bug. It definitely should not destroy indestructible blocks.

**Comment by capnkirok** [comment]
Ok this will be fixed in next release. Updated in 1.15 and 1.12 as well.
