### ISSUE TITLE
Cloud pet lightning ability destroys any blocks, including bedrock

### ISSUE THREAD

**Issue by Dejeh** [capnkirok/Inventory-Pets#423]
Using the cloud pet in the direction of any block breaks the block on top of it.

version:
InventoryPets-1.16-2.0.12
mods:
just inventory pets
video:
https://user-images.githubusercontent.com/72144320/110711742-0f027f00-81ce-11eb-8364-05d5ea6b48c6.mp4

**Comment by Dejeh** [comment]
well it seems 8 minutes ago someone opened the same issue lol

**Comment by capnkirok** [comment]
Going to close this one as its a dupe. 7 years of this mod, and no-one has caught this until now. Definitely a bug.
