### ISSUE TITLE
Treetop chests not spawning (1.16.5, 1.16-2.0.12)

### ISSUE THREAD

**Issue by greedycooler** [capnkirok/Inventory-Pets#424]
I have excavated every leaf in 3 forests (vanilla forests btw), turned up the frequency in configs to 10, and pretty much everything there is to do in order to find the treetops. However, I have not found a single treetop chest.

Other cloud chests, underwater dungeons, etc. seem to be working fine, it's the treetop one specifically that just isn't spawning.

**Comment by capnkirok** [comment]
Thanks for the report. I'll verify and get back to you.

**Comment by capnkirok** [comment]
![2021-03-13_19 32 22](https://user-images.githubusercontent.com/9628379/111053578-ef1fc500-8432-11eb-9469-2660d8684f2c.png)
 
Just tested in a new world, and got this looking in one direction (the floating blocks indicate the locations). This is set at 5 out of 10.

You probably know this, but chests only generate in new chunks. In general, I'd expect 2-3 chests in a large forest biome at normal 5 spawn rate. However, there's no guarantee they will spawn. We are at the mercy of minecraft's RNG.

I do feel like this is a bit low, so I may increase slightly based on your comment. However, it does still work (tested multiple times). I think you just had bad luck.
