### ISSUE TITLE
Bed Pet kicks from server when trying to use feeding bag

### ISSUE THREAD

**Issue by RGFTheCoder** [capnkirok/Inventory-Pets#426]
As the title states, the Bed Pet crashes the server when trying to use feeding bag

Log: https://gist.github.com/RGFTheCoder/b8048a7a78cb48bfaf47d6a7e54c5779

**Comment by capnkirok** [comment]
Yep, that's a bug. It definitely should not be calling client side code from the server. Thank you for the log!

**Comment by capnkirok** [comment]
Found the same bugged code on the Banana and the Brewing Stand. All 3 are fixed now. Thank you so much for the report.
