### ISSUE TITLE
Dubstep causes all tamed creatures to die.....

### ISSUE THREAD

**Issue by butterflygirl30** [capnkirok/Inventory-Pets#427]
My friend on my server got a dubstep pet and it caused all tamed creatures with in a radius, to (we think)  teleport through walls and get stuck in the walls and die. We lost so many animals to this. Please fix!

**Comment by capnkirok** [comment]
I can add a check for tamed creatures.

**Comment by capnkirok** [comment]
Ok I've added this for the next release. Please note, this will only skip Tamed creatures.

**Comment by capnkirok** [comment]
Also applied the same logic to the Sun Pet, Black Hole, and Moon.
