### ISSUE TITLE
Textures are broken

### ISSUE THREAD

**Issue by yektako** [capnkirok/Inventory-Pets#43]
All textures are broken

![2016-01-31_16 02 41](https://cloud.githubusercontent.com/assets/16986693/12702530/ba604a16-c834-11e5-998d-499d33da7bf6.png)
![2016-01-31_16 06 13](https://cloud.githubusercontent.com/assets/16986693/12702532/ba613d72-c834-11e5-8363-a0c7f4afd4ff.png)
![2016-01-31_16 06 25](https://cloud.githubusercontent.com/assets/16986693/12702531/ba60ae34-c834-11e5-8f20-88cc1e6e39de.png)

**Comment by capnkirok** [comment]
There's nothing wrong with the textures in 1.8, so it's something else. I would delete and re-install Inventory Pets with a fresh download.

**Comment by capnkirok** [comment]
Let me know if you still have problems after doing the above
