### ISSUE TITLE
TNT in treetops

### ISSUE THREAD

**Issue by Murrlin** [capnkirok/Inventory-Pets#435]
1.16.5 Forge 36.1.0
With the treetop TNT setting disabled in the config, I still got TNT (on at least two separate instances).

**Comment by capnkirok** [comment]
Verified this was a bug. Had not initialized the config value properly. Fixed in 2.0.13 (releasing soon).

**Comment by Murrlin** [comment]
Bless you!! I admit to having a blast imagining you dilligently coding your little hooves off. Although, I don't envy any author the constant restarts.
