### ISSUE TITLE
Grave Pet Not Saving Baubles For 1.12.2

### ISSUE THREAD

**Issue by Clyax113** [capnkirok/Inventory-Pets#437]
Hello.  The Grave Pet does not save Baubles for the latest version of 1.12.2.  I noticed that this was solved for game version 1.16.5 in 1.9-1.4.8.jar on Jul 17, 2016, but even the 1.12.2 version from Feb 7 2021 doesn't have this feature.  If it wasn't expected to be added to 1.12.2 then I please ask that it is.

**Comment by capnkirok** [comment]
Well, in 1.16.5, I just make sure and restore all items dropped into your inventory. However, it doesn't place them back in the baubles slots. Far from perfect.

Should be working 1.12.2, so I'll see what's going on.

**Comment by capnkirok** [comment]
Ok, I've fixed this in 1.12 dev. Look for the update in the next release (2.0.13).

**Comment by Clyax113** [comment]
> 
> 
> Ok, I've fixed this in 1.12 dev. Look for the update in the next release (2.0.13).

Thank you.
