### ISSUE TITLE
1.16.5 Crash related to Minecolonies

### ISSUE THREAD

**Issue by Reginald-Halifrax** [capnkirok/Inventory-Pets#438]
Unfortunately for me and my wife we lost an hour of gameplay discovering this bug. As a result, I did all I could to make sure it is specifically a miscommunication between these mods.

When "summoning" the anvil pet with a Minecolonies citizen nearby, the game promptly crashes.

[Crash Log](https://github.com/capnkirok/Inventory-Pets/files/6291116/crash-2021-04-10_23.06.26-server.txt)
[Game Log](https://github.com/capnkirok/Inventory-Pets/files/6291117/latest.log)

**Comment by capnkirok** [comment]
Thanks for the report. Your assessment is correct about the miscommunication. Good timing, as I plan on a release today.

**Comment by capnkirok** [comment]
Ok, found the issue. Look for the fix in 2.0.13
