### ISSUE TITLE
Black Hole Pet crashing client and server when used for the third time.

### ISSUE THREAD

**Issue by That-One-Nerd** [capnkirok/Inventory-Pets#439]
Hi there. I run a small private server for me and my friends, and we were playing with the black hole pet, but it seems to be broken. On the first 2 tries, it does absolutely nothing, but on the third use, it crashed the game. The server remained running, but anyone who tried to join would just get the message: "Internal Server Error."
 The console reads: "java.lang.NullPointerException: Ticking player." Upon trying to do the same thing on a single player world, all of MC crashes, and the user can no longer join that world. It still does not do anything on the first and second uses. Is there a new release that fixes it, or is there any way to reverse the slow-time effect (I assume that is what is causing the issue, although it might be the eating of the food, since it only happens on the third use) without joining the world?

I am using mod version 2.0.12, my client crash log is [here](https://github.com/capnkirok/Inventory-Pets/files/6297528/crash-2021-04-12_10.14.08-server.txt), and my server crash log is [this screenshot](https://user-images.githubusercontent.com/78499572/114413297-db739580-9b7b-11eb-8067-3aed0ac2a283.png)

**Comment by That-One-Nerd** [comment]
Something I just noticed is that my average tick speed is close to 1 ms. That might have something to do with it. Would you happen to know any way to raise the tick speed through a command in the console?

**Comment by capnkirok** [comment]
Nope, this is just a bug, I don't know why it hasn't been reported earlier. It had to do with the way I implemented looking at ItemTags... just for this pet. 

Look for a new release later tonight that fixes the issue.
