### ISSUE TITLE
Illuminati Pet can alter crafting recipes (1.12)

### ISSUE THREAD

**Issue by Diedntgo** [capnkirok/Inventory-Pets#440]
Hello,
Today I noticed that when I got an ingot from the Illuminati Pet and looked at the recipes, I saw that the block form only converted to one ingot instead of nine like it's supposed to. After summoning a lot more items with the pet, I saw that the recipes of items that give you more than one item changes to only give you one after getting it from the pet (Blocks only make one ingot, fences only make one fence, etc.) . I also saw that if the item has multiple recipes, it only changes one of them, and I have to relaunch the game to reset the recipes back to normal.

Examples can be found [here](https://imgur.com/a/sRmKdJJ)
**Version:** InventoryPets-1.12-2.0.12

**Comment by capnkirok** [comment]
Whaaaaaa....?

Illuminati Pet just pulls the output from crafting recipes, or it pulls random items based on their numeric ID. It does not change crafting recipes.

I'll do some testing now.

**Comment by capnkirok** [comment]
I'm not able to replicate this issue. Did you by chance remove a mod or tweak some recipes? Can you let me know what other mods you have installed?

![image](https://user-images.githubusercontent.com/9628379/114640790-d0fdec80-9c9e-11eb-9d97-16a2b6ed924f.png)

**Comment by Diedntgo** [comment]
Even if I only have inventory pets installed by itself with every setting/configuration at default, it still changes recipes with multiple items as an output to only output one item after getting it from the pet.
![2021-04-14_20 49 43](https://user-images.githubusercontent.com/64341357/114798499-77abc100-9d63-11eb-8194-c79492d15de1.png)

**Comment by capnkirok** [comment]
I will continue to try to replicate. In this situation above, the illuminati Pet gave you 1 Cobblestone at some point. And then you grabbed the other 5 somehow, and then you put it in the crafting table?

**Comment by Diedntgo** [comment]
No, I got the wall from the pet, and when I tried to craft it instead of the normal recipe (which gives you six) it changed to only give me one wall.
Decided to make a [video](https://vimeo.com/537094257) to try and help show what happens better

**Comment by capnkirok** [comment]
Thank you for the video, that really helped. After re-testing I was able to replicate (with Ender Nuggets/Ender Pearl). It doesn't occur all the time, just some of the time. Definitely bizarre.I believe this only occurs on 1.12, but will test later versions as well. 

Restart fixes the issue, as you mentioned. 

I'll see if I can figure out what's going on!

**Comment by capnkirok** [comment]
Ok! I figured this one out. It has to do with how I was handling ItemStacks. I was referring to the Recipe Output directly, which is something you should never do to an ItemStack... always make a copy first (unless you intend to alter it). Also explains the inconsistent behavior. I've fixed this in 1.12, 1.15, and 1.16 and it will be in the 2.0.14 release.
