### ISSUE TITLE
Sound bug while using the house pet (1.16.4)

### ISSUE THREAD

**Issue by ghost** [capnkirok/Inventory-Pets#442]
When i use the house pet it makes a weird buzzing sound i'll add a video to show the bug. I am not sure if my ambient sounds mod is related to this bug?

https://user-images.githubusercontent.com/77813719/114734506-90f14500-9d44-11eb-8d7b-55fa25c19128.mp4

**Comment by capnkirok** [comment]
That's the sound it makes when it's hungry

**Comment by capnkirok** [comment]
I just verified this is working as intended, so closing
