### ISSUE TITLE
Datapack issue preventing launch with latest release [1.16.5]

### ISSUE THREAD

**Issue by ModernGamingWorld** [capnkirok/Inventory-Pets#443]
As soon as I updated to the New version of Inventory pets for 1.16.5, it refused to allow me to join any single player world by throwing up a Datapack issue related to milk. I had to downgrade your mod just to be able to rejoin anyworlds

**Comment by capnkirok** [comment]
Can you share the error you received? And if you have a latest.log can you share that? I can't really do anything without context, and this is the only report of this issue so far.

**Comment by capnkirok** [comment]
@ModernGamingWorld Hey there. Following up on this one. Want to make sure you can update, because that last one was a big one.

**Comment by ModernGamingWorld** [comment]
Sorry did not see this till now, but its working now and not sure why as before it was causing due to something with milk
