### ISSUE TITLE
Feed bag clearing out when switching from Creative to Survival

### ISSUE THREAD

**Issue by anchovey707** [capnkirok/Inventory-Pets#444]
When I swap from Creative -> Survival, the feed bag becomes empty. I sometimes will put myself in creative when I need to walk away from a minute and then swap back. I was messing around trying to pinpoint the error, and it might be from opening the creative menu, or moving the feed bag around in my inventory, while in creative.

**Comment by anchovey707** [comment]
It does seem to clear the bag when opening the creative menu/inventory

**Comment by capnkirok** [comment]
Please update to the latest version (2.0.13). This was fixed in the last release.

**Comment by anchovey707** [comment]
> Please update to the latest version (2.0.13). This was fixed in the last release.

Sorry, I downloaded it about a week ago, and didn't realize and assumed I had the latest.

**Comment by capnkirok** [comment]
No worries! I think you must have just missed the update. Let me know if it's working for you!

**Comment by capnkirok** [comment]
Also, be advised that the Feed Bag currently only works in the hotbar (working on this fix now)
