### ISSUE TITLE
1.16.5 Anvil Pet Issues

### ISSUE THREAD

**Issue by Reginald-Halifrax** [capnkirok/Inventory-Pets#445]
This is unfortunately another error from the anvil pet from me, although it doesn't match #438 that closely, (or at all for that matter).

In this case I had summoned an anvil pet, and as soon as an Ice and Fire cyclops "roared," this crash occurred.

It seems to me anvil pet may need some additional work to be sure to dodge issues like these in the future if possible.

Just like last time, I built a controlled environment to test this in:

[Crash Log](https://github.com/capnkirok/Inventory-Pets/files/6345892/crash-2021-04-20_14.26.26-server.txt)
[Game Log](https://github.com/capnkirok/Inventory-Pets/files/6345895/latest.log)

Sorry for the trouble!

**Comment by capnkirok** [comment]
Similar to the previous error, though in that it's a casting issue. I can place error trapping around this so it won't happen again. I'll also look for any other 'similar' occurrences. What's odd is that this Entity is essentially a copy of the vanilla Slime Pet with some minor changes to behavior and a new model, so not sure why we are seeing compat issues. The code I'm changing is in fact, vanilla code.

**Comment by Reginald-Halifrax** [comment]
Super odd, forgive me when I say i am not super familiar with minecraft mod code, but do you think its something like a class method issue? I know it isn't entirely uncommon for some languages to change method names and/or values after inheriting them.

**Comment by capnkirok** [comment]
Ok, I have this one fixed as well. Interestingly, the vanilla code did have some error checks in place in certain areas, but not all. Looks like me changing the default targeting behavior to be more 'friendly' exposed the weak points.

The code I changed (I added the if statement to prevent casting if not the same instance): 
```
if (this.slime.getMoveHelper() instanceof AnvilPetEntity.MoveHelperController) {
    ((AnvilPetEntity.MoveHelperController)this.slime.getMoveHelper()).setDirection(this.slime.rotationYaw, 
    this.slime.canDamagePlayer());
}
```
