### ISSUE TITLE
Broken Tag

### ISSUE THREAD

**Issue by WenXin20** [capnkirok/Inventory-Pets#446]
`Minecraft v1.16.5`
`Forge v36.1.4`
`Inventory Pets v2.0.14`

I found this in my log: `Couldn't load block tag inventorypets:chests as it is missing following references: quark:chest`.
Quark is installed, but doesn't have a block called `quark:chest`

**Comment by capnkirok** [comment]
Thanks @WenXin20 ! I saw this too, looks like something might have changed with tags and/or quark. I'll investigate!

**Comment by WenXin20** [comment]
Yeah, no problem!

**Comment by capnkirok** [comment]
I've removed the reference, error should stop appearing now in next release.
