### ISSUE TITLE
No config option to modify speed boost from chicken pet

### ISSUE THREAD

**Issue by ABirdNamedSuki** [capnkirok/Inventory-Pets#447]
Exactly as the title says, I like the concept of the chicken giving speed and whatnot, but want to balance it better in my game.
In my opinion, Speed 4 is a bit too crazy for something that cheap.
There are similar pets, like the cloud pet, that do allow you to change the speed given.

Can you do the same for the chicken?

**Comment by capnkirok** [comment]
Will add to the next version. Along with the levels for several other pets.

**Comment by ABirdNamedSuki** [comment]
Thank you, that's great news!
I temporarily removed this mod from my pack for balance reasons, but this change will convince me to bring it back.
Keep up the good work!

**Comment by capnkirok** [comment]
I'm putting in a temporary update for this next release, just for the chicken.

**Comment by ABirdNamedSuki** [comment]
I appreciate that, thank you.

Can you close this issue when you believe the change has been successfully made?

**Comment by capnkirok** [comment]
The 2.0.15 version is now available on CurseForge. Look for chickenEffectLevel in the config.
