### ISSUE TITLE
[1.16.5] Quantum Pet Crashes Server

### ISSUE THREAD

**Issue by TopOnPC** [capnkirok/Inventory-Pets#448]
I spawned the pet in and it crashed the server. Is there a way to despawn it or kill it with it's entity id?
[crash-2021-05-07_20.18.47-server.txt](https://github.com/capnkirok/Inventory-Pets/files/6444809/crash-2021-05-07_20.18.47-server.txt)
[logs_latest.log](https://github.com/capnkirok/Inventory-Pets/files/6444810/logs_latest.log)

**Comment by capnkirok** [comment]
Hey TopOnPC. I reviewed the crash logs, and don't see any mention of Inventory Pets in the logs except that is listed as one of the mods present. In other words, I'll have to test more using your environment as there are no real clues here.

One way I can think of removing the 'mini-quantum pets' is to put the game into peaceful mode, which should remove them from the game.

**Comment by capnkirok** [comment]
I tested thoroughly on my server, and was unable to replicate the problem. Hopefully, the solution I provided above worked for you. I'm closing this, but will be on the lookout for any similar reports if they come up.
