### ISSUE TITLE
Mooshroom Pet not filling bowls

### ISSUE THREAD

**Issue by Adm1n04** [capnkirok/Inventory-Pets#450]
The mooshroom pet isn't filling empty bowls like its supposed to.

**Comment by capnkirok** [comment]
Which version of Inventory Pets and Minecraft are you using?

**Comment by capnkirok** [comment]
Actually, looks like 1.15 and 1.16 versions are not working.

**Comment by capnkirok** [comment]
Actually, I just tested. This is working as intended. An empty bowl will be converted to Mushroom Stew right before the pet eats. The Mooshroom will eat roughly twice per Minecraft day (so about every 10-12 minutes or so).

What is happening on your side, and please share the above information (Minecraft version, Inventory Pets version).

**Comment by Adm1n04** [comment]
Its my fault its just wayyy slower than I expected.
