### ISSUE TITLE
Portal Pet crashes the game

### ISSUE THREAD

**Issue by Fishwicks** [capnkirok/Inventory-Pets#451]
Any idea why the Nether Portal Pet (I found in a chest in the overworld) crashes the game when used?

**Comment by Fishwicks** [comment]
It teleports me, but it crashes the game and I have to reopen the world just to see where I am and play again

**Comment by capnkirok** [comment]
I need your crash log and the version of Minecraft and Inventory Pets you are using, then I could tell you.

**Comment by Fishwicks** [comment]
I'm on latest version for both inventory pets and Minecraft (not snapshots), however whenever the crash happens there is no log. It might just be my own computer's shortcomings.

**Comment by capnkirok** [comment]
Mmmm... there's always a log. Go into your Minecraft folder, then find the logs folder and look for a file called 'latest.log.' You can attach that here, it will show me what was happening right at the moment of the crash.

**Comment by Fishwicks** [comment]
The last log I have is from around 4 hours ago, and it isn't even when I
had the mod.
