### ISSUE TITLE
Portal Pet Only Going to Nether Roof

### ISSUE THREAD

**Issue by Adm1n04** [capnkirok/Inventory-Pets#452]
Every single time I use my portal pet I teleport the the nether roof. No matter my y level at all. When I teleport back I go to the regular overworld and that part is working fine.

**Comment by capnkirok** [comment]
Sometimes this happens.The Portal pet can't find a good spot and leaves you above the Nether. This part is a bug, which I can fix, but to fix your current situation:

Unfortunately, the Portal Pet remembers the last place you were in the Nether, so it transfers it back to where you came from.

A few ways to solve this if you are stuck:
- Create a Nether Portal the normal way and transfer to the Nether. Use the Nether Portal to return and it will be fixed and remember your new spot
- Make/acquire a new Nether Portal pet and use that
- If you can, you can also go into creative mode and dig through the Nether roof into an area you can walk around. From there, go to the Overworld using the pet and it will update your last spot in Nether.

**Comment by capnkirok** [comment]
Ok, I've updated the pet so it won't ever put you above 120 height in the nether, so this shouldn't happen in the future.
