### ISSUE TITLE
Sheep pet not eating from anywhere

### ISSUE THREAD

**Issue by Dostic** [capnkirok/Inventory-Pets#453]
Hello I havent used mods in a while and I saw that this was updated to 1.16.5 and instantly installed it.
After using it a while and figuring everything out I made a sheep pet to get wool and it seems like the sheep pet is unable to produce any? I tried putting wheat into a feed bag, leaving that feed bag in my hotbar, leaving it open, leaving wheat in my inventory, holding the sheep pet in my off-hand, holding the feedbag/wheat and the sheep pet at the same time to no success.
If theres any other info required Im happy to provide it.
The mod version I use is "InventoryPets-1.16-2.0.14"

**Comment by Dostic** [comment]
After trying more of the pets it seems that no pet gives me any items, all the effects work.

**Comment by capnkirok** [comment]
Everything is working as intended. Two things:
- Pets eat roughly twice per Minecraft day, roughly 7.5 real world minutes
- As of 2.0, there's a new feature where you can toggle pet giving. The default is off. To toggle it on, hit Sneak + Right Click. This info is on the pet tooltip.

**Comment by Dostic** [comment]
I have been playing with the sheep pet in my inventory since I submitted this ticket with the pet giving set to on and I have not received any wool. Wheat has been sitting in the feedbag and in my inventory.

**Comment by Dostic** [comment]
Okay after all this time it seems that either of the items needs to sit in the hotbar but I dont know which one or if its even both, otherwise it wont work for me

**Comment by capnkirok** [comment]
I believe you. However, there could be many reasons this is happening. It would be a major issue if it was happening for everyone, but yours is the only report.

- Are you on a server?
- What other mods do you have installed?
- Have you tried deleting your config? You mentioned you used to play this mod... perhaps there's some old setting you have in there you forgot about from a previous version?

**Comment by Dostic** [comment]
Ah that was almost time perfect, I got a single piece of wool after letting both sit in my hotbar, Im gonna test around to see which one needs to be in it for it to work.

**Comment by capnkirok** [comment]
Yes, Inventory Pets must be in the hotbar for it to work. The food can be anywhere in the inventory, including the Feed Bag.

**Comment by Dostic** [comment]
My apologies I was not aware of that, thank you for quickly helping me and making such a great mod!
