### ISSUE TITLE
Feed Bag only works occasionally

### ISSUE THREAD

**Issue by Clebb1** [capnkirok/Inventory-Pets#454]
So put my iron nuggets in the feed bag for my anvil pet but it wouldn't eat them. After some time i tried it again at this time it worked and now doesn't work again and i can't figure out why. Yes i am sure that i have the right food for my pets bc it works when i have the food in my inventory and not the bag and i also have the bag in the standard vanilla inventory and not any other weird stuff.

**Comment by capnkirok** [comment]
What version of Minecraft and Inventory Pets are you using?

**Comment by Clebb1** [comment]
I'm running Minecraft 1.16.5 and inventorypets-1.16.5-2.0.14

**Comment by deemah350** [comment]
I'm having the same issue, i was running inventorypets on 1.12.2 and it was working flawlessly, upgraded my whole game and all of the mods to 1.16.5, installed the inventorypets, the pets themselves work as they should but the feed bag does not work at all. none of the pets take anything out of the feed bag, i have to keep everything in my regular inventory

**Comment by Clebb1** [comment]
> I'm having the same issue, i was running inventorypets on 1.12.2 and it was working flawlessly, upgraded my whole game and all of the mods to 1.16.5, installed the inventorypets, the pets themselves work as they should but the feed bag does not work at all. none of the pets take anything out of the feed bag, i have to keep everything in my regular inventory

I got it tow work! It's a bit weird but it's working. So i got all my pets to 0 durability, then i dragged them into my inventory (not my hotbar), then i got all of the food out of my feed bag (which was not working at the moment), after that i got all my pets along with my feed bag back into my hotbar and after that i put all the food into my feed bag, then put my feed bag im my normal inventory and voila it works, i hope it's working for you aswell :)

**Comment by ecksfiftyone** [comment]
I can confirm this issue - 1.16.5 - 2.0.14
Feed bag does not work. 
If I open the feedbag manually, the pets eat.

**Comment by capnkirok** [comment]
Hey guys -

Just realized I fixed this issue in development (#441), but never pushed it live. Look for the 2.0.15 version, which I aim to push to CurseForge on Sunday, June 6.

PC
