### ISSUE TITLE
Off Setting for some pets?

### ISSUE THREAD

**Issue by ZoologyGal** [capnkirok/Inventory-Pets#458]
Hello,
I am new to using this modpack on my own and I'm a bit confused on the [off] description on some pets, the spider for example. It says that the spider "Gives You String [off]" but does this mean the function is off or it works in the offhand? If it is off, how do I turn it on? I haven't edited the mod or anything since downloading it as I'm not sure how to do that haha.. I've searched every resource and forum I could to find an answer before posting this. Thanks in advance.

I am using minecraft version 1.16.5, mod version InventoryPets-1.16-2.0.14 (latest release), and have attached an image.
![spider form](https://user-images.githubusercontent.com/85260886/120560754-4baad480-c3d1-11eb-8b5a-6cfd5e65a925.jpg)

**Comment by Coraline77447** [comment]
What the [Off] means for some of the inventory pets is for their second function.
How to turn their second function on/off is to sneak + right click  or in this case shift + right click while you're holding the pet in your main hand, may work in the off-hand but I've never tried that yet.
Btw it says "Give Items Toggle [Sneak + Right Click] underneath "Gives You String [Off]" which tells you how to turn on/off their second function. 
After you sneak + right click it'll say "Gives You String [On]".
You're welcome in advance.

**Comment by capnkirok** [comment]
Thanks @Coraline77447 !

I put this in the 1.16 version at a request. It allows you to turn on/off the giving of items.
