### ISSUE TITLE
how do you get nuggets?

### ISSUE THREAD

**Issue by MIcrowavemmm** [capnkirok/Inventory-Pets#459]
I have tried crafting them, smelting an ingot im trying to get an anvil pet but normal iron nuggets don't work (why) the feed bag did nothing and i cant find anything on how to get it. please help.

**Comment by capnkirok** [comment]
I recommend you install JEI (mod) to get all the recipes. For iron nuggets, it's just the vanilla recipe.. so just put the Iron Ingot into a crafting table to get your nuggets. Same rule for Gold, Emerald, Diamond, etc. The only exception is Lapis Nuggets, which requires 1 Lapis Lazuli + 1 block of dirt.
