### ISSUE TITLE
1.16.5 Disabling (some) pets in config seems to do nothing 2.0.15

### ISSUE THREAD

**Issue by YOUR-WORST-TACO** [capnkirok/Inventory-Pets#460]
Forge version: 36.1.31

Disabling inventory pet on server seems to have no effect on client from being able to use pets
I have tested:
- creepers
- saddles
- flying saddles

[See config here](https://pastebin.com/Lw18T35u)

If I copy the config to my client it "sort of" works but even then this should be enforced by the server regardless of client configs right?

I desperately need this for my server as several of these pets are very broken for our uses.

Thank you.

**Comment by capnkirok** [comment]
Yes, this should be enforced by server regardless of client. I'll run some tests using your examples. It could be that these pets are just not coded to disable properly.

Just checking, but you did re-start your server, correct?

**Comment by YOUR-WORST-TACO** [comment]
I restarted my server many many times and changed the config many times, when I get back on Monday I can play around more to see if a mod is conflicting, but looking at the debug log gave me signs of possible conflict.

**Comment by capnkirok** [comment]
Can confirm that the Creeper Pet had a bug which prevented the disable functionality from working. Checking other pets now.

**Comment by capnkirok** [comment]
Different story with Saddle and Flying Saddle. Mounting a mob caused a client/server desync. It allowed you to mount the mob, but not control it. I've been able to fix these and the Creeper in my development server. Going to do a full sweep of all pets before I make a release.

Another bug is that the pet tooltip only reflects what's on the Client config on 1.16.x, and not what's on the Server.

**Comment by capnkirok** [comment]
Ok, did a full sweep. This is the result of the new config system. I had only done a cursory test. Besides the Creeper and the Saddles, the following pets were affected and do not properly disable features properly:
- Spider (climb, hang on wall)
- Sponge (all functionality)
- Magma (walk on lava)
- Biome (all functionality)
- Jukebox (all functionality)
- Furnace (smelting)
- Cloud (fly)
- Torch (place and set fire)

These will be fixed in the next release.

**Comment by Umbrial** [comment]
I would like to add that the silverfish isn't being disabled by the config, granted that's in single player. This seemed a better place to note it than making a new thread since it's for the same version ^-^'

**Comment by capnkirok** [comment]
Thanks @Umbrial, fixed that one too for 1.12 - 1.19. See the 2.0.17 release, out soon.
