### ISSUE TITLE
Housepet

### ISSUE THREAD

**Issue by boburnhamlookingass** [capnkirok/Inventory-Pets#463]
Is there a way to disble housepet for 1.12.2 my friend accidently set his spawn with house pet at spawn and our base is very far away is there a way to disable it?(Edit btw i dont have access to config/serverfiles since the owner is mostly offline)

**Comment by capnkirok** [comment]
Well, you can reset the House Pet spawn point at at any time with a shift right-click. Is that what you mean?

**Comment by boburnhamlookingass** [comment]
> Well, you can reset the House Pet spawn point at at any time with a shift right-click. Is that what you mean?

no i mean like disable it since my friend is very far away(Make it so that when he dies he doesnt spawn back where he set the house pet since the house pet is overiding his bed

**Comment by capnkirok** [comment]
Once your friend sleeps in his bed, that should reset the spawn point. Setting the spawn point with the house pet does the same thing as sleeping in a bed (using the same code even). This is not a special 'House Pet' spawn point, but your actual spawn point set by Minecraft. So, you can't disable it, you can only reset it.
