### ISSUE TITLE
Mod Capability issue with Mob-Catcher and Inventory-Pets 

### ISSUE THREAD

**Issue by IchigoGames** [capnkirok/Inventory-Pets#465]
Minecraft 1.16.5
Forge 36.1.32
inventorypets-1.16.5-2.0.15
mobcatcher-3.2

this is a Multiplayer only issue i found in my new pack after a lot of testing i found the issue only happens when Mob-Catcher and Inventory-Pets  are installed 

how to reproduce issue: 1st Install both mods 2nd load up a multplayer game with them and join it 3rd after loading into multplayer world get your self a mob capture device and grab any mob near you the mob type does not mater 4th jump into water
and get disconnected from server.

the only way to help a player after this happens to them is to /tp them out of water or go into there inv and remove the mob capture device 

Logs from server https://www.dropbox.com/s/usv3gwxcr7frgxg/logs%20from%20server.zip?dl=0 there in a zip
Logs from clint https://www.dropbox.com/s/wnag8cpgtn317lg/logs%20from%20clint.zip?dl=0 also in zip 

Note as i dont know who needs to fix what ill report this issue to both mods

**Comment by IchigoGames** [comment]
https://github.com/Tfarcenim/Mob-Catcher/issues/9

**Comment by capnkirok** [comment]
Looks like this was closed by Tfarcenim
