### ISSUE TITLE
Nuggets missing tags

### ISSUE THREAD

**Issue by WenXin20** [capnkirok/Inventory-Pets#466]
`Minecraft v1.16.5`
`Forge v36.1.32`
`Inventory Pets v2.0.15`

Nuggets are missing the item tag `forge:nuggets/type` for mod recipe compatibility. For example, iron nuggets use `forge:nuggets/iron`.

**Comment by capnkirok** [comment]
Yes, will include in next release.

**Comment by Boolyman** [comment]
Is this still not working?  Many mods add Ender Nuggets, and this is a huge inconvenience having to set up ways for the player to get the exact type of nugget you require.
