### ISSUE TITLE
Suggestion: Add a way to blacklist whole mods from the illuminati pet

### ISSUE THREAD

**Issue by avianavatar** [capnkirok/Inventory-Pets#468]
I think it would be good if we could blacklist whole mods in the config from having their items chosen by the illuminati pet not just individual items.
For example the block armour mod adds a ton of different types of armour depending on what mods you have installed so you are much more likely to get items from that mod every time you use the illuminati pet. This could also allow more options for modpack creators if they wanted to restrict what mods you are allowed to get items from for balance reasons

**Comment by Blackout03** [comment]
***I think*** this is already possible by putting an asterisks after the mod id
For example ***I think*** "minecraft:*" would make it so no items with vanilla can be obtained. (Don't quote me on this as currently can not test this)

**Comment by capnkirok** [comment]
Blackout03 is correct. However, you don't need the asterisk. You can open the default blacklist now and see an example for "bibliocraft:"
