### ISSUE TITLE
Pingot Pet Stops Working After One Use of Auto-Extract While "Pets Must Eat"=false

### ISSUE THREAD

**Issue by Willasaurusrrex** [capnkirok/Inventory-Pets#47]
I have an issue where once I use the Auto Extract feature for the Pingot pet while the command "Pets Must Eat"=false, the Pingot pet doesn't work at all anymore. It's still in my inventory, however, when I try to use it, it fails to work.
I have the latest version of the mod for Inventory Pets as well.

**Comment by capnkirok** [comment]
Yes, this is a bug. Thanks for reporting. Will fix in the next update.

**Comment by Willasaurusrrex** [comment]
Thank you!~ :D

**Comment by capnkirok** [comment]
Fixed in development. Fix will be in 1.4.0 update.
