### ISSUE TITLE
Solstice Leggings

### ISSUE THREAD

**Issue by Tsunomaki** [capnkirok/Inventory-Pets#470]
I adjusted my computer time to December 23 to try to get Solstice Leggings
but it always give me Solstice Boots
i dont know how to get this.
My game version is 1.16.5

English is not my native language,so i need to use google to translation my words
If I have a grammatical error that you can’t understand,i am sorry about this.

**Comment by capnkirok** [comment]
Agh. This is a bug. I have Boots two days in a row. I'll have to fix.
