### ISSUE TITLE
How can I reable pets that are disabled

### ISSUE THREAD

**Issue by NexIsThebEst** [capnkirok/Inventory-Pets#474]
Hello I'm playing a minecraft mod pack called Roguelike Adventures and Dungeons (RAD) and it has some pets disable but by god I worked hard for those pets and just want to use them to help me get the edge I guess in a game where all my stuff  breaks. 
I just have the Anvil Pet and Loot pet but I want to get the others just need to find a way to reable it. pls help.

my minecraft version is: 1.12.2 

pets disable are 
-Slime pet
-Cloud pet
-Loot pet
-Grave Pet
-Flying Saddle Pet
-Enchanting Table pet
-Double chest pet
-Chest pet
-Anvil Pet

**Comment by NexIsThebEst** [comment]
Version I'm on is 1.12.2

**Comment by NexIsThebEst** [comment]
minecraft

**Comment by capnkirok** [comment]
You can just go into the config file and re-enable them. There's a config gui on 1.12, so pretty straightforward.

**Comment by NexIsThebEst** [comment]
thank you
