### ISSUE TITLE
[1.12.2] Juggernaut Pet's invulnerability cooldown is shared between all players.

### ISSUE THREAD

**Issue by SonicX8000** [capnkirok/Inventory-Pets#476]
Minecraft: 1.12.2
Forge: 14.23.5.2855

inventorypets-1.12-2.0.15

-----

I dunno if you still do updates for 1.12.2 but apparently the Juggernaut Pet's invulnerability cooldown is shared between all players. If one player actives invulnerability the rest of the players will be unable to active theirs. This was first noticed in a server that me & a few friends play on with 300+ mods.

I'll try to see if I could try testing this in a server with only inventory pets to see if the timer is still shared although I dunno when I'll be able to do that.

**Comment by capnkirok** [comment]
Yes, that's definitely not intended. Will take a look.

**Comment by capnkirok** [comment]
This was fixed in later versions (1.16.5+)
