### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by xxlio109** [capnkirok/Inventory-Pets#478]
https://github.com/TeamTwilight/twilightforest/issues/1396

**Comment by capnkirok** [comment]
Yes, this looks like an InvPets problem. Looking into it now.

**Comment by capnkirok** [comment]
@xxlio109 are you still seeing this issue? And do you have crash report still?

**Comment by capnkirok** [comment]
@xxlio109 closing this as I didn't hear back. If it happens again, shoot me the crash report and I'll reopen.
