### ISSUE TITLE
Cloud Pet OP ability

### ISSUE THREAD

**Issue by ElLiox** [capnkirok/Inventory-Pets#479]
First of all, sorry for my bad English

The cloud pet allows you to fly infinitely at the cost of nothing
I would not like to disable it in my world because i think his ability to throw lightning strikes its well made and balanced (3 strikes per nether quartz)
But his ability to fly should last a limited time. I personally think 1 minute flying per nether quartz is balanced
it's just a suggestion

**Comment by capnkirok** [comment]
Well, it does consume Quartz (over time... 2x per minecraft day), so not entirely Free.
