### ISSUE TITLE
mooshroom pet not working on crops

### ISSUE THREAD

**Issue by KattleyaL** [capnkirok/Inventory-Pets#480]
when i right click de crops doesnt grow but the trees and grass does version is inventorypets-1.16.5-2.0.15

**Comment by capnkirok** [comment]
I tested this and it's working for me. Any other info you can share? Are you on a server, what crops are you trying this on? What modpack are you using, if any?

**Comment by Anthony-T-M** [comment]
I'd like to add on to this as I just encountered this issue myself. I moved from the 1.12.2 version of InventoryPets to 1.16.5 and the Mooshroom Pet is specifically not working on any crops. It works fine when I use it on grass or grass blocks, but crops produce no reaction. 

I am also using inventorypets-1.16.5-2.0.15. I tried this on both a server and on a singleplayer world, and I attempted to use it on Mystical World's Aubergine Seeds, the vanilla Wheat Seeds and Beetroot Seeds, and Pam's Harvestcraft 2's Blackberry Seeds. I'm using a custom modpack I made myself running on forge-36.2.29. The contents of which are here: https://pastebin.com/XnZkknMg

Thank you.

**Comment by capnkirok** [comment]
Very late reply. I see no issues in a standalone environment on client or server on any of these versions, which leads me to believe that it might be a conflict in the modpack. I'll try to test with these other mods installed to see if there's a conflict.

**Comment by capnkirok** [comment]
Can confirm this is a conflict with Pam's Harvestcraft, which seems to be hijacking the bonemeal event.

**Comment by Anthony-T-M** [comment]
> Can confirm this is a conflict with Pam's Harvestcraft, which seems to be hijacking the bonemeal event.

Should I wait for an update to Inventory Pets or should I try a different version of Pam's?

**Comment by capnkirok** [comment]
I can work around Pam's implementation. I'll update in 1.18 and going forward as well.
