### ISSUE TITLE
Quantum Crystal Monster pet, lagging out game when ability is used

### ISSUE THREAD

**Issue by GlarkThe** [capnkirok/Inventory-Pets#483]
I found the quantum crystal pet in a cloud dungeon/chest and used the pet, but shortly after my world lagged out, and now anytime I log back into said world I am promptly kicked out before I can even move or see the world.

*Using the latest version for 1.7.10
*no crash log available for some reason

If it possibly helps, I'm using the crazy craft 3.0 modpack https://voidswrath.com/modpacks/crazy-craft-3-0/

**Comment by capnkirok** [comment]
Not supporting this version any more. Never did figure out what the conflict was on that one. Great modpack though.
