### ISSUE TITLE
Loot Pets don't stack in 1.12 but do in 1.16

### ISSUE THREAD

**Issue by hagfelsh** [capnkirok/Inventory-Pets#485]
In #10 , @capnkirok mentioned that you didn't intend for them to stack, but there would be a config parameter to enable this if desired. I haven't figured out where that is. 

or... how can loot pets be made to stack in the 1.12 release?  The folks on our server don't have much time to play so the grind reduction that stacking loot pets in 1.16 made possible sort of gave us a survival-lite mode.   It was really great.

**Comment by capnkirok** [comment]
Pets shouldn't stack.. unless a different type of Pet. It was a bug fix, sorry to say.
