### ISSUE TITLE
Biome pet has very odd selection of biomes (1.16.5)

### ISSUE THREAD

**Issue by mrbuilder1961** [capnkirok/Inventory-Pets#488]
### Problem:
When you use the biome pet, it only gives a very small amount of biomes to choose from, and depending on the biome you're in (or possibly your position idk) it will change the options. At first I thought you had to visit the biomes for them to show up, but then after some time they were no longer on the list.
Also, the biomes shown seem to be Minecraft-only. Not sure if that's intentional, but it is what it is.

Now this next part should probably be a bug report of it's own but might as well try to kill 2 birds with one stone. When you Shift+Right-Click to select the biome, there is a varying amount of lag that (in my experience) can be anywhere from about 2 seconds to almost 6. My guess is that with all of the biomes from other mods (namely BOP), the searching method you use is inefficient or there is something completely unrelated going on that is causing this. This lag isn't crazy important to me right now due to the bug mentioned above, but still important imho.
### Expectation:
Either there are only a few biomes to pick from and you have to visit them to be able to search, or some other type of fancy mechanism. Basically, anything that's consistent. And for the 2nd bug, no-very minimal lag.

### Attachments:
[This](https://vimeo.com/676688639) video I recorded of both bugs in-action

### Mods:
I have about 100 mods, but for this bug specifically I only have a few that would probably be affecting this, but modding is weird so here ya go (the `.disabled` mods are, you guessed it, disabled!):

![tmp](https://user-images.githubusercontent.com/66807297/153735660-0e2086f5-0434-4747-94ff-2361774ba25d.png)

**Comment by capnkirok** [comment]
Apologies. I haven't been checking the issue log much recently. Thank you so much for the detailed information.

The problem with the Biome Pet is that it's only checking on the client side for the biomes, and is therefore limited to what is currently loaded in memory. I have yet to figure out how to identify the biomes without the chunks being loaded. 

Also, you are right, that first search is really inefficient. I'm checking hundreds of chunks, but of course, that means nothing on the client side if the chunks are not currently loaded. So, wasted cycles for sure.

Will continue to work on this one.

**Comment by mrbuilder1961** [comment]
If I were to give my 2 cents, I would try:
- List of biomes: Pull from a registry of loaded biomes, and maybe filter out biomes that can't generate in the current dimension
- Searching for the biomes: Search on the server instead (which would probably be more accurate but less efficient), ignore a small radius of chunks around the player, or potentially even use the world seed to get a biome map and search that

An important disclaimer I should mention is I haven't attempted any of these suggestions before, so I'm not sure how many of these are feasible or are even possible, but I thought on the off-chance that these could be potentially helpful I would chip in. Good luck and take your time!

**Comment by capnkirok** [comment]
I have this fixed in 1.18.2, trying to see if there's a way to backport.

**Comment by mrbuilder1961** [comment]
if it's feasible, i would honestly prefer the fix for 1.19, but idk if you even have a 1.19 release planned. either way it isn't really a problem for me anymore so do what you want!

**Comment by capnkirok** [comment]
It's already included in 1.19, should be released soon! Going to close this one.
