### ISSUE TITLE
Squid Pet too fast

### ISSUE THREAD

**Issue by iiBluKitty** [capnkirok/Inventory-Pets#489]
1.16.5 Forge 36.2.28
Inventory Pets 2.0.15

The squid pet launches you through oceans when swimming (very very fast, not in a good way)

maybe add a config or slow it down a bit? It's very hard to control

**Comment by capnkirok** [comment]
There is a config option to remove the speed boost. Has been there all along. There is an additional bug that gives an extra speed boost when flying + sprinting, which I need to fix, but you can always flip the config.
