### ISSUE TITLE
Mooshroom Pet not working with Pam's (1.16.5)

### ISSUE THREAD

**Issue by Umbrial** [capnkirok/Inventory-Pets#490]
Mooshroom pet doesn't bone meal crops with Pam's HarvestCraft installed, including vanilla crops. It's probably not a big deal, just felt it worth noting.

**Comment by capnkirok** [comment]
Well, it'd be nice if that worked. I'll take a look. Generally speaking, for this to work the plant/crop needs to extend Minecraft's default BlockCrop or tag.

**Comment by capnkirok** [comment]
Ok, found the issue and have a workaround.
