### ISSUE TITLE
cloud pet still obtainable even if dissabeld in config 1.16.5

### ISSUE THREAD

**Issue by GreenForzeGaming** [capnkirok/Inventory-Pets#495]
cloud pet still available via illuminati pet, even though its been disabeld, also pls add a flying off in config. want too use the thunder alone

**Comment by capnkirok** [comment]
- You can add the Cloud Pet to the illuminati_blacklist.json file to prevent it dropping.
- Disabled allows users to collect pets, but not use their abilities. 

Could add a 'flying off' config, but that would be an enhancement.

**Comment by GreenForzeGaming** [comment]
Ah i see well. The issue stands with the cloud pet being disabled. I can still fly and use it. Id love it for the collectable purpose but even disabled it works. Also flying off would be so so cool. Trying to balance a mod pack as much as possible and who has not wanted to spam things with thunder 🤣. Also thx for quick replys! Love the mod!

________________________________

**Comment by GreenForzeGaming** [comment]
well another issue accured, the meta pet still spawns the cloud pet so no matter what i do people can fly with the cloud pet

**Comment by capnkirok** [comment]
Ok, I've added a disableCloudFly config in the next update, version 2.0.20.
