### ISSUE TITLE
[1.12.2] None of the pets I tried work while in inventory

### ISSUE THREAD

**Issue by Semi0ne** [capnkirok/Inventory-Pets#496]
I didn't try every pet, but the many pets I did try do not work while in my inventory. They only work while in the hotbar. I can try them all if you like.

Inventory Pets: 2.0.15
Modpack: Roguelike Adventures and Dungeons (R.A.D. - 1.49 - Revamp)
Minecraft: 1.12.2
Forge: 14.23.5.2859

**Comment by capnkirok** [comment]
They only work in the hotbar and they are well fed. You could always look at the mod home page...
