### ISSUE TITLE
Achievements not registering

### ISSUE THREAD

**Issue by VinceKezel** [capnkirok/Inventory-Pets#503]
I'm not seeing some of the achievements that should have been marked completed. 
For example:

- Pacifist (Acquire all the peaceful pets)
- First Pet (acquire your first pet)
- Pet Beginner (Acquire five pets)

![Capture_inventory_pets_fault](https://user-images.githubusercontent.com/49579475/175424041-9f9e33db-9acf-43d8-a935-9ba2f6118890.JPG)

**Comment by capnkirok** [comment]
What version of Inventory Pets is this? 1.16.5?

**Comment by VinceKezel** [comment]
> What version of Inventory Pets is this? 1.16.5?

2.0.15 on 1.16.5

**Comment by capnkirok** [comment]
I finally tested this and was not able to reproduce on server or client. I can only imagine you had either a mod conflict - were you playing with any other mods installed? Or somehow, the internal server crashed and it wasn't connecting. I'll leave this open for a few more days, but will close unless I hear back.
