### ISSUE TITLE
black listing items in inveotry pet config illuminati_blacklist.json file doesnt work

### ISSUE THREAD

**Issue by Timmy123321** [capnkirok/Inventory-Pets#504]
i have mods i want black listed set up like  "mystical_agriculture:": 0 yet i still get things from each mod ive blacklisted

**Comment by capnkirok** [comment]
Sadly, I never responded to this because I didn't think it was a bug because the modid is "mysticalagriculture" with no underscore. But there is also a bug on the 1.16.5 version. Fixed in the 2.0.20 version, out soon.
