### ISSUE TITLE
Inventory loading error?

### ISSUE THREAD

**Issue by Choochfactor** [capnkirok/Inventory-Pets#506]
Just a simple error. I'm posting it here because it's only happening with the ender chest pet and only around a hopper/anvil/enchantment table/grindstone?
Pastebin crash log - https://pastebin.com/cU3vBvVb
I haven't tried recreating the crash elsewhere yet It's only been in this specific spot so far.

**Comment by capnkirok** [comment]
Took a break, and now back. But this crash log has expired. Can you repost?

**Comment by capnkirok** [comment]
Haven't heard back, so closing. Please re-post if it happens again.
