### ISSUE TITLE
Squid Pet swim boost is too OP

### ISSUE THREAD

**Issue by ElLiox** [capnkirok/Inventory-Pets#510]
When you use the Squid pet you get the Swim boost effect, but when you sprint underwater (swimming) you get an absurdly powerful speed effect.
This happens both in the new versions of the mod [InventoryPets-1.16-2.0.15]
and in version 1.12.2 [InventoryPets-1.12-2.0.15]
with the AquaAcrobatics mod (any version) which brings the swimming mechanics of the new MC versions
https://github.com/Fuzss/aquaacrobatics/issues/102

**Comment by capnkirok** [comment]
Fixed this in 1.18, but need to retro fix in 1.16 & 1.12.
