### ISSUE TITLE
[Crash]: Spider pet causing crash "java.lang.NullPointerException: Ticking player"

### ISSUE THREAD

**Issue by kalutro** [capnkirok/Inventory-Pets#511]
Using the modpack Rustic Waters II and recently got the Spider pet.  Have crashed twice just standing in my base, not even actively using the pet, though it is in my hotbar.

[crash-2022-09-04_10.30.45-server.zip](https://github.com/capnkirok/Inventory-Pets/files/9485212/crash-2022-09-04_10.30.45-server.zip)

**Comment by capnkirok** [comment]
My god, this was confusing. I finally figured it out, you were playing in hardcore pet food mode, and my hardcore food OreDictionary item tag had a typo.

Fixed in next release.
