### ISSUE TITLE
1.12.2 config 

### ISSUE THREAD

**Issue by Surr3alD3sign** [capnkirok/Inventory-Pets#513]
Im playing 1.12.2 and cannot enable the crafting recipes for any of the pets that by default have crafting disabled, i want to be able to craft them bc hunting down hundreds of these dungeons is annoying and id rather not. (update, the config does say that the recipes are enabled but they still dont work) (update 2, idk what i did but it works now, i changed nothing but it works now and i no longer need help)

**Comment by capnkirok** [comment]
Thanks for following up, glad it worked out.
