### ISSUE TITLE
Dog whines constantly and cant be deleted

### ISSUE THREAD

**Issue by 814ckc4t** [capnkirok/Inventory-Pets#514]
I've literally had to abandon this dog in a cave somewhere because I just can't deal with its constant whining. I can't delete it either, its heartbreaking. Please let us delete pets. And please fix the issue with the pet growing bigger with each level up. My dog is only level 4 and is as tall as the villagers

**Comment by capnkirok** [comment]
Is this the Wolf Pet? That is heartbreaking, I agree. Can you tell me which version of Minecraft and Inventory pets you are using?

**Comment by capnkirok** [comment]
Didn't hear back, so closing this one.
