### ISSUE TITLE
Cheetah does not eat anything when you change 

### ISSUE THREAD

**Issue by mihlek1** [capnkirok/Inventory-Pets#515]
On config
petsEatWholeItems: true

Also, when you change this config on the server side, the tooltips does not update to clients (forge 1.16.5, online-mode: false), so the food pets eat is still shown as the old versions (e.g.: Iron golem pet still shows iron ingot, even though it consumes iron blocks)

**Comment by capnkirok** [comment]
Yeah, I saw this on 1.18, but I'll go back and fix 1.16.5 now.

**Comment by capnkirok** [comment]
Will be fixed in next release. It eats raw fish for the record.
