### ISSUE TITLE
[1.18.2] Pets not animated in JEI or hotbar, mod conflict

### ISSUE THREAD

**Issue by PhweeDev** [capnkirok/Inventory-Pets#519]
In the tweet, I mentioned performance issues. I believe I'm wrong on that as world load wasn't longer and frame rates are just stuttery for a bit, and then get "normal" after a while.

However, I mentioned pets not being animated. This I found was a conflict with Rubidium when a specific argument is set in its' config.  When rubidium has the entry "mixin.features.item=false" set to false, the pets will not be animated. Is there any way for you to integrate an override so the pets will be animated no matter what? Here's the config and latest log if it's of any use.

Log: https://paste.gg/p/anonymous/adb37e8f7bc442b0a42cc6dd50b78308

Config: https://paste.gg/p/anonymous/f2bae6c08bb24e6a87d192042f1b321e

**Comment by capnkirok** [comment]
I'll take a look and see what I can do, I've just started using mixins, so a bit of a rookie here (but that's never stopped me).

On the performance side, I know you mentioned things have stabilized. But I think there are some optimizations I can do, especially on the Player Events side.

Stay tuned on both,

**Comment by PhweeDev** [comment]
Also, a few things I wanted to note.

-The "update checker" for 1.18 seems kind of off. Perhaps look into that?
-Your "copyright" on the CurseForge page says 2015-2021. Will you be making it open source? Or are you going to update your copyright?
-Have you considered making a Discord server of some sort to keep people updated a bit easier?

**Comment by Monstrcow** [comment]
Btw, rubidium is buggy af
