### ISSUE TITLE
Grave pet deletes Baubles upon Death.

### ISSUE THREAD

**Issue by plazia** [capnkirok/Inventory-Pets#52]
Awesome pet and I love how it restores inventory perfectly upon death. It does however seem to delete your Baubles items.

**Comment by capnkirok** [comment]
Ahhh, yeah, it doesn't look at baubles. I'll take a look at the API.

**Comment by capnkirok** [comment]
Ok, finally found an compat example for Baubles and checked out the API. No timing yet, but will work on it.

**Comment by capnkirok** [comment]
Finally. Fixed in Dev. Will roll out next update.

**Comment by capnkirok** [comment]
No Baubles API for 1.8, and not out yet for 1.10. Will update 1.10 when the API is released.
