### ISSUE TITLE
Cooldown To death negation pets

### ISSUE THREAD

**Issue by DoctorMage** [capnkirok/Inventory-Pets#520]
Enderman pet/ Slime pet

Can both surivive a /kill @e looping command block
Cooldown would mean these abillities are less abuseable

there are other situations were the death negation is more abuseable 
command block loop is just example

**Comment by capnkirok** [comment]
I think a default cooldown is warranted on the Enderman, but not default on the Slime. The Slime is a legendary, very difficult to acquire and requires steep food (Golden Apple). 

But, I can add configs for both (like I have for Illuminati).

**Comment by capnkirok** [comment]
Ok, I have a solution for this, I think it works well.

Enderman can only save you if you have more than 1/2 heart. If you are saved by Enderman Pet, you are then set to 1/2 heart and your Food level is set to no more than 5 hearts. So, you'll need to heal before the Pet will work again.
