### ISSUE TITLE
Sated Chest pets can be stored in themselves deleting it and it's contents.  

### ISSUE THREAD

**Issue by DaCubeKitten** [capnkirok/Inventory-Pets#522]
I suggest a system similar to how current shulker boxes work.

**Comment by capnkirok** [comment]
I'm not sure how you are able to store Chest Pets inside Chest Pets. There is code specifically in place to prevent this from happening: Chest Pet, Double Chest Pet, and Feed Bags. However, I did see the exceptions didn't include the new Sated Chest Pets. Is that what you are referring to? I'm putting that change in now.

**Comment by DaCubeKitten** [comment]
Yes it was, I apologize for not specifying. Thank you.

**Comment by capnkirok** [comment]
No worries. Super glad that was it and thanks for reporting! This is fixed in dev. Hope to push an update in the next few days!
