### ISSUE TITLE
question: is someone working on 1.19.2 ? :)

### ISSUE THREAD

**Issue by Jannik44** [capnkirok/Inventory-Pets#523]
a few of the more famous mods mods recieved 1.19.2 updates and im currently creating a modpack, should i skip Inventorypets or will a 1.19.2 Version be realeased soon?

**Comment by capnkirok** [comment]
You should rejoice bc 1.19.2 should be released this week.

**Comment by Jannik44** [comment]
that's great news, thanks 👍

**Comment by capnkirok** [comment]
If you are still watching this thread, had a little trouble with WorldGen, but just got it going today. Should be good to go sometime this weekend. Please note, I'm working on 1.19.3 version, might even upgrade to 1.19.4.

**Comment by sharkweekthings** [comment]
Ohh nooo, does this mean no 1.19.2, and you had to go to 19.3/4? 

Love the mod, just came to see if this was available for 1.19.2 and saw this thread.

**Comment by FearAK** [comment]
Would really love a 1.19.2 version aswell

**Comment by FearAK** [comment]
1.19.2 was indeed skipped :(

**Comment by capnkirok** [comment]
Skipped, but not forgotten. I just wrote yesterday I will backport to 1.19.2.

**Comment by FearAK** [comment]
Oh awesome! Thank you :D Sorry I didn't realise

**Comment by PROJAVIP** [comment]
I still don't see it. plis add this mod

**Comment by PROJAVIP** [comment]
Plis update this mod to 1.19.2. in curseforge i don't see it.

**Comment by capnkirok** [comment]
It's not done yet :) working on it. Aiming for this weekend.

**Comment by PedroLima8080** [comment]
Will it be ready at Saturday? i'm creating a modpack to play with my friend's and i will put this mod :D
