### ISSUE TITLE
Dupe glitch with feed bag

### ISSUE THREAD

**Issue by Jayv6** [capnkirok/Inventory-Pets#527]
If you try to put stackable items in the bag from the upper left hand of the inventory itll dupe the items.
the top 6

**Comment by capnkirok** [comment]
Thanks, I'll prioritize this and try to get the update this weekend.

**Comment by Jayv6** [comment]
Also i just found another one with the sated double chest. If you open it the move it from that hotbar space then drop an item from the chest inventory it dupes the item

**Comment by Jayv6** [comment]
I know why that is happening. when you move the pet in your inventory while it is open it doesnt update the pet so you can take stuff out but when you put stuff it after you move it it will just delete the items

**Comment by capnkirok** [comment]
Ok, I've fixed the first one on the Feed Bag in the development environment. Something wrong in my quick-move code. Your description was key, thanks.

**Comment by capnkirok** [comment]
Ok, I've fixed the second issue too. If you try to pick up the pet while it's open, it will now close.
