### ISSUE TITLE
[Issue] Illuminati Invis Skill and Slime Crash

### ISSUE THREAD

**Issue by smoong951** [capnkirok/Inventory-Pets#528]
In Minecraft 1.19.3, there is an issue with slime when using the Illuminati Pet's skill.
I'm using the JEI (1.19.3) mod with it, and haven't used any other mods.

[Game Crash]
The game crashed whilst ticking player
Error: java.lang.ClassCastException: class net.minecraft.world.entity.monster.Slime cannot be cast to class net.minecraft.world.entity.monster.Monster (net.minecraft.world.entity.monster.Slime and net.minecraft.world.entity.monster.Monster are in module minecraft@1.19.3 of loader 'TRANSFORMER' @68ed3f30)

[crash-2023-06-10_21.40.13-server.txt](https://github.com/capnkirok/Inventory-Pets/files/11712458/crash-2023-06-10_21.40.13-server.txt)

**Comment by capnkirok** [comment]
Thanks for the crash log. Yep, definitely a bug.

**Comment by capnkirok** [comment]
Ok, this will be fixed in the next release.
