### ISSUE TITLE
Illuminati pet dosent work [Aternos]

### ISSUE THREAD

**Issue by ImBlexer** [capnkirok/Inventory-Pets#529]
Im on a Aternos server and i crafted an Illuminati pet and dosent work, first was disabled and i activated, but it still doesnt work anyways!
its activated but doesnt do nothing, i need help

**Comment by capnkirok** [comment]
Mmmm.... I can assure you it works fine in standalone SP or MP environment, though I have never tested Aternos. My guess is you didn't enable it on the Server side?

What version of Minecraft/Forge/Aternos are you using?

**Comment by capnkirok** [comment]
Any updates here? Why was it originally disabled?

**Comment by capnkirok** [comment]
Closing this due to inablity to repro/lacking data.
