### ISSUE TITLE
[Language] Create Korean localization

### ISSUE THREAD

**Issue by smoong951** [capnkirok/Inventory-Pets#530]
Hi. I created a Korean localization file.
Please add it to the mod!

★★★ The JSON file is not uploading, so I'm posting it as a TXT file. Please change it to JSON extension. ★★★
[ko_kr.txt](https://github.com/capnkirok/Inventory-Pets/files/11714023/ko_kr.txt)

-----------------------------------------------------------------------------

▶ These sentences don't work when translated.

"info.biomepet.loading": "Loading biomes ..." (en_us.json, line 609)
Note: petBiome.class, line 251

"tooltip.ip.wolfsays1": "says there is a" (en_us.json, line 589)
"tooltip.ip.wolfsays2": "nearby." (en_us.json, line 590)
Note: petWolf.class, line 261

▶ And these sentences are not added to en_us.json.

"No Cobblestone Pet holder found in range!"
Note: petDirt.class, line 483

"No Dirt Pet holder found in range!"
Note: petCobblestone.class, line 484

**Comment by capnkirok** [comment]
Thanks so much! I'll add to next release.

**Comment by capnkirok** [comment]
Ok, these will go into the 2.0.18 version on MC versions 1.16, 1.18, and 1.19.

감사해요
