### ISSUE TITLE
Cant find config file  (Attempting to enable/ disable certain pet abilities [illuminati pet etc]) (UNSOLVED SO FAR)

### ISSUE THREAD

**Issue by SladeWOOMY** [capnkirok/Inventory-Pets#533]
I am trying to enable the illuminati pets item ability but the curseforge mod has it disabled. I know its possible but I don't remember how to do it.

**Comment by capnkirok** [comment]
I'm really not sure how to help you. Here's a video showing where the config is: https://www.youtube.com/watch?v=HCAFohxg97k

If you are playing a server, the config file is on the server, and can only be edited by an admin.
