### ISSUE TITLE
illuminati pet confusion

### ISSUE THREAD

**Issue by Kerbal-Man** [capnkirok/Inventory-Pets#536]

**Comment by Kerbal-Man** [comment]
I didn't think pressing enter would create it...
but here's what I was going to say:

I was using an Illuminati pet when I got another Illuminati pet
![image](https://github.com/capnkirok/Inventory-Pets/assets/100152985/ecce4947-28f9-46d6-9572-7f70e64a0426)
I got a nether star and beacon but it also rained diamond, is this the pet or something else?

**Comment by capnkirok** [comment]
You got a rare achievement. Congrats :)

**Comment by capnkirok** [comment]
Should also play the theme from 2001 A Space Odyssey.

**Comment by Kerbal-Man** [comment]
Ok, thank you, the owner of the smp didn't believe me. LOL

**Comment by capnkirok** [comment]
You should be able to the owner the Achievement. It's very, very rare.
