### ISSUE TITLE
Dakrness Effect not being removed

### ISSUE THREAD

**Issue by Jayv6** [capnkirok/Inventory-Pets#538]
The cow pets doesnt remove the darkness effect when it is applied

**Comment by capnkirok** [comment]
Thanks. Yeah, I haven't updated this pet in a while, will take a look.

**Comment by capnkirok** [comment]
Ok, Cow Pet will now remove the following negative Potion Effects:
Unluck, Weakness, Bad Omen, and Darkness.

See next update (2.0.19), should release in couple of days
