### ISSUE TITLE
[1.19.2] Cloud Pet and Squid Pet

### ISSUE THREAD

**Issue by qznfbnj** [capnkirok/Inventory-Pets#540]
## Mod List
Forge-43.2.13
inventorypets-1.19.2-2.0.18

## Description
If these bugs are fixed in the development version, please feel free to close this issue:

(1) Sometimes Cloud Pet can fly even if not in inventory.

https://github.com/capnkirok/Inventory-Pets/assets/100760086/12b5f1f2-9159-48b2-9f9a-4cd469539259

(2) Use Cloud Pet to fly underwater, Squid Pet will speed you up infinitely.

https://github.com/capnkirok/Inventory-Pets/assets/100760086/ef495ca5-f40f-48c7-97e6-606049b60286

**Comment by capnkirok** [comment]
Thanks for posting this. Yes, these need to be fixed. I need to re-write this 'acceleration' functionality from the ground up. Stay tuned.

**Comment by capnkirok** [comment]
Ok Part 1 (Cloud Pet allows flight after you remove from Inventory) is fixed in Dev. Looks like I broke something when I implemented some performance improvements. Was not an issue on 1.16, just 1.18 and 1.19.

**Comment by capnkirok** [comment]
Ok, Part 2 is fixed (Squid Infinite Speed).

**Comment by qznfbnj** [comment]
Tomorrow morning I will test the cloud pets in 2.0.19.

**Comment by qznfbnj** [comment]
2.0.19 can still fly without pets... (I just discovered that after the pet's durability is exhausted, the flight ability obtained through this bug will not avoid falling damage)
![image](https://github.com/capnkirok/Inventory-Pets/assets/100760086/dae6734e-1894-4c99-ab58-fb0f78daf4a9)
![image](https://github.com/capnkirok/Inventory-Pets/assets/100760086/5fc485e1-1a7f-4a42-be68-b2018d2c39dc)
