### ISSUE TITLE
[1.16 - 1.19.2] (Flying) Saddle issue

### ISSUE THREAD

**Issue by qznfbnj** [capnkirok/Inventory-Pets#541]
You can "dismount"(CLIEND SIDE?) in the inventory GUI, after exiting the GUI you can act freely, and then you can still (actually) dismount(SERVER SIDE?)

https://github.com/capnkirok/Inventory-Pets/assets/100760086/fcd54cfb-13fa-4ed1-a49c-150d52b03c37

**Comment by capnkirok** [comment]
I see. Yes, it seems that bug has been there since this Pet was introduced. In vanilla it appears you can't dismount if you have a GUI open, probably because it causes a client/server de-sync.

**Comment by capnkirok** [comment]
Ok, this is fixed in dev. Will be available in next release (2.0.19)
