### ISSUE TITLE
[1.18.2] Double Chest Pet Immediately Closes When Using Them

### ISSUE THREAD

**Issue by thelovelyduchessreturns** [capnkirok/Inventory-Pets#544]
Experiencing an issue with my Double Chest pets where they won't stay open and instead automatically close on me. Not sure what's causing it. Video attached showing what's going on.

https://github.com/capnkirok/Inventory-Pets/assets/139078819/49a18241-e105-46f5-8691-111c304de0f9

**Comment by capnkirok** [comment]
That's so sad. I'll take a look!

**Comment by capnkirok** [comment]
Yep, it's a bug. Hang on to the chests, the next update will fix them.

**Comment by thelovelyduchessreturns** [comment]
Thank you!

**Comment by capnkirok** [comment]
Ok, already fixed in development. I'll try to get a release out in the next couple of days. Thanks for reporting!

**Comment by capnkirok** [comment]
So sorry this took so long. Major life stuff happened. Anyway, release will be out today (Dec 11).
