### ISSUE TITLE
How to customize pets [1.12.2]

### ISSUE THREAD

**Issue by ElLiox** [capnkirok/Inventory-Pets#548]
First of all sorry for my bad english

I saw that inside the configuration file there is a "customize pets" part
I tried to change the favorite food for the chicken pet and it did not work (a diamond instead of wheat seeds)
I just did it to try, what I really want to do is change the favorite food of the anvil pet (an iron block instead of an iron nugget)
I did not find examples of how to get this
I would appreciate if you help me

**Comment by capnkirok** [comment]
Hey there. This feature isn't implemented yet, but is being worked on. However, you can do a mod-wide upgrade to pet foods to increase difficulty by changing a config. I believe in 1.12 it's either called hardcorefood or petsEatWholeFoods... , just set that to true.
