### ISSUE TITLE
Grave pet does not restore Curios slots, armour, or off hand items

### ISSUE THREAD

**Issue by Silk-Hood** [capnkirok/Inventory-Pets#549]
Grave pet does not restore aromour, Curios slot items or offhand items.

**Comment by capnkirok** [comment]
Which version of Inventory Pets and Minecraft are you on?

**Comment by Silk-Hood** [comment]
2.0.19 on 1.18.2 forge 40.2.5

**Comment by capnkirok** [comment]
Baubles doesn't exist past 1.12 as far as I know. Has someone done a remake? If so, can you let me know what the mod is you are using?

**Comment by Silk-Hood** [comment]
Sorry i meant curios slots. Armour slots don't restore anyway

**Comment by capnkirok** [comment]
Ok perfect. I'll see what the API looks like. Offhand is a head-scratcher. Possible Mojang changed the slot number behind the scenes.

**Comment by MrOscarvs** [comment]
This bugs also happens in the 1.16.5 Forge version

**Comment by capnkirok** [comment]
Ok, fixed offhand. Looking into Curios now that I have the API integrated into Inventory pets.

**Comment by capnkirok** [comment]
Ok, Armor fixed. Curios I can't seem to place back in the Curios inventory, so placing in Main Inventory for now. At least you don't lose them anymore.
