### ISSUE TITLE
-21 Cooked fish?

### ISSUE THREAD

**Issue by insuusvenerati** [capnkirok/Inventory-Pets#55]
Not sure if this is a bug with inventory pets or not but I currently have -21 Cooked Fish in my feed bag. The ocelot pet just keeps eating from the negative stack. I can even eat from it and the number just keeps going down. 

I'm running 1.4.0 on MC 1.8.9 with forge 1764

**Comment by capnkirok** [comment]
That is definitely a bug, will check it out. Hope it's just the Ocelot, or I've got bigger problems. Thanks for the report!

**Comment by capnkirok** [comment]
Sadly, this affects all pets. Checking other versions.

**Comment by capnkirok** [comment]
And all versions 1.7.10 and 1.8.9. Due to the new Container logic. Definitely a bad one. Will have an update out in about a week.

**Comment by insuusvenerati** [comment]
Wish I could see the code :P

**Comment by capnkirok** [comment]
Thinking about making IP open source when we publish the API in a couple of months :P

Suffice it to say, this was a dumb one :D

**Comment by insuusvenerati** [comment]
Hey isn't hurting me. Infinite cooked fish? I'll take it.

**Comment by insuusvenerati** [comment]
Do you have an IRC? I'm having another issue but wanted to make sure it wasn't an intended affect first.

**Comment by capnkirok** [comment]
Yah, no IRC. I know, I know. Can you post here, or send me a note via the mc forum: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2402467-inventory-pets-animated-creatures-that-live-in

**Comment by capnkirok** [comment]
Closed in 1.4.1, and 1.4.3
