### ISSUE TITLE
Inventory pets mod disables flight for a mod called "Identity"

### ISSUE THREAD

**Issue by Burgh1** [capnkirok/Inventory-Pets#552]
The mod is basically just like morph, When killing a mob you can have thier abilities and shape, before adding the mod flight works perfectly on bats and blazes but after adding InventoryPets mod it is disabled, I tried to work something on the config file but that didn't get me anywhere by the way I'm playing on 1.18.2 and InventoryPet version is 2.0.19 @capnkirok

**Comment by Kyrnterra** [comment]
Using Budschie's Morph mod (1.18.2), can confirm this mod is preventing flight for some reason.

**Comment by capnkirok** [comment]
Well, I finally figured this out. A permanent fix for other mods with flight capabilities.

**Comment by capnkirok** [comment]
It's going to require a whitelist.

**Comment by Burgh1** [comment]
Does that mean flight issue can't be fixed?

**Comment by capnkirok** [comment]
It can be fixed, it's just going to require me to create exception logic based on a whitelist of accepted items or mods that allow flight. It'll be JSON file like the Illumunati Blacklist, which I can partially populate. Working on it now.

**Comment by capnkirok** [comment]
Related to #566

**Comment by capnkirok** [comment]
These should both be fixed in 2.1 version, should be released today.
