### ISSUE TITLE
Cloud pet fly ability doesn't work

### ISSUE THREAD

**Issue by M4rk0P** [capnkirok/Inventory-Pets#556]
I added inventory pets to a modpack called Better MC [Forge] on 1.19.2. I crafted the cloud pet because I knew it was the best way to travel at the time, but it didn't work when I tried to fly.

**Comment by capnkirok** [comment]
Check to see if flight is enabled on the server properties file.

**Comment by M4rk0P** [comment]
How do I find the server properties file?

**Comment by capnkirok** [comment]
https://www.youtube.com/watch?v=ezM_TjNnE1k

**Comment by M4rk0P** [comment]
I meant where i could possibly find the settings in something. I found this file named server core and looked a little into that. could that be what i'm looking for?

**Comment by capnkirok** [comment]
It's outlined in the youtube video. The file is literally called server.properties and the setting you are looking for is the very first item, "allow-flight" which is what you want to set to true.
