### ISSUE TITLE
Illuminati pet question 

### ISSUE THREAD

**Issue by Monstrcow** [capnkirok/Inventory-Pets#558]
I'm trying to mess around with rng manipulation and the illuminati pet, and I noticed there wasn't a better place to ask than here, how exactly does the illuminati pet decide the item it gives? It can handle mods, so it can't be drawing a block id, but then how does it choose?

**Comment by capnkirok** [comment]
There are several options in the config. Default is crafted recipes only. In this case, it's just random based on those results. If you choose any item, then it's random based on Item ID.
