### ISSUE TITLE
Chest Pet Bug - 1.19.2 Version 2.0.19 Chest Pet crashes game when moving to inventory

### ISSUE THREAD

**Issue by Brimstone287** [capnkirok/Inventory-Pets#559]
Okay, so, I did read over the entire fix of the previous issue the Chest pet was having and am getting the same error as the other guy where the player gets kicked from the server because the NBT is Null (Chest Pet kick players from the server #535). HOWEVER, I'm getting the issue still on the newer version but only in extremely specific circumstances. When the player shift clicks the pet into an inventory, they crash and get the error (same issue with the /give command) which then involves fixing the world by manually deleting the item from their inventory through NBTExplorer. BUT if they craft the pet, or manually move the pet into the inventory by directly dragging it into their inventory (ex. from creative dragging (NOT SHIFT CLICKING) a chest pet into the hotbar or taking the chest pet out of a spawned chest and dragging it into the inventory) it works fine. Super bizarre but hopefully all the information helps lol. Basically unless the chest pet moves inventories by manually picking up the item and placing it down, it crashes the game.

**Comment by necrotozoa** [comment]
I got this exact problem as well, the chest pet crashes the game after i moved it into RefinedStorage's grid and gave me this error:

**internal exception java.lang.nullpointerexception cannot invoke "net.minecraft.nbt.CompoundTag.m_128425_(String, int)" because "nbt" is null**

I can't access the storage that i dropped the chest pet in to, and it's crucial because it's in a main storage where i store all my items. It will always kick me if i attempt to open the RefinedStorage grid.

**Comment by Brimstone287** [comment]
So the only fix I think I'd be able to help you with is a had to go into the physical code of the world (I think I use NBTExplorer) and sift through the file until you find your refined storage system and manually delete the chest pet out of the inventory. After you do that I actually disabled the chest pet and the other ones that hold inventory until the mod gets updated again. Bag of Holding is a solid alternative in the meantime!

**Comment by necrotozoa** [comment]
i manually had to disable and re-enable the invpet mod itself for it to clear away from my grid, from there on everything else is smooth sailing. Never putting let alone picking up chest pets ever again

**Comment by capnkirok** [comment]
Hey guys. Yes, clearly a compat issue. For sure, NBT should not be null here. I've managed to fix it standalone, but other mods that poke into this area are having issues. Will report back after I can find a fix.

**Comment by necrotozoa** [comment]
ight dude thanks for the clarification good luck with it

**Comment by Brimstone287** [comment]
Sounds good! Thanks for the assist always appreciated 😄

**Comment by capnkirok** [comment]
related to #561

**Comment by capnkirok** [comment]
This is fixed in next release (coming soon).
1.20.1. 2.1.2
1.19.2 , 2.1.2.1
18.2, 2.1.2
