### ISSUE TITLE
StoneSpawn crashing server

### ISSUE THREAD

**Issue by dig** [capnkirok/Inventory-Pets#56]
Not really sure what causes it, I'm guessing some type of random generator.

inventorypets: inventorypets-1.7.10-1.3.91
forge: forge-1.7.10-10.13.4.1448-1.7.10
modpack: crundeecraft

Crash-report:
http://pastebin.com/aZWT867u

**Comment by Time6628** [comment]
Already fixed in the latest versions. https://github.com/capnkirok/Inventory-Pets/issues/30

**Comment by capnkirok** [comment]
Thanks Time6628. DigitalSniperz. As Time6628 said, try updating to version 1.4.0.
