### ISSUE TITLE
inventory pet doesnt let me fly

### ISSUE THREAD

**Issue by Latchy2022** [capnkirok/Inventory-Pets#560]
whenever i would join a world it doesnt let me fly even ftb /fly command wont work

**Comment by capnkirok** [comment]
What version of minecraft and inventory pets are you using?

**Comment by capnkirok** [comment]
I need more details, otherwise I have to close. Flying is working fine in client and server environments.

**Comment by capnkirok** [comment]
I fixed a bug that was causing a conflict with other mods that enabled flight. I'm assuming that was the issue here.
See #552 and download the 2.0.20 when it's out.
