### ISSUE TITLE
Cannot create the inventory pet [BUG]

### ISSUE THREAD

**Issue by MiszDee** [capnkirok/Inventory-Pets#563]
I hope that you can fix it, so that I can play with that mod
![WhatsApp Image 2023-12-18 at 23 40 48_be64be1b](https://github.com/capnkirok/Inventory-Pets/assets/154252280/9a6a2744-2ce8-4635-9219-0770c63e8b52)
![WhatsApp Image 2023-12-18 at 23 40 57_626b5f21](https://github.com/capnkirok/Inventory-Pets/assets/154252280/3e78f064-138a-4473-8b4f-df806dfd9c11)
@capnkirok 

> 1.20.1 ver

**Comment by capnkirok** [comment]
Really not sure how to respond to this. Recipe works fine. I did notice it strictly requires Minecraft items, so you can't use other mods' items. 

{
  "result": {
    "item": "inventorypets:pet_cloud"
  },
  "pattern": [
    "OFO",
    "ODO",
    "OGO"
  ],
  "type": "minecraft:crafting_shaped",
  "key": {
    "D": {
      "item": "minecraft:nether_star"
    },
    "F": {
      "item": "minecraft:quartz"
    },
    "G": {
      "item": "minecraft:diamond"
    },
    "O": {
      "item": "minecraft:iron_nugget"
    }
  }
}

**Comment by capnkirok** [comment]
Did you try to use the Fake Diamond to try to make this (the one the April Fool Pet gives you?)

**Comment by capnkirok** [comment]
Closing, as I've tested in multiple environments and this is the only report. I think you pulled in a Fake Diamond.
