### ISSUE TITLE
Inventory pets disables other mods flight

### ISSUE THREAD

**Issue by Mikecolle** [capnkirok/Inventory-Pets#566]
inventory pets on 1.20.1 disables all forms of creative type flight
-angel ring
-fluegal tiara
-flight potion
-ars neuou 
-/fly command

it does not disable the non creative flight of things like
mekanism jetpacks
create jetpacks

**Comment by capnkirok** [comment]
Yes, known issue and will be addressed by mid-Jan. 
#562

**Comment by capnkirok** [comment]
Alright, this is fixed in Dev. Had to make an exclusion list, but it works. Will release after I get in a few more fixes.

**Comment by capnkirok** [comment]
- adding in Mystical Agriculture Chestplate

**Comment by Diversion98** [comment]
with Inventory Pets 2.1.1, its still not fixed with FTB Essentials 2001.2.2
Still can't use the /fly command when Inventory Pets is loaded ingame

**Comment by Mikecolle** [comment]
has this been fixed yet  would love to add inventory pets back to the modpack

**Comment by capnkirok** [comment]
@Mikecolle yes. I just received a report that Vampirism is not working (though I have yet to confirm), but the rest I've been able to make work.
