### ISSUE TITLE
Why is there no code?

### ISSUE THREAD

**Issue by Jannik44** [capnkirok/Inventory-Pets#567]
Why is inventorypets not open source?

**Comment by Jannik44** [comment]
i see...

**Comment by capnkirok** [comment]
Sorry, could have provided you with some good reasons:
1) I have to fight copyright every day. The idea, code, and textures are constantly copied by other modders, youtubers, hired modders, even other games. It sucks. Most of my other mods are open source, but this one gets abused over and over. Making it open source would make it even worse. I actually had to hire an attorney at one point and issue cease and desist letters.
2) I am not terribly proud of this code. One of my first mods and it needs to be completely refactored and optimized. I am an adult with a full-time job and family and haven't had time to do this much needed pass.

It's definitely in the future, just not now.

**Comment by Jannik44** [comment]
Wow, i did not knew that copyright issues are that big of a problem, i personally never really thought that even people like youtubers or other modders would steal open source code to this extent 👀

I understand your decision to keep this mod closed source and I hope you can find some time to work on it in the future. It’s one of me and my friends favorite mods and I appreciate all the hard work you put into it. Thank you for sharing it with us. 🙏🏻
