### ISSUE TITLE
Mod conflicts with another mod I wanna use

### ISSUE THREAD

**Issue by Eeve2espeon** [capnkirok/Inventory-Pets#569]
For some reason the inventory pets mod conflicts with this mod ProjectE: https://www.curseforge.com/minecraft/mc-mods/projecte/files/4860857
I was wondering if you could fix that?

**Comment by capnkirok** [comment]
Hi Eeve2espeon. Can you provide any detail? Just saying there is a conflict provides me no guidance.

What is the conflict? What happens, where?
What version of Inventory Pets and ProjectE are you using?
What version of Minecraft and Forge are you using?

**Comment by capnkirok** [comment]
@Eeve2espeon haven't heard back from you, so planning to close this weekend if I don't hear back. Can't do anything without details.

**Comment by capnkirok** [comment]
Closing this as the answers I'm looking for are in #596
