### ISSUE TITLE
Nothing spawning in 

### ISSUE THREAD

**Issue by thekalkara131** [capnkirok/Inventory-Pets#571]
I've had this issue briefly before I moved, and it's happening again now that i'm set up at my new place. I added the inventory pets mod to the Better MC modpack on curseforge, and I'm not getting any inventory pets spawning in. I've ran around enough that I am positive I should have seen at least one tree pet, but neither me nor my girlfriend have seen any. In addition, I haven't seen any cloud pet dungeons either. I'm using the latest version of inventory pets for 1.19.2, 2.0.20. I'm playing the latest 1.19.2 version of Better MC, like I said this was an issue while we were playing briefly before we moved. I can look up the pets in JEI and see that they're in the modpack.

**Comment by capnkirok** [comment]
Pet dungeons won't spawn in an existing world unless you regenerate the chunks. They are structures which either need to be added before creating a world, or when you generate new chunks.
