### ISSUE TITLE
Spawner blocks + Pixelmon causing a lag-inducing excessive amount of spawns

### ISSUE THREAD

**Issue by Anthony-T-M** [capnkirok/Inventory-Pets#572]
This is happening currently with Inventory Pets 1.16.5-2.0.20 and Pixelmon 1.16.5-9.1.10. 

Pixelmon by default replaces Minecraft mob spawns with Pokemon. This is the cause when encountering a mob spawner, where Pokemon will spawn at the same rate as vanilla mobs.

For some reason, however, encountering an Inventory Pets spawn block (such as in an underground dungeon) causes Pokemon to spawn by the dozens in seconds, causing the game to lag tremendously.

I changed `disableMobsSpawnInDungeons` to `true` but that did not have any effect. I'm not sure if there's anything else I can do aside from report the issue here and to Pixelmon's devs. Thank you.

**Comment by capnkirok** [comment]
Yeah, it looks like I somehow disabled the code the stopped this from happening. Fixed in next release.
