### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by bkipper22** [capnkirok/Inventory-Pets#573]
I'm breaking inventory pet chests and it's dropping a "polly" all the chests drop this.

**Comment by capnkirok** [comment]
Dropping a "polly"? I have no idea what you mean. Sounds like another mod is doing that. What version of Inventory Pets and Minecraft are you using? And do you have any other mods that modify drops installed?

**Comment by danygarciagza** [comment]
yeah, that is intentional and only happens when you break it without opening first; even with the risk of it being a trapped chest, if you open and close very quickly and then open again (or break if that's your preference) the contents of the chest will be visible and correct

**Comment by capnkirok** [comment]
Ah yes, correct.
