### ISSUE TITLE
Golems are aggressive towards pets

### ISSUE THREAD

**Issue by MaraDra** [capnkirok/Inventory-Pets#574]
Hello, first of all I want to thank you for the funny and useful mod. But it’s upsetting that golems consider pets (anvil, for example) to be an aggressive mob. Can't this be fixed?
Sorry for my English, this post was made using Google.

**Comment by capnkirok** [comment]
Ah yes. I could see that as they are based on Slimes. I'll take a peek and see what can be done.

**Comment by MaraDra** [comment]
Thanks for the answer. I hope the day comes when I don’t have to hide behind doors to summon an anvil))

**Comment by capnkirok** [comment]
Ok, have this fixed in Dev. Should release an update this weekend.
