### ISSUE TITLE
Cloud Pet's effect constantly active in Creative (1.16.5)

### ISSUE THREAD

**Issue by GoldeRuby** [capnkirok/Inventory-Pets#575]
Rewriting my entire post after further testing.
I'd encountered the issue while testing a custom modpack in Creative mode, and noticed that my flight speed was much faster, and I was jumping very fast, and 2 blocks high. Only now (just prior to writing) did I discover the Cloud Pet's ability after searching it under issues, and decided to test the issue myself. in Survival mode, everything works as normal, but once I change into Creative mode, I have the increased flight speed and jump height, without the Cloud in my inventory. This issue won't affect a normal Survival world, but I felt it was worth bringing up. If not to be fixed, for this thread to serve as a "It's not just you, here's what I found." to others with a similar issue.

**Comment by MundM2007** [comment]
Another thing that happens, is that in spectator you always fly downwards, this movement related problem is fixed, if you put a cloud pet in your inventory.

**Comment by MundM2007** [comment]
also it actually seems like this is already reported in #568 and already fixed in dev

**Comment by capnkirok** [comment]
Yes, this is a dupe. Still working on a couple of other issues.
