### ISSUE TITLE
Cow pet is not removing the levitation effect

### ISSUE THREAD

**Issue by Jayv6** [capnkirok/Inventory-Pets#576]
The cow pet is not removing the levitation effect when it is applied from shulkers.
Version: InventoryPets-1.20.1-2.0.20

**Comment by capnkirok** [comment]
Is Levitation considered a harmful or negative effect? I thought it was neutral?

**Comment by Jayv6** [comment]
I would think so as it is applied from a hostile mob.

**Comment by Jayv6** [comment]
Maybe you could add it to were it is off by default but can have it to where the cow pet can remove the effect

**Comment by capnkirok** [comment]
I'll make a config for this. I've seen other mods use the levitate spell for in game flight, so don't want to create another conflict.
