### ISSUE TITLE
Error/Crash with Grave Pet in Inventory (NOT Hotbar)

### ISSUE THREAD

**Issue by knavesmith** [capnkirok/Inventory-Pets#578]
Running Minecraft 1.20.1 using Forge 47.2.0 and Inventory Pets 2.0.20

[crash-2024-02-09_03.10.44-server.txt](https://github.com/capnkirok/Inventory-Pets/files/14220874/crash-2024-02-09_03.10.44-server.txt)

Steps to Reproduce:
1. Die without the Grave Pet
2. Respawn
3. Put a Grave Pet in your inventory but NOT in the hotbar
4. Die again (Error/Crash occurs)

If you die from a mob, the game crashes. Otherwise, you respawn with your inventory wiped, and the error gets suppressed. You can still see the error occur if you use the /kill command for step 4.

**Comment by capnkirok** [comment]
Thanks for the detailed repro steps. This will be fixed in next release.
