### ISSUE TITLE
Night vision not working unless underwater

### ISSUE THREAD

**Issue by LabGoblin** [capnkirok/Inventory-Pets#58]
as the title says the night vision potion effect doesnt work unless your underwater. if you leave the water after its applied it is removed.

Modlist
https://www.dropbox.com/s/699f5ynmk4ltlw8/Modlist.PNG?dl=0

**Comment by capnkirok** [comment]
Yeah, that's not supposed to happen. Should only be the case with Squid Pet, not with the regular potion effects. Looks like a bug, but I'll dive deeper. Thx!

**Comment by capnkirok** [comment]
Can confirm this is an issue on 1.8 and 1.8.9. OK on 1.7.10. Of course, Ocelot still works :smile:

**Comment by capnkirok** [comment]
This will be fixed in 1.4.1 (already fixed in Dev)

**Comment by capnkirok** [comment]
Closed in 1.4.3
