### ISSUE TITLE
sated double chest pet won't work

### ISSUE THREAD

**Issue by acatwithagat** [capnkirok/Inventory-Pets#580]
when right clicked it opens for a split second then instantly closes while the normal double chest pet works, ideas?

**Comment by capnkirok** [comment]
What version of Inventory Pets and Minecraft are you running? I remember this being an old bug that I fixed. You may need to just update.

**Comment by acatwithagat** [comment]
we're running the latest version of 1.19.2 v2.0.20

**Comment by capnkirok** [comment]
Thanks, I'll take a peek! Hoping to have a long overdue release out this weekend.

**Comment by capnkirok** [comment]
Yep, I missed a line of code Thanks for the report. Should be updated this weekend.
