### ISSUE TITLE
Additional conflicts with other flight mods

### ISSUE THREAD

**Issue by Kingdemonic666** [capnkirok/Inventory-Pets#586]
Minecraft Forge 47.2.20
Inventory Pets 2.1 (1.20.1)
After testing, the following mods still have issues when Inventory Pets is installed:
Rings of Ascension: Ring of Flight
Apotheotic Additions: Jewel of the Aether
Bosses of Mass Destruction: Table of Elevation
Angel Ring 2: All Angel Rings

I have not tested all of the Angel Rings mods, but I can confirm that "AzureDooms Angel Ring" works with Inventory Pets 2.1.

Edit:
tested other Angels Rings for 1.20.1, all of the following conflict:
MassTech Angel Ring
Better Angel Ring
Alternative Angel Ring

**Comment by capnkirok** [comment]
Thank you for the specifics. Super helpful.

**Comment by capnkirok** [comment]
Ok, I've been able to add compatibility for all of the above except for Alternative Angel Ring, which is blocking other mods as well. You'll have to reach out to that mod developer.

See next release 2.1.1

**Comment by JensenButton9** [comment]
I can confirm this also breaks flight with Mekanisms Mek suit as well as creative flight with gravitational jetpack from Gravisuit Classic

**Comment by capnkirok** [comment]
@JensenButton9 these jetpacks will work again in 2.1.1
