### ISSUE TITLE
Spectator mode no longer has any form of flight

### ISSUE THREAD

**Issue by zander123p** [capnkirok/Inventory-Pets#587]
Expected results: Going into spectator mode will act as in vanilla, as in having flight to not fall through the floor.

Observed results: Going into spectator mode will have no flight enabled making you fall into the void.

**Comment by capnkirok** [comment]
I'll check this on all versions. Aiming for another flight update this weekend.

**Comment by capnkirok** [comment]
Confirmed it was on all versions. Apologies, I thought I caught this in the earlier release.

**Comment by capnkirok** [comment]
Fixed in dev. Next release 2.1.1 coming this weekend.

**Comment by PopSikle23** [comment]
do you know when exactly?

**Comment by PopSikle23** [comment]
> Fixed in dev. Next release 2.1.1 coming this weekend.

do you know when?*

**Comment by capnkirok** [comment]
Aiming for Sunday. Ran into an issue on the 1.20.x verion still trying to fix.

**Comment by PopSikle23** [comment]
> Aiming for Sunday. Ran into an issue on the 1.20.x verion still trying to fix.

hows it going?
