### ISSUE TITLE
1.20.1 Not working (Inventory Pets 2024)

### ISSUE THREAD

**Issue by Canadit101** [capnkirok/Inventory-Pets#588]
I tried to play Minecraft and it keeps saying this, Although the day before it was working. How do I fix this?

Edit 1: I already tried to remove the mod and add it back to my world and it still continued to say this.

![Screenshot 2024-03-06 224432](https://github.com/capnkirok/Inventory-Pets/assets/162547565/b1d5e77a-5506-406b-8c2d-957bb65c2677)

**Comment by Luviam** [comment]
That error looks like its not happy with you not having the mod "Curios API" which is interesting as Inventory Pets shouldn't depend on it. And if it does, either a bug or the dev(s) forgot to add that to their mod pages.

**Comment by capnkirok** [comment]
> That error looks like its not happy with you not having the mod "Curios API" which is interesting as Inventory Pets shouldn't depend on it. And if it does, either a bug or the dev(s) forgot to add that to their mod pages.

~~Curios is not required. I'm including the API in my build (as recommended by Curios dev). In any case, you should not be receiving this error, so will take a look.~~

Confirmed issue on my end.

**Comment by capnkirok** [comment]
@Canadit101 if you still can't get it to work, would recommend you downgrade to the previous version.

**Comment by Canadit101** [comment]
The problem was fixed after downloading the mod "Curios API". The funny part is that newest update must have affected it since this issue only happened after the update.

Edit: Thank you for the help!!

**Comment by capnkirok** [comment]
I can confirm I made a mistake in the implementation requiring you to have Curios installed. I'm going to leave this open for others who run into this problem. And will fix in the meantime. Apologies.

Two solutions to those in this predicament.
1) Download Curios API mod
2) Downgrade to previous version of Inventory Pets

**Comment by capnkirok** [comment]
Welp, it looks like I need to make Curios API required dependency if we want flight to work for other mods that use curios.I've updated Forge to reflect for current version.

**Comment by capnkirok** [comment]
Added to next release.
