### ISSUE TITLE
Illuminati Pet Question

### ISSUE THREAD

**Issue by zzApotheosis** [capnkirok/Inventory-Pets#59]
Java 8 Update 77 (64-bit)
MCP v9.05
FML v7.10.99.99
Minecraft Forge 10.13.4.1614
OptiFine_1.7.10_HD_U_D3
FastCraft 1.21

I see that a good chunk of your tickets with this mod are aimed at the Illuminati Pet. Haha!

I also have a question about it. I'm playing on a multiplayer server with my girlfriend and we both have crafted Illuminati Pets. One thing I have noticed is that when either of us use the Illuminati Pet's abilities, the cooldown timer starts for both of us, which leads me to believe that the Illuminati Pet's cooldown timer is global for all players. Was this intended?

Also, I noticed that the 2 minute cooldown timer actually takes longer than two minutes, but actually takes around 3 minutes to complete.

**Comment by capnkirok** [comment]
The Illuminati Pet gets a lot of attention :)

It's not supposed to be shared, so this is a bug. Working on it with the next release. Thanks for the feedback! See also #53 

EDIT: Full history, it wasn't intended to be shared globally, just between multiple pets in one hotbar. Then I decided against it after more feedback (like this!)

**Comment by capnkirok** [comment]
Ok, figured out a solution, and it's working in development. It will be pushed with the next release (1.4.1). Thanks again!

**Comment by capnkirok** [comment]
Fixed in 1.7.10, still working on 1.8, 1.8.9

**Comment by capnkirok** [comment]
Will roll out this change to 1.8, 1.8.9, 1.9.4, and 1.10

**Comment by capnkirok** [comment]
Finally ready, rolling out in 1.4.8
