### ISSUE TITLE
1.18.2 - Inventory Pets prevents creative flight from other mods e.g angel rings.

### ISSUE THREAD

**Issue by CluckII** [capnkirok/Inventory-Pets#590]
1.18.2
Version: 2.1

I noticed this whilst testing my own modpack. Inventory Pets currently prevents modded means of flight, such as angel rings and mystical agriculture. It also disables flight in spectator mode. I manually went through disabling about 340-ish mods, and flight functioned without issue with Inv. Pets disabled.  

It might be conflicting with another mod, but there's little that would suggest it. I'm assuming something within Inv. Pets disables creative flight? I don't know if this is a known or common issue, but thought to inform you about this. Thanks!

**Comment by capnkirok** [comment]
Please update to v 2.1.1. Have been working on this for some weeks and was released yesterday.

This release does not include an exception for Curios/Angel Ring. I'm testing an API integration on 1.20 first before I backport.
