### ISSUE TITLE
Inventory Pets & Mystical Adaptations Insanium Armor

### ISSUE THREAD

**Issue by puppet04** [capnkirok/Inventory-Pets#591]
For some reason, the inventory pets mod disables the mystical agriculture armour with a flight augment( that things together was supposed to make you fly)

**Comment by capnkirok** [comment]
Are you using version 2.1.1 ? And what version of Minecraft are you on? Supremium armor was specifically fixed and verified already.

**Comment by puppet04** [comment]
im on 1.18.2 using the inventory pets 2.1.1

**Comment by puppet04** [comment]
> im on 1.18.2 using the inventory pets 2.1.1

oh wait, when it updated, the supremium armor works now, but the addon that adds the insanium armour doesn't

**Comment by puppet04** [comment]
> Are you using version 2.1.1 ? And what version of Minecraft are you on? Supremium armor was specifically fixed and verified already.

Do you plan to fix the insanium armour too?

**Comment by capnkirok** [comment]
@puppet04 that's a different mod, for the record (Mystical Adaptations), which was not called out as an issue until now. Yes, I can add an exception there as well. 

For the record Supremium Armor from Mythical Agriculture is working in 2.1.1 version.

**Comment by capnkirok** [comment]
I've added Insanium Armor in 1.19.2, the latest version (2.1.2), still need to update in 1.20.2.
