### ISSUE TITLE
Compat Issue: Extra Golems & Living Anvil

### ISSUE THREAD

**Issue by MaraDra** [capnkirok/Inventory-Pets#592]
Good afternoon. I was very pleased with the prompt solution to the bug with golem aggression, thank you for that)
But, unfortunately, the golems from the Extra Golems mod still attack the anvil (and maybe other pets). I don’t quite understand whether I should contact you or the author of Extra Golems?
I think this could be considered a compatibility issue?
(Sorry for my English)

**Comment by capnkirok** [comment]
I'll have to take a look at the mod and what they do. If they extend the current Golem entity, then I can create blanket coverage.

**Comment by capnkirok** [comment]
I was able to modify to cover the base Golem entity instead of just the Iron Golem. In the next release (2.1.2)
