### ISSUE TITLE
[1.19.2] Flight Broken Curios-related

### ISSUE THREAD

**Issue by sharkweekthings** [capnkirok/Inventory-Pets#594]
Forge 1.19.2
inventorypets-1.19.2-2.1.1
Botania-1.19.2-440-FORGE
AngelRing2-1.19.2-2.1.8

This seems to be a mod conflict/issue; where Inventory Pets is the one causing other things to break.

With these 3 mods installed, a player cannot use any Flugel Tiara, or any version of the Angel Ring for flight.  If I remove InventoryPets, Botania and AngelRing start working again. 

I have tried a few different routes of messing with the Cloud pet, since I assume it's something to do with that causing the issue.

Cloud Pet Enabled
Cloud Flight Enabled

Cloud Pet Disabled
Cloud Flight Disabled

Cloud Pet Disabled
Cloud Flight Enabled

Cloud Pet Enabled
Cloud Flight Disabled

Doesn't seem to matter, the only thing that lets you fly with the other mods is fully disabling Inventory Pets mod as a whole. 

Unfortunately, my Modpack kind of has all 3 mods ingrained into it with progression in mind. So, I am hoping that you have some magic that you're able to work in order to get things working again.

**Comment by sharkweekthings** [comment]
inventorypets-1.19.2-2.0.20

This is the last version of InventoryPets that worked with both Botania and AngelRing.

**Comment by capnkirok** [comment]
Hey there @sharkweekthings this is a known issue and I put an experimental fix into the 1.20.x version which involves using the Curios API. The fix appears to be working so I can use the same method.

Related to #584

**Comment by capnkirok** [comment]
Ok 1.19.2 was updated to include Curios related items.
