### ISSUE TITLE
cloud pet + config file (Mincraft forge 1.20.1, (InventoryPets-1.20.1-2.1.1)

### ISSUE THREAD

**Issue by anni0banni** [capnkirok/Inventory-Pets#595]
Hi,
1. After I use the cloud pet, I still have the ability to fly even tho its not in my inventory anymore. Only disconnecting fixes it.
2. I want to make the pets not craftable/make the recipes harder. Its says in the forum that both are configurable in the config file tho there is no line with these option.

pls help and love the mod <3

**Comment by capnkirok** [comment]
1. What other mods that have flight capabilities do you have installed?
2. Sadly, this is no longer possible after 1.18 version, due to a change within Minecraft. Would recommend you try a tool like Crafttweaker which will allow you to do what you are looking for.

**Comment by anni0banni** [comment]
1. only the ather Im aware of. Tho Ive not even entered that yet and dont have anything else giving me flying capabilities. It stared after the recent update and was fine before. It also fine for my friend playing on the same server
