### ISSUE TITLE
[1.19.2] ProjectE Flight Issues

### ISSUE THREAD

**Issue by Skylord2016** [capnkirok/Inventory-Pets#596]
Minecraft 1.19.2
Forge-43.3.9
Inventory Pets 2.1.1
ProjectE 1.10

Hiya, I wasn't sure if I should add onto previous threads or start a new one.
I've been having some issues which I think are related to [(https://github.com/capnkirok/Inventory-Pets/issues/584)]
& [(https://github.com/capnkirok/Inventory-Pets/issues/569)]

The Swiftwolf's Rending Gale ring & Ring of Arcana from ProjectE are both supposed to have creative mode flight, but are not activating.
All other abilities from the rings work, just not flight. 
When I've investigated the issue with ProjectE they have said it's to do with conflicting flight mods. 
They also have an open github request ([https://github.com/sinkillerj/ProjectE/issues/2326])

**Comment by capnkirok** [comment]
Checking all versions.

**Comment by capnkirok** [comment]
Fixed in next release (2.1.2)

**Comment by capnkirok** [comment]
For the record, I found ProjectE flight to be inconsistent. I removed Inventory Pets and saw the same issues with other mods installed next to ProjectE.
