### ISSUE TITLE
Cloud Pet flight bugged in server 1.18.2

### ISSUE THREAD

**Issue by TypicalNeko** [capnkirok/Inventory-Pets#599]
forgspi-4.0.15-4.x.jar 
inventorypets-1.18.2-19.0.4.jar

We have a pretty modpack including other flying stuff like angel rings (which also seem to not work cause of the bugs already known). But currently my friend uses the cloud pet but has to spam jump a lot to even get it to work and get her into the air and it instead gives her a slow fall like affect almost. While when I take her same cloud pet it works just fine no issues. I tried opping her, killing to reset, server restart, etc a lot of things but nothing seemed to work so im unsure what the problem is. It also happens to the other server member. The server is being ran by me on my computer and I'm port forwarding to connect them.

**Comment by capnkirok** [comment]
What version of Inventory Pets are you using? The one you reference doesn't exist: inventorypets-1.18.2-19.0.4.jar

**Comment by TypicalNeko** [comment]
Oops my bad I copied the wrong numbers when reading it. 
It's inventorypets-1.18.2-2.1.1

**Comment by capnkirok** [comment]
Ok phew. I've put in updates for 1.20.x and 1.19.x that I need to replicate into 1.18. It will fix the 'angel rings' issues and a few others including what you mention. Look for an update this weekend (usually Sunday). Version will be inventorypets-1.18.2-2.1.2.

**Comment by TypicalNeko** [comment]
Okay thank you for the notification and confirmation ^^

**Comment by capnkirok** [comment]
Still working on this, found another bug in 1.18.2 I want to fix. Should be up in the next day or so.
