### ISSUE TITLE
Editing the config/ common file doesn't effect anything in the game.

### ISSUE THREAD

**Issue by zeldock** [capnkirok/Inventory-Pets#600]
I edit the confif file and restart the server but nothing changes for any of the inventory pets.

**Comment by zeldock** [comment]
**1.20.1**

**Comment by capnkirok** [comment]
That doesn't make any sense. What config settings are you changing?

**Comment by capnkirok** [comment]
Do you happen to have an old config and are changing / hiding recipes? Because I had to remove that ability after Mojang removed that functionality.

If that's the case. Would recommend you delete your config and restart your server to create a fresh one.

**Comment by capnkirok** [comment]
Hey @zeldock I'm going to close this one in a few days since I haven't heard back. Configs are working fine or my github would have blown up by now, so assume there's something else going on (see note above).

**Comment by capnkirok** [comment]
Please re-open if you tried the above and the issue persists.
