### ISSUE TITLE
Two advancements only available in Multiplayer

### ISSUE THREAD

**Issue by ExpendedEcho** [capnkirok/Inventory-Pets#601]
Two advancements require multiplayer, making the mod impossible to fully complete in singleplayer.

**Comment by capnkirok** [comment]
I assume you are referring to the Cobblestone & Dirt achievements? There is definitely a way to get all achievements in single player. I don't think you've explored all possibilities, as morbid as they might be.

**Comment by ExpendedEcho** [comment]
What exactly is the other option? I ended up resorting to cheats as zombies are incapable of holding Inventory Pets.

**Comment by capnkirok** [comment]
You can hold both pets in your hotbar at the same time, right?

**Comment by ExpendedEcho** [comment]
Which does not allow for you to be detected as a holder.

**Comment by capnkirok** [comment]
Hmmmm .... it's possible I accidentally changed this. I'll verify!

**Comment by capnkirok** [comment]
Apologies. Looks like I did change it. The intention was you could do this to yourself. I'll fix in next update. Thanks for flagging!

**Comment by capnkirok** [comment]
Ok, this is fixed in dev environment and will be in the next release out in a couple of days (2.1.3). Thx.
