### ISSUE TITLE
Game crashes when using ender chest pet.

### ISSUE THREAD

**Issue by ZestyZenki** [capnkirok/Inventory-Pets#602]
Minecraft crashes whenever using the enderchest pet when you are touching a chest. The game only crashes when you are touching a chest and u use the ender chest pet apparently due to it getting it mixed up therefore it crashes instantly. 
(For forge 47.4.0) (Inventory pets 1.20.1-2.1.2)

**Comment by capnkirok** [comment]
Yes, likely a bug I didn't test for. Thank you for the detail.

**Comment by capnkirok** [comment]
Ok, this is fixed in development environment. Look for it in a future release before end of September.
