### ISSUE TITLE
Flight module from RFTools Environmental Controller broken in 1.18.2

### ISSUE THREAD

**Issue by foobazbar123** [capnkirok/Inventory-Pets#604]
Forge 40.2.17
RFToolsBase 1.18-3.0.12
RFToolsUtility 1.18-4.0.24
InventoryPets-1.18.2-2.1.2

It appears that Inventory Pets of the above version completely breaks the Environmental Controller's flight module. It doesn't appear to impact flight from other mods, just RFTools. I checked their github, and no issue is logged there. Let me know if there is any additional information or such I can provide :)

**Comment by capnkirok** [comment]
I'll add to the exceptions list.

**Comment by foobazbar123** [comment]
There was another mod that was also impacted, but I'm not sure I recall which one it was at the moment. I did notice a pattern where item based flight was usually not impacted, but effect or area based mods were crippled. For instance, the flight module from Mystical Agriculture was okay

**Comment by capnkirok** [comment]
I made a few updates for the 2.1.3 version, including new exceptions for Xycraft, Vampirism, and RFTools. Should be released soon.
