### ISSUE TITLE
bat mod on vampirism dont work after install inventorypets

### ISSUE THREAD

**Issue by Alcatone** [capnkirok/Inventory-Pets#606]
description :

inventorypets-1.20.1-2.1.2
vampirism-1.20.1-1.10.8
forge-47.3.0

everything worked on my mod pack until I installed inventorypets in my modpack because it breaks the functionality of flying as a vampirism bat.

**Comment by capnkirok** [comment]
Thanks for the submission. I had put in an exception for vampirism, but it wasn't working on the 2.1.2 version. I've fixed in the dev environment. Please look for 2.1.3 release, coming soon.
