### ISSUE TITLE
Fly Ability for Cloud Pet and Better Angel Ring not working in 2.1.2 (1.20.1)

### ISSUE THREAD

**Issue by DenEgg** [capnkirok/Inventory-Pets#607]
Minecraft 1.20.1
Forge - 47.3.0
Inventory Pets - 2.1.2
Curios - 5.9.1
Better Angel Ring - 1.0.2

I've read through #584 , where it seemed to be fixed in 2.1.2, but it's still not working for me, even with deactivating the whole Cloud Pet Configs.

**Comment by capnkirok** [comment]
That's because Better Angel Ring is not on the list of exceptions. Can add. 

It's not tied to the Cloud Pet configs, though that is not a bad idea.

**Comment by DenEgg** [comment]
I just found out, there might be another Culprit Mod. Just tested both Angel Rings mod with Inventory Pets but without my Modpack and it worked fine...

The Culprit is a Weapon Mod named "Master Weapons". The Armor adds Flight, deactivates other mods flight function and doesn't have a config to deactivate. It's too cheaty though.

I don't know if the mod is worthy for your exceptions, but for me it has to be removed from my Modpack. So fortunately everything works fine now.

**Comment by capnkirok** [comment]
Well, that's good news! Thank you for the follow up.
