### ISSUE TITLE
chest pets except for enderchest pet kicks from server but not single player world 1.20.1

### ISSUE THREAD

**Issue by CurseHex** [capnkirok/Inventory-Pets#608]
all chest pets work on single player worlds fine no problem

player is kicked apon interacting or recieving single or double chest pet on multiplayer server    but the ender chest pet works fine

This message is displayed when kicked: Internal Exception: io.netty.handler.codec.DecoderException:  Java.lang.NullPointerException

I have tested every single pet on multiplayer and they all work except for the single and double chest pet Kicking issue
There is no issue with using these pets on single player worlds the problem is multiplayer only 

I use a specific version of forge for compatibility with other mods in my pack it is: forge-1.20.1-47.1.3

**Comment by CurseHex** [comment]
![Capture](https://github.com/user-attachments/assets/f2ed14f8-1355-43e0-8d16-0e96ca7d745b)
These are all the mods I have loaded maybe there are known conflics

**Comment by CurseHex** [comment]
![Creative](https://github.com/user-attachments/assets/68c48480-aff1-4492-8c42-1b2c8f20be1a)

UPDATE: this crash only occurs when pets are taken from the creative inventory directly

Survival crafting and using single and double chest pets does not kick player from server ONLY when these pets are taken from creative inventory screen 
Obtaining them via crafting or /give @a inventorypets:pet_chest does not kick player

**Comment by capnkirok** [comment]
Likely related #613 though may be a different conflict.

Some mod is attempting to access the chest inventory before the title of the chest is assigned.

**Comment by capnkirok** [comment]
Confirmed this is a bug and not a mod conflict.

**Comment by capnkirok** [comment]
It appears to only happen when dragging a chest into your inventory from the Creative screen, as you stated. Bug affected Chest Pet, Double Chest Pet, Sated Chests, and Feed Bag (for the record).

**Comment by capnkirok** [comment]
Ok, this is fixed in my dev environment. Look for it in the next release (2.1.3) at the end of this month (September).
