### ISSUE TITLE
Anvil pet dupe

### ISSUE THREAD

**Issue by LesCaftieres** [capnkirok/Inventory-Pets#610]
dupe with anvil pet when he repair curios slot item 

mod use : Mine&Slash, Curios, inventoryPet

version 1.20.1forge 47.3.5

https://www.youtube.com/watch?v=5lq6YCuj_y0

**Comment by capnkirok** [comment]
Related to #603

**Comment by capnkirok** [comment]
You can disable the pet for now.

**Comment by capnkirok** [comment]
This is fixed in 2.1.3
