### ISSUE TITLE
Inventory Pets breaks Xycraft balloon on a stick

### ISSUE THREAD

**Issue by Luminaire0** [capnkirok/Inventory-Pets#611]
Inventory pets will break the flight ability of the balloon on a stick.  Disabling the flight pets also doesn't fix it.

To reproduce, install Xycraft machines, and install Inventory Pets, and give yourself a balloon on a stick.  Place the stick on the ground.  It will not take off.

Minecraft 1.20.1
Forge 47.3.0

**Comment by capnkirok** [comment]
Yes, Xcraft machines is not on the the exceptions list. Will add in future update.

**Comment by capnkirok** [comment]
Ok this is fixed in next release. Didn't realize Soaryn was back. Release will be out soon.
