### ISSUE TITLE
Cloud pet not properly disabling / Incompatible with Mekasuit Grav unit

### ISSUE THREAD

**Issue by ilee2413** [capnkirok/Inventory-Pets#612]
I have tried just about everything to disable the cloud pet on a server i manage however it doesnt seem to disable unless the players disable it in their own personal common config.

Additionally it seems to disable Mekanism's Mekasuit Gravitational Modulating Unit unless the player is holding a cloud pet in their hotbar.

This is persistent even in the case that players disable the pet in their common config.

**Comment by capnkirok** [comment]
Mekasuit Gravitational Modulating Unit is not on the exceptions list. I will add it to the next release (in September). 

I'll take a look at the 'disable' config. I haven't seen that reported yet by anyone else. Can I ask what version of Inventory Pets and Minecraft you are using

**Comment by ilee2413** [comment]
Inventory Pets 2.1.2
Minecraft 1.20.1

thank you

**Comment by capnkirok** [comment]
Ok, this is fixed in dev and will be in the next release coming very soon.
