### ISSUE TITLE
House Pet seems to have trouble teleporting to spawn points not set by the pet - 1.20.1

### ISSUE THREAD

**Issue by Proteale** [capnkirok/Inventory-Pets#615]
I've been using the House Pet in a custom modpack but it seems really inconsistent in its usage. A lot of the time, it would initiate the teleport, and I could see on the minimap that it had teleported me to my spawn point, but it shows me falling through the void and then landing me right back where I teleported from. Basically the pet would try to teleport me, but would just end up not going anywhere. 

I tried to get it to work and when I would set the spawn point manually using the House pet's power, I could teleport fine, but trying to teleport to a spawn point set at a bed would almost never work.

**Comment by capnkirok** [comment]
Which modpack are you using? And are you playing on a server environment?

**Comment by capnkirok** [comment]
Verified your theory. If you sleep in a bed instead of using the House's built in Spawnpoint setter, it can't seem to find the location.

**Comment by capnkirok** [comment]
Absolutely bizarre bug. Only occurs on 1.20.x. Both Client and Server show correct position, but player renders in different location. Found a way to force sync correct location through sending a packet.

Fixed in next release (2.1.3). Thanks for flagging.
