### ISSUE TITLE
Cloud Pet gives infinite flight

### ISSUE THREAD

**Issue by RealKurogane** [capnkirok/Inventory-Pets#616]
I am playing a modpack called Project Architect 2 and I add the inventory pets mod. When I put the cloud pet in my hotbar I can fly like normal but then I can still fly even if the pet isn't in my inventory. The effect only goes away when switching dimensions. Can someone help?

**Comment by KERERCVASD** [comment]
This might help:This file might fix it
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic

you may need to install the c compiler

**Comment by capnkirok** [comment]
What version of Minecraft & Inventory Pets are you on?

**Comment by RealKurogane** [comment]
Minecraft 1.20.1 and Inventory pets 2.1.2 although upon further research it seems any item that gives me flight has the same glitch so it might not be an inventory pets problem.

**Comment by capnkirok** [comment]
I've just tested this again, and it's not Inventory Pets, so closing. Let me know if you find out what mod is causing it, thx.
