### ISSUE TITLE
Client Crashing When Opening Feed Bag

### ISSUE THREAD

**Issue by Dorko316** [capnkirok/Inventory-Pets#617]
My friends and I recently updated our server to 1.20.1. Since then, whenever I try to open a feed bag, my game crashes with the following error. No crash report is produced. 

![WhatsApp Image 2024-09-27 at 22 35 21_f0e522ba](https://github.com/user-attachments/assets/bf333cc9-9678-4d16-8084-77d5f8fdcf85)

We're using version 2.1.2.

Log: [](url)
[latest.log](https://github.com/user-attachments/files/17172152/latest.log)

Any idea what's wrong?

**Comment by capnkirok** [comment]
Hi @Dorko316, yes. This is the same error plaguing a few other folks. #613 #608 . It's fixed in dev, but I'm wrapping a few more bug fixes into the next release.

**Comment by Dorko316** [comment]
Ok good. Glad we're not the only ones. Do you know when the next release will come out?
