### ISSUE TITLE
every time I break a chest it gives a poisonous potato but if i open it, it summon tnt what do I do

### ISSUE THREAD

**Issue by Legoavenger05** [capnkirok/Inventory-Pets#619]

**Comment by capnkirok** [comment]
Yes, breaking the chest will give you a poisonous potato. That is to prevent you from cheating by breaking the chest :)

If you open it... it will always **hiss** like there is TNT... but only 1/4 of the time is it actually TNT. You have to be careful and look to see if there's actually TNT or not. And move quickly away if there is.
