### ISSUE TITLE
1.8.9 April Fools update causing server issues

### ISSUE THREAD

**Issue by Not-February** [capnkirok/Inventory-Pets#64]
https://paste.ee/p/RHEMB

Seems to be having trouble with something regarding the player data file. I added this into an existing world; would that cause issues?

EDIT: Forgot to mention; I was able to log in fine, but it spammed the log with that right before I connected. I haven't tried actually using any pets thus far.

**Comment by capnkirok** [comment]
Yes, this happens this first time this is run. It's trying to load an extended properties file that isn't there. It's just a warning message. It should not run again the second time. If you want, you can try it on a separate world, and see the results. Let me know how it goes!

**Comment by Not-February** [comment]
Ah, alright. It didn't look very friendly, so I've been wary of doing much involving the inventory pets in case it was something that needed to be fixed. Thanks for the input.
