### ISSUE TITLE
Storing null in NBTTagCompounds

### ISSUE THREAD

**Issue by bloodmc** [capnkirok/Inventory-Pets#65]
http://pastebin.com/qjxxeViN

null should never be stored in NBT

Currently using MC1.8.9 1.4.0 version

**Comment by capnkirok** [comment]
Will take a look. Storing null is weird. Storing null onto the _sponge_ is very weird.

Edit: Realized last week that 'Sponge' refers to SpongeForge and not the pet Sponge.

**Comment by bloodmc** [comment]
@capnkirok thanks!. We purposely crash the game and log a stacktrace to avoid bad data being stored in NBT.

As seen here

https://github.com/SpongePowered/SpongeForge/blob/master/src/main/java/org/spongepowered/mod/mixin/core/nbt/MixinNBTTagCompound.java#L43

**Comment by bloodmc** [comment]
@capnkirok any luck with fixing this?

**Comment by capnkirok** [comment]
Ok, think I figured this one out. Was a typo in the Extended Properties setter. Issuing a fix shortly. Thanks for reporting!

**Comment by capnkirok** [comment]
Ok, this is updated in 1.4.4, now on Curse

**Comment by capnkirok** [comment]
Reopening. Still seeing issues with SpongeForge. Typo didn't change anything.

**Comment by capnkirok** [comment]
BloodMC, if you are still there, try this version. I've just made an additional null check. Very curious to hear the result: https://www.dropbox.com/s/aiv70vq9ng57h91/inventorypets-1.8.9-1.4.4.jar?dl=0

**Comment by capnkirok** [comment]
Closing this on our side. Have confirmed that my additional check fixes the issue. Solved in 1.4.5

**Comment by capnkirok** [comment]
http://minecraft.curseforge.com/projects/inventory-pets/files/2297618
