### ISSUE TITLE
1.8.9 Causes sponge to force shutdown the server

### ISSUE THREAD

**Issue by Mickimoo** [capnkirok/Inventory-Pets#66]
Hello!

Recently testing some mods with sponge has show that there is an issue with InventoryPets. It seems that there are 'null' checks missing, according to sponge.

http://pastie.org/private/pu4967kfaguhpxikfpjvq

Full fml log:
https://gist.github.com/Mickimoo2/ed39186861cc8f058308ef84f7d4e99b

I would highly appreciate if there is a fix :)

**Comment by capnkirok** [comment]
There are null checks in the code. This was also reported by two others and we're looking into it. Could be an issue with SpongeForge too, not sure.

**Comment by capnkirok** [comment]
Let me know what happens with this version: https://www.dropbox.com/s/aiv70vq9ng57h91/inventorypets-1.8.9-1.4.4.jar?dl=0

Please note that the code should never reach the point where it crashed if it was null, but I'm willing to try additional checks if it helps.

**Comment by capnkirok** [comment]
#65

**Comment by Mickimoo** [comment]
Seems to be working, just spam for the exceptions now :)

http://pastie.org/private/zkac5jc3zkftwfch5zzdq

Full log:
https://gist.github.com/Mickimoo2/833c19e252adc4e6da27236085a7e52b

**Comment by capnkirok** [comment]
Ok, cool. The spam exception should only happen the first time you run it. Let me know if you continue seeing it. Closing this after I upload the update.

**Comment by capnkirok** [comment]
http://minecraft.curseforge.com/projects/inventory-pets/files/2297618
