### ISSUE TITLE
Quick Suggestion

### ISSUE THREAD

**Issue by zzApotheosis** [capnkirok/Inventory-Pets#67]
Minecraft 1.7.10
MCP v9.05
FML v7.10.99.99
Minecraft Forge 10.13.4.1614
Optifine OptiFine_1.7.10_HD_U_D4
FastCraft 1.23
Inventory Pets 1.7.10-1.4.3

Hey again! I'm playing a heavily modded private modpack with Solar Expansion installed alongside Inventory Pets (both of which are awesome). I'm not exactly an expert in Java (just finished CS1), but it seems that the Inventory Pets recipe for Lapis Nuggets overrides the recipe for Lapis Shards from Solar Expansion, so I can't craft anything for that mod. Both mods break a single lapis lazuli into 9 smaller components, but they use different oredictionary entries. I'm sure a quick fix for this would be to add "shardLapis" as an oredict entry for the Lapis Nugget.

And as always, thanks for this awesome mod!

You can see my struggles here :P
https://drive.google.com/open?id=0B_wljXPJi507SXlqY0t0cE9iUGc

**Comment by capnkirok** [comment]
Thanks for the suggestion, will try to get this in the next update.

**Comment by capnkirok** [comment]
Ok, I've added this to all versions, thanks for the suggestion 👍

**Comment by capnkirok** [comment]
This is in place in 1.9 and 1.9.4 already

**Comment by capnkirok** [comment]
Fixed in 1.7.10

**Comment by capnkirok** [comment]
Fixed in all version
