### ISSUE TITLE
Cloud Pet flight not working 1.8.9 version 1.4.5

### ISSUE THREAD

**Issue by Frobuzmumber** [capnkirok/Inventory-Pets#69]
Found the cloud pet in a really tall tree, tried to fly, was not able to. Went into creative, pulled out another and had the same issue. Tested on single player world and had the same issue. There is no error message or message of any kind in chat or client log as well as server log.

the following is my complete mod list, tested client and server side. 

AbyssalCraft Integration-1.8.9-1.4.3.jar
AbyssalCraft-1.8.9-1.9.1.6.jar
ArmorPlusMod1.9.1(1.8.9).jar
Baubles-1.8.9-1.1.3.0 (1).jar
bdlib-1.10.0.32-mc1.8.9.jar
Bookshelf-API-1.8.9-2.3.7.jar
CorrelatedPotentialistics-0.2.3_01.jar
craftnstar-1.8.9-0.3.1.jar
CraftTweaker-1.8.9-3.0.8.jar.dis
DWA-V1.3.1-mc1.8.9.jar
DynamicLights-1.8.8.jar
DynamicSurroundings-1.8.9-2.0.5.6.jar
EDM-5.2.0.jar
emeraldobsidianmod-1.8-1.3.1.jar
Excore-1.5.3-1.8.9.jar
ExNihilo2-0.28.jar
extrautils2-1.8.9-alpha-0.0.2.jar
FastLeafDecay-1.8-1.6.jar
ForeverEnoughItems-1.0.10-1.8.9.jar
generators-0.9.20.11-mc1.8.9.jar
GrimoireOfGaia3-1.8.9-1.3.3.jar
HardcoreDarkness-MC1.8.8-1.8.jar
inventorypets-1.8.9-1.4.5.jar
InventoryTweaks-1.60-40.jar
ironchest-1.8.9-6.0.125.770.jar
JEIAddons_1.8.9-0.12.0.57 (1).jar
jei_1.8.9-2.28.18.186.jar
journeymap-1.8.9-5.1.5-unlimited (1).jar
Loot++-1.6.1_for_1.8.9 (1).jar
LuckyBlock_1-8-9_v7-0-2 (1).zip
Mantle-1.8.9-0.9.2.jar
MCMultiPart-1.0.9-universal.jar
MoreFurnaces-1.5.1-MC1.8.9.jar
NeoTech-1.8.9-2.4.4.jar
OptiFine_1.8.9_HD_U_H5 (1).jar
OverpoweredInventory-1.8.9-2.1.0.jar
PlayerAPI-1.8.9-1.0.jar
PneumaticCraft-1.8.9-1.13.8-12-universal.jar
Slabcraft-V3.01 - MC1.8.9 Forge.jar
SoundFilters-0.8_for_1.8 (1).jar
Staircraft-V3.01 - MC1.8.9 Forge.jar
TConstruct-1.8.9-2.2.1.jar
VeinMiner-1.8.9_0.31.4.unknown.jar
Waila-1.6.0-B3_1.8.8.jar
WailaHarvestability-mc1.8.x-1.1.7.jar
Wallcraft-V3.01 - MC1.8.9 Forge.jar
Wawla-1.8.9-1.1.4.171.jar

Also: 
in Addons: 
Lucky Block rainbow v1.8.zip
Lucky Block Spiral v1.10.zip
V1.3 The Doctor Who lucky Block.zip

Forge version:
forge-1.8.9-11.15.1.1902-1.8.9

**Comment by capnkirok** [comment]
Closed. Due to conflict with ArmorPlusMod1.9.1, problem is on that mod's side.
