### ISSUE TITLE
[1.9] Musical Quiver Pet Bug

### ISSUE THREAD

**Issue by BellaRose0613** [capnkirok/Inventory-Pets#72]
So... I right-clicked the quiver pet in gamemode 1 and it started playing music. I doubt this is intentional though. Oh, and it doesn't shoot any arrows in either gamemodes, regardless if it has feathers or not.

**Comment by capnkirok** [comment]
It is supposed to play the music in Creative. Two questions: 
- Does it shoot arrows if you just right click and let go?
- What version of 1.9 (Forge) are you using

**Comment by BellaRose0613** [comment]
- No
- Version release 1.9-forge1.9-12.16.0.1877-1.9

**Comment by capnkirok** [comment]
Just checking... you are using a bow right, for shooting? The quiver only enables a bow to shoot rapid fire.... (the reason I ask this dumb question is because I can't replicate it). 😭

**Comment by BellaRose0613** [comment]
I'm so dumb. Please don't laugh at me. |:l

**Comment by capnkirok** [comment]
No worries! I think we may need to update the text on the Quiver to make it clearer.
