### ISSUE TITLE
Pingot Pet not detecting Nether Quartz

### ISSUE THREAD

**Issue by BellaRose0613** [capnkirok/Inventory-Pets#74]
@capnkirok I placed Nether Quartz for the Pingot Pet to detect. However, it did not detect the Nether Quartz ore. Is this intentional? Or is it a bug?

**Comment by capnkirok** [comment]
Probably also 1.7.10, 1.8, and 1.8.9 (checking...)

**Comment by capnkirok** [comment]
Yup, this is also an issue on all 1.8+ versions. Now I feel bad for Nether Quartz 😢 .

Fixed in dev.

**Comment by capnkirok** [comment]
This bug is not present in 1.9 and 1.9.4 versions
