### ISSUE TITLE
Loot Pet not working with Nether Quartz Ore

### ISSUE THREAD

**Issue by BellaRose0613** [capnkirok/Inventory-Pets#75]
@capnkirok Additionally, the Loot Pet won't work with Nether Quartz ore either. Poor Nether Quartz :(

**Comment by capnkirok** [comment]
This is now fixed in dev.

**Comment by capnkirok** [comment]
Also, this bug existed in 1.7.10, 1.8, and 1.8.9! Super find.

**Comment by capnkirok** [comment]
This bug is not present in 1.9 or 1.9.4

**Comment by capnkirok** [comment]
Fixed in 1.7.10
