### ISSUE TITLE
[1.9] Jukebox Pet Unstoppable Music!

### ISSUE THREAD

**Issue by BellaRose0613** [capnkirok/Inventory-Pets#77]
@capnkirok Welp, once I played the music on the Jukebox Pet, it wouldn't stop when I right-clicked. :b

**Comment by capnkirok** [comment]
Just trying to figure out the Jukebox issue. Seems to work fine here (I'm on an earlier version - the 1887 recommended version). But I don't think that's it. I will look into another way of stopping music.
