### ISSUE TITLE
Results of testing all pets 

### ISSUE THREAD

**Issue by Frobuzmumber** [capnkirok/Inventory-Pets#78]
1.9 Inventory pets 1.4.6 BETA
cow pet: works fine
sheep pet: works fine
pig pet: works fine
chicken pet: egg vanishes upon death, all fine
squid pet: works fine
ocelot pet: works fine
mooshroom pet: works fine
Ghast pet: works fine
spider pet: hang on wall doesn't work
iron golem pet: works fine
snow golem pet: works fine
enderman pet: works fine
creeper pet: works fine
magma pet: works fine
wither pet: works fine
blaze pet: works fine
bed pet: works fine
chest pet: works fine
double chest pet: works fine
enderchest pet: works fine
furnace pet: works fine
crafting pet: works fine
enchantment table pet: only works in creative, in survival states that it requires lapis (not nuggets) including levels won't enchant
jukebox pet: plays fine, skips to next fine, doens't stop when right click
anvil pet: works fine
brewing pet: works fine
nether portal pet: works fine
sponge pet: works fine
purplicious cow: works fine, my favorite pet! :)
mickerson pet: works fine
pingot pet: works perfect, yet OP! :)
quantum crystal monster pet: minions attack player and cause damage
banana pet: works fine
loot pet: works extra fine! :)
slime pet: works perfect
cloud pet: flight and fast flight works fine, lightning strikes, but no damage to mobs and doesn't convert creepers to supercharged creepers and doesn't change pigs to pigmen, see feed bag for other issue
pufferfish pet: works fine
black hole pet: works fine
quiver pet: rapid fire doesn't always shoot, bugged, infinity works fine
pacman pet: works fine
cheeta pet: works fine
house pet: works fine
silverfish pet: works awesome!
wolf pet: works fine
apple pet: works fine
sheild pet: works fine
heart pet: works fine
moon pet: works fine
dubstep pet: works fine
juggernaut: works fine
illuminati: works fine
grave pet: works fine
april fools pet: Its not april, didn't work.. lol
feed bag: nether quartz are in the feed bag, the cloud pet looses flight when it eats

Keep up the good work and thank you for such a great mod! :)

**Comment by capnkirok** [comment]
- Can you tell me which version of Forge you are using? Also are you on server or client?
- You can change the config to allow the April Fools' pet to work year round (if you want)

Cheers!

**Comment by Frobuzmumber** [comment]
forge-1.9.12.16.1901, client. I am about to start testing server side, just have to assemble the server. If you have any specific things you want me to test with it, just let me know. I have a linux server at my disposal (in my closet!) and can set up a test server on the fly.

**Comment by capnkirok** [comment]
@Frobuzmumber Hey there again! Can you test a new version for me? 

https://dl.dropboxusercontent.com/u/127642501/inventorypets-1.4.6%20BETA.jar

Things I would like to know:
- I can't test if the updated Jukebox Pet stop playing now works (can't replicate). Can you let me know?
- Lightning Strike should now convert mobs
- Ocelot and Squid don't crash servers when placed in inventory
- Trees are correct height
- Question: Does the Cloud Pet give you an: "[Player] moved too quickly... " error in console?

Still working on Quiver and Enchanting table, so no changes there.

Thanks for your help!

**Comment by Frobuzmumber** [comment]
Sorry about the delayed response, I just got the notification. I will get right on it

**Comment by Frobuzmumber** [comment]
Ok, Jukebox works fine now! Awesome!
Lightning converts mobs
Ocelot and Squid don't crash now
Trees are good
When using the cloud pet, the extra speed does still give you [player] moved to quickly, this also happens when sprinting with the chicken pet. Just walking with the chicken pet doesn't give that message.

If you need anything else, hit me up on twitter or shoot me an email (frobuzmumber@gmail.com)

**Comment by capnkirok** [comment]
Thank you very much kind sir.

**Comment by capnkirok** [comment]
Dupes: 
Enchant #71 
Quiver #70

**Comment by capnkirok** [comment]
- Chicken Pet now drops real eggs (not ghost ones)
- Quiver Pet working
