### ISSUE TITLE
[1.9] Pets I had issues with

### ISSUE THREAD

**Issue by BellaRose0613** [capnkirok/Inventory-Pets#79]
@capnkirok Finally, I have finished the beta test for the inventory pets mod for 1.9. There may still be bugs that I have missed, so don't criticize me for anything, please. :(
![2016-06-05_15 14 47](https://cloud.githubusercontent.com/assets/19763590/15807617/b74d3ec4-2b30-11e6-97d9-981685ee5b31.png)

**Comment by capnkirok** [comment]
No criticisms here. Thank you so much for the help with testing. Really really appreciated 👍

**Comment by capnkirok** [comment]
Closing this as the bugs are listed elsewhere. Thanks again!
