### ISSUE TITLE
Tree dungeons stand out

### ISSUE THREAD

**Issue by Frobuzmumber** [capnkirok/Inventory-Pets#81]
Noticed in the 1.8.9 version and 1.9 beta version that the tree dungeons are mostly (if not all) in really tall trees (between 10 and 12 blocks high). Also, I have found a cloud pet in the tree, thought they were supposed to only be in the cloud dungeons.

**Comment by capnkirok** [comment]
OH! Yes, that was for testing, so I could find them easier. Guess it worked. 

I'll check on the Cloud Pet too. That one is def. wrong.

**Comment by capnkirok** [comment]
Ok, tree height is fixed in Dev. Now onto Cloud.

**Comment by capnkirok** [comment]
Ok, Cloud (and all other Dungeon Drops it turns out) are fixed in Dev.
