### ISSUE TITLE
[1.7.10] Random Crash report 

### ISSUE THREAD

**Issue by runescapejon** [capnkirok/Inventory-Pets#83]
http://pastebin.com/6hsj03nq

**Comment by capnkirok** [comment]
Grrr... I know exactly what this is. It's a ticking spawner block on the exact border of your server world. I did update this recently so that if the block is on the border of a chunk, it no longer ticks, but this appears not to be working. I may have to reproduce the setup to get a real test.

**Comment by capnkirok** [comment]
This one is not present in 1.9 and 1.9.4

**Comment by capnkirok** [comment]
Ok, I've redone how spawner blocks work entirely. At the first tick, it will check if it's on a chunk border (and a server). If so, it will disable ticking. Will push this update out today on 1.7.10. Let me know if you still have issues.

**Comment by capnkirok** [comment]
Closing this here after testing. Please let me know if you still see it.
