### ISSUE TITLE
Grave Pet not working with Advent of Ascension installed

### ISSUE THREAD

**Issue by capnkirok** [capnkirok/Inventory-Pets#86]
Reported by Trollking6

**Comment by Frobuzmumber** [comment]
A thought on this,  with advent of ascension they use the gamerule keepAllInventory instead of keepInventory..  Perhaps that is why it doesn't work.

**Comment by capnkirok** [comment]
Hmmm... I did see that, I'll check it out. I've tried to deconstruct the events in the mod, but no luck so far that way. I wonder...

**Comment by capnkirok** [comment]
Finally responding here. No, it has nothing to do with keepInventory. Definitely intervention by AOA. Going to put a warning in Inventory Pets.

Warning message added to console on game start.
