### ISSUE TITLE
[1.9.4] Incompatibility with Guide Book (Crash)

### ISSUE THREAD

**Issue by wise-io** [capnkirok/Inventory-Pets#87]
Didn't know if you saw the forum post, but Inventory Pets + Guide Book causes a crash. I don't know which mod is responsible, so I'm posting it in both Gits.

http://pastebin.com/1gY6KdWt

GuideBook Github issue: https://github.com/Creysys/GuideBook/issues/4

**Comment by capnkirok** [comment]
Left a note on Creysys github. I have a few recipes that are hidden via config, which may be causing a null error. Hoping he can add a null check.

**Comment by capnkirok** [comment]
Still exists in the 1.6 version of Guide Book just released, but Creysys says he will work on it.

**Comment by capnkirok** [comment]
This is now fixed in 1.6.2 of Guide Book.
