### ISSUE TITLE
[1.9.4] Grave pet item dupe bug

### ISSUE THREAD

**Issue by wise-io** [capnkirok/Inventory-Pets#90]
This bug occurs when using both the chest/double chest pet and the grave pet. 

Steps to recreate:
- Have both pets in hot bar.
- Put bones in chest pet.
- Die - grave pet saves inventory, but doesn't eat a bone
- Die again - items are dropped and grave pet saves them (still doesn't eat a bone), resulting in item duplication.

**Comment by capnkirok** [comment]
Ooohhh, that sounds very bad. Will check it out.

**Comment by capnkirok** [comment]
Ok, found the problem. It actually dupes everything if you didn't have a bone. This is fixed in dev, and will be released in 1.4.8
