### ISSUE TITLE
Ocelot = creeper parties

### ISSUE THREAD

**Issue by wise-io** [capnkirok/Inventory-Pets#91]
My ocelot brings all the creepers to the yard...
My creep.... is better than yours..

Sorry, couldn't resist. My ocelot seems to attract creeper hoards to my house while I am inside it. It also appears to work for everyone in a LAN world.

http://imgur.com/a/V0dz5

**Comment by capnkirok** [comment]
This one I know. The code grabs all Creepers loaded into the game at the moment. Then it sends them to one of two fixed points. This is in need of some upgrading. Thanks for posting.

**Comment by wise-io** [comment]
Their behavior is hilarious. I wouldn't have posted it if it didn't also allow me to get tons of experience every time I walk out the door to slay them all. 

Is there a way to turn the effect on/off based on proximity to the player?

If you can't tell, I use your mod a lot. My 8 year old son and I love it. You should have heard him laughing the first time he saw all those creepers running around. Thanks for that experience. I felt the least I could do is report the issues that I'm finding. Hope I'm not annoying!

**Comment by capnkirok** [comment]
Not annoying at all, I love the feedback! No way to turn the effect off (other than remove from your hotbar). I've seen some players do that... grab a whole bunch, drop the pet, then wait until the absolute last second and pick it up again and make them run.

**Comment by capnkirok** [comment]
Gonna put this in 1.5

**Comment by capnkirok** [comment]
Fixed in Dev.... ha ha ha, it's only been open for a year :)
