### ISSUE TITLE
Cloud Pet lightning destroys blocks

### ISSUE THREAD

**Issue by RacerDelux** [capnkirok/Inventory-Pets#93]
When you cast in on a bock in the middle of a wall, it will destroy the block above it. This even works on protected land with ftbutils.
https://i.gyazo.com/5ab75640587aebfde3af6a3713b0185b.png

**Comment by capnkirok** [comment]
Yeah, it converts the top block to fire. We were trying to make it behave more like real lightning. I haven't look at this in awhile, let me see if there's a better way to do this.

**Comment by capnkirok** [comment]
Ok, found a better way to do this, just lighting the top block. Thanks for the suggestion. Now fixed in dev in all versions, due to release with 1.4.8
