### ISSUE TITLE
[1.7.10] Pingot bug

### ISSUE THREAD

**Issue by MineWitherMC** [capnkirok/Inventory-Pets#94]
Hello, Pingot is not working on Metadata ores, for example Tinkers aluminum gives me Netherrack Slag that isn't usable in any way. I know it's the same as already fixed #60, but it wasn't fixed for InvPets 1.4.7.1 for 1.7.10 and probably other versions. I had to disable pingot via MT.

**Comment by capnkirok** [comment]
Weird. This was fixed some time ago, as you noted. Tinker's has just one ore block, and uses meta data to determine which type it is. So, somehow, we're losing the metadata, as Netherrack Slag is the ore block with metadata 0. Thanks for the report!

**Comment by capnkirok** [comment]
Yep, definitely something wonky here with the way I'm handling the metadata. And the version of TC i'm testing is from October, so it's my fault for sure. Working on a solution now.

**Comment by capnkirok** [comment]
Ok, this is now fixed. Looks like I broke something in a recent update. I was only setting the Metadata after you 'checked' for ore [right click], otherwise it defaulted either to Zero, or the last Metadata you had 'checked'. Fixed in Dev, will release in 1.4.8.
