### ISSUE TITLE
[1.9.4] A few small enhancements

### ISSUE THREAD

**Issue by wise-io** [capnkirok/Inventory-Pets#95]
A few ideas/issues:
- Show status effects added by pets in top right corner of screen (like potions). This would allow you to tell what abilities you have at a glance.
- Pets should look for food from feed bag from right to left, in order to take from smaller stacks first.
- Perhaps the feed bag should have more rows (2 rows total maybe?) It is very expensive for such a small amount of slots.

**Comment by capnkirok** [comment]
- I like this first suggestion. Status Effects are easier to do in 1.9+. Will have to think about it a bit.
- Eating right to left, hmmm, never thought about that. Easy to do, but let me check.
- Not sure I agree with this one, a few modpackers complain about how easy it is to make.

Thanks for the suggestions!

**Comment by capnkirok** [comment]
Well, I finally implemented 2 rows in Feed Bags in 1.15 & 1.16+. The rest I am leaving as is!
