### ISSUE TITLE
[1.9.4][1.4.7] Silk touch yields spawner

### ISSUE THREAD

**Issue by Madslocher** [capnkirok/Inventory-Pets#96]
The spawner in the small caves can be harvested with a silk touch pickaxe and replaced in the world.

Minecraft 1.9.4 Inventory-pets 1.4.7

**Comment by capnkirok** [comment]
Ha ha ha! Didn't think about that one. Easy to change.

**Comment by capnkirok** [comment]
Ok, this is fixed in dev on all versions on all spawners. Will be released with 1.4.8.
