### ISSUE TITLE
[SOLVED] Downloaded InventoryPets and it Crashed my Game 

### ISSUE THREAD

**Issue by TinyTotCyborg** [capnkirok/Inventory-Pets#99]
I downloaded inventory pets and tried to run minecraft and while it was opening the game it crashed. I took inventory pets out of my mod folder and tried to run minecraft and it worked. I have other mods and I know they aren't the issue because inventory pets and my mods have worked many times before. When my game crashed it said "EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffbd9ab4fdc, pid=11232, tid=16124" and it also said "Failed to write core dump. Minidumps are not enabled by default on client versions of Windows". Please help me. Thank you.

**Comment by capnkirok** [comment]
Weird. Never seen that before. What version are you trying to run... 1.9?

Check out this thread, see if it helps: http://www.minecraftforum.net/forums/support/unmodified-minecraft-client/2626897-minecraft-1-9-solved-failed-to-write-core-dump

**Comment by TinyTotCyborg** [comment]
I was trying to run 1.7.10. But I'll check out the thread you sent me.

**Comment by TinyTotCyborg** [comment]
Thank you for the thread! It helped me alot.

**Comment by capnkirok** [comment]
Great!
